/** Productividad y Desarrollo · Unidad 1 · Semana 7. */
import { lesson, S } from '../../../../dsl';

export default [
  lesson({
    id: 's07-pyd-1', title: 'De la evidencia a una acción ambiental viable', icon: 'ClipboardCheck', minutes: 14,
    gancho: '¿Cómo pasamos de una preocupación por el agua a una acción que sí se puede realizar y verificar?',
    objetivos: ['Diseñar una acción ambiental viable con causa, evidencia, responsabilidad, recursos y verificación'],
    resumen: [
      'Una acción viable responde a una causa sustentada por evidencia, asigna responsables y usa recursos disponibles.',
      'La verificación define un indicador y una comparación; no promete resultados que la evidencia no garantiza.',
      'La vegetación puede influir en erosión, escorrentía e infiltración según condiciones locales; una tala observada no prueba por sí sola la causa de un cambio en el agua.',
    ],
    media: {
      id: 's07-pyd-1-cadena', kind: 'diagram', title: 'Canvas de acción ambiental', aspect: '16:9',
      alt: 'Plantilla de acción con campos de causa, evidencia, responsable, recursos, acción e indicador de verificación.',
      brief: 'Diagrama horizontal 1600×900, rotulado CASO SIMULADO, con seis campos grandes: CAUSA POR COMPROBAR, EVIDENCIA DISPONIBLE, ACCIÓN, RESPONSABLE, RECURSOS e INDICADOR DE VERIFICACIÓN. Incluir un ejemplo parcial sobre una fuga visible, sin completar la respuesta evaluada. Flechas de lectura claras, contraste alto, texto grande y versión apta para escala de grises.',
    },
    steps: [
      S.explain({ fase: 'explorar', areas: ['pyd'], cnb: ['pyd:5.1.2', 'pyd:5.3.2'], title: 'Una propuesta que se puede comprobar', prompt: 'Una buena intención se vuelve proyecto cuando conecta evidencia, acción, responsables, recursos y verificación.' }, { icon: 'ClipboardCheck', body: 'Usaremos **escenarios simulados**. No atribuiremos mediciones ni consultas a una comunidad real.' }),
      S.choice({ fase: 'construir', areas: ['pyd'], cnb: ['pyd:5.1.2'], prompt: 'Una fotografía muestra árboles retirados cerca de un nacimiento. ¿Qué conclusión es válida?', explain: 'La observación permite una pregunta, no una causa demostrada.' }, { options: [{ id: 'a', text: 'La remoción puede justificar estudiar suelo, lluvia, erosión y caudal antes de concluir' }, { id: 'b', text: 'Atribuir el cambio de caudal a un único factor sin comparar registros' }, { id: 'c', text: 'Planificar una siembra sin revisar suelo, especies, permisos ni un indicador' }], correct: ['a'] }),
      S.explain({ fase: 'construir', areas: ['pyd'], cnb: ['pyd:5.1.2', 'pyd:5.3.2'], title: 'Seis campos del plan', prompt: 'Cada campo evita una promesa vaga.' }, { icon: 'ListChecks', body: 'La acción debe ser proporcional a la evidencia y a los recursos.', reveal: [{ icon: 'Search', front: 'Causa o factor', back: 'Explicación apoyada por evidencia o marcada como hipótesis.' }, { icon: 'FileCheck', front: 'Evidencia', back: 'Dato, registro u observación identificada.' }, { icon: 'Wrench', front: 'Acción', back: 'Tarea concreta que atiende el factor.' }, { icon: 'UserCheck', front: 'Responsable', back: 'Quién realiza y da seguimiento.' }, { icon: 'Package', front: 'Recursos', back: 'Materiales y tiempo disponibles.' }, { icon: 'Gauge', front: 'Verificación', back: 'Indicador comparable antes y después.' }] }),
      S.ejemplo({ fase: 'construir', areas: ['pyd'], cnb: ['pyd:5.1.2', 'pyd:5.3.2'], title: 'Ejemplo resuelto: fuga en un caso escolar', prompt: 'Mira cómo una evidencia limitada sostiene una acción pequeña.' }, { icon: 'Wrench', problem: 'La ficha simulada registra 12 goteos por minuto en una llave y humedad debajo.', steps: [{ text: '**Causa/factor:** empaque posiblemente desgastado; requiere revisión.' }, { text: '**Evidencia:** conteo simulado de goteos y humedad observada.' }, { text: '**Acción y responsable:** personal autorizado revisa y cambia el empaque si corresponde.' }, { text: '**Recursos:** empaque, llave de herramienta y 20 minutos.' }, { text: '**Verificación:** repetir el conteo durante un minuto.' }], answer: 'La acción no promete resolver todos los problemas de agua; atiende la evidencia disponible.' }),
      S.match({ fase: 'construir', areas: ['pyd'], cnb: ['pyd:5.3.2'], prompt: 'Une cada campo con el dato que le corresponde.', hint: 'Pregunta qué función cumple cada frase.', explain: 'Un plan completo distingue decisión, ejecución y comprobación.' }, { leftTitle: 'Campo', rightTitle: 'Dato', pairs: [{ id: 'a', left: 'Responsable', right: 'Personal autorizado de mantenimiento' }, { id: 'b', left: 'Recursos', right: 'Empaque y herramienta' }, { id: 'c', left: 'Verificación', right: 'Repetir el conteo de goteos' }, { id: 'd', left: 'Evidencia', right: '12 goteos por minuto en el caso' }] }),
      S.sort({ fase: 'construir', areas: ['pyd'], cnb: ['pyd:5.1.2'], prompt: 'Clasifica las propuestas.', hint: 'Una propuesta viable cabe en recursos y no promete garantías.', explain: 'La viabilidad incluye alcance, evidencia y seguridad.' }, { buckets: [{ id: 'v', label: 'Viable', icon: 'Check', color: 'var(--c-ok)' }, { id: 'n', label: 'No viable', icon: 'X', color: 'var(--c-bad)' }], items: [{ id: 'a', text: 'Revisar una fuga identificada y repetir el conteo', bucket: 'v' }, { id: 'b', text: 'Prometer que una siembra impedirá que el nacimiento se seque', bucket: 'n' }, { id: 'c', text: 'Comparar escorrentía en un modelo con suelo cubierto y expuesto', bucket: 'v' }, { id: 'd', text: 'Afirmar que un solo árbol resolverá la calidad del agua', bucket: 'n' }] }),
      S.choice({ fase: 'aplicar', areas: ['pyd'], cnb: ['pyd:5.1.2', 'pyd:5.3.2'], prompt: 'Caso simulado: el registro muestra 7 activaciones innecesarias de una bomba por una fuga. ¿Qué plan es completo?', explain: 'La opción conecta evidencia, responsable, recursos y verificación.' }, { options: [{ id: 'a', text: 'Personal autorizado revisa la fuga con repuesto disponible y compara activaciones durante periodos iguales' }, { id: 'b', text: 'El estudiantado desmonta la bomba sin herramientas' }, { id: 'c', text: 'Se planta un árbol y se afirma que la bomba consumirá menos' }], correct: ['a'] }),
      S.write({ fase: 'aplicar', areas: ['pyd'], cnb: ['pyd:5.1.2', 'pyd:5.3.2'], prompt: 'Diseña una acción para el caso de la bomba: causa o factor, evidencia, acción, responsabilidad, recursos y verificación.', explain: 'Completa los seis campos con una acción factible y un indicador comparable.' }, { minWords: 34, placeholder: 'Causa/factor: ...\nEvidencia: ...\nAcción: ...\nResponsable: ...\nRecursos: ...\nVerificación: ...', model: 'Factor posible: fuga en una llave. Evidencia: siete activaciones registradas. Acción: solicitar una revisión segura. Responsable: personal de mantenimiento. Recursos: repuesto y hoja de registro. Verificación: comparar activaciones durante dos periodos iguales antes y después.', rubric: ['Relacioné causa o factor con evidencia', 'Definí acción y responsabilidad', 'Usé recursos realistas', 'Incluí una verificación'] }),
      S.choice({ fase: 'comprobar', areas: ['pyd'], cnb: ['pyd:5.1.2', 'pyd:5.3.2'], prompt: '¿Qué plan de acción contiene causa/evidencia, responsabilidad, recursos y verificación?' }, { options: [{ id: 'a', text: 'Fuga según registro; mantenimiento usa un repuesto y compara goteos antes y después' }, { id: 'b', text: 'Cuidar el planeta entre todos' }, { id: 'c', text: 'Sembrar sin identificar el problema ni medir resultados' }], correct: ['a'] }),
      S.choice({ fase: 'comprobar', areas: ['pyd'], cnb: ['pyd:5.1.2', 'pyd:5.3.2'], prompt: 'Caso nuevo: una canaleta simulada tiene sedimentos después de lluvia. ¿Qué propuesta integra causa por comprobar, evidencia, acción, responsable, recursos y verificación?' }, { options: [{ id: 'a', text: 'Factor: suelo expuesto; evidencia: sedimentos; acción: prueba de cobertura; responsable: equipo del modelo; recursos: bandeja y cobertura; verificación: comparar sedimentos' }, { id: 'b', text: 'Sembrar sin identificar el factor, las condiciones locales ni un indicador' }, { id: 'c', text: 'Limpiar sin registrar evidencia, responsable, recursos ni indicador' }], correct: ['a'] }),
    ],
  }),
];
