/** Ciencias Sociales · Unidad 1 · Semana 4. */
import { lesson, S } from '../../../../dsl';

export default [
  lesson({
    id: 's04-ccss-1', title: 'Ciencias Sociales para investigar preguntas', icon: 'Search', minutes: 14,
    gancho: 'Una pregunta sobre la comunidad puede necesitar varias miradas y evidencia.',
    objetivos: ['Valorar la investigacion social al relacionar Ciencias Sociales con preguntas personales, comunitarias y nacionales'],
    resumen: ['Historia estudia procesos en el tiempo; Geografia, territorio y relaciones espaciales.', 'Sociologia estudia grupos e instituciones; Antropologia, culturas y formas de vida.', 'La investigacion social convierte inquietudes personales y nacionales en preguntas que pueden responderse con evidencia.'],
    media: { id: 's04-ccss-1-ciencias', kind: 'diagram', title: 'Miradas para una pregunta social', aspect: '16:9', alt: 'Cuatro lupas representan Historia, Geografia, Sociologia y Antropologia alrededor de una pregunta.', brief: 'Diagrama 1600x900 con una pregunta comunitaria al centro y cuatro lupas: Historia-tiempo, Geografia-territorio, Sociologia-grupos e instituciones, Antropologia-culturas y formas de vida. Agregar flecha hacia "decidir con evidencia". Texto grande, alto contraste e iconos ademas de color.' },
    steps: [
      S.explain({ fase: 'explorar', areas: ['ccss'], cnb: ['ccss:5.1.1', 'ccss:5.1.4'], prompt: 'Valora la investigacion social: Historia, Geografia, Sociologia y Antropologia ayudan a responder preguntas personales, comunitarias y nacionales para decidir con evidencia.' }, { icon: 'Search', body: 'Las Ciencias Sociales aportan miradas distintas. Investigarlas importa porque permite fundamentar respuestas en vez de depender solo de rumores.' }),
      S.explain({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:5.1.1', 'ccss:5.1.4'], prompt: 'Relaciona Historia, Geografia, Sociologia y Antropologia con la importancia de la investigacion social para preguntas personales, comunitarias y nacionales.' }, { icon: 'BookOpenCheck', body: '**Historia:** cambios en el tiempo. **Geografia:** territorio. **Sociologia:** grupos e instituciones. **Antropologia:** culturas y formas de vida. La investigacion social valora cada pregunta y ayuda a decidir con evidencia.' }),
      S.ejemplo({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:5.1.1', 'ccss:5.1.4'], title: 'Modelo de pregunta social', prompt: 'Observa como valorar la investigacion social usando Historia, Geografia, Sociologia y Antropologia para una pregunta comunitaria y nacional.' }, { icon: 'Lightbulb', problem: '¿Por que cambio el uso de la plaza y que significa para distintas familias?', steps: [{ text: 'Historia busca cuando y por que cambio.' }, { text: 'Geografia estudia ubicacion y acceso.' }, { text: 'Sociologia y Antropologia examinan grupos, usos y significados.' }, { text: 'Valorar estas miradas permite decidir con evidencia en la comunidad y relacionar el caso con preguntas del pais.' }], answer: 'Una pregunta social puede necesitar varias disciplinas y evidencia.' }),
      S.match({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:5.1.1', 'ccss:5.1.4'], prompt: 'Con ayuda, valora la investigacion social y relaciona Historia, Geografia, Sociologia y Antropologia con preguntas personales, comunitarias y nacionales.', hint: 'Busca tiempo, territorio, grupos o cultura.', explain: 'Cada disciplina aporta evidencia diferente para fundamentar decisiones.' }, { pairs: [{ id: 'a', left: 'Historia', right: 'Cambio de una costumbre en el tiempo' }, { id: 'b', left: 'Geografia', right: 'Acceso territorial a servicios' }, { id: 'c', left: 'Sociologia', right: 'Participacion de grupos e instituciones' }, { id: 'd', left: 'Antropologia', right: 'Significados culturales de una practica' }] }),
      S.choice({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:5.1.1', 'ccss:5.1.4'], prompt: '¿Que opcion valora la investigacion social con Historia, Geografia, Sociologia y Antropologia para responder preguntas personales, comunitarias y nacionales?', hint: 'Valorar implica reconocer utilidad y decidir con evidencia.', explain: 'La opcion correcta vincula disciplinas, preguntas y utilidad social.' }, { options: [{ id: 'a', text: 'Comparar sus evidencias ayuda a fundamentar respuestas y decisiones' }, { id: 'b', text: 'Una opinion sin fuente basta para todo problema' }, { id: 'c', text: 'Las preguntas personales nunca se relacionan con el pais' }], correct: ['a'] }),
      S.write({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:5.1.1', 'ccss:5.1.4'], prompt: 'Valora de forma independiente la investigacion social: usa Historia, Geografia, Sociologia y Antropologia para una pregunta personal o comunitaria y otra nacional; explica su importancia para decidir con evidencia.' }, { minWords: 28, placeholder: 'Pregunta... Disciplinas... Importancia...', model: 'Historia y Geografia explican cambios, lugares y acceso; Sociologia y Antropologia estudian grupos, relaciones y significados. Investigar una inquietud local y nacional permite comprenderla mejor y decidir con evidencia suficiente.', rubric: ['Relacione las cuatro disciplinas', 'Inclui dos escalas de pregunta', 'Valore la utilidad de investigar'] }),
      S.choice({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:5.1.1', 'ccss:5.1.4'], prompt: 'Al valorar investigacion social, ¿como ayudan Historia, Geografia, Sociologia y Antropologia a preguntas personales, comunitarias y nacionales?', }, { options: [{ id: 'a', text: 'Aportan evidencia temporal, territorial, grupal y cultural para fundamentar respuestas' }, { id: 'b', text: 'Reemplazan toda pregunta con una sola opinion' }, { id: 'c', text: 'Solo sirven para memorizar nombres' }], correct: ['a'] }),
      S.choice({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:5.1.1', 'ccss:5.1.4'], prompt: 'Salida: valora la investigacion social con Historia, Geografia, Sociologia y Antropologia ante preguntas personales, comunitarias y nacionales.' }, { options: [{ id: 'a', text: 'Integra miradas y evidencia para comprender y decidir mejor' }, { id: 'b', text: 'Descarta preguntas de la comunidad por ser pequenas' }, { id: 'c', text: 'Acepta rumores sin comprobar' }], correct: ['a'] }),
      S.tf({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:5.1.1', 'ccss:5.1.4'], prompt: 'Salida nueva: comprueba como Historia, Geografia, Sociologia y Antropologia dan importancia a la investigacion social de preguntas personales, comunitarias y nacionales para decidir con evidencia.' }, { statements: [{ text: 'Una inquietud personal puede convertirse en pregunta investigable.', answer: true }, { text: 'Varias disciplinas pueden aportar evidencia complementaria.', answer: true }, { text: 'Investigar no tiene utilidad para decisiones comunitarias o nacionales.', answer: false }] }),
    ],
  }),

  lesson({
    id: 's04-ccss-2', title: 'Usamos herramientas para reunir informacion', icon: 'ClipboardList', minutes: 14,
    gancho: 'Observar, entrevistar y encuestar producen registros distintos.',
    objetivos: ['Usar herramientas de observacion, entrevista y encuesta para reunir informacion de un material suministrado'],
    resumen: ['La guia de observacion registra hechos visibles con criterios.', 'La entrevista recoge respuestas abiertas; la encuesta, respuestas comparables.', 'Una herramienta no autoriza inventar datos ni afirmar mas de lo que muestra el material.'],
    media: { id: 's04-ccss-2-herramientas', kind: 'diagram', title: 'Tres herramientas de recoleccion', aspect: '16:9', alt: 'Una guia de observacion, una entrevista y una encuesta junto a un caso ficticio.', brief: 'Diagrama 1600x900. Mostrar una guia de observacion con casillas, una entrevista con preguntas abiertas y una encuesta con opciones, junto a una ficha rotulada "caso ficticio suministrado". Incluir nota "registrar, no inventar". Texto grande, alto contraste y orden de lectura accesible.' },
    steps: [
      S.explain({ fase: 'explorar', areas: ['ccss'], cnb: ['ccss:5.3.1'], prompt: 'Usa observacion, entrevista y encuesta para registrar informacion del caso y los datos suministrados.' }, { icon: 'ClipboardList', body: 'Cada herramienta responde mejor a una necesidad: ver y registrar, profundizar una respuesta o comparar respuestas.' }),
      S.explain({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:5.3.1'], prompt: 'Aplica observacion, entrevista y encuesta al material suministrado sin inventar registros.' }, { icon: 'ListChecks', body: '**Observacion:** criterio visible. **Entrevista:** pregunta abierta y respuesta textual. **Encuesta:** misma pregunta y opciones para varias personas. Se registra solo lo suministrado.' }),
      S.ejemplo({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:5.3.1'], title: 'Modelo con ficha suministrada', prompt: 'Observa como usar las tres herramientas con un caso suministrado.' }, { icon: 'SearchCheck', problem: 'Ficha ficticia: en el recreo, 6 estudiantes usan la cancha; Ana responde "falta sombra"; encuesta: 8 prefieren arboles y 4 un techo.', steps: [{ text: 'Observacion: registrar 6 estudiantes en la cancha.' }, { text: 'Entrevista: conservar la respuesta abierta de Ana.' }, { text: 'Encuesta: organizar 8 arboles y 4 techo.' }], answer: 'Cada dato se vincula con la herramienta que lo produjo.' }),
      S.match({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:5.3.1'], prompt: 'Con ayuda, usa observacion, entrevista y encuesta para organizar el material suministrado del caso ficticio.', hint: 'Distingue hecho visible, respuesta abierta y conteo comparable.', explain: 'La fuente suministrada determina el registro; no se agregan respuestas.' }, { pairs: [{ id: 'a', left: 'Se ven tres bancas ocupadas', right: 'Guia de observacion' }, { id: 'b', left: 'Luis explica por que usa el patio', right: 'Entrevista' }, { id: 'c', left: '9 eligen sombra y 5 eligen juegos', right: 'Encuesta' }] }),
      S.choice({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:5.3.1'], prompt: 'Usa observacion, entrevista y encuesta: selecciona el registro valido del material suministrado.', hint: 'No conviertas una respuesta individual en dato de todo el grupo.', explain: 'Una entrevista aporta una perspectiva, no una proporcion colectiva.' }, { options: [{ id: 'a', text: 'Entrevista: Marta dijo que prefiere sentarse cerca de la biblioteca' }, { id: 'b', text: 'Encuesta: toda la escuela piensa igual que Marta' }, { id: 'c', text: 'Observacion: Marta representa a todas las familias' }], correct: ['a'] }),
      S.write({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:5.3.1'], prompt: 'Usa observacion, entrevista y encuesta con este material suministrado: se observan 4 bebederos, Joel dice "uno gotea", y la encuesta registra 7 reparacion / 3 cartel. Completa un registro por herramienta.' }, { minWords: 22, placeholder: 'Observacion... Entrevista... Encuesta...', model: 'Observacion: hay cuatro bebederos disponibles. Entrevista suministrada: Joel informa un goteo constante. Encuesta simulada: siete personas eligen reparacion y tres prefieren colocar un cartel.', rubric: ['Use las tres herramientas', 'Registre solo datos suministrados', 'Distingui tipos de evidencia'] }),
      S.choice({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:5.3.1'], prompt: 'Al usar observacion, entrevista y encuesta con una ficha de datos suministrados, ¿que accion demuestra uso real?', }, { options: [{ id: 'a', text: 'Completar cada registro con la evidencia correspondiente' }, { id: 'b', text: 'Inventar respuestas que faltan' }, { id: 'c', text: 'Nombrar herramientas sin registrar nada' }], correct: ['a'] }),
      S.choice({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:5.3.1'], prompt: 'Salida: usa observacion, entrevista y encuesta para seleccionar el registro correcto del material suministrado.' }, { options: [{ id: 'a', text: 'Visible-observacion; respuesta abierta-entrevista; conteo comun-encuesta' }, { id: 'b', text: 'Todo dato corresponde a entrevista' }, { id: 'c', text: 'Las herramientas permiten inventar detalles' }], correct: ['a'] }),
      S.tf({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:5.3.1'], prompt: 'Salida nueva: aplica observacion, entrevista y encuesta al caso con registros suministrados.' }, { statements: [{ text: 'Una guia de observacion usa criterios visibles.', answer: true }, { text: 'Una entrevista abierta puede conservar las palabras de una persona.', answer: true }, { text: 'Una encuesta autoriza completar respuestas no suministradas.', answer: false }] }),
    ],
  }),

  lesson({
    id: 's04-ccss-3', title: 'De sociedades cazadoras y recolectoras a agricultoras', icon: 'History', minutes: 15,
    gancho: 'La agricultura transformo muchas formas de vida, aunque los cambios fueron graduales y diversos.',
    objetivos: ['Comparar caracteristicas, cambios y formas de vida de sociedades cazadoras, recolectoras y agricultoras'],
    resumen: ['Muchas sociedades cazadoras y recolectoras combinaron movilidad, campamentos y conocimiento estacional.', 'La agricultura favorecio asentamientos mas permanentes, cultivos, almacenamiento y nuevas tareas.', 'La transicion fue gradual, ocurrio en momentos distintos y no significa que todas las sociedades siguieran una sola ruta.'],
    media: { id: 's04-ccss-3-sociedades', kind: 'diagram', title: 'Cambios en formas de vida', aspect: '16:9', alt: 'Linea comparativa de campamento movil, recoleccion, caza, cultivo y aldea permanente.', brief: 'Diagrama historico 1600x900 que compara movilidad y campamentos estacionales de sociedades cazadoras-recolectoras con cultivos, almacenamiento y aldeas de sociedades agricultoras. Incluir flechas discontinuas y nota "transiciones graduales y diversas, no una escala de superioridad". Alto contraste, texto grande y descripcion accesible.' },
    steps: [
      S.explain({ fase: 'explorar', areas: ['ccss'], cnb: ['ccss:6.2.1'], prompt: 'Compara la evolucion y las formas de vida de sociedades cazadoras, recolectoras y agricultoras: movilidad, campamento, cultivo y aldea.' }, { icon: 'History', body: 'Los cambios en subsistencia transformaron asentamientos y tareas, pero no ocurrieron igual ni al mismo tiempo en todas partes.' }),
      S.explain({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:6.2.1'], prompt: 'Distingue sociedades cazadoras-recolectoras y agricultoras por movilidad, campamentos, cultivos, almacenamiento y aldeas.' }, { icon: 'GitCompare', body: 'Cazar y recolectar suele requerir conocimiento estacional y movilidad entre campamentos. Cultivar puede favorecer sedentarismo relativo, aldeas y almacenamiento. Hubo combinaciones y transiciones graduales.' }),
      S.ejemplo({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:6.2.1'], title: 'Modelo de comparacion', prompt: 'Observa como comparar la evolucion y formas de vida cazadora, recolectora y agricultora.' }, { icon: 'Columns2', problem: 'Dos conjuntos de evidencias muestran campamentos estacionales y una aldea con graneros.', steps: [{ text: 'Campamentos y movilidad se relacionan con caza y recoleccion estacional.' }, { text: 'Cultivos, graneros y aldea estable se relacionan con agricultura.' }, { text: 'La diferencia indica un cambio gradual de subsistencia y asentamiento, no superioridad.' }], answer: 'La evidencia permite comparar formas de vida y procesos de cambio.' }),
      S.sort({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:6.2.1'], prompt: 'Con ayuda, compara evolucion y formas de vida cazadora-recolectora y agricultora: movilidad, campamento, cultivo y aldea.', hint: 'Busca desplazamiento estacional o produccion y almacenamiento.', explain: 'Algunas sociedades combinaron ambas formas; aqui se clasifica el rasgo predominante.' }, { buckets: [{ id: 'cr', label: 'Cazadora-recolectora', icon: 'Footprints' }, { id: 'ag', label: 'Agricultora', icon: 'Wheat' }], items: [{ id: 'a', text: 'Campamento estacional y movilidad', bucket: 'cr' }, { id: 'b', text: 'Caza y recoleccion de plantas silvestres', bucket: 'cr' }, { id: 'c', text: 'Cultivo y almacenamiento', bucket: 'ag' }, { id: 'd', text: 'Aldea mas permanente', bucket: 'ag' }] }),
      S.choice({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:6.2.1'], prompt: 'Compara la evolucion y formas de vida de cazadores, recolectores y agricultores por movilidad, campamento, cultivo y aldea.', hint: 'La transicion fue gradual y diversa.', explain: 'La agricultura cambio subsistencia y asentamiento sin borrar de inmediato otras practicas.' }, { options: [{ id: 'a', text: 'Muchas comunidades combinaron practicas durante cambios graduales' }, { id: 'b', text: 'Todas cambiaron el mismo ano' }, { id: 'c', text: 'La agricultura elimino toda movilidad' }], correct: ['a'] }),
      S.write({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:6.2.1'], prompt: 'Compara de forma independiente evolucion y formas de vida cazadora-recolectora y agricultora; incluye movilidad, campamento, cultivo, almacenamiento y aldea.' }, { minWords: 26, placeholder: 'La primera forma... La segunda... El cambio...', model: 'La caza y recoleccion implicaron movilidad y campamentos temporales; la agricultura sumo cultivos, almacenamiento y aldeas permanentes. La transicion fue gradual, diversa y distinta segun cada territorio.', rubric: ['Compare subsistencia', 'Compare asentamiento', 'Explique el cambio sin una escala de superioridad'] }),
      S.choice({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:6.2.1'], prompt: 'Al comparar evolucion y formas de vida cazadora, recolectora y agricultora, ¿que evidencia distingue movilidad y campamento de cultivo y aldea?', }, { options: [{ id: 'a', text: 'Campamentos estacionales frente a campos, almacenamiento y asentamiento mas permanente' }, { id: 'b', text: 'El color de las herramientas' }, { id: 'c', text: 'Una fecha unica para todo el mundo' }], correct: ['a'] }),
      S.choice({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:6.2.1'], prompt: 'Salida: compara evolucion y formas de vida cazadora-recolectora y agricultora mediante movilidad, campamento, cultivo y aldea.' }, { options: [{ id: 'a', text: 'Movilidad estacional y campamentos; luego cultivos, almacenamiento y aldeas en transiciones diversas' }, { id: 'b', text: 'Las formas de vida fueron identicas' }, { id: 'c', text: 'Toda sociedad abandono la recoleccion de inmediato' }], correct: ['a'] }),
      S.tf({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:6.2.1'], prompt: 'Salida nueva: distingue evolucion y formas de vida cazadora, recolectora y agricultora por movilidad, campamento, cultivo y aldea.' }, { statements: [{ text: 'La movilidad podia seguir ciclos estacionales.', answer: true }, { text: 'Cultivo y almacenamiento favorecieron asentamientos mas permanentes.', answer: true }, { text: 'La transicion fue instantanea e igual en todas partes.', answer: false }] }),
    ],
  }),
];
