/** Ciencias Sociales · Unidad 1 · Semana 5. */
import { lesson, S } from '../../../../dsl';

export default [
  lesson({
    id: 's05-ccss-1', title: 'Tecnologia y aportes de Egipto y Mesopotamia', icon: 'Landmark', minutes: 15,
    gancho: '¿Como ayudaron los rios, el riego y la organizacion a sostener ciudades antiguas?',
    objetivos: ['Organizar el desarrollo y los aportes de Egipto y Mesopotamia en un esquema'],
    resumen: ['Egipto se desarrollo junto al Nilo y Mesopotamia entre el Tigris y el Eufrates.', 'Canales, diques, arado y calendarios apoyaron la agricultura y requirieron organizacion.', 'Sus aportes pueden organizarse como politicos, economicos y culturales sin suponer que surgieron de una sola persona.'],
    media: { id: 's05-ccss-1-kit', kind: 'diagram', title: 'Dos civilizaciones fluviales', aspect: '16:9', alt: 'Mapa esquematico ubica Egipto y Mesopotamia junto a una matriz de tecnologia agricola y aportes politicos, economicos y culturales.', brief: 'Diagrama historico 1600x900. Ubicar Nilo, Tigris y Eufrates sin fronteras modernas. Incluir canales, diques y arado como desarrollo tecnologico/agricola. Agregar una matriz vacia con columnas POLITICO, ECONOMICO y CULTURAL para organizar aportes. Texto grande, alto contraste, flechas con etiquetas y nota "sintesis didactica; procesos desarrollados durante siglos".' },
    steps: [
      S.explain({ fase: 'explorar', areas: ['ccss'], cnb: ['ccss:6.3.1', 'ccss:6.3.5'], prompt: 'Relaciona el desarrollo tecnologico y agricola de Egipto y Mesopotamia con aportes politicos, economicos y culturales organizados en un esquema.' }, { icon: 'Map', body: '**Egipto**, junto al Nilo, y **Mesopotamia**, entre Tigris y Eufrates, desarrollaron riego y agricultura. Su organizacion produjo aportes **politicos, economicos y culturales** que pueden esquematizarse.' }),
      S.explain({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:6.3.1', 'ccss:6.3.5'], title: 'Agua, agricultura y organizacion', prompt: 'Compara tecnologia agricola y organiza aportes de Egipto y Mesopotamia en dimensiones politicas, economicas y culturales.' }, { icon: 'TableProperties', body: 'Ambas sociedades usaron **canales, diques, arados y calendarios** para apoyar agricultura y almacenamiento. **Politico:** reyes, faraones, leyes y administracion. **Economico:** riego, excedentes, oficios y comercio. **Cultural:** escritura, matematicas, calendarios y arquitectura.' }),
      S.ejemplo({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:6.3.1', 'ccss:6.3.5'], title: 'Modelo: esquema comparativo', prompt: 'Observa como organizar tecnologia agricola y aportes politicos, economicos y culturales de Egipto y Mesopotamia.' }, { icon: 'Workflow', problem: '¿Donde colocar cada evidencia?', steps: [{ text: 'Egipto y Mesopotamia: canales y diques → desarrollo tecnologico y agricola.' }, { text: 'Administracion de obras y leyes → aporte politico.' }, { text: 'Excedentes, oficios y comercio → aporte economico.' }, { text: 'Jeroglificos, cuneiforme, calendarios y arquitectura → aporte cultural.' }], answer: 'El esquema relaciona tecnologia agricola con organizacion y clasifica aportes sin mezclar dimensiones.' }),
      S.sort({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:6.3.1', 'ccss:6.3.5'], prompt: 'Guia: organiza el desarrollo agricola de Egipto y Mesopotamia y sus aportes politicos, economicos y culturales.', hint: 'Pregunta si la evidencia trata poder y leyes, produccion e intercambio, o conocimientos y expresiones.', explain: 'Canales y arados apoyaron agricultura; la administracion, los excedentes y la escritura muestran dimensiones distintas.' }, { buckets: [{ id: 'p', label: 'Politico', icon: 'Scale', color: 'var(--area-ccss)' }, { id: 'e', label: 'Economico', icon: 'Store', color: 'var(--c-maiz-strong)' }, { id: 'c', label: 'Cultural', icon: 'BookOpen', color: 'var(--area-l1)' }], items: [{ id: 'a', text: 'Administracion de canales y leyes', bucket: 'p' }, { id: 'b', text: 'Excedentes agricolas y comercio', bucket: 'e' }, { id: 'c', text: 'Escritura cuneiforme y jeroglifica', bucket: 'c' }] }),
      S.choice({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:6.3.1', 'ccss:6.3.5'], prompt: '¿Que esquema relaciona tecnologia y agricultura de Egipto y Mesopotamia con aportes politicos, economicos y culturales?' }, { options: [{ id: 'a', text: 'Canales y arados-agricultura; administracion-politico; excedentes-economico; escrituras-cultural' }, { id: 'b', text: 'Pirámide-politico; todos los demas aportes-cultural' }, { id: 'c', text: 'Los rios realizaron por si solos toda la organizacion' }], correct: ['a'] }),
      S.write({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:6.3.1', 'ccss:6.3.5'], prompt: 'Organiza un esquema textual: desarrollo tecnologico/agricola de Egipto y Mesopotamia y un aporte politico, economico y cultural de cada civilizacion.' }, { minWords: 28, placeholder: 'Egipto → agricultura... Politico... Mesopotamia →...', model: 'Egipto y Mesopotamia desarrollaron sistemas de riego para apoyar la agricultura. En lo politico organizaron administraciones; en lo economico produjeron excedentes; y en lo cultural crearon escrituras, calendarios y conocimientos matematicos.', rubric: ['Inclui ambas civilizaciones', 'Relacione tecnologia y agricultura', 'Organice aportes en tres dimensiones'] }),
      S.choice({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:6.3.1', 'ccss:6.3.5'], prompt: 'En un esquema de Egipto y Mesopotamia, ¿como se organizan tecnologia agricola y aportes politicos, economicos y culturales?' }, { options: [{ id: 'a', text: 'Riego y arado apoyan agricultura; administracion es politica, excedentes son economicos y escritura es cultural' }, { id: 'b', text: 'Toda evidencia pertenece solo a cultura' }, { id: 'c', text: 'Agricultura y tecnologia no se relacionaron con organizacion' }], correct: ['a'] }),
      S.tf({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:6.3.1', 'ccss:6.3.5'], prompt: 'Comprueba el esquema de tecnologia agricola y aportes politicos, economicos y culturales de Egipto y Mesopotamia.' }, { statements: [{ text: 'Canales y diques apoyaron la agricultura y exigieron organizacion.', answer: true }, { text: 'Excedentes y comercio son aportes economicos.', answer: true }, { text: 'Escritura y calendarios fueron tecnologias agricolas sin dimension cultural.', answer: false }] }),
      S.reflect({ fase: 'reflexionar', areas: ['ccss'], cnb: ['ccss:6.3.1', 'ccss:6.3.5'], prompt: 'Revisa las relaciones de tu esquema.' }, { statements: ['Diferencie ambas civilizaciones', 'Relacione agricultura y tecnologia', 'Clasifique aportes en tres dimensiones'], commitments: ['Evitare atribuir procesos largos a una sola causa'] }),
    ],
  }),

  lesson({
    id: 's05-ccss-2', title: 'Factores de los viajes europeos', icon: 'Compass', minutes: 14,
    gancho: '¿Por que los viajes europeos por el Atlantico aumentaron durante los siglos XV y XVI?',
    objetivos: ['Explicar factores combinados que favorecieron la llegada europea a America y otros pueblos'],
    resumen: ['El Renacimiento estimulo estudio y recuperacion de conocimientos; la imprenta amplio la circulacion de informacion.', 'La expansion comercial y maritima impulso la busqueda de rutas y recursos.', 'Brujula, astrolabio, cartografia y carabelas facilitaron navegacion; ningun factor explica por si solo la llegada ni sus consecuencias para otros pueblos.'],
    media: { id: 's05-ccss-2-cambio', kind: 'diagram', title: 'Factores conectados de los viajes', aspect: '16:9', alt: 'Red causal conecta Renacimiento, imprenta, expansion comercial y tecnologia de navegacion con viajes europeos y llegada a pueblos de America.', brief: 'Diagrama historico 1600x900 en forma de red. Cuatro nodos: RENACIMIENTO, IMPRENTA, EXPANSION MARITIMA Y COMERCIAL, y NAVEGACION (brujula, astrolabio, cartografia, carabela). Flechas convergen en VIAJES EUROPEOS y CONTACTO/LLEGADA A AMERICA Y OTROS PUEBLOS. Incluir nota "factores combinados; no justifica conquista ni violencia". Alto contraste, texto legible y sin imagen heroica de conquistadores.' },
    steps: [
      S.explain({ fase: 'explorar', areas: ['ccss'], cnb: ['ccss:6.4.4'], prompt: 'Explica como Renacimiento, imprenta, expansion maritima y comercial, y tecnologia de navegacion favorecieron viajes y llegada europea a America y otros pueblos.' }, { icon: 'Compass', body: 'La llegada europea no tuvo una sola causa. Se combinaron **Renacimiento, imprenta, expansion maritima y comercial**, y herramientas de **navegacion** como brujula, astrolabio, mapas y carabelas.' }),
      S.explain({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:6.4.4'], title: 'Una red de factores', prompt: 'Relaciona ideas, informacion, comercio y navegacion con la llegada europea a America y otros pueblos.' }, { icon: 'Network', body: 'El **Renacimiento** estimulo estudio; la **imprenta** difundio informacion; la expansion **comercial y maritima** motivo buscar rutas; la tecnologia de **navegacion** facilito travesias. Juntas favorecieron viajes europeos que llegaron a America y a otros pueblos, con contactos, conquistas y efectos desiguales.' }),
      S.ejemplo({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:6.4.4'], title: 'Modelo: factores que se conectan', prompt: 'Observa como explicar Renacimiento, imprenta, comercio y navegacion sin elegir una causa unica.' }, { icon: 'GitBranch', problem: '¿Como se construye una explicacion multifactorial de la llegada europea?', steps: [{ text: 'Renacimiento → interes por estudiar el mundo.' }, { text: 'Imprenta → mayor circulacion de mapas y conocimientos.' }, { text: 'Expansion comercial y maritima → busqueda de rutas.' }, { text: 'Brujula, astrolabio, cartografia y carabelas → navegacion de larga distancia.' }, { text: 'Factores combinados → viajes y llegada a America y otros pueblos.' }], answer: 'Ningun elemento explica por si solo el proceso.' }),
      S.match({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:6.4.4'], prompt: 'Guia: relaciona Renacimiento, imprenta, expansion comercial/maritima y tecnologia de navegacion con los viajes y la llegada europea a America y otros pueblos.', hint: 'Ideas, difusion, motivacion comercial y capacidad tecnica cumplen funciones distintas.', explain: 'Los cuatro factores se complementaron; no conviertas uno en causa unica.' }, { pairs: [{ id: 'a', left: 'Renacimiento', right: 'Estudio y recuperacion de conocimientos' }, { id: 'b', left: 'Imprenta', right: 'Circulacion mas amplia de informacion' }, { id: 'c', left: 'Expansion comercial y maritima', right: 'Busqueda de rutas y recursos' }, { id: 'd', left: 'Tecnologia de navegacion', right: 'Facilito travesias largas' }] }),
      S.choice({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:6.4.4'], prompt: '¿Que explicacion combina Renacimiento, imprenta, expansion maritima/comercial y navegacion para explicar viajes y llegada europea a America y otros pueblos?' }, { options: [{ id: 'a', text: 'Ideas y conocimientos circularon, crecieron intereses comerciales y nuevas tecnicas facilitaron travesias' }, { id: 'b', text: 'La brujula causo por si sola todos los viajes' }, { id: 'c', text: 'Los pueblos de America solicitaron la conquista europea' }], correct: ['a'] }),
      S.write({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:6.4.4'], prompt: 'Explica en una red breve como Renacimiento, imprenta, expansion maritima y comercial, y tecnologia de navegacion favorecieron la llegada europea a America y otros pueblos.' }, { minWords: 26, placeholder: 'Renacimiento... Imprenta... Comercio... Navegacion...', model: 'El Renacimiento impulso nuevos estudios, la imprenta difundio informacion, el comercio motivo la busqueda de rutas y los avances de navegacion facilitaron viajes europeos hacia America y otros pueblos.', rubric: ['Inclui los cuatro factores', 'Explique su relacion', 'Evite una causa unica o una justificacion de la conquista'] }),
      S.choice({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:6.4.4'], prompt: 'Para explicar la llegada europea a America y otros pueblos, ¿que relacion integra Renacimiento, imprenta, expansion comercial/maritima y navegacion?' }, { options: [{ id: 'a', text: 'Estudio + difusion de informacion + busqueda de rutas + tecnicas para travesias' }, { id: 'b', text: 'Una sola invencion produjo todo el proceso' }, { id: 'c', text: 'No hubo intereses comerciales' }], correct: ['a'] }),
      S.tf({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:6.4.4'], prompt: 'Evalua los factores Renacimiento, imprenta, expansion maritima/comercial y navegacion en los viajes y la llegada europea a America y otros pueblos.' }, { statements: [{ text: 'La imprenta pudo ampliar la circulacion de informacion.', answer: true }, { text: 'La expansion comercial motivo buscar rutas.', answer: true }, { text: 'El Renacimiento fue la unica causa de la llegada.', answer: false }] }),
      S.reflect({ fase: 'reflexionar', areas: ['ccss'], cnb: ['ccss:6.4.4'], prompt: 'Revisa tu explicacion de factores historicos.' }, { statements: ['Inclui ideas, informacion, comercio y tecnologia', 'Relacione factores sin aislarlos', 'No presente la conquista como logro neutral'], commitments: ['Distinguire explicacion historica de justificacion'] }),
    ],
  }),

  lesson({
    id: 's05-ccss-3', title: 'Causas y consecuencias de las guerras mundiales', icon: 'History', minutes: 15,
    gancho: '¿Por que una guerra mundial no puede explicarse con una sola causa?',
    objetivos: ['Relacionar causas y consecuencias de la Primera y Segunda Guerra Mundial'],
    resumen: ['La Primera Guerra Mundial surgio de varios factores: rivalidades imperialistas, militarismo, nacionalismos, alianzas y una crisis detonante.', 'La Segunda Guerra Mundial tuvo factores como consecuencias no resueltas de la primera guerra, expansionismo, fascismo y nazismo, crisis y fracaso de la seguridad colectiva.', 'Ambas produjeron millones de muertes, desplazamiento y destruccion; la segunda incluyo el Holocausto y fue seguida por la ONU y un nuevo orden internacional.'],
    media: { id: 's05-ccss-3-mapa', kind: 'diagram', title: 'Dos guerras, multiples factores e impactos', aspect: '16:9', alt: 'Linea de tiempo compara causas multiples y consecuencias humanas y politicas de la Primera y Segunda Guerra Mundial.', brief: 'Linea de tiempo historica 1600x900 con dos tramos: PRIMERA GUERRA MUNDIAL (1914-1918) y SEGUNDA GUERRA MUNDIAL (1939-1945). En cada tramo mostrar varios factores y consecuencias humanas, economicas, territoriales y politicas. Incluir Holocausto como persecucion y asesinato sistematico de seis millones de judios y millones de otras victimas, con lenguaje sobrio y sin imagenes violentas. Texto grande, alto contraste y nota "sintesis; ninguna guerra se explica por una sola causa".' },
    steps: [
      S.explain({ fase: 'explorar', areas: ['ccss'], cnb: ['ccss:6.5.1'], prompt: 'Relaciona multiples factores y consecuencias de la Primera Guerra Mundial y la Segunda Guerra Mundial; ninguna se explica por una sola causa.' }, { icon: 'History', body: 'En ambas guerras hubo **multiples factores**. Distinguir condiciones de largo plazo, decisiones, detonantes y consecuencias evita una explicacion de causa unica.' }),
      S.explain({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:6.5.1'], title: 'Dos redes historicas', prompt: 'Compara causas y consecuencias de la Primera y Segunda Guerra Mundial mediante multiples factores.' }, { icon: 'Network', body: '**Primera Guerra Mundial:** imperialismo, militarismo, nacionalismos, alianzas y crisis de 1914; consecuencias: muertes, desplazamiento, destruccion y cambios territoriales. **Segunda Guerra Mundial:** tensiones no resueltas, crisis, expansionismo, fascismo y nazismo; consecuencias: muertes masivas, Holocausto, desplazamiento, destruccion, ONU y nuevo orden internacional. No se explica ninguna por una sola causa.' }),
      S.ejemplo({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:6.5.1'], title: 'Modelo: factor, detonante y consecuencia', prompt: 'Observa como relacionar multiples factores y consecuencias en la Primera y Segunda Guerra Mundial.' }, { icon: 'Workflow', problem: '¿Como evitar decir que un solo hecho causo todo?', steps: [{ text: 'Primera: alianzas y militarismo ya creaban tension; el asesinato de Sarajevo fue un detonante, no la unica causa.' }, { text: 'Segunda: expansionismo nazi, fascismo, crisis y tensiones posteriores a 1918 se combinaron.' }, { text: 'Consecuencias comunes: muertes, desplazamiento y destruccion.' }, { text: 'Consecuencias especificas: cambios territoriales tras la primera; Holocausto y creacion de la ONU tras la segunda.' }], answer: 'La relacion usa multiples factores, detonantes y consecuencias.' }),
      S.sort({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:6.5.1'], prompt: 'Guia: organiza multiples factores y consecuencias de la Primera y Segunda Guerra Mundial.', hint: 'Distingue el proceso de 1914-1918 del de 1939-1945 y separa causa de consecuencia.', explain: 'Un detonante acelera una crisis; no reemplaza los demas factores.' }, { buckets: [{ id: 'p', label: 'Primera Guerra Mundial', icon: 'Calendar', color: 'var(--area-ccss)' }, { id: 's', label: 'Segunda Guerra Mundial', icon: 'CalendarDays', color: 'var(--c-maiz-strong)' }], items: [{ id: 'a', text: 'Sistema de alianzas y crisis de 1914', bucket: 'p' }, { id: 'b', text: 'Expansionismo nazi e invasion de Polonia', bucket: 's' }, { id: 'c', text: 'Tratados y cambios territoriales posteriores a 1918', bucket: 'p' }, { id: 'd', text: 'Holocausto y creacion posterior de la ONU', bucket: 's' }] }),
      S.choice({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:6.5.1'], prompt: '¿Que analisis relaciona multiples factores y consecuencias de la Primera Guerra Mundial y la Segunda Guerra Mundial sin afirmar una sola causa?' }, { options: [{ id: 'a', text: 'La primera combino rivalidades, alianzas y militarismo; la segunda, tensiones no resueltas, expansionismo y fascismo; ambas causaron muerte, desplazamiento y destruccion' }, { id: 'b', text: 'Cada guerra tuvo exactamente una causa y ninguna consecuencia social' }, { id: 'c', text: 'Las dos guerras fueron el mismo conflicto sin diferencias' }], correct: ['a'] }),
      S.write({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:6.5.1'], prompt: 'Compara multiples factores y dos consecuencias de la Primera Guerra Mundial y la Segunda Guerra Mundial. Explica por que ninguna tuvo una sola causa.' }, { minWords: 30, placeholder: 'Primera: factores... consecuencias... Segunda...', model: 'La Primera Guerra Mundial combino alianzas, rivalidades y militarismo. La Segunda combino expansionismo, fascismo y tensiones previas. Ambas causaron muerte y desplazamiento; ninguna se explica por una sola causa aislada.', rubric: ['Inclui ambas guerras', 'Nombre multiples factores', 'Relacione consecuencias con cuidado historico'] }),
      S.choice({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:6.5.1'], prompt: '¿Que opcion compara multiples factores y consecuencias de la Primera Guerra Mundial y la Segunda Guerra Mundial, pues ninguna se explica por una sola causa?' }, { options: [{ id: 'a', text: 'Alianzas y rivalidades influyeron en la primera; expansionismo y fascismo en la segunda; ambas dejaron muertes, desplazamiento y destruccion' }, { id: 'b', text: 'Sarajevo explica por si solo ambas guerras' }, { id: 'c', text: 'Las guerras no cambiaron fronteras ni sociedades' }], correct: ['a'] }),
      S.tf({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:6.5.1'], prompt: 'Comprueba multiples factores y consecuencias de la Primera Guerra Mundial y la Segunda Guerra Mundial; ninguna se explica por una sola causa.' }, { statements: [{ text: 'El asesinato de Sarajevo fue detonante dentro de tensiones previas.', answer: true }, { text: 'Expansionismo, fascismo y tensiones no resueltas influyeron en la segunda guerra.', answer: true }, { text: 'Las dos guerras tuvieron una sola causa y no produjeron desplazamientos.', answer: false }] }),
      S.reflect({ fase: 'reflexionar', areas: ['ccss'], cnb: ['ccss:6.5.1'], prompt: 'Revisa tu comparacion historica.' }, { statements: ['Diferencie factor, detonante y consecuencia', 'Inclui ambas guerras', 'Evite una causa unica'], commitments: ['Usare lenguaje sobrio al tratar violencia historica'] }),
    ],
  }),
];
