/** Ciencias Sociales · Unidad 1 · Semana 6. */
import { lesson, S } from '../../../../dsl';

export default [
  lesson({
    id: 's06-ccss-1', title: 'Guerra Fría, conflicto y sociedad civil', icon: 'History', minutes: 15,
    gancho: '¿Cómo influyó una rivalidad mundial en Guatemala y qué consecuencias vivió la población civil?',
    objetivos: ['Analizar la relación entre Guerra Fría, conflicto armado interno e impacto en la sociedad civil'],
    resumen: ['La Guerra Fría fue una rivalidad política, económica e ideológica con repercusiones mundiales.', 'En Guatemala influyó en el conflicto armado interno, pero no fue su única causa.', 'La sociedad civil sufrió violencia, desplazamiento y daños a comunidades, y también desarrolló formas de organización y defensa de derechos.'],
    media: { id: 's06-ccss-1-guerra-fria', kind: 'diagram', title: 'Contexto e impactos del conflicto', aspect: '16:9', alt: 'Línea de tiempo de 1960 a 1996 con contexto de Guerra Fría, conflicto armado interno y efectos sobre población civil.', brief: 'Diagrama horizontal 1600×900, sin imágenes gráficas. Separar CONTEXTO INTERNACIONAL, CONFLICTO ARMADO INTERNO e IMPACTO EN SOCIEDAD CIVIL. Incluir una nota de atribución a Guatemala: Memoria del Silencio, CEH, 1999. Texto grande y alto contraste.' },
    steps: [
      S.explain({ fase: 'explorar', areas: ['ccss'], cnb: ['ccss:6.5.5', 'ccss:6.5.6'], title: 'Contexto no significa causa única', prompt: 'La Guerra Fría influyó en el conflicto armado interno de Guatemala y este tuvo un impacto profundo en la sociedad civil.' }, { icon: 'GitBranch', body: 'La rivalidad internacional reforzó apoyos, discursos anticomunistas y estrategias militares. También existían desigualdad, exclusión y conflictos políticos internos. La población civil no fue un actor uniforme y no debe confundirse con los grupos armados.' }),
      S.explain({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:6.5.5', 'ccss:6.5.6'], title: 'Fuente histórica autosuficiente', prompt: 'Lee la síntesis atribuida y distingue contexto, causas internas e impacto civil.' }, { icon: 'BookOpenCheck', body: '**Fuente:** Comisión para el Esclarecimiento Histórico, *Guatemala: Memoria del Silencio* (1999), síntesis didáctica. El conflicto armado interno ocurrió entre 1960 y 1996. La Guerra Fría influyó mediante anticomunismo, apoyos externos y doctrinas de seguridad, junto con causas internas como desigualdad, exclusión, racismo y cierre político. Los enfrentamientos afectaron gravemente a la sociedad civil mediante muertes, desapariciones, desplazamiento, ruptura comunitaria y daños económicos y culturales; la población maya fue afectada de manera desproporcionada. Familias, comunidades y organizaciones también buscaron verdad, derechos y paz.' }),
      S.ejemplo({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:6.5.5', 'ccss:6.5.6'], title: 'Modelo de relación e impacto', prompt: 'Relaciona Guerra Fría, conflicto armado interno y sociedad civil sin simplificar.' }, { icon: 'Workflow', problem: '¿Cómo construir una explicación histórica?', steps: [{ text: 'Contexto: rivalidad y anticomunismo de la Guerra Fría.' }, { text: 'Proceso: conflicto armado interno con causas internacionales e internas.' }, { text: 'Impacto: violencia y desplazamiento afectaron a población civil y comunidades.' }, { text: 'Respuesta civil: organización por derechos, verdad y paz.' }], answer: 'La Guerra Fría influyó, no determinó sola; el impacto civil debe evaluarse por evidencia.' }),
      S.match({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:6.5.5', 'ccss:6.5.6'], prompt: 'Relaciona evidencia y dimensión.', hint: 'Contexto explica influencia; impacto describe consecuencias para civiles.', explain: 'La clasificación evita llamar combatiente a toda la población.' }, { pairs: [{ id: 'a', left: 'Doctrinas anticomunistas y apoyos externos', right: 'Influencia de la Guerra Fría' }, { id: 'b', left: 'Desplazamiento y ruptura comunitaria', right: 'Impacto en sociedad civil' }, { id: 'c', left: 'Desigualdad y exclusión', right: 'Causas internas' }] }),
      S.sort({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:6.5.5', 'ccss:6.5.6'], prompt: 'Organiza afirmaciones de la fuente.', hint: 'No conviertas una influencia en causa única.', explain: 'Una explicación completa combina contexto, causas internas e impacto civil.' }, { buckets: [{ id: 's', label: 'Sustentada', icon: 'BadgeCheck', color: 'var(--c-ok)' }, { id: 'x', label: 'Simplificación', icon: 'TriangleAlert', color: 'var(--c-maiz-strong)' }], items: [{ id: 'a', text: 'La Guerra Fría influyó en el conflicto armado interno', bucket: 's' }, { id: 'b', text: 'La Guerra Fría fue la única causa', bucket: 'x' }, { id: 'c', text: 'La sociedad civil sufrió impactos diferenciados', bucket: 's' }, { id: 'd', text: 'Toda persona civil pertenecía a un grupo armado', bucket: 'x' }] }),
      S.choice({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:6.5.5', 'ccss:6.5.6'], prompt: 'Caso histórico nuevo: durante la Guerra Fría aumentan apoyos militares y anticomunismo; en un conflicto armado interno hay desplazamiento de comunidades. ¿Qué análisis relaciona contexto e impacto en sociedad civil?' }, { options: [{ id: 'a', text: 'La rivalidad internacional pudo influir junto con causas internas; el desplazamiento muestra impacto sobre población civil' }, { id: 'b', text: 'La Guerra Fría explica por sí sola toda la violencia' }, { id: 'c', text: 'El desplazamiento demuestra que toda la población combatía' }], correct: ['a'] }),
      S.write({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:6.5.5', 'ccss:6.5.6'], prompt: 'Explica con la fuente cómo la Guerra Fría se relacionó con el conflicto armado interno y evalúa un impacto en la sociedad civil.' }, { minWords: 26, placeholder: 'La Guerra Fría influyó... El conflicto afectó...', model: 'La Guerra Fría influyó mediante anticomunismo y apoyos externos, junto con causas internas. El conflicto desplazó comunidades, rompió vínculos y dañó profundamente la vida de la población civil.', rubric: ['Relacioné contexto y conflicto', 'Evalué impacto civil', 'Evité una causa única'] }),
      S.choice({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:6.5.5', 'ccss:6.5.6'], prompt: '¿Qué explicación relaciona Guerra Fría y conflicto armado interno y evalúa impacto en la sociedad civil?' }, { options: [{ id: 'a', text: 'La Guerra Fría influyó junto con causas internas; violencia y desplazamiento afectaron a población civil y comunidades' }, { id: 'b', text: 'La población civil inició la Guerra Fría' }, { id: 'c', text: 'El conflicto no tuvo consecuencias sociales' }], correct: ['a'] }),
      S.tf({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:6.5.5', 'ccss:6.5.6'], prompt: 'Evalúa la relación entre Guerra Fría, conflicto armado interno e impacto en sociedad civil.' }, { statements: [{ text: 'La Guerra Fría influyó, pero causas internas también importaron.', answer: true }, { text: 'Desplazamiento y ruptura comunitaria fueron impactos sobre población civil.', answer: true }, { text: 'Toda la sociedad civil formó parte de movimientos armados.', answer: false }] }),
      S.reflect({ fase: 'reflexionar', areas: ['ccss'], cnb: ['ccss:6.5.5', 'ccss:6.5.6'], prompt: 'Revisa tu explicación histórica.' }, { statements: ['Diferencié influencia y causa única', 'Reconocí el impacto civil', 'Usé lenguaje respetuoso'], commitments: ['Consultaré fuentes de memoria histórica con cuidado'] }),
    ],
  }),

  lesson({
    id: 's06-ccss-2', title: 'Apertura democrática y condiciones de vida', icon: 'Vote', minutes: 15,
    gancho: '¿Volver a elecciones competitivas mejora automáticamente empleo, educación, salud o agua?',
    objetivos: ['Relacionar la apertura democrática latinoamericana con avances, desafíos y condiciones socioeconómicas'],
    resumen: ['En América Latina, varias transiciones desde regímenes autoritarios ampliaron elecciones y participación política.', 'Esos avances coexistieron con desigualdad, violencia, exclusión e instituciones débiles.', 'Los procesos políticos pueden influir en políticas y servicios, pero no garantizan mejoras socioeconómicas automáticas.'],
    media: { id: 's06-ccss-2-apertura', kind: 'diagram', title: 'Apertura y condiciones de vida', aspect: '16:9', alt: 'Matriz con transición política, avance democrático, condición económica o social y desafío en Guatemala y Chile.', brief: 'Matriz histórica 1600×900. Dos filas: Guatemala 1985–1986 y Chile 1988–1990. Columnas PROCESO, AVANCE, CONDICIÓN SOCIOECONÓMICA y DESAFÍO. No usar retratos ni respuestas de evaluación. Texto grande, alto contraste y nota de síntesis histórica.' },
    steps: [
      S.explain({ fase: 'explorar', areas: ['ccss'], cnb: ['ccss:6.7.1', 'ccss:6.7.4'], title: 'Avance político y desafío social', prompt: 'En América Latina, una transición desde régimen autoritario hacia gobierno civil y elecciones puede influir en empleo, educación, salud, agua y desigualdad, pero no garantiza resolverlos.' }, { icon: 'Landmark', body: 'La **apertura democrática** amplía derechos políticos y participación. Sus avances se evalúan junto con desafíos persistentes y condiciones económicas y sociales de habitantes.' }),
      S.explain({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:6.7.1', 'ccss:6.7.4'], title: 'Dos fichas históricas', prompt: 'Compara proceso, avance, condición y desafío en dos aperturas democráticas latinoamericanas.' }, { icon: 'LibraryBig', body: '**Guatemala:** la Constitución de 1985 y el gobierno civil electo en 1986 formaron parte de una apertura democrática. Se ampliaron elecciones y participación política, mientras el conflicto armado continuó hasta 1996; persistieron desigualdad, exclusión, violencia y acceso desigual a servicios. **Chile:** el plebiscito de 1988 abrió el camino a un gobierno civil electo en 1990. Volvieron elecciones competitivas y participación política; persistieron desigualdades y límites institucionales. En ambos casos, el proceso político pudo influir en políticas de empleo, educación, salud y agua, pero no garantizó mejores condiciones por sí solo. Fuente: síntesis didáctica de hechos constitucionales y electorales ampliamente documentados.' }),
      S.ejemplo({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:6.7.1', 'ccss:6.7.4'], title: 'Modelo de matriz', prompt: 'Relaciona apertura democrática latinoamericana y condiciones de vida.' }, { icon: 'TableProperties', problem: 'Transición a gobierno civil con desigualdad persistente.', steps: [{ text: 'Proceso: transición desde régimen autoritario.' }, { text: 'Avance: elecciones competitivas y participación política.' }, { text: 'Condición: acceso desigual a educación, salud o agua.' }, { text: 'Desafío: instituciones débiles pueden limitar políticas; la apertura no garantiza igualdad.' }], answer: 'Se reconoce un avance democrático y un desafío socioeconómico simultáneo.' }),
      S.sort({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:6.7.1', 'ccss:6.7.4'], prompt: 'Clasifica elementos de una apertura democrática latinoamericana.', hint: 'Avance amplía derechos; desafío o condición muestra lo pendiente.', explain: 'Los procesos políticos pueden influir en condiciones sin resolverlas automáticamente.' }, { buckets: [{ id: 'a', label: 'Avance', icon: 'Vote', color: 'var(--c-ok)' }, { id: 'd', label: 'Condición o desafío', icon: 'TriangleAlert', color: 'var(--c-maiz-strong)' }], items: [{ id: 'x', text: 'Elecciones competitivas y participación política', bucket: 'a' }, { id: 'y', text: 'Desigualdad y acceso desigual a servicios', bucket: 'd' }, { id: 'z', text: 'Gobierno civil electo', bucket: 'a' }, { id: 'w', text: 'Violencia e instituciones débiles persistentes', bucket: 'd' }] }),
      S.match({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:6.7.1', 'ccss:6.7.4'], prompt: 'Relaciona proceso político y posible efecto, sin garantía.', hint: 'Usa “puede influir” y conserva desafíos.', explain: 'Presupuesto e instituciones conectan decisiones con condiciones de vida.' }, { pairs: [{ id: 'a', left: 'Elecciones competitivas', right: 'Pueden cambiar quién decide políticas y presupuestos' }, { id: 'b', left: 'Participación política', right: 'Puede abrir demandas sobre empleo y servicios' }, { id: 'c', left: 'Instituciones débiles', right: 'Pueden limitar la aplicación de políticas' }] }),
      S.choice({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:6.7.1', 'ccss:6.7.4'], prompt: 'En América Latina, una transición desde régimen autoritario trae gobierno civil, elecciones competitivas y participación política; persisten desigualdad, desempleo y acceso desigual al agua. ¿Qué análisis relaciona avance, desafío y condiciones?' }, { options: [{ id: 'a', text: 'Hay avance democrático; el proceso puede influir en políticas, pero no garantiza resolver condiciones socioeconómicas' }, { id: 'b', text: 'Las elecciones garantizan igualdad y servicios' }, { id: 'c', text: 'La desigualdad demuestra que no hubo ningún avance político' }], correct: ['a'] }),
      S.write({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:6.7.1', 'ccss:6.7.4'], prompt: 'Analiza una apertura democrática latinoamericana: transición o proceso político, avance, desafío y relación posible con empleo, educación, salud o agua.' }, { minWords: 26, placeholder: 'Proceso... Avance... Desafío... Relación...', model: 'La transición amplió elecciones y participación ciudadana. Persistieron desigualdad e instituciones débiles. El proceso político puede influir en empleo y servicios públicos, pero por sí solo no garantiza mejorarlos.', rubric: ['Nombré proceso y avance', 'Identifiqué desafío', 'Relacioné una condición sin garantía'] }),
      S.choice({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:6.7.1', 'ccss:6.7.4'], prompt: 'En América Latina, ¿qué opción relaciona transición, avance de apertura democrática, desafío y condiciones económicas o sociales?' }, { options: [{ id: 'a', text: 'Gobierno civil y elecciones amplían participación; desigualdad e instituciones débiles persisten y pueden limitar mejoras en empleo o servicios' }, { id: 'b', text: 'La elección elimina automáticamente pobreza y violencia' }, { id: 'c', text: 'Los procesos políticos nunca influyen en condiciones de vida' }], correct: ['a'] }),
      S.tf({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:6.7.1', 'ccss:6.7.4'], prompt: 'Evalúa cómo una apertura democrática latinoamericana puede influir en condiciones socioeconómicas: reconoce avances, desafíos y que el proceso político no garantiza mejoras automáticas.' }, { statements: [{ text: 'Una transición a gobierno civil puede ampliar participación política.', answer: true }, { text: 'Desigualdad, violencia o instituciones débiles pueden persistir tras el avance.', answer: true }, { text: 'Las elecciones garantizan empleo, educación, salud y agua iguales.', answer: false }] }),
      S.reflect({ fase: 'reflexionar', areas: ['ccss'], cnb: ['ccss:6.7.1', 'ccss:6.7.4'], prompt: 'Revisa tu análisis.' }, { statements: ['Diferencié avance y solución total', 'Relacioné política y condiciones', 'Conservé desafíos'], commitments: ['Evitaré causalidades automáticas'] }),
    ],
  }),

  lesson({
    id: 's06-ccss-3', title: 'Bloques americanos que cooperan', icon: 'Network', minutes: 14,
    gancho: '¿Cómo se reconoce un esfuerzo de integración y no solo el nombre o la ubicación de un bloque?',
    objetivos: ['Organizar esfuerzos reales de integración y cooperación de bloques americanos en un esquema'],
    resumen: ['Un bloque reúne países que coordinan objetivos mediante instrumentos.', 'CAN y CARICOM desarrollan esfuerzos regionales relacionados con ambiente, clima y agua.', 'Un esquema distingue miembros, preocupación, instrumento y acción conjunta.'],
    media: { id: 's06-ccss-3-bloques', kind: 'diagram', title: 'Cooperación regional', aspect: '16:9', alt: 'Mapa de América con Comunidad Andina y CARICOM junto a una matriz de miembros, preocupación, instrumento y esfuerzo.', brief: 'Diagrama horizontal 1600×900. Señalar región andina y Caribe sin fronteras disputadas. Matriz vacía con BLOQUE, MIEMBROS, PREOCUPACIÓN, INSTRUMENTO y ESFUERZO. Alto contraste, texto grande y nota de fuentes institucionales CAN y CARICOM.' },
    steps: [
      S.explain({ fase: 'explorar', areas: ['ccss'], cnb: ['ccss:6.6.6'], title: 'Cooperación significa acción conjunta', prompt: 'Organiza en un esquema esfuerzos de Comunidad Andina y CARICOM por agua, ambiente o clima: miembros, preocupación, instrumento y esfuerzo.' }, { icon: 'Network', body: 'Ubicar un bloque no basta. La cooperación regional se reconoce por una estrategia, marco, política u organismo que coordina información, planificación o acciones conjuntas.' }),
      S.explain({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:6.6.6'], title: 'Tarjetas institucionales resumidas', prompt: 'Identifica instrumento y acción de cooperación, no solo la subregión de cada bloque.' }, { icon: 'LibraryBig', body: '**Comunidad Andina (CAN):** Bolivia, Colombia, Ecuador y Perú integran este bloque. La Estrategia Andina para la Gestión Integrada de los Recursos Hídricos, aprobada mediante la Decisión 763, coordina planificación e intercambio de información y conocimientos. **CARICOM:** reúne Estados y territorios del Caribe. Ante preocupaciones de ambiente, clima y agua, cuenta con un marco regional de política ambiental y organismos de cooperación meteorológica que coordinan orientación e información técnica. Fuentes: síntesis de portales institucionales de CAN y CARICOM; no se afirma que los bloques administren servicios locales.' }),
      S.ejemplo({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:6.6.6'], title: 'Modelo de esquema comparativo', prompt: 'Organiza Comunidad Andina y CARICOM por miembros, preocupación, instrumento y esfuerzo.' }, { icon: 'Workflow', problem: 'Comparar cooperación regional por agua y clima.', steps: [{ text: 'CAN → países andinos → agua → Estrategia Andina → planificación e intercambio.' }, { text: 'CARICOM → miembros caribeños → ambiente, clima y agua → marco y organismo regional → orientación e información técnica.' }], answer: 'El esquema muestra esfuerzos concretos de dos bloques, no solo sus nombres.' }),
      S.sort({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:6.6.6'], prompt: 'Clasifica instrumentos y esfuerzos de Comunidad Andina y CARICOM.', hint: 'La estrategia hídrica es andina; el marco ambiental y la coordinación meteorológica son caribeños.', explain: 'El esquema organiza instrumento y esfuerzo por bloque.' }, { buckets: [{ id: 'can', label: 'Comunidad Andina', icon: 'Mountain', color: 'var(--area-ccss)' }, { id: 'car', label: 'CARICOM', icon: 'Waves', color: 'var(--c-maiz-strong)' }], items: [{ id: 'a', text: 'Estrategia Andina de recursos hídricos', bucket: 'can' }, { id: 'b', text: 'Planificación e intercambio hídrico', bucket: 'can' }, { id: 'c', text: 'Marco regional ambiental', bucket: 'car' }, { id: 'd', text: 'Información meteorológica coordinada', bucket: 'car' }] }),
      S.match({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:6.6.6'], prompt: 'Relaciona campo y evidencia para el esquema de CAN y CARICOM.', hint: 'Instrumento organiza; esfuerzo describe lo que hacen juntos.', explain: 'Miembros, preocupación, instrumento y esfuerzo forman una organización completa.' }, { pairs: [{ id: 'a', left: 'Instrumento CAN', right: 'Estrategia Andina hídrica' }, { id: 'b', left: 'Esfuerzo CAN', right: 'Intercambio de información' }, { id: 'c', left: 'Instrumento CARICOM', right: 'Marco ambiental regional' }, { id: 'd', left: 'Esfuerzo CARICOM', right: 'Coordinación técnica sobre clima y agua' }] }),
      S.sort({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:6.6.6'], prompt: 'Organiza un esquema nuevo de esfuerzos de Comunidad Andina y CARICOM por agua, ambiente y clima: miembros, instrumento y cooperación regional.', }, { buckets: [{ id: 'can', label: 'Esquema CAN', icon: 'Mountain', color: 'var(--area-ccss)' }, { id: 'car', label: 'Esquema CARICOM', icon: 'Waves', color: 'var(--c-maiz-strong)' }], items: [{ id: 'a', text: 'Países andinos · Estrategia hídrica · planificación conjunta', bucket: 'can' }, { id: 'b', text: 'Miembros caribeños · marco ambiental · coordinación técnica', bucket: 'car' }, { id: 'c', text: 'CAN · agua · intercambio de conocimientos', bucket: 'can' }, { id: 'd', text: 'CARICOM · clima y agua · información meteorológica', bucket: 'car' }] }),
      S.write({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:6.6.6'], prompt: 'Organiza en un esquema textual los esfuerzos de Comunidad Andina y CARICOM: miembros o subregión, preocupación de agua/ambiente/clima, instrumento y acción conjunta.' }, { minWords: 28, placeholder: 'CAN →... CARICOM →...', model: 'CAN → países andinos → gestión del agua → Estrategia Andina → planificación e intercambio regional entre miembros. CARICOM → países del Caribe → clima, ambiente y agua → marco regional → coordinación e información técnica compartida.', rubric: ['Incluí dos bloques', 'Nombré instrumentos', 'Organicé esfuerzos conjuntos'] }),
      S.choice({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:6.6.6'], prompt: '¿Qué esquema organiza esfuerzos de Comunidad Andina y CARICOM por agua, ambiente o clima mediante instrumento y cooperación regional?' }, { options: [{ id: 'a', text: 'CAN → Estrategia Andina → planificación e intercambio; CARICOM → marco ambiental → coordinación técnica e información' }, { id: 'b', text: 'CAN → Andes; CARICOM → Caribe' }, { id: 'c', text: 'Ambos bloques reparan directamente servicios locales' }], correct: ['a'] }),
      S.tf({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:6.6.6'], prompt: 'Evalúa el esquema de esfuerzos de Comunidad Andina y CARICOM por agua, ambiente y clima.' }, { statements: [{ text: 'La Estrategia Andina puede organizar planificación e intercambio sobre agua.', answer: true }, { text: 'El marco ambiental de CARICOM puede orientar coordinación e información técnica.', answer: true }, { text: 'Relacionar solo cada bloque con su subregión explica todo su esfuerzo de cooperación.', answer: false }] }),
      S.reflect({ fase: 'reflexionar', areas: ['ccss'], cnb: ['ccss:6.6.6'], prompt: 'Revisa tu esquema de cooperación.' }, { statements: ['Incluí dos bloques', 'Diferencié instrumento y esfuerzo', 'No atribuí servicios locales'], commitments: ['Buscaré acciones concretas, no solo nombres'] }),
    ],
  }),
];
