/** Ciencias Sociales · Unidad 1 · Semana 7. */
import { lesson, S } from '../../../../dsl';

export default [
  lesson({
    id: 's07-ccss-1', title: 'Comparar procesos de paz', icon: 'Handshake', minutes: 14,
    gancho: 'Dos países firman acuerdos de paz: ¿qué debemos comparar además de la fecha?',
    objetivos: ['Comparar procesos de paz por sus acuerdos, actores y formas de participación'],
    resumen: ['Un proceso de paz busca terminar o transformar un conflicto mediante negociación y acuerdos.', 'Para comparar se observan acuerdos, actores y participación social.', 'Firmar es un paso; implementar y vigilar los compromisos requiere participación continua.'],
    media: {
      id: 's07-ccss-1-mapa', kind: 'diagram', title: 'Dos procesos de paz para comparar', aspect: '16:9',
      alt: 'Mapa de América con Guatemala y Colombia señaladas y tres columnas vacías para acuerdos, actores y participación.',
      brief: 'Diagrama horizontal 1600×900. Mapa claro de América con Guatemala y Colombia señaladas, sin banderas. A la derecha, matriz con columnas ACUERDOS, ACTORES y PARTICIPACIÓN, sin respuestas completas. Incluir fechas 1996 y 2016 y rótulo FUENTES DIDÁCTICAS RESUMIDAS. Texto grande, contraste alto, lectura lineal y sin retratos de personas reales.',
    },
    steps: [
      S.explain({ fase: 'explorar', areas: ['ccss'], cnb: ['ccss:7.2.1'], title: 'Una comparación con criterios', prompt: 'Comparar no es solo nombrar países: se aplican los mismos criterios a cada proceso.' }, { icon: 'Columns3', body: 'Usaremos **acuerdos, actores y participación** para encontrar semejanzas y diferencias.' }),
      S.choice({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.2.1'], prompt: '¿Cuál pregunta compara actores?', explain: 'Los actores son las partes que negocian y quienes acompañan el proceso.' }, { options: [{ id: 'a', text: '¿Quiénes negociaron y quiénes acompañaron?' }, { id: 'b', text: '¿Qué color tenía el documento?' }, { id: 'c', text: '¿Cuál país está más al norte?' }], correct: ['a'] }),
      S.explain({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.2.1'], title: 'Tres criterios', prompt: 'Lee qué evidencia busca cada criterio.' }, { icon: 'ListChecks', body: 'Una comparación responsable se basa en fuentes identificadas y reconoce que cada proceso tiene un contexto propio.', reveal: [{ icon: 'ScrollText', front: 'Acuerdos', back: 'Compromisos sobre el fin de la violencia, derechos, participación o reformas.' }, { icon: 'Users', front: 'Actores', back: 'Gobierno, grupo armado y mediadores o acompañantes.' }, { icon: 'MessageCircle', front: 'Participación', back: 'Consultas, propuestas, votaciones, organizaciones y seguimiento ciudadano.' }] }),
      S.reading({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.2.1'], prompt: 'Lee las dos fichas didácticas resumidas.', hint: 'Subraya mentalmente un acuerdo, los actores y una forma de participación.', explain: 'Las fichas ofrecen los mismos tres campos para poder comparar.' }, { genre: 'Fichas históricas resumidas', heading: 'Guatemala 1996 y Colombia 2016', passage: 'FICHA A · Guatemala. El Gobierno de Guatemala y la URNG firmaron el Acuerdo de Paz Firme y Duradera en 1996, con acompañamiento de Naciones Unidas. El conjunto de acuerdos incluyó compromisos sobre derechos humanos, identidad y derechos de los pueblos indígenas, participación y reformas. Organizaciones sociales aportaron propuestas en la Asamblea de la Sociedad Civil.\n\nFICHA B · Colombia. El Gobierno de Colombia y las FARC-EP firmaron el Acuerdo Final en 2016, con acompañamiento internacional. Incluyó compromisos sobre fin del conflicto, participación política, desarrollo rural, víctimas y reincorporación. Hubo foros y propuestas ciudadanas; el texto fue sometido a plebiscito y luego ajustado.', questions: [{ q: '¿Qué semejanza de actores aparece?', options: [{ id: 'a', text: 'En ambos negociaron un gobierno y un grupo armado, con acompañamiento internacional' }, { id: 'b', text: 'En ambos negoció solo el estudiantado' }, { id: 'c', text: 'No hubo acompañamiento' }], correct: 'a' }] }),
      S.ejemplo({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.2.1'], title: 'Modelo de comparación', prompt: 'Construye una afirmación con semejanza, diferencia y evidencia.' }, { icon: 'GitCompare', problem: '¿Cómo se comparan las formas de participación?', steps: [{ text: 'Guatemala: organizaciones presentaron propuestas mediante la Asamblea de la Sociedad Civil.' }, { text: 'Colombia: hubo foros, propuestas y un plebiscito; después se ajustó el texto.' }, { text: 'Semejanza: en ambos hubo participación fuera de las partes negociadoras.' }, { text: 'Diferencia: las formas concretas de participación no fueron iguales.' }], answer: 'La comparación nombra los dos procesos y usa el mismo criterio.' }),
      S.match({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.2.1'], prompt: 'Relaciona evidencia y criterio.', hint: 'Compromiso = acuerdo; quién interviene = actor; aporte social = participación.', explain: 'El criterio organiza la evidencia sin mezclarla.' }, { leftTitle: 'Evidencia', rightTitle: 'Criterio', pairs: [{ id: 'a', left: 'Gobierno y URNG', right: 'Actores' }, { id: 'b', left: 'Compromisos sobre derechos humanos', right: 'Acuerdos' }, { id: 'c', left: 'Propuestas de organizaciones sociales', right: 'Participación' }, { id: 'd', left: 'Gobierno y FARC-EP', right: 'Actores' }] }),
      S.sort({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:7.2.1'], prompt: 'Completa la matriz comparativa con datos de las fichas.', explain: 'Cada dato se ubica por proceso y criterio.' }, { buckets: [{ id: 'gua', label: 'Guatemala 1996', icon: 'MapPin', color: 'var(--area-ccss)' }, { id: 'col', label: 'Colombia 2016', icon: 'MapPin', color: 'var(--c-maiz-strong)' }], items: [{ id: 'a', text: 'Actor: URNG', bucket: 'gua' }, { id: 'b', text: 'Actor: FARC-EP', bucket: 'col' }, { id: 'c', text: 'Participación: Asamblea de la Sociedad Civil', bucket: 'gua' }, { id: 'd', text: 'Participación: foros y plebiscito', bucket: 'col' }, { id: 'e', text: 'Acuerdo: identidad y derechos de pueblos indígenas', bucket: 'gua' }, { id: 'f', text: 'Acuerdo: desarrollo rural y reincorporación', bucket: 'col' }] }),
      S.write({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:7.2.1'], prompt: 'Compara Guatemala 1996 y Colombia 2016: una semejanza y una diferencia que incluyan acuerdos, actores y participación.', explain: 'La respuesta debe usar datos de ambas fichas y los tres criterios.' }, { minWords: 30, placeholder: 'Semejanza: ...\nDiferencia: ...', model: 'En ambos participaron un gobierno y un grupo armado y hubo aportes sociales. Cambiaron los acuerdos específicos y la participación: Guatemala tuvo la Asamblea de la Sociedad Civil; Colombia, foros y plebiscito.', rubric: ['Nombré ambos procesos', 'Comparé acuerdos y actores', 'Comparé participación'] }),
      S.choice({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:7.2.1'], prompt: '¿Qué opción compara correctamente acuerdos y actores de los dos procesos?' }, { options: [{ id: 'a', text: 'Ambos reunieron gobierno y grupo armado; sus acuerdos compartieron el fin del conflicto, pero incluyeron compromisos específicos distintos' }, { id: 'b', text: 'Fueron idénticos porque ocurrieron en América' }, { id: 'c', text: 'Solo importa la fecha de firma' }], correct: ['a'] }),
      S.choice({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:7.2.1'], prompt: '¿Qué diferencia de participación está respaldada por las fichas?' }, { options: [{ id: 'a', text: 'Guatemala incluyó propuestas de la Asamblea de la Sociedad Civil; Colombia tuvo foros y plebiscito' }, { id: 'b', text: 'Ningún proceso recibió aportes sociales' }, { id: 'c', text: 'Solo participaron personas extranjeras' }], correct: ['a'] }),
    ],
  }),

  lesson({
    id: 's07-ccss-2', title: 'Jóvenes que practican una cultura de paz', icon: 'MessageCircle', minutes: 13,
    gancho: '¿Qué puede hacer un grupo de jóvenes cuando dos equipos quieren usar el mismo espacio?',
    objetivos: ['Analizar cómo la participación juvenil democrática responde pacíficamente a un conflicto social'],
    resumen: ['La apertura democrática amplía espacios para opinar y decidir, pero la desigualdad y la exclusión pueden limitar quién participa.', 'La juventud practica cultura de paz cuando escucha necesidades, propone acuerdos y da seguimiento sin suponer que el diálogo resuelve por sí solo las condiciones sociales.'],
    media: {
      id: 's07-ccss-2-mediacion', kind: 'diagram', title: 'Ruta de mediación juvenil', aspect: '16:9',
      alt: 'Cuatro escenas muestran a jóvenes escuchando necesidades, proponiendo opciones, acordando turnos y revisando el acuerdo.',
      brief: 'Diagrama horizontal 1600×900 en cuatro escenas numeradas: ESCUCHAR, RESUMIR, PROPONER y REVISAR. Mostrar dos grupos juveniles diversos alrededor de una pila escolar ficticia y una estudiante mediadora que no impone la decisión. Rótulos grandes, contraste alto, flechas con patrón además de color y lectura de izquierda a derecha. No incluir respuestas de evaluación ni estereotipos culturales.',
    },
    steps: [
      S.explain({ fase: 'explorar', areas: ['ccss'], cnb: ['ccss:7.1.2', 'ccss:7.2.5', 'ccss:6.7.1', 'ccss:6.7.4'], title: 'Participar es un avance que enfrenta límites', prompt: 'Abrir decisiones a la juventud es una práctica democrática; para que sea significativa también hay que reconocer barreras sociales y económicas.' }, { icon: 'Handshake', body: 'Escuchar, proponer y dar seguimiento ayuda a tramitar conflictos sin violencia. No garantiza por sí solo igualdad ni acceso a recursos.' }),
      S.choice({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.2.5'], prompt: 'Dos grupos quieren la cancha a la misma hora. ¿Qué respuesta inicia un acuerdo?', explain: 'Primero se escuchan necesidades; después se buscan opciones.' }, { options: [{ id: 'a', text: 'Escuchar a ambos grupos y resumir qué necesita cada uno' }, { id: 'b', text: 'Gritar para imponer el turno' }, { id: 'c', text: 'Excluir al grupo más pequeño' }], correct: ['a'] }),
      S.explain({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.1.2', 'ccss:7.2.5', 'ccss:6.7.1', 'ccss:6.7.4'], title: 'Cuatro preguntas para participar', prompt: 'Una decisión democrática y pacífica considera voces, necesidades, propuesta y seguimiento.' }, { icon: 'Users', body: 'Participar no es solo asistir: implica reconocer quién enfrenta una barrera y compartir responsabilidad.', reveal: [{ icon: 'Ear', front: 'Voces', back: '¿Quiénes pueden hablar y quiénes quedan fuera?' }, { icon: 'Scale', front: 'Condiciones', back: '¿Qué horarios, recursos o desigualdades influyen?' }, { icon: 'Lightbulb', front: 'Propuesta', back: '¿Qué opción atiende a las partes sin violencia?' }, { icon: 'ClipboardCheck', front: 'Seguimiento', back: '¿Quién revisará el acuerdo y cuándo?' }] }),
      S.ejemplo({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.1.2', 'ccss:7.2.5'], title: 'Ejemplo de mediación juvenil', prompt: 'Observa cómo una estudiante ayuda sin decidir por los demás.' }, { icon: 'MessagesSquare', problem: 'Dos secciones necesitan la cancha para practicar.', steps: [{ text: 'Ana escucha y resume: ambas tienen una presentación esta semana.' }, { text: 'Pregunta qué horarios son indispensables.' }, { text: 'Las secciones acuerdan turnos de 20 minutos y una práctica conjunta final.' }, { text: 'Dos delegados revisarán mañana si funcionó.' }], answer: 'La joven facilita escucha, propuesta y seguimiento.' }),
      S.match({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.2.5'], prompt: 'Une frase y habilidad.', hint: 'Busca qué acción realiza la frase.', explain: 'Las frases concretas vuelven practicables las habilidades.' }, { leftTitle: 'Frase', rightTitle: 'Habilidad', pairs: [{ id: 'a', left: 'Entiendo que necesitan agua para dos actividades', right: 'Escucha' }, { id: 'b', left: 'Propongo repartir los horarios', right: 'Propuesta' }, { id: 'c', left: 'Revisemos el acuerdo el viernes', right: 'Seguimiento' }] }),
      S.sort({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.1.2', 'ccss:6.7.4'], prompt: 'Clasifica las acciones juveniles.', hint: 'Una apertura democrática incluye voces y responsabilidad; excluir o amenazar la debilita.', explain: 'La participación pacífica amplía decisiones sin ocultar los conflictos.' }, { buckets: [{ id: 'p', label: 'Amplía participación', icon: 'Handshake', color: 'var(--c-ok)' }, { id: 'v', label: 'Limita participación', icon: 'Zap', color: 'var(--c-bad)' }], items: [{ id: 'a', text: 'Invitar a jóvenes de ambos grupos a proponer opciones', bucket: 'p' }, { id: 'b', text: 'Difundir un rumor para presionar', bucket: 'v' }, { id: 'c', text: 'Registrar el acuerdo y revisarlo', bucket: 'p' }, { id: 'd', text: 'Excluir a quienes tienen otro horario', bucket: 'v' }] }),
      S.choice({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:7.1.2', 'ccss:7.2.5', 'ccss:6.7.1', 'ccss:6.7.4'], prompt: 'Caso simulado: una asamblea juvenil abre participación para resolver el acceso desigual a una pila; un sector solo puede llegar al final de la tarde. ¿Qué plan reconoce el avance democrático y la condición social?', explain: 'La opción adecuada combina voz, necesidad concreta, acuerdo pacífico y seguimiento.' }, { options: [{ id: 'a', text: 'Escuchar a ambos sectores, reservar un turno accesible y revisar si el acuerdo reduce la barrera' }, { id: 'b', text: 'Mantener el horario de la mayoría sin escuchar al otro sector' }, { id: 'c', text: 'Afirmar que abrir la asamblea ya eliminó toda desigualdad' }], correct: ['a'] }),
      S.write({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:7.1.2', 'ccss:7.2.5', 'ccss:6.7.1', 'ccss:6.7.4'], prompt: 'Escribe una intervención juvenil: reconoce la barrera de horario, abre participación, propone un acuerdo pacífico y define seguimiento.', explain: 'La propuesta debe distinguir el avance de participar del desafío social que todavía requiere atención.' }, { minWords: 26, placeholder: 'La barrera es... Escuchemos a... Propongo... Revisaremos...', model: 'La barrera es que un sector llega tarde. Escuchemos sus horarios antes de decidir. Propongo reservar un turno vespertino y que dos representantes revisen el viernes si el acceso fue más equitativo.', rubric: ['Reconocí una condición social', 'Abrí participación sin excluir', 'Propuse acuerdo y seguimiento'] }),
      S.choice({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:7.1.2', 'ccss:6.7.4'], prompt: '¿Qué análisis distingue avance democrático y desafío?' }, { options: [{ id: 'a', text: 'Abrir la asamblea amplía participación, pero todavía hay que atender barreras de horario y exclusión' }, { id: 'b', text: 'La asamblea garantiza que desaparezca toda desigualdad' }, { id: 'c', text: 'Participar significa que nadie puede discrepar' }], correct: ['a'] }),
      S.choice({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:7.2.5', 'ccss:6.7.1'], prompt: '¿Qué decisión responde pacíficamente a una condición social desigual?' }, { options: [{ id: 'a', text: 'Escuchar la barrera, ajustar el turno y verificar el acceso' }, { id: 'b', text: 'Culpar al sector que llega tarde' }, { id: 'c', text: 'Ignorar los horarios porque ya hubo reunión' }], correct: ['a'] }),
    ],
  }),

  lesson({
    id: 's07-ccss-3', title: 'Cooperar desde la comunidad hasta la región', icon: 'Users', minutes: 13,
    gancho: '¿Qué comparten un equipo comunitario y una red de países cuando coordinan una necesidad?',
    objetivos: ['Comparar cómo organizaciones comunitarias y regionales coordinan responsabilidades ante necesidades comunes'],
    resumen: ['Una organización comunitaria coordina personas y recursos cercanos; un bloque regional coordina países de una subregión.', 'En ambas escalas se necesita un propósito compartido, participantes identificados y responsabilidades, aunque sus alcances son distintos.'],
    media: {
      id: 's07-ccss-3-servicio', kind: 'diagram', title: 'Plantilla de servicio comunitario', aspect: '16:9',
      alt: 'Plantilla vacía con campos para necesidad, participantes, responsabilidad, recursos, acuerdo y verificación.',
      brief: 'Diagrama horizontal 1600×900 rotulado CASO SIMULADO. Seis campos vacíos con iconos descriptivos: NECESIDAD, PARTICIPANTES, RESPONSABILIDAD, RECURSOS, ACUERDO y VERIFICACIÓN. Añadir una flecha de revisión desde verificación hacia necesidad. Texto grande, contraste alto, patrones además de color y orden de lectura claro. No completar el producto ni atribuir hechos a una comunidad real.',
    },
    steps: [
      S.explain({ fase: 'explorar', areas: ['ccss'], cnb: ['ccss:7.1.3', 'ccss:6.6.6'], title: 'Cooperar en distintas escalas', prompt: 'Una organización coordina participantes y responsabilidades para atender una necesidad común.' }, { icon: 'ClipboardList', body: 'En la comunidad puede organizar un servicio concreto; en una región, varios países forman bloques para cooperar en asuntos compartidos. Cambia la escala, no la necesidad de coordinación.' }),
      S.choice({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.1.3'], prompt: '¿Qué propuesta es un servicio comunitario organizado?', explain: 'Tiene necesidad, responsables, recursos y verificación.' }, { options: [{ id: 'a', text: 'Equipo estudiantil rotula chorros del caso, con permiso, materiales asignados y revisión semanal' }, { id: 'b', text: 'Alguien dice que cuidará el agua algún día' }, { id: 'c', text: 'Un grupo actúa sin acordar responsabilidades' }], correct: ['a'] }),
      S.explain({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.1.3', 'ccss:6.6.6'], title: 'Tres partes comparables', prompt: 'Para comparar escalas, busca propósito, participantes y coordinación.' }, { icon: 'ListChecks', body: 'Un grupo comunitario reúne personas u organizaciones locales. Un bloque regional reúne países y coordina esfuerzos sin convertirse en una sola nación.', reveal: [{ icon: 'Target', front: 'Propósito', back: 'Necesidad o asunto compartido.' }, { icon: 'Users', front: 'Participantes', back: 'Personas y organizaciones, o países miembros.' }, { icon: 'Network', front: 'Coordinación', back: 'Responsabilidades y acciones acordadas.' }] }),
      S.ejemplo({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.1.3', 'ccss:6.6.6'], title: 'Ejemplo: dos escalas de cooperación', prompt: 'Compara sin confundir sus alcances.' }, { icon: 'GitCompare', problem: 'Un comité escolar cuida una pila; SICA coordina cooperación entre países centroamericanos.', steps: [{ text: 'Propósito: ambos atienden asuntos compartidos.' }, { text: 'Participantes: el comité reúne personas de una escuela; SICA, países de Centroamérica.' }, { text: 'Coordinación: ambos distribuyen responsabilidades, pero en escalas diferentes.' }], answer: 'Se parecen en la coordinación y se diferencian en participantes y alcance.' }),
      S.match({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.1.3'], prompt: 'Une elemento y ejemplo.', hint: 'Pregunta qué función cumple.', explain: 'Cada elemento responde una pregunta del plan.' }, { leftTitle: 'Elemento', rightTitle: 'Ejemplo', pairs: [{ id: 'a', left: 'Participantes', right: 'Consejo estudiantil y dos responsables' }, { id: 'b', left: 'Recursos', right: 'Cartel reutilizable y ficha de registro' }, { id: 'c', left: 'Verificación', right: 'Comparar cinco recreos' }] }),
      S.match({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:6.6.6'], prompt: 'Relaciona cada bloque de cooperación con su subregión principal.', hint: 'Usa la ubicación indicada en cada nombre o ficha.', explain: 'El esquema distingue esfuerzos de integración dentro del continente americano.' }, { leftTitle: 'Bloque', rightTitle: 'Subregión', pairs: [{ id: 'a', left: 'SICA', right: 'Centroamérica' }, { id: 'b', left: 'CARICOM', right: 'Caribe' }, { id: 'c', left: 'Comunidad Andina', right: 'Región andina' }, { id: 'd', left: 'MERCOSUR', right: 'Sur de América' }] }),
      S.choice({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:7.1.3'], prompt: 'Caso simulado: se mezclan residuos junto al tanque. ¿Qué organización comunitaria es viable?', explain: 'La opción asigna una tarea proporcional a participantes cercanos.' }, { options: [{ id: 'a', text: 'Equipo escolar usa recipientes disponibles, asigna responsables y revisa un registro simulado' }, { id: 'b', text: 'Un bloque de países limpia el tanque escolar' }, { id: 'c', text: 'Una persona promete resolverlo sin responsables' }], correct: ['a'] }),
      S.write({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:7.1.3', 'ccss:6.6.6'], prompt: 'Compara las dos escalas: propósito, participantes y forma de coordinación de un comité escolar del caso y un bloque regional.', explain: 'No les atribuyas la misma tarea: compara cómo se organizan.' }, { minWords: 28, placeholder: 'Ambos... El comité... El bloque regional...', model: 'Ambos coordinan una necesidad común. El comité reúne personas de la escuela y asigna una tarea local. Un bloque regional reúne países y acuerda cooperación entre sus miembros.', rubric: ['Nombré propósito compartido', 'Distinguí participantes', 'Diferencié alcance y coordinación'] }),
      S.choice({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:7.1.3'], prompt: '¿Qué dato vuelve verificable un servicio de rotulación?' }, { options: [{ id: 'a', text: 'Comparar registros de errores antes y después' }, { id: 'b', text: 'Decir que seguramente funcionó' }, { id: 'c', text: 'Cambiar de objetivo al final' }], correct: ['a'] }),
      S.choice({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:6.6.6'], prompt: '¿Qué esquema representa correctamente la cooperación regional?' }, { options: [{ id: 'a', text: 'SICA → países centroamericanos; CARICOM → países del Caribe' }, { id: 'b', text: 'SICA → estudiantes de una escuela; CARICOM → una familia' }, { id: 'c', text: 'Todos los bloques tienen exactamente los mismos miembros y tareas' }], correct: ['a'] }),
    ],
  }),
];
