/** Ciencias Sociales · Unidad 1 · Semana 7. */
import { lesson, S } from '../../../../dsl';

export default [
  lesson({
    id: 's07-ccss-1', title: 'Comparar procesos de paz', icon: 'Handshake', minutes: 14,
    gancho: 'Dos países firman acuerdos de paz: ¿qué debemos comparar además de la fecha?',
    objetivos: ['Comparar procesos de paz por sus acuerdos, actores y formas de participación'],
    resumen: ['Un proceso de paz busca terminar o transformar un conflicto mediante negociación y acuerdos.', 'Para comparar se observan acuerdos, actores y participación social.', 'Firmar es un paso; implementar y vigilar los compromisos requiere participación continua.'],
    media: {
      id: 's07-ccss-1-mapa', kind: 'diagram', title: 'Dos procesos de paz para comparar', aspect: '16:9',
      alt: 'Mapa de América con Guatemala y Colombia señaladas y tres columnas vacías para acuerdos, actores y participación.',
      brief: 'Diagrama horizontal 1600×900. Mapa claro de América con Guatemala y Colombia señaladas, sin banderas. A la derecha, matriz con columnas ACUERDOS, ACTORES y PARTICIPACIÓN, sin respuestas completas. Incluir fechas 1996 y 2016 y rótulo FUENTES DIDÁCTICAS RESUMIDAS. Texto grande, contraste alto, lectura lineal y sin retratos de personas reales.',
    },
    steps: [
      S.explain({ fase: 'explorar', areas: ['ccss'], cnb: ['ccss:7.2.1'], title: 'Una comparación con criterios', prompt: 'Comparar no es solo nombrar países: se aplican los mismos criterios a cada proceso.' }, { icon: 'Columns3', body: 'Usaremos **acuerdos, actores y participación** para encontrar semejanzas y diferencias.' }),
      S.choice({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.2.1'], prompt: '¿Cuál pregunta compara actores?', explain: 'Los actores son las partes que negocian y quienes acompañan el proceso.' }, { options: [{ id: 'a', text: '¿Quiénes negociaron y quiénes acompañaron?' }, { id: 'b', text: '¿Qué color tenía el documento?' }, { id: 'c', text: '¿Cuál país está más al norte?' }], correct: ['a'] }),
      S.explain({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.2.1'], title: 'Tres criterios', prompt: 'Lee qué evidencia busca cada criterio.' }, { icon: 'ListChecks', body: 'Una comparación responsable se basa en fuentes identificadas y reconoce que cada proceso tiene un contexto propio.', reveal: [{ icon: 'ScrollText', front: 'Acuerdos', back: 'Compromisos sobre el fin de la violencia, derechos, participación o reformas.' }, { icon: 'Users', front: 'Actores', back: 'Gobierno, grupo armado y mediadores o acompañantes.' }, { icon: 'MessageCircle', front: 'Participación', back: 'Consultas, propuestas, votaciones, organizaciones y seguimiento ciudadano.' }] }),
      S.reading({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.2.1'], prompt: 'Lee las dos fichas didácticas resumidas.', hint: 'Subraya mentalmente un acuerdo, los actores y una forma de participación.', explain: 'Las fichas ofrecen los mismos tres campos para poder comparar.' }, { genre: 'Fichas históricas resumidas', heading: 'Guatemala 1996 y Colombia 2016', passage: 'FICHA A · Guatemala. El Gobierno de Guatemala y la URNG firmaron el Acuerdo de Paz Firme y Duradera en 1996, con acompañamiento de Naciones Unidas. El conjunto de acuerdos incluyó compromisos sobre derechos humanos, identidad y derechos de los pueblos indígenas, participación y reformas. Organizaciones sociales aportaron propuestas en la Asamblea de la Sociedad Civil.\n\nFICHA B · Colombia. El Gobierno de Colombia y las FARC-EP firmaron el Acuerdo Final en 2016, con acompañamiento internacional. Incluyó compromisos sobre fin del conflicto, participación política, desarrollo rural, víctimas y reincorporación. Hubo foros y propuestas ciudadanas; el texto fue sometido a plebiscito y luego ajustado.', questions: [{ q: '¿Qué semejanza de actores aparece?', options: [{ id: 'a', text: 'En ambos negociaron un gobierno y un grupo armado, con acompañamiento internacional' }, { id: 'b', text: 'En ambos negoció solo el estudiantado' }, { id: 'c', text: 'No hubo acompañamiento' }], correct: 'a' }] }),
      S.ejemplo({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.2.1'], title: 'Modelo de comparación', prompt: 'Construye una afirmación con semejanza, diferencia y evidencia.' }, { icon: 'GitCompare', problem: '¿Cómo se comparan las formas de participación?', steps: [{ text: 'Guatemala: organizaciones presentaron propuestas mediante la Asamblea de la Sociedad Civil.' }, { text: 'Colombia: hubo foros, propuestas y un plebiscito; después se ajustó el texto.' }, { text: 'Semejanza: en ambos hubo participación fuera de las partes negociadoras.' }, { text: 'Diferencia: las formas concretas de participación no fueron iguales.' }], answer: 'La comparación nombra los dos procesos y usa el mismo criterio.' }),
      S.match({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.2.1'], prompt: 'Relaciona evidencia y criterio.', hint: 'Compromiso = acuerdo; quién interviene = actor; aporte social = participación.', explain: 'El criterio organiza la evidencia sin mezclarla.' }, { leftTitle: 'Evidencia', rightTitle: 'Criterio', pairs: [{ id: 'a', left: 'Gobierno y URNG', right: 'Actores' }, { id: 'b', left: 'Compromisos sobre derechos humanos', right: 'Acuerdos' }, { id: 'c', left: 'Propuestas de organizaciones sociales', right: 'Participación' }, { id: 'd', left: 'Gobierno y FARC-EP', right: 'Actores' }] }),
      S.sort({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:7.2.1'], prompt: 'Completa la matriz comparativa con datos de las fichas.', explain: 'Cada dato se ubica por proceso y criterio.' }, { buckets: [{ id: 'gua', label: 'Guatemala 1996', icon: 'MapPin', color: 'var(--area-ccss)' }, { id: 'col', label: 'Colombia 2016', icon: 'MapPin', color: 'var(--c-maiz-strong)' }], items: [{ id: 'a', text: 'Actor: URNG', bucket: 'gua' }, { id: 'b', text: 'Actor: FARC-EP', bucket: 'col' }, { id: 'c', text: 'Participación: Asamblea de la Sociedad Civil', bucket: 'gua' }, { id: 'd', text: 'Participación: foros y plebiscito', bucket: 'col' }, { id: 'e', text: 'Acuerdo: identidad y derechos de pueblos indígenas', bucket: 'gua' }, { id: 'f', text: 'Acuerdo: desarrollo rural y reincorporación', bucket: 'col' }] }),
      S.write({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:7.2.1'], prompt: 'Compara Guatemala 1996 y Colombia 2016: una semejanza y una diferencia que incluyan acuerdos, actores y participación.', explain: 'La respuesta debe usar datos de ambas fichas y los tres criterios.' }, { minWords: 30, placeholder: 'Semejanza: ...\nDiferencia: ...', model: 'En ambos participaron un gobierno y un grupo armado y hubo aportes sociales. Cambiaron los acuerdos específicos y la participación: Guatemala tuvo la Asamblea de la Sociedad Civil; Colombia, foros y plebiscito.', rubric: ['Nombré ambos procesos', 'Comparé acuerdos y actores', 'Comparé participación'] }),
      S.choice({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:7.2.1'], prompt: '¿Qué opción compara correctamente acuerdos y actores de los dos procesos?' }, { options: [{ id: 'a', text: 'Ambos reunieron gobierno y grupo armado; sus acuerdos compartieron el fin del conflicto, pero incluyeron compromisos específicos distintos' }, { id: 'b', text: 'Fueron idénticos porque ocurrieron en América' }, { id: 'c', text: 'Solo importa la fecha de firma' }], correct: ['a'] }),
      S.choice({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:7.2.1'], prompt: '¿Qué diferencia de participación está respaldada por las fichas?' }, { options: [{ id: 'a', text: 'Guatemala incluyó propuestas de la Asamblea de la Sociedad Civil; Colombia tuvo foros y plebiscito' }, { id: 'b', text: 'Ningún proceso recibió aportes sociales' }, { id: 'c', text: 'Solo participaron personas extranjeras' }], correct: ['a'] }),
    ],
  }),

  lesson({
    id: 's07-ccss-2', title: 'Juventud que dialoga por el agua', icon: 'MessagesSquare', minutes: 14,
    gancho: '¿Cómo puede la juventud transformar un desacuerdo sobre el cuidado del agua en un acuerdo pacífico?',
    objetivos: ['Practicar habilidades juveniles de diálogo para construir cultura de paz'],
    resumen: ['La infancia y la juventud consolidan cultura de paz cuando escuchan, expresan necesidades sin atacar y construyen acuerdos.', 'Parafrasear demuestra comprensión; un mensaje en primera persona explica una preocupación sin culpar.', 'Una propuesta pacífica incluye una acción posible y una forma de revisar el acuerdo.'],
    media: {
      id: 's07-ccss-2-mediacion', kind: 'diagram', title: 'Ruta juvenil de diálogo', aspect: '16:9',
      alt: 'Secuencia vacía para escuchar, parafrasear, expresar una necesidad y proponer un acuerdo sobre el cuidado del agua.',
      brief: 'Diagrama horizontal 1600×900. Mostrar a jóvenes diversos conversando junto a un lavamanos escolar genérico, sin atribuir hechos a una escuela real. Incluir cuatro estaciones rotuladas ESCUCHAR, PARAFRASEAR, MENSAJE EN PRIMERA PERSONA y PROPONER UN ACUERDO, sin escribir respuestas del ejercicio. Contraste alto, texto grande, orden de lectura claro y patrones además de color.',
    },
    steps: [
      S.explain({ fase: 'explorar', areas: ['ccss'], cnb: ['ccss:7.1.2'], title: 'La juventud también construye paz', prompt: 'La cultura de paz se consolida con prácticas cotidianas, no solo con discursos.' }, { icon: 'Users', body: 'Niñas, niños y jóvenes aportan cuando escuchan, evitan burlas, expresan necesidades y proponen acuerdos que cuidan a las personas y los recursos comunes.' }),
      S.choice({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.1.2'], prompt: 'En un caso simulado, dos grupos discrepan sobre cómo reducir el desperdicio de agua. ¿Qué participación juvenil fortalece la cultura de paz?', explain: 'Participar pacíficamente significa intervenir con respeto y buscar una solución compartida.' }, { options: [{ id: 'a', text: 'Escuchar ambas razones y ayudar a construir una propuesta verificable' }, { id: 'b', text: 'Ridiculizar al grupo contrario' }, { id: 'c', text: 'Decidir sin escuchar a nadie' }], correct: ['a'] }),
      S.explain({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.1.2', 'ccss:7.2.5'], title: 'Cuatro movimientos de diálogo', prompt: 'Practica una ruta breve para que la juventud construya cultura de paz.' }, { icon: 'MessagesSquare', body: '**Escuchar** sin interrumpir → **parafrasear** la razón ajena → usar un **mensaje en primera persona** (“Me preocupa... porque...”) → formular una **propuesta o acuerdo** que pueda revisarse.' }),
      S.ejemplo({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.2.5'], title: 'Modelo de respuesta pacífica', prompt: 'Observa cómo se responde sin atacar.' }, { icon: 'MessageCircle', problem: 'Una estudiante propone cerrar siempre la llave; otro teme que no alcance el tiempo para lavarse bien.', steps: [{ text: 'Escucho: dejo que explique su preocupación.' }, { text: 'Parafraseo: “Te preocupa que el cuidado del agua dificulte el lavado de manos”.' }, { text: 'Mensaje en primera persona: “Me preocupa dejar la llave abierta mientras nos enjabonamos”.' }, { text: 'Propuesta: cerrar durante el enjabonado y revisar juntos si la rutina permite un lavado adecuado.' }], answer: 'La respuesta reconoce la otra necesidad y propone una prueba, no una imposición.' }),
      S.match({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.2.5'], prompt: 'Relaciona cada frase con la habilidad social que practica.', hint: 'Parafrasear repite la idea con tus palabras; el mensaje en primera persona expresa una preocupación propia.', explain: 'Nombrar la habilidad ayuda a usarla en un diálogo real.' }, { pairs: [{ id: 'a', left: '“Entiendo que te preocupa el tiempo de lavado”', right: 'Parafrasear' }, { id: 'b', left: '“Me preocupa desperdiciar agua”', right: 'Mensaje en primera persona' }, { id: 'c', left: '“Probemos cerrar durante el enjabonado y revisemos”', right: 'Proponer un acuerdo' }] }),
      S.sort({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.2.5'], prompt: 'Clasifica respuestas ante el desacuerdo simulado.', hint: 'La cultura de paz cuida la dignidad y mantiene abierto el diálogo.', explain: 'Escuchar y proponer desarrollan habilidades; culpar o burlarse aumenta el conflicto.' }, { buckets: [{ id: 'paz', label: 'Construye cultura de paz', icon: 'Handshake', color: 'var(--c-ok)' }, { id: 'escala', label: 'Escala el conflicto', icon: 'TriangleAlert', color: 'var(--c-maiz-strong)' }], items: [{ id: 'a', text: 'Pedir que cada grupo explique su razón', bucket: 'paz' }, { id: 'b', text: 'Decir que la otra idea es ridícula', bucket: 'escala' }, { id: 'c', text: 'Proponer una prueba y una revisión', bucket: 'paz' }, { id: 'd', text: 'Interrumpir para imponer una respuesta', bucket: 'escala' }] }),
      S.write({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:7.1.2', 'ccss:7.2.5'], prompt: 'Práctica juvenil de cultura de paz: durante la lección, responde al desacuerdo sobre el agua con tres partes: parafrasea una razón, escribe un mensaje en primera persona y propone un acuerdo verificable.' }, { minWords: 24, placeholder: 'Comprendo que... Me preocupa... Propongo que...', model: 'Comprendo que quieres mantener un lavado adecuado. Me preocupa dejar correr agua sin usarla. Propongo cerrar durante el enjabonado y revisar al final si cumplimos ambas necesidades.', rubric: ['Parafraseé sin juzgar', 'Usé un mensaje en primera persona', 'Propuse un acuerdo revisable'] }),
      S.choice({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:7.1.2', 'ccss:7.2.5'], prompt: '¿Por qué esta práctica juvenil ayuda a consolidar cultura de paz?', explain: 'Las habilidades sociales convierten la participación en diálogo y cooperación.' }, { options: [{ id: 'a', text: 'Porque la juventud escucha, expresa necesidades sin atacar y crea un acuerdo' }, { id: 'b', text: 'Porque evita que otras personas opinen' }, { id: 'c', text: 'Porque una sola persona impone la solución' }], correct: ['a'] }),
      S.choice({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:7.1.2', 'ccss:7.2.5'], prompt: 'En un nuevo desacuerdo sobre turnos para revisar una llave, ¿qué respuesta muestra a la juventud practicando cultura de paz con escucha, paráfrasis y propuesta?', }, { options: [{ id: 'a', text: '“Entiendo que necesitas otro horario; me preocupa dejar el punto sin revisión. Propongo intercambiar turnos y comprobar mañana”' }, { id: 'b', text: '“Tu razón no importa; se hace como digo”' }, { id: 'c', text: '“No hablaré y luego culparé al grupo”' }], correct: ['a'] }),
      S.tf({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:7.2.5'], prompt: 'Evalúa estas habilidades sociales de cultura de paz.' }, { statements: [{ text: 'Parafrasear antes de proponer ayuda a comprobar que comprendimos la otra razón.', answer: true }, { text: 'Un acuerdo pacífico exige que una parte renuncie a hablar.', answer: false, why: 'El diálogo protege la participación y busca una solución compartida.' }] }),
    ],
  }),

  lesson({
    id: 's07-ccss-3', title: 'Simulamos la organización de un servicio por el agua', icon: 'ClipboardCheck', minutes: 14,
    gancho: '¿Cómo se organiza un equipo cuando tiene poco tiempo y una persona responsable falta?',
    objetivos: ['Participar en la organización simulada de una actividad escolar de servicio sobre el agua'],
    resumen: ['La simulación permite practicar organización sin afirmar que se realizó un servicio fuera de la lección.', 'Organizar exige propósito, roles, secuencia, recursos y respuesta ante restricciones.', 'Cada estudiante completa una contribución usable dentro del escenario simulado; una aplicación real requeriría acuerdos y responsables reales.'],
    media: {
      id: 's07-ccss-3-servicio', kind: 'diagram', title: 'Simulación de organización del servicio', aspect: '16:9',
      alt: 'Tablero didáctico de una simulación con propósito, roles, secuencia, recurso, restricción y contribución para cuidar el agua.',
      brief: 'Diagrama horizontal 1600×900 con rótulo SIMULACIÓN. Mostrar seis campos vacíos: PROPÓSITO, ROLES, SECUENCIA, RECURSO, RESTRICCIÓN y CONTRIBUCIÓN. Añadir tarjetas genéricas de coordinación, redacción y revisión, sin nombres ni destinatarios reales. No afirmar publicación o servicio completado. Texto grande, contraste alto y orden de lectura claro.',
    },
    steps: [
      S.explain({ fase: 'explorar', areas: ['ccss'], cnb: ['ccss:7.1.3'], title: 'Práctica simulada', prompt: 'Participarás en una **simulación de organización**, no en un servicio ya realizado.' }, { icon: 'HandHeart', body: 'El escenario permite asignar roles, ordenar tareas, resolver una restricción y producir una contribución. No hay publicación, destinatario ni despliegue externo.' }),
      S.choice({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.1.3'], prompt: '¿Qué describe honestamente la actividad?', explain: 'La participación ocurre en la organización simulada dentro de la lección.' }, { options: [{ id: 'a', text: 'Una práctica para organizar un servicio escolar posible' }, { id: 'b', text: 'Una campaña ya ejecutada en la comunidad' }, { id: 'c', text: 'Una consulta real a destinatarios' }], correct: ['a'] }),
      S.explain({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.1.3'], title: 'Organización completa', prompt: 'Una actividad de servicio se organiza antes de ponerse en práctica.' }, { icon: 'ListChecks', body: '**Propósito**, **roles responsables**, **secuencia de tareas**, **recursos**, **restricciones** y **verificación** permiten coordinar una contribución segura.' }),
      S.ejemplo({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.1.3'], title: 'Modelo de simulación', prompt: 'Observa una organización que no finge resultados externos.' }, { icon: 'ClipboardCheck', problem: 'Preparar rótulos didácticos sobre el cierre cuidadoso de llaves.', steps: [{ text: 'Coordinación reparte roles de redacción y revisión.' }, { text: 'Redacción crea una instrucción breve.' }, { text: 'Revisión comprueba seguridad y claridad.' }, { text: 'Si falta alguien, coordinación redistribuye una tarea antes de cerrar.' }], answer: 'El producto es una contribución para la simulación; usarla fuera requeriría autorización real.' }),
      S.sort({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.1.3'], prompt: 'Asigna roles de la simulación de servicio.', hint: 'Coordinar organiza; redactar produce; revisar comprueba.', explain: 'Cada rol aporta una parte distinta.' }, { buckets: [{ id: 'co', label: 'Coordinación' }, { id: 're', label: 'Redacción' }, { id: 'vi', label: 'Revisión' }], items: [{ id: 'a', text: 'Distribuir tiempos y responsables', bucket: 'co' }, { id: 'b', text: 'Escribir una instrucción segura', bucket: 're' }, { id: 'c', text: 'Comprobar claridad y límites', bucket: 'vi' }] }),
      S.match({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.1.3'], prompt: 'Relaciona cada elemento de organización con su ejemplo.', hint: 'La secuencia indica orden; la restricción exige ajuste.', explain: 'El esquema permite anticipar la coordinación.' }, { pairs: [{ id: 'a', left: 'Propósito', right: 'Recordar el cierre cuidadoso de una llave' }, { id: 'b', left: 'Secuencia', right: 'Redactar, revisar y registrar' }, { id: 'c', left: 'Restricción', right: 'La persona revisora está ausente' }] }),
      S.order({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:7.1.3'], prompt: 'En la simulación, organiza la secuencia de tareas y roles responsables del servicio escolar sobre agua.' }, { items: [{ id: 'a', text: 'Coordinación asigna roles' }, { id: 'b', text: 'Redacción prepara la instrucción' }, { id: 'c', text: 'Revisión comprueba seguridad y claridad' }, { id: 'd', text: 'Coordinación registra la contribución terminada' }], labels: { start: 'Primero', end: 'Al final' } }),
      S.dilemma({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:7.1.3'], prompt: 'Resuelve una restricción de coordinación en la simulación: falta la persona revisora y quedan dos minutos.' }, { scene: { icon: 'Timer', text: 'El equipo ya redactó, pero necesita revisar antes de cerrar la práctica.' }, options: [{ id: 'a', icon: 'Users', text: 'Coordinación reasigna la revisión con una lista breve', consequence: 'La secuencia conserva control y tiempo.', values: ['Cooperación', 'Responsabilidad'], constructive: true }, { id: 'b', icon: 'BadgeCheck', text: 'Marcar la revisión como hecha sin realizarla', consequence: 'La evidencia sería falsa.', values: ['Apariencia'], constructive: false }] }),
      S.write({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:7.1.3'], prompt: 'Completa tu contribución usable para la simulación: escribe una instrucción de rótulo, el rol responsable y una comprobación breve. No afirmes que fue publicada.' }, { minWords: 14, placeholder: 'Instrucción:... Rol responsable:... Comprobación:...', model: 'Instrucción: cierra la llave al terminar y avisa si gotea. Rol responsable: redacción. Comprobación: revisar que sea segura y clara.', rubric: ['Produje una instrucción usable', 'Nombré el rol responsable', 'Incluí una comprobación'] }),
      S.choice({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:7.1.3'], prompt: '¿Qué evidencia demuestra participación en la organización simulada del servicio?' }, { options: [{ id: 'a', text: 'Asignar roles, ordenar tareas, resolver la ausencia y completar una contribución' }, { id: 'b', text: 'Afirmar que el rótulo ya fue publicado' }, { id: 'c', text: 'Prometer ayudar algún día' }], correct: ['a'] }),
      S.tf({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:7.1.3'], prompt: 'Evalúa la práctica de organización simulada.' }, { statements: [{ text: 'Redistribuir un rol ante una ausencia es una contribución de coordinación.', answer: true }, { text: 'La simulación prueba que se completó un servicio real en la escuela.', answer: false, why: 'Solo evidencia la práctica de organización dentro de la lección.' }, { text: 'Una contribución usable debe corresponder a un rol y a la secuencia acordada.', answer: true }] }),
    ],
  }),
];
