/** Ciencias Sociales · Unidad 1 · Semana 7. */
import { lesson, S } from '../../../../dsl';

export default [
  lesson({
    id: 's07-ccss-1', title: 'Comparar procesos de paz', icon: 'Handshake', minutes: 14,
    gancho: 'Dos países firman acuerdos de paz: ¿qué debemos comparar además de la fecha?',
    objetivos: ['Comparar procesos de paz por sus acuerdos, actores y formas de participación'],
    resumen: ['Un proceso de paz busca terminar o transformar un conflicto mediante negociación y acuerdos.', 'Para comparar se observan acuerdos, actores y participación social.', 'Firmar es un paso; implementar y vigilar los compromisos requiere participación continua.'],
    media: {
      id: 's07-ccss-1-mapa', kind: 'diagram', title: 'Dos procesos de paz para comparar', aspect: '16:9',
      alt: 'Mapa de América con Guatemala y Colombia señaladas y tres columnas vacías para acuerdos, actores y participación.',
      brief: 'Diagrama horizontal 1600×900. Mapa claro de América con Guatemala y Colombia señaladas, sin banderas. A la derecha, matriz con columnas ACUERDOS, ACTORES y PARTICIPACIÓN, sin respuestas completas. Incluir fechas 1996 y 2016 y rótulo FUENTES DIDÁCTICAS RESUMIDAS. Texto grande, contraste alto, lectura lineal y sin retratos de personas reales.',
    },
    steps: [
      S.explain({ fase: 'explorar', areas: ['ccss'], cnb: ['ccss:7.2.1'], title: 'Una comparación con criterios', prompt: 'Comparar no es solo nombrar países: se aplican los mismos criterios a cada proceso.' }, { icon: 'Columns3', body: 'Usaremos **acuerdos, actores y participación** para encontrar semejanzas y diferencias.' }),
      S.choice({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.2.1'], prompt: '¿Cuál pregunta compara actores?', explain: 'Los actores son las partes que negocian y quienes acompañan el proceso.' }, { options: [{ id: 'a', text: '¿Quiénes negociaron y quiénes acompañaron?' }, { id: 'b', text: '¿Qué color tenía el documento?' }, { id: 'c', text: '¿Cuál país está más al norte?' }], correct: ['a'] }),
      S.explain({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.2.1'], title: 'Tres criterios', prompt: 'Lee qué evidencia busca cada criterio.' }, { icon: 'ListChecks', body: 'Una comparación responsable se basa en fuentes identificadas y reconoce que cada proceso tiene un contexto propio.', reveal: [{ icon: 'ScrollText', front: 'Acuerdos', back: 'Compromisos sobre el fin de la violencia, derechos, participación o reformas.' }, { icon: 'Users', front: 'Actores', back: 'Gobierno, grupo armado y mediadores o acompañantes.' }, { icon: 'MessageCircle', front: 'Participación', back: 'Consultas, propuestas, votaciones, organizaciones y seguimiento ciudadano.' }] }),
      S.reading({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.2.1'], prompt: 'Lee las dos fichas didácticas resumidas.', hint: 'Subraya mentalmente un acuerdo, los actores y una forma de participación.', explain: 'Las fichas ofrecen los mismos tres campos para poder comparar.' }, { genre: 'Fichas históricas resumidas', heading: 'Guatemala 1996 y Colombia 2016', passage: 'FICHA A · Guatemala. El Gobierno de Guatemala y la URNG firmaron el Acuerdo de Paz Firme y Duradera en 1996, con acompañamiento de Naciones Unidas. El conjunto de acuerdos incluyó compromisos sobre derechos humanos, identidad y derechos de los pueblos indígenas, participación y reformas. Organizaciones sociales aportaron propuestas en la Asamblea de la Sociedad Civil.\n\nFICHA B · Colombia. El Gobierno de Colombia y las FARC-EP firmaron el Acuerdo Final en 2016, con acompañamiento internacional. Incluyó compromisos sobre fin del conflicto, participación política, desarrollo rural, víctimas y reincorporación. Hubo foros y propuestas ciudadanas; el texto fue sometido a plebiscito y luego ajustado.', questions: [{ q: '¿Qué semejanza de actores aparece?', options: [{ id: 'a', text: 'En ambos negociaron un gobierno y un grupo armado, con acompañamiento internacional' }, { id: 'b', text: 'En ambos negoció solo el estudiantado' }, { id: 'c', text: 'No hubo acompañamiento' }], correct: 'a' }] }),
      S.ejemplo({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.2.1'], title: 'Modelo de comparación', prompt: 'Construye una afirmación con semejanza, diferencia y evidencia.' }, { icon: 'GitCompare', problem: '¿Cómo se comparan las formas de participación?', steps: [{ text: 'Guatemala: organizaciones presentaron propuestas mediante la Asamblea de la Sociedad Civil.' }, { text: 'Colombia: hubo foros, propuestas y un plebiscito; después se ajustó el texto.' }, { text: 'Semejanza: en ambos hubo participación fuera de las partes negociadoras.' }, { text: 'Diferencia: las formas concretas de participación no fueron iguales.' }], answer: 'La comparación nombra los dos procesos y usa el mismo criterio.' }),
      S.match({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.2.1'], prompt: 'Relaciona evidencia y criterio.', hint: 'Compromiso = acuerdo; quién interviene = actor; aporte social = participación.', explain: 'El criterio organiza la evidencia sin mezclarla.' }, { leftTitle: 'Evidencia', rightTitle: 'Criterio', pairs: [{ id: 'a', left: 'Gobierno y URNG', right: 'Actores' }, { id: 'b', left: 'Compromisos sobre derechos humanos', right: 'Acuerdos' }, { id: 'c', left: 'Propuestas de organizaciones sociales', right: 'Participación' }, { id: 'd', left: 'Gobierno y FARC-EP', right: 'Actores' }] }),
      S.explain({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:6.6.6', 'ccss:6.7.1', 'ccss:6.7.4'], title: 'Cooperación, democracia y condiciones de vida', prompt: 'Los procesos de paz se conectan con redes regionales, apertura democrática y condiciones sociales.' }, { icon: 'Network', body: 'En América, bloques como **SICA** y organismos como la **OEA** coordinan cooperación. La apertura democrática amplía elecciones, derechos y participación, pero enfrenta desafíos de implementación. Estos procesos políticos pueden influir en seguridad, educación, salud y oportunidades; no producen mejoras automáticas.', reveal: [{ icon: 'Map', front: 'SICA', back: 'Integra países centroamericanos y coordina cooperación regional.' }, { icon: 'Globe', front: 'OEA', back: 'Reúne países del continente para cooperación, democracia y derechos humanos.' }, { icon: 'Vote', front: 'Apertura democrática', back: 'Incluye avances en elecciones, derechos e instituciones, junto con desafíos de participación y cumplimiento.' }] }),
      S.match({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:6.6.6'], prompt: 'Relaciona la red de cooperación con su alcance.', hint: 'SICA es centroamericano; OEA es continental.', explain: 'Un esquema de bloques muestra qué países coordinan esfuerzos y a qué escala.' }, { leftTitle: 'Organización', rightTitle: 'Alcance', pairs: [{ id: 'a', left: 'SICA', right: 'Integración y cooperación centroamericana' }, { id: 'b', left: 'OEA', right: 'Cooperación entre países del continente americano' }] }),
      S.choice({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:6.7.1', 'ccss:6.7.4'], prompt: 'Después de un acuerdo se amplían espacios de participación, pero persisten desigualdad y compromisos sin cumplir. ¿Qué análisis es adecuado?', explain: 'Reconoce un avance democrático, un desafío y su relación posible con condiciones sociales.' }, { options: [{ id: 'a', text: 'La participación es un avance; el incumplimiento y la desigualdad son desafíos que pueden limitar mejoras sociales' }, { id: 'b', text: 'La firma garantiza de inmediato bienestar económico y social' }, { id: 'c', text: 'Los procesos políticos no se relacionan con la vida de la población' }], correct: ['a'] }),
      S.sort({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:7.2.1'], prompt: 'Completa la matriz comparativa con datos de las fichas.', explain: 'Cada dato se ubica por proceso y criterio.' }, { buckets: [{ id: 'gua', label: 'Guatemala 1996', icon: 'MapPin', color: 'var(--area-ccss)' }, { id: 'col', label: 'Colombia 2016', icon: 'MapPin', color: 'var(--c-maiz-strong)' }], items: [{ id: 'a', text: 'Actor: URNG', bucket: 'gua' }, { id: 'b', text: 'Actor: FARC-EP', bucket: 'col' }, { id: 'c', text: 'Participación: Asamblea de la Sociedad Civil', bucket: 'gua' }, { id: 'd', text: 'Participación: foros y plebiscito', bucket: 'col' }, { id: 'e', text: 'Acuerdo: identidad y derechos de pueblos indígenas', bucket: 'gua' }, { id: 'f', text: 'Acuerdo: desarrollo rural y reincorporación', bucket: 'col' }] }),
      S.write({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:7.2.1'], prompt: 'Compara Guatemala 1996 y Colombia 2016: una semejanza y una diferencia que incluyan acuerdos, actores y participación.', explain: 'La respuesta debe usar datos de ambas fichas y los tres criterios.' }, { minWords: 30, placeholder: 'Semejanza: ...\nDiferencia: ...', model: 'En ambos participaron un gobierno y un grupo armado y hubo aportes sociales. Cambiaron los acuerdos específicos y la participación: Guatemala tuvo la Asamblea de la Sociedad Civil; Colombia, foros y plebiscito.', rubric: ['Nombré ambos procesos', 'Comparé acuerdos y actores', 'Comparé participación'] }),
      S.choice({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:7.2.1'], prompt: '¿Qué opción compara correctamente acuerdos y actores de los dos procesos?' }, { options: [{ id: 'a', text: 'Ambos reunieron gobierno y grupo armado; sus acuerdos compartieron el fin del conflicto, pero incluyeron compromisos específicos distintos' }, { id: 'b', text: 'Fueron idénticos porque ocurrieron en América' }, { id: 'c', text: 'Solo importa la fecha de firma' }], correct: ['a'] }),
      S.choice({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:7.2.1'], prompt: '¿Qué diferencia de participación está respaldada por las fichas?' }, { options: [{ id: 'a', text: 'Guatemala incluyó propuestas de la Asamblea de la Sociedad Civil; Colombia tuvo foros y plebiscito' }, { id: 'b', text: 'Ningún proceso recibió aportes sociales' }, { id: 'c', text: 'Solo participaron personas extranjeras' }], correct: ['a'] }),
    ],
  }),

  lesson({
    id: 's07-ccss-2', title: 'Jóvenes que practican una cultura de paz', icon: 'MessageCircle', minutes: 13,
    gancho: '¿Qué puede hacer un grupo de jóvenes cuando dos equipos quieren usar el mismo espacio?',
    objetivos: ['Aplicar habilidades personales y sociales para construir acuerdos pacíficos'],
    resumen: ['La juventud ayuda a consolidar una cultura de paz cuando escucha, dialoga, coopera y rechaza la violencia.', 'Un acuerdo pacífico reconoce necesidades, responsabilidades y una forma de seguimiento.'],
    media: {
      id: 's07-ccss-2-mediacion', kind: 'diagram', title: 'Ruta de mediación juvenil', aspect: '16:9',
      alt: 'Cuatro escenas muestran a jóvenes escuchando necesidades, proponiendo opciones, acordando turnos y revisando el acuerdo.',
      brief: 'Diagrama horizontal 1600×900 en cuatro escenas numeradas: ESCUCHAR, RESUMIR, PROPONER y REVISAR. Mostrar dos grupos juveniles diversos alrededor de una pila escolar ficticia y una estudiante mediadora que no impone la decisión. Rótulos grandes, contraste alto, flechas con patrón además de color y lectura de izquierda a derecha. No incluir respuestas de evaluación ni estereotipos culturales.',
    },
    steps: [
      S.explain({ fase: 'explorar', areas: ['ccss'], cnb: ['ccss:7.1.2', 'ccss:7.2.5'], title: 'La paz se practica', prompt: 'La cultura de paz se construye con habilidades y decisiones cotidianas, no solo con documentos nacionales.' }, { icon: 'Handshake', body: 'Jóvenes pueden abrir espacios de escucha, proponer opciones y dar seguimiento a acuerdos.' }),
      S.choice({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.2.5'], prompt: 'Dos grupos quieren la cancha a la misma hora. ¿Qué respuesta inicia un acuerdo?', explain: 'Primero se escuchan necesidades; después se buscan opciones.' }, { options: [{ id: 'a', text: 'Escuchar a ambos grupos y resumir qué necesita cada uno' }, { id: 'b', text: 'Gritar para imponer el turno' }, { id: 'c', text: 'Excluir al grupo más pequeño' }], correct: ['a'] }),
      S.explain({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.1.2', 'ccss:7.2.5'], title: 'Cuatro habilidades', prompt: 'Relaciona cada habilidad con una acción visible.' }, { icon: 'Users', body: 'Participar en paz implica actuar y aceptar responsabilidades.', reveal: [{ icon: 'Ear', front: 'Escucha', back: 'Dejar hablar y resumir sin burlas.' }, { icon: 'MessageSquare', front: 'Diálogo', back: 'Expresar una necesidad sin atacar.' }, { icon: 'Lightbulb', front: 'Propuesta', back: 'Buscar opciones que atiendan a las partes.' }, { icon: 'ClipboardCheck', front: 'Seguimiento', back: 'Definir quién revisa el acuerdo y cuándo.' }] }),
      S.ejemplo({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.1.2', 'ccss:7.2.5'], title: 'Ejemplo de mediación juvenil', prompt: 'Observa cómo una estudiante ayuda sin decidir por los demás.' }, { icon: 'MessagesSquare', problem: 'Dos secciones necesitan la cancha para practicar.', steps: [{ text: 'Ana escucha y resume: ambas tienen una presentación esta semana.' }, { text: 'Pregunta qué horarios son indispensables.' }, { text: 'Las secciones acuerdan turnos de 20 minutos y una práctica conjunta final.' }, { text: 'Dos delegados revisarán mañana si funcionó.' }], answer: 'La joven facilita escucha, propuesta y seguimiento.' }),
      S.match({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.2.5'], prompt: 'Une frase y habilidad.', hint: 'Busca qué acción realiza la frase.', explain: 'Las frases concretas vuelven practicables las habilidades.' }, { leftTitle: 'Frase', rightTitle: 'Habilidad', pairs: [{ id: 'a', left: 'Entiendo que necesitan agua para dos actividades', right: 'Escucha' }, { id: 'b', left: 'Propongo repartir los horarios', right: 'Propuesta' }, { id: 'c', left: 'Revisemos el acuerdo el viernes', right: 'Seguimiento' }] }),
      S.sort({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.1.2'], prompt: 'Clasifica las acciones juveniles.', hint: 'Consolidar paz amplía participación y evita daño.', explain: 'Las acciones pacíficas no ignoran el conflicto: lo tramitan sin violencia.' }, { buckets: [{ id: 'p', label: 'Construye paz', icon: 'Handshake', color: 'var(--c-ok)' }, { id: 'v', label: 'Agrava el conflicto', icon: 'Zap', color: 'var(--c-bad)' }], items: [{ id: 'a', text: 'Invitar a jóvenes de ambos grupos a proponer opciones', bucket: 'p' }, { id: 'b', text: 'Difundir un rumor para presionar', bucket: 'v' }, { id: 'c', text: 'Registrar el acuerdo y revisarlo', bucket: 'p' }, { id: 'd', text: 'Amenazar a quien discrepa', bucket: 'v' }] }),
      S.choice({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:7.1.2', 'ccss:7.2.5'], prompt: 'En un caso simulado, dos sectores disputan el horario de una pila comunitaria. ¿Qué plan juvenil es más pacífico?', explain: 'Combina escucha, participación, acuerdo y seguimiento.' }, { options: [{ id: 'a', text: 'Reunir representantes, escuchar necesidades, acordar turnos y revisar el resultado' }, { id: 'b', text: 'Cerrar la pila al otro sector' }, { id: 'c', text: 'Publicar acusaciones sin verificar' }], correct: ['a'] }),
      S.write({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:7.1.2', 'ccss:7.2.5'], prompt: 'Escribe una intervención breve de un joven mediador: resumen de necesidades, propuesta y seguimiento.', explain: 'Una mediación no culpa ni decide de forma unilateral.' }, { minWords: 24, placeholder: 'Ambos grupos necesitan... Propongo... Revisaremos...', model: 'Ambos sectores necesitan acceso en horas distintas. Propongo turnos acordados y un espacio para emergencias. Dos jóvenes revisarán el viernes si se respetaron.', rubric: ['Resumí ambas necesidades', 'Propuse una opción pacífica', 'Incluí seguimiento'] }),
      S.choice({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:7.1.2'], prompt: '¿Por qué es importante la participación juvenil en una cultura de paz?' }, { options: [{ id: 'a', text: 'Porque permite practicar diálogo, cooperación y responsabilidad en decisiones presentes' }, { id: 'b', text: 'Porque solo las personas adultas pueden proponer acuerdos' }, { id: 'c', text: 'Porque evita escuchar a otros grupos' }], correct: ['a'] }),
      S.choice({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:7.2.5'], prompt: '¿Qué frase muestra escucha activa?' }, { options: [{ id: 'a', text: 'Entiendo que ambos necesitan el espacio; revisemos los horarios de cada grupo' }, { id: 'b', text: 'Mi grupo gana y punto' }, { id: 'c', text: 'No necesito saber qué piensan' }], correct: ['a'] }),
    ],
  }),

  lesson({
    id: 's07-ccss-3', title: 'Organizar un servicio comunitario', icon: 'Users', minutes: 13,
    gancho: 'Una buena intención, ¿cómo se convierte en un servicio organizado y pacífico?',
    objetivos: ['Organizar una participación juvenil viable en un servicio comunitario'],
    resumen: ['El servicio comunitario responde a una necesidad mediante una organización existente o un equipo definido.', 'Un plan viable aclara tarea, participantes, recursos, acuerdo pacífico y verificación.'],
    media: {
      id: 's07-ccss-3-servicio', kind: 'diagram', title: 'Plantilla de servicio comunitario', aspect: '16:9',
      alt: 'Plantilla vacía con campos para necesidad, participantes, responsabilidad, recursos, acuerdo y verificación.',
      brief: 'Diagrama horizontal 1600×900 rotulado CASO SIMULADO. Seis campos vacíos con iconos descriptivos: NECESIDAD, PARTICIPANTES, RESPONSABILIDAD, RECURSOS, ACUERDO y VERIFICACIÓN. Añadir una flecha de revisión desde verificación hacia necesidad. Texto grande, contraste alto, patrones además de color y orden de lectura claro. No completar el producto ni atribuir hechos a una comunidad real.',
    },
    steps: [
      S.explain({ fase: 'explorar', areas: ['ccss'], cnb: ['ccss:7.1.3'], title: 'Participar con organización', prompt: 'Un servicio comunitario no se improvisa: parte de una necesidad sustentada y reparte responsabilidades.' }, { icon: 'ClipboardList', body: 'Diseñaremos un plan para un **escenario simulado**, sin prometer visitas, entrevistas ni trabajo fuera de la lección.' }),
      S.choice({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.1.3'], prompt: '¿Qué propuesta es un servicio comunitario organizado?', explain: 'Tiene necesidad, responsables, recursos y verificación.' }, { options: [{ id: 'a', text: 'Equipo estudiantil rotula chorros del caso, con permiso, materiales asignados y revisión semanal' }, { id: 'b', text: 'Alguien dice que cuidará el agua algún día' }, { id: 'c', text: 'Un grupo actúa sin acordar responsabilidades' }], correct: ['a'] }),
      S.explain({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.1.3', 'ccss:7.2.5'], title: 'Cinco partes', prompt: 'Cada parte permite coordinar y resolver diferencias pacíficamente.' }, { icon: 'ListChecks', body: 'La participación sirve cuando otras personas pueden comprenderla, realizarla y revisarla.', reveal: [{ icon: 'Target', front: 'Necesidad', back: 'Problema sustentado por evidencia del caso.' }, { icon: 'Users', front: 'Participantes', back: 'Personas u organización y responsabilidades.' }, { icon: 'Package', front: 'Recursos', back: 'Materiales y tiempo realistas.' }, { icon: 'Handshake', front: 'Acuerdo', back: 'Cómo se decidirán turnos o desacuerdos.' }, { icon: 'ClipboardCheck', front: 'Verificación', back: 'Qué señal mostrará avance.' }] }),
      S.ejemplo({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.1.3', 'ccss:7.2.5'], title: 'Ejemplo: cuidar una pila escolar ficticia', prompt: 'El plan usa solo datos suministrados.' }, { icon: 'ClipboardCheck', problem: 'La ficha del caso reporta que una llave queda abierta durante el recreo.', steps: [{ text: 'Necesidad: reducir aperturas innecesarias observadas en la ficha.' }, { text: 'Participantes: consejo estudiantil; dos responsables colocan y revisan un recordatorio.' }, { text: 'Recursos: cartel reutilizable y registro de cinco recreos.' }, { text: 'Acuerdo: turnos voluntarios; si hay diferencia, se escucha y ajusta.' }, { text: 'Verificación: comparar el número de aperturas registradas.' }], answer: 'Es un servicio pequeño, concreto y verificable.' }),
      S.match({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.1.3'], prompt: 'Une elemento y ejemplo.', hint: 'Pregunta qué función cumple.', explain: 'Cada elemento responde una pregunta del plan.' }, { leftTitle: 'Elemento', rightTitle: 'Ejemplo', pairs: [{ id: 'a', left: 'Participantes', right: 'Consejo estudiantil y dos responsables' }, { id: 'b', left: 'Recursos', right: 'Cartel reutilizable y ficha de registro' }, { id: 'c', left: 'Verificación', right: 'Comparar cinco recreos' }] }),
      S.order({ fase: 'construir', areas: ['ccss'], cnb: ['ccss:7.1.3'], prompt: 'Ordena la organización del servicio.', hint: 'Primero comprende la necesidad; al final verifica.', explain: 'El orden evita actuar antes de acordar.' }, { labels: { start: 'Inicio', end: 'Seguimiento' }, items: [{ id: 'a', text: 'Revisar evidencia del caso' }, { id: 'b', text: 'Definir tarea y participantes' }, { id: 'c', text: 'Asignar recursos y responsabilidades' }, { id: 'd', text: 'Acordar cómo resolver diferencias' }, { id: 'e', text: 'Verificar el resultado' }] }),
      S.choice({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:7.1.3', 'ccss:7.2.5'], prompt: 'Caso simulado: se mezclan residuos junto al tanque. ¿Qué plan es viable y pacífico?', explain: 'La opción organiza una acción proporcional a la evidencia.' }, { options: [{ id: 'a', text: 'Equipo escolar separa recipientes ya disponibles, acuerda turnos y registra mezclas durante una semana simulada' }, { id: 'b', text: 'Acusar públicamente a una familia sin evidencia' }, { id: 'c', text: 'Prometer construir una planta de tratamiento' }], correct: ['a'] }),
      S.write({ fase: 'aplicar', areas: ['ccss'], cnb: ['ccss:7.1.3', 'ccss:7.2.5'], prompt: 'Diseña el servicio del caso: necesidad, participantes, responsabilidad, recursos, acuerdo y verificación.', explain: 'Usa solamente el escenario suministrado.' }, { minWords: 30, placeholder: 'Necesidad: ...\nParticipantes y responsabilidad: ...\nRecursos: ...\nAcuerdo: ...\nVerificación: ...', model: 'Necesidad: residuos mezclados. Participantes: comité escolar; dos estudiantes rotulan. Recursos: etiquetas. Acuerdo: turnos. Verificación: contar mezclas en registros simulados.', rubric: ['Definí participantes y responsabilidad', 'Usé recursos factibles', 'Incluí acuerdo y verificación'] }),
      S.choice({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:7.1.3'], prompt: '¿Qué dato vuelve verificable un servicio de rotulación?' }, { options: [{ id: 'a', text: 'Comparar registros de errores antes y después' }, { id: 'b', text: 'Decir que seguramente funcionó' }, { id: 'c', text: 'Cambiar de objetivo al final' }], correct: ['a'] }),
      S.choice({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:7.1.3', 'ccss:7.2.5'], prompt: 'Si dos participantes discrepan sobre turnos, ¿qué decisión conserva la cultura de paz?' }, { options: [{ id: 'a', text: 'Escuchar razones, ajustar responsabilidades y registrar el acuerdo' }, { id: 'b', text: 'Excluir a quien discrepa' }, { id: 'c', text: 'Amenazar con abandonar el servicio' }], correct: ['a'] }),
    ],
  }),
];
