import { S, lesson, semana } from '../../dsl';

/**
 * SEMANA 5 · Unidad 1 "Conociendo nuestras raíces"
 * Tema generador: Una escuela que todas las personas pueden recorrer
 * Cierre: Taller "Mapa táctil para toda la escuela" (Matemáticas · Arte · Ciudadanía · Productividad).
 */
export default semana({
  id: 's05',
  unidad: 1,
  semana: 5,
  kind: 'aprendizaje',
  temaGenerador: 'Una escuela que todas las personas pueden recorrer',
  title: 'Una escuela que todas las personas pueden recorrer',
  subtitle: 'Coordenadas, texturas, participación y trabajo seguro para identificar y reducir barreras',
  icon: 'Accessibility',
  color: 'var(--area-art)',
  contexto: 'La accesibilidad se construye con las personas, no para ellas sin preguntar. Esta semana usamos coordenadas para ubicar espacios, texturas y contraste para comunicar, participación para escuchar y decidir, y herramientas con procedimientos seguros. Trabajaremos con criterios publicados y un caso ficticio; haremos una prueba de claridad entre pares con los ojos abiertos. La consulta especializada con personas con discapacidad o especialistas queda pendiente hasta que la escuela pueda acordarla. Un mapa táctil puede orientar, pero no garantiza acceso para todas las personas ni elimina todas las barreras: también existen barreras físicas, de comunicación, sensoriales y actitudinales que la escuela debe identificar y atender.',
  ejes: ['equidad', 'vida-ciudadana', 'seguridad', 'tecnologia'],
  media: {
    id: 's05-portada',
    kind: 'image',
    title: 'Recorrido accesible por la escuela',
    aspect: '16:9',
    alt: 'Estudiantes y una persona adulta revisan un plano táctil de la escuela; una ruta con relieve conecta la entrada, la dirección, un aula y los baños.',
    brief: 'Ilustración editorial conceptual de una escuela pública guatemalteca. En una mesa, estudiantes revisan entre pares un plano táctil con los ojos abiertos; una tarjeta visible dice "consulta especializada pendiente". El plano muestra cuadrícula, coordenadas grandes, leyenda de cuatro texturas y una ruta continua en relieve. Al fondo se ven una rampa, pasamanos, señalización de alto contraste y un pasillo despejado. No presentar la escena como evidencia de una consulta local ya realizada; todas las personas mantienen los ojos abiertos y participan como ellas mismas. Evitar ayuda condescendiente y promesas de accesibilidad universal.',
  },
  badge: {
    id: 'cartografo-accesible',
    name: 'Cartógrafo que escucha',
    icon: 'Map',
    desc: 'Ubicas espacios, pruebas la claridad entre pares y registras la consulta especializada como pendiente.',
  },
  lessons: [
    lesson({
      id: 's05-d5-taller',
      kind: 'taller',
      day: 5,
      title: 'Mapa táctil para toda la escuela',
      icon: 'Map',
      minutes: 18,
      objetivos: ['Aplicar coordenadas, textura, participación y manejo seguro de materiales para construir, probar y revisar un plano táctil escolar'],
      resumen: [
        'El producto es un plano táctil con coordenadas, una leyenda y una ruta accesible propuesta.',
        'La prueba entre pares revisa claridad con los ojos abiertos; la consulta especializada con personas con discapacidad o especialistas queda pendiente.',
        'El mapa orienta, pero no sustituye la eliminación de barreras físicas, comunicativas, sensoriales y actitudinales.',
      ],
      media: {
        id: 's05-taller-kit-tactil',
        kind: 'image',
        title: 'Kit reutilizable de plano táctil',
        aspect: '4:3',
        alt: 'Bandeja rotulada con base cuadriculada, piezas lavables de cuatro texturas, cordón grueso, etiquetas grandes y una guía de montaje.',
        brief: 'Activo físico de alta preparación pendiente. Reemplazo durable: 8 kits reutilizables para grupos de 3 o 4, cada uno en bandeja rotulada, con base rígida lavable cuadriculada de 40 por 40 cm, ejes y coordenadas de alto contraste, 12 piezas grandes precortadas de EVA, corcho, plástico corrugado y fieltro, cordón grueso con cierre de gancho y felpa, etiquetas impresas grandes y cuatro muestras para la leyenda. Todas las esquinas deben estar redondeadas; no incluir piezas punzantes, granos sueltos ni adhesivo húmedo. Preparación central: fabricar y probar una vez, registrar piezas y guardar cada kit completo. Preparación docente normal, máximo 2 minutos: distribuir una bandeja por grupo y comprobar con la lista que contiene base, ruta, 12 zonas y cuatro muestras. Reemplazo o alternativa de baja tecnología: cartón corrugado y retazos limpios precortados por una persona adulta fuera del tiempo de clase, unidos con cinta de doble cara ya colocada. Todo recorte y pegado permanente ocurre en la preparación central, fuera de la sesión habitual.',
      },
      steps: [
        S.explain(
          { fase: 'explorar', areas: ['fc'], cnb: ['fc:3.2.1'], ambito: 'convivir', title: '1 min · Encargo y límites',
            prompt: '**1 min.** La escuela pide un plano táctil. Hoy usarán criterios publicados y un caso ficticio, no evidencia de una consulta local.' },
          { icon: 'MessageCircleQuestion', body: 'La prueba entre pares permite revisar claridad, pero no sustituye la participación de personas con discapacidad. Registren **consulta especializada pendiente** y no atribuyan opiniones no expresadas. Un plano puede apoyar la orientación, pero **no garantiza acceso para todas las personas** ni elimina todas las barreras físicas, de comunicación, sensoriales y actitudinales.' },
        ),
        S.project(
          { fase: 'construir', areas: ['fc'], cnb: ['fc:3.2.1', 'fc:3.2.2'], ambito: 'convivir', title: '1 min · Lean el caso ficticio',
            prompt: '**1 min.** Lean un brief ficticio compuesto a partir de criterios publicados de accesibilidad y anoten dos requisitos de diseño.' },
          { goal: 'Convertir una referencia claramente etiquetada en requisitos verificables, sin presentarla como consulta local.',
            steps: [
              { title: 'Caso ficticio', detail: 'El encargo propone conectar entrada, dirección, aula de sexto y baños.' },
              { title: 'Criterios publicados', detail: 'La referencia recomienda una ruta continua en relieve, rótulos grandes y texturas contrastantes.' },
            ],
            evidence: 'Dos requisitos escritos en la hoja del equipo.',
            rubric: ['Identificamos la fuente como ficticia y publicada', 'No afirmamos haber consultado a una persona local'] },
        ),
        S.coord(
          { fase: 'construir', areas: ['mat'], cnb: ['mat:1.5.3'], ambito: 'hacer', title: '1 min · Verifiquen una coordenada',
            prompt: '**1 min.** Con la entrada como origen, coloquen la dirección en **(−3, 2)**.',
            hint: 'Primero x: 3 a la izquierda. Después y: 2 hacia arriba.',
            explain: '(−3, 2) queda a la izquierda y arriba del origen.' },
          { range: { xmin: -5, xmax: 5, ymin: -5, ymax: 5 }, task: { kind: 'place', x: -3, y: 2, emoji: '🏫', label: 'Dirección' } },
        ),
        S.project(
          { fase: 'aplicar', areas: ['mat', 'fc'], cnb: ['mat:1.5.3', 'fc:3.2.1'], ambito: 'hacer', title: '2 min · Armen la base',
            prompt: '**2 min.** Usen el kit preparado. Definan el origen y ubiquen cuatro destinos según el brief ficticio.' },
          { goal: 'Construir la base coordenada del plano.',
            steps: [
              { title: 'Origen', detail: 'Marquen la entrada principal como (0, 0) y mantengan visibles los ejes x e y.' },
              { title: 'Cuatro destinos', detail: 'Coloquen dirección (−3, 2), aula (2, 3), baños (4, −2) y bebedero (1, −3).' },
            ],
            evidence: 'Base con origen, ejes, coordenadas y cuatro lugares rotulados.',
            rubric: ['Leímos cada par como x y luego y', 'Los cuatro destinos coinciden con sus coordenadas'] },
        ),
        S.match(
          { fase: 'aplicar', areas: ['mat', 'art'], cnb: ['mat:1.5.3', 'art:3.2.1'], ambito: 'hacer', title: '1 min · Alineen símbolos y datos',
            prompt: '**1 min.** Antes de fijar las piezas, unan cada destino con su coordenada y textura acordada.' },
          { leftTitle: 'Destino', rightTitle: 'Dato del plano', pairs: [
            { id: 'a', left: 'Dirección', right: '(−3, 2) · EVA lisa' },
            { id: 'b', left: 'Aula', right: '(2, 3) · fieltro suave' },
            { id: 'c', left: 'Baños', right: '(4, −2) · plástico corrugado' },
            { id: 'd', left: 'Bebedero', right: '(1, −3) · corcho rugoso' },
          ] },
        ),
        S.project(
          { fase: 'aplicar', areas: ['art'], cnb: ['art:3.2.1'], ambito: 'hacer', title: '2 min · Construyan la leyenda',
            prompt: '**2 min.** Elijan cuatro materiales del kit con textura y contraste visual claramente diferentes.' },
          { goal: 'Crear una leyenda táctil y visual consistente.',
            steps: [
              { title: 'Cuatro muestras', detail: 'Asignen EVA lisa, corcho rugoso, plástico corrugado y fieltro suave a cuatro tipos de espacio.' },
              { title: 'Clave', detail: 'Fijen una muestra de cada textura junto a su nombre en letra grande y alto contraste.' },
            ],
            evidence: 'Leyenda con cuatro muestras seguras y sus significados.',
            rubric: ['Las texturas se distinguen entre sí', 'La clave coincide con las piezas del plano'] },
        ),
        S.project(
          { fase: 'aplicar', areas: ['mat', 'art'], cnb: ['mat:1.5.3', 'art:3.2.1'], ambito: 'hacer', title: '2 min · Marquen la ruta',
            prompt: '**2 min.** Unan entrada, dirección, aula y baños con el cordón continuo del kit; anoten las coordenadas de cada parada.' },
          { goal: 'Representar una ruta accesible propuesta sin afirmar que ya está libre de barreras.',
            steps: [
              { title: 'Ruta continua', detail: 'Fijen el cordón sin cruces ni extremos sueltos y dejen libres las etiquetas.' },
              { title: 'Comprobación física', detail: 'Comparen la propuesta con el pasillo real: ancho, escalones, pendientes, puertas y objetos que obstruyen requieren revisión de la escuela.' },
            ],
            evidence: 'Ruta en relieve con cuatro paradas coordenadas y una lista de barreras por verificar.',
            rubric: ['La ruta puede seguirse sin perder el cordón', 'No presentamos como accesible un tramo que no fue verificado'] },
        ),
        S.order(
          { fase: 'aplicar', areas: ['pyd'], cnb: ['pyd:3.2.3', 'pyd:3.2.4'], ambito: 'hacer', title: '1 min · Apliquen el proceso seguro',
            prompt: '**1 min.** Ordenen el manejo seguro de las piezas y herramientas del kit.' },
          { items: [
            { id: 'a', text: 'Revisar piezas, bordes y cierres antes de usarlos' },
            { id: 'b', text: 'Trabajar en una mesa despejada con las piezas grandes' },
            { id: 'c', text: 'Presionar cierres sin usar tijeras ni objetos punzantes' },
            { id: 'd', text: 'Contar, limpiar y guardar todo en la bandeja rotulada' },
          ] },
        ),
        S.project(
          { fase: 'aplicar', areas: ['fc', 'art'], cnb: ['fc:3.2.1', 'art:3.2.1'], ambito: 'convivir', title: '2 min · Prueba de claridad entre pares',
            prompt: '**2 min.** Un compañero prueba una consigna con los ojos abiertos y participa como él mismo. Esta prueba revisa la claridad del mapa; la consulta especializada permanece pendiente.' },
          { goal: 'Recoger retroalimentación real entre pares sin atribuirla a usuarios con discapacidad.',
            steps: [
              { title: 'Consigna', detail: 'Con los ojos abiertos, localiza los baños desde la entrada y explica qué símbolos ayudan o confunden.' },
              { title: 'Registro', detail: 'Anoten un comentario de claridad y una sugerencia del compañero; identifiquen la fuente como prueba entre pares.' },
            ],
            evidence: 'Registro de retroalimentación de la prueba entre pares, con ojos abiertos.',
            rubric: ['Todas las personas mantuvieron los ojos abiertos', 'El registro no se presenta como consulta especializada'] },
        ),
        S.project(
          { fase: 'aplicar', areas: ['mat', 'art', 'pyd'], cnb: ['mat:1.5.3', 'art:3.2.1', 'pyd:3.2.3'], ambito: 'hacer', title: '2 min · Revisión dirigida',
            prompt: '**2 min.** Corrijan una dificultad observada y vuelvan a comprobar coordenadas, leyenda, ruta y seguridad.' },
          { goal: 'Mejorar el producto con evidencia.',
            steps: [
              { title: 'Una corrección', detail: 'Muevan una pieza, cambien una textura, separen elementos o reparen el cordón según la retroalimentación entre pares.' },
              { title: 'Lista final', detail: 'Verifiquen cuatro coordenadas, cuatro claves coincidentes, ruta continua y ninguna pieza suelta o filosa.' },
            ],
            evidence: 'Plano revisado y nota breve que relaciona observación, cambio y nueva comprobación.',
            rubric: ['El cambio responde a evidencia de la prueba', 'Ruta, clave, coordenadas y texturas siguen alineadas'] },
        ),
        S.choice(
          { fase: 'comprobar', areas: ['fc'], cnb: ['fc:3.2.1'], title: '1 min · Salida de participación',
            prompt: '**1 min.** En un caso ficticio, una futura consultora indica que dos texturas se confunden. ¿Qué acción respetaría su participación?' },
          { options: [
            { id: 'a', text: 'Pedirle que compare alternativas y cambiar la clave según la prueba' },
            { id: 'b', text: 'Explicarle que el equipo ya decidió y conservar el diseño' },
            { id: 'c', text: 'Hablar por ella ante la dirección sin volver a consultarla' },
          ], correct: ['a'] },
        ),
        S.choice(
          { fase: 'comprobar', areas: ['pyd'], cnb: ['pyd:3.2.4'], title: '1 min · Salida de seguridad',
            prompt: '**1 min.** Al revisar el kit aparece una pieza con una esquina cortante. ¿Qué corresponde?' },
          { options: [
            { id: 'a', text: 'Retirarla, reportarla y usar una pieza segura de reemplazo' },
            { id: 'b', text: 'Cubrirla con la mano durante la prueba' },
            { id: 'c', text: 'Dejarla porque la actividad dura pocos minutos' },
          ], correct: ['a'] },
        ),
        S.reflect(
          { fase: 'reflexionar', areas: ['mat', 'art', 'fc', 'pyd'], cnb: ['mat:1.5.3', 'art:3.2.1', 'fc:3.2.1', 'pyd:3.2.4'], ambito: 'ser', title: '1 min · Reflexión',
            prompt: '**1 min.** Revisa la evidencia del equipo y elige un compromiso realista.' },
          { statements: [
            'Usé coordenadas coherentes entre el plano y la ruta',
            'Hice coincidir texturas y clave',
            'Registré la retroalimentación de la prueba entre pares sin presentarla como consulta especializada',
            'Anoté el estado honesto: consulta especializada pendiente',
            'Reconozco barreras que el mapa no resuelve',
          ], commitments: [
            'Presentaré la lista de barreras al gobierno escolar',
            'Como próximo paso, solicitaré a la dirección una consulta con personas con discapacidad o especialistas antes de fabricar una versión permanente',
            'Guardaré el kit completo para que otro grupo pueda revisarlo',
          ] },
        ),
      ],
    }),

    lesson({
      id: 's05-d5-reto',
      kind: 'reto',
      day: 5,
      title: 'Reto de la semana 5',
      icon: 'Trophy',
      minutes: 14,
      objetivos: ['Transferir lo aprendido en las diez áreas a situaciones nuevas'],
      resumen: ['Resolví situaciones nuevas de las diez áreas sin pistas ni respuestas reutilizadas.'],
      media: {
        id: 's05-d5-reto',
        kind: 'image',
        title: 'Mesa de revisión del plano escolar',
        aspect: '16:9',
        alt: 'Mesa con un plano táctil, una hoja de coordenadas, muestras de textura, un registro de prueba entre pares y herramientas escolares guardadas de forma segura.',
        brief: 'Mock de producción para una imagen cenital clara, legible en celular. Mostrar el producto real de la semana: plano táctil cuadriculado con cuatro destinos, ruta continua, leyenda de cuatro texturas y coordenadas visibles. Alrededor, una ficha rotulada "prueba entre pares, ojos abiertos", una tarjeta "consulta especializada pendiente", una lista de revisión y una bandeja cerrada con perforadora y tijeras de punta roma. No mostrar evidencia atribuida a personas con discapacidad, piezas filosas sueltas, personas con los ojos cubiertos ni mensajes que prometan accesibilidad universal.',
      },
      steps: [
        S.coord({ fase: 'comprobar', areas: ['mat'], cnb: ['mat:1.5.3'], prompt: 'En un plano nuevo, coloca la biblioteca en **(−1, 5)**.' },
          { range: { xmin: -5, xmax: 5, ymin: -5, ymax: 5 }, task: { kind: 'place', x: -1, y: 5, emoji: '📚', label: 'Biblioteca' } }),
        S.fill({ fase: 'comprobar', areas: ['l1'], cnb: ['l1:7.1.2'], prompt: 'Completa la concordancia del aviso escolar.' },
          { text: 'Las entradas [[amplias]] permanecen [[despejadas]].', distractors: ['amplia', 'despejado', 'amplios'] }),
        S.choice({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:4.2.1'], prompt: 'Un grupo busca una actividad protectora para el recreo. ¿Cuál cumple mejor ese propósito?' },
          { options: [
            { id: 'a', text: 'Organizar juegos cooperativos voluntarios con acompañamiento adulto' },
            { id: 'b', text: 'Dejar a cada estudiante sin opciones ni espacios compartidos' },
            { id: 'c', text: 'Ofrecer sustancias para soportar el cansancio' },
          ], correct: ['a'] }),
        S.order({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:6.2.1'], prompt: 'Ordena el cambio histórico desde grupos móviles hasta aldeas con oficios.' },
          { items: [
            { id: 'a', text: 'Caza y recolección en grupos móviles' },
            { id: 'b', text: 'Domesticación de plantas y animales' },
            { id: 'c', text: 'Producción y almacenamiento de excedentes' },
            { id: 'd', text: 'Especialización de oficios en aldeas' },
          ] }),
        S.choice({ fase: 'comprobar', areas: ['l2'], cnb: ['l2:1.2.2', 'l2:3.3.4'], prompt: '¿Qué mensaje argumenta con una razón comprobable?' },
          { options: [
            { id: 'a', text: 'Propongo reparar el pasamanos porque la inspección registró dos soportes flojos' },
            { id: 'b', text: 'El pasamanos está junto a la pared' },
            { id: 'c', text: 'Repárenlo porque sí' },
          ], correct: ['a'] }),
        S.fill({ fase: 'comprobar', areas: ['l3'], cnb: ['l3:2.2.3'], prompt: 'Complete: Ellos rotulan el mapa cuidadosamente. (They label the map carefully.)' },
          { text: '[[They]] [[label]] the map [[carefully]].', distractors: ['Labels', 'careful', 'He'] }),
        S.choice({ fase: 'comprobar', areas: ['fc'], cnb: ['fc:3.2.2'], prompt: '¿Qué propuesta permite rendir cuentas al gobierno escolar?' },
          { options: [
            { id: 'a', text: 'Publicar el acuerdo, la persona responsable, la fecha y el resultado de la revisión' },
            { id: 'b', text: 'Prometer cambios sin responsables ni fecha' },
            { id: 'c', text: 'Decidir en secreto y evitar preguntas' },
          ], correct: ['a'] }),
        S.match({ fase: 'comprobar', areas: ['art'], cnb: ['art:3.2.1'], prompt: 'Une cada muestra nueva con la sensación táctil que comunica.' },
          { pairs: [
            { id: 'a', left: 'Goma EVA sin relieve', right: 'Lisa' },
            { id: 'b', left: 'Cartón corrugado', right: 'Acanalada' },
            { id: 'c', left: 'Esponja firme', right: 'Porosa' },
          ] }),
        S.sort({ fase: 'comprobar', areas: ['ef'], cnb: ['ef:2.1.9'], prompt: 'Juzga estas ejecuciones del pase por arriba del hombro con salto, a altura media o alta y con mano izquierda o derecha.' },
          { buckets: [
            { id: 'correcta', label: 'Ejecución correcta', icon: 'CircleCheck' },
            { id: 'ajuste', label: 'Necesita ajuste', icon: 'RefreshCw' },
          ], items: [
            { id: 'a', text: 'Salta con impulso del pie derecho y pasa con la izquierda por arriba del hombro a la altura media del pecho', bucket: 'correcta' },
            { id: 'b', text: 'Salta con impulso del pie izquierdo y pasa con la derecha por arriba del hombro a altura alta, hacia las manos elevadas', bucket: 'correcta' },
            { id: 'c', text: 'Con la izquierda, envía un pase alto antes de saltar y sin llevar el balón por arriba del hombro', bucket: 'ajuste' },
            { id: 'd', text: 'Con la derecha, hace un pase medio desde abajo y aterriza antes de soltar el balón', bucket: 'ajuste' },
          ] }),
        S.sort({ fase: 'comprobar', areas: ['pyd'], cnb: ['pyd:3.2.3', 'pyd:3.2.4'], prompt: 'Clasifica acciones al usar una perforadora de papel escolar.' },
          { buckets: [
            { id: 'antes', label: 'Antes', icon: 'ClipboardCheck' },
            { id: 'durante', label: 'Durante', icon: 'Hand' },
            { id: 'despues', label: 'Después', icon: 'PackageCheck' },
          ], items: [
            { id: 'a', text: 'Comprobar que la base esté estable', bucket: 'antes' },
            { id: 'b', text: 'Mantener los dedos fuera del mecanismo', bucket: 'durante' },
            { id: 'c', text: 'Vaciar los círculos de papel y guardarla', bucket: 'despues' },
          ] }),
      ],
    }),
  ],
  bank: [
    S.number({ fase: 'comprobar', areas: ['mat'], cnb: ['mat:2.1.1'], prompt: 'La serie **6, 16, 36, 76, …** sigue “×2, luego +4”. ¿Qué número sigue?' },
      { answer: 156 }),
    S.highlight({ fase: 'comprobar', areas: ['l1'], cnb: ['l1:5.2.2'], prompt: 'Toca solo las palabras que caracterizan la señal.' },
      { target: 'palabras connotativas', text: 'Esta puerta {ancha} tiene una manija {lisa} y un rótulo {visible}.' }),
    S.choice({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:4.2.1'], prompt: '¿Qué evidencia ilustra mejor cómo una actividad social puede proteger una vida sana?' },
      { options: [
        { id: 'a', text: 'Un registro muestra asistencia voluntaria a un club de teatro, nuevas amistades y estrategias para manejar el estrés' },
        { id: 'b', text: 'Un anuncio repite una promesa sin mostrar actividad ni resultados' },
        { id: 'c', text: 'Una lista enumera sustancias sin relacionarlas con decisiones saludables' },
      ], correct: ['a'] }),
    S.choice({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:6.3.1'], prompt: '¿Qué obra permitió llevar agua a cultivos en Egipto y Mesopotamia?' },
      { options: [
        { id: 'a', text: 'Canales de riego' },
        { id: 'b', text: 'Vías de ferrocarril' },
        { id: 'c', text: 'Torres de radio' },
      ], correct: ['a'] }),
    S.sort({ fase: 'comprobar', areas: ['l2'], cnb: ['l2:1.2.2'], prompt: 'Clasifica la intención principal de cada mensaje escolar.' },
      { buckets: [
        { id: 'i', label: 'Informar', icon: 'Info' },
        { id: 'e', label: 'Explicar', icon: 'ListOrdered' },
        { id: 'a', label: 'Argumentar', icon: 'MessageSquareText' },
      ], items: [
        { id: 'a', text: 'La biblioteca abre a las siete.', bucket: 'i' },
        { id: 'b', text: 'Primero gira la manija y luego empuja la puerta.', bucket: 'e' },
        { id: 'c', text: 'Conviene despejar el corredor porque la observación halló tres obstáculos.', bucket: 'a' },
      ] }),
    S.choice({ fase: 'comprobar', areas: ['l3'], cnb: ['l3:2.2.3'], prompt: 'Choose the sentence with correct order.' },
      { options: [
        { id: 'a', text: 'She opens the wide door slowly.' },
        { id: 'b', text: 'She the wide door slowly opens.' },
        { id: 'c', text: 'Slowly wide she door opens.' },
      ], correct: ['a'] }),
    S.order({ fase: 'comprobar', areas: ['fc'], cnb: ['fc:3.2.1'], prompt: 'Ordena un proceso participativo para mejorar el patio.' },
      { items: [
        { id: 'a', text: 'Preguntar a quienes usan el patio' },
        { id: 'b', text: 'Acordar una mejora posible' },
        { id: 'c', text: 'Realizar la acción acordada' },
        { id: 'd', text: 'Revisar el resultado con las personas participantes' },
      ] }),
    S.choice({ fase: 'comprobar', areas: ['art'], cnb: ['art:3.2.1'], prompt: '¿Qué par ofrece mayor contraste táctil para dos símbolos vecinos?' },
      { options: [
        { id: 'a', text: 'Fieltro suave y cartón corrugado' },
        { id: 'b', text: 'Dos retazos del mismo fieltro' },
        { id: 'c', text: 'Dos hojas de papel liso' },
      ], correct: ['a'] }),
    S.match({ fase: 'comprobar', areas: ['ef'], cnb: ['ef:2.1.9'], prompt: 'Identifica la mano y la altura en cada pase por arriba del hombro con salto.' },
      { leftTitle: 'Ejecución observada', rightTitle: 'Mano y altura', pairs: [
        { id: 'a', left: 'Salta y suelta con la izquierda hacia el pecho de su pareja', right: 'Izquierda · altura media' },
        { id: 'b', left: 'Salta y suelta con la derecha por encima de la cabeza de su pareja', right: 'Derecha · altura alta' },
        { id: 'c', left: 'Salta y suelta con la derecha hacia el pecho de su pareja', right: 'Derecha · altura media' },
        { id: 'd', left: 'Salta y suelta con la izquierda por encima de la cabeza de su pareja', right: 'Izquierda · altura alta' },
      ] }),
    S.choice({ fase: 'comprobar', areas: ['pyd'], cnb: ['pyd:3.2.4'], prompt: 'Una polea escolar tiene la cuerda deshilachada. ¿Qué haces antes de usarla?' },
      { options: [
        { id: 'a', text: 'No usarla y reportar el daño para que una persona responsable la repare' },
        { id: 'b', text: 'Jalar más fuerte para terminar rápido' },
        { id: 'c', text: 'Pedir a alguien que se coloque debajo de la carga' },
      ], correct: ['a'] }),
  ],
});
