import { S, lesson, semana } from '../../dsl';

/** Semana 6: una propuesta alimentaria adaptable, no una prescripción. */
export default semana({
  id: 's06',
  unidad: 1,
  semana: 6,
  kind: 'aprendizaje',
  temaGenerador: 'Una refacción nutritiva con recursos locales',
  title: 'Una refacción nutritiva con recursos locales',
  subtitle: 'Nutrientes, opciones disponibles, conjuntos, comunicación, proyecto y costo',
  icon: 'Salad',
  color: 'var(--area-cnt)',
  contexto: 'Las refacciones posibles cambian según la comunidad, la temporada, la disponibilidad y el presupuesto. Compararemos opciones que podrían encontrarse en distintos lugares de Guatemala, como tortilla, frijol, pepitoria, huevo, banano, papaya, naranja, güisquil o aguacate, sin asumir que todas están disponibles para todas las familias. Analizaremos qué nutrientes pueden aportar, compararemos conjuntos y prepararemos una propuesta con presupuesto. Antes de elegir o preparar alimentos se consultan alergias, intolerancias, restricciones alimentarias y prácticas familiares o culturales. La preparación real requiere higiene y apoyo o supervisión de una persona adulta cuando haya calor, cuchillos, cocción u otros riesgos.',
  ejes: ['vida-familiar', 'equidad', 'trabajo', 'seguridad'],
  media: {
    id: 's06-portada', kind: 'image', title: 'Opciones locales para una refacción', aspect: '16:9',
    alt: 'Mesa escolar con tortillas, frijoles cocidos, bananos, papaya, pepitoria, huevos, güisquil y agua; estudiantes comparan nutrientes y costos.',
    brief: 'Ilustración editorial clara de una mesa escolar en Guatemala. Mostrar porciones separadas de tortilla, frijol cocido, banano, papaya, pepitoria, huevo cocido, güisquil y agua, tarjetas de ingredientes, una tabla de presupuesto y dos conjuntos. Incluir una ficha visible: "consultar alergias y restricciones". Presentar diversidad regional sin afirmar disponibilidad universal. Sin marcas ni juicios morales sobre los alimentos.',
  },
  badge: {
    id: 'planificador-refaccion-local', name: 'Planificador de opciones locales', icon: 'ClipboardCheck',
    desc: 'Comparaste opciones y justificaste un menú, un presupuesto y un plan adaptable.',
  },
  lessons: [
    lesson({
      id: 's06-d5-taller',
      kind: 'taller',
      day: 5,
      title: 'Una refacción local que nutre',
      icon: 'CookingPot',
      minutes: 19,
      gancho: 'El comité necesita una propuesta adaptable para 12 personas. ¿Cómo puede justificar el menú, comparar opciones y comprobar que el costo cabe en el escenario?',
      objetivos: ['Integrar evidencia de Ciencias, Matemáticas, L1 y Productividad en una propuesta de refacción local adaptable'],
      resumen: [
        'El producto contiene un menú justificado, una comparación de conjuntos, un presupuesto simple y un esquema del proyecto.',
        'Los alimentos pueden aportar varios nutrientes; la justificación describe aportes sin prometer resultados de salud.',
        'Los precios del escenario son ilustrativos y no representan precios actuales del mercado.',
        'La propuesta consulta alergias, intolerancias y restricciones, y separa la planificación de cualquier preparación real con apoyo adulto.',
      ],
      media: {
        id: 's06-taller-ficha', kind: 'image', title: 'Ficha de propuesta de refacción', aspect: '4:3',
        alt: 'Ficha dividida en menú justificado, comparación de conjuntos, presupuesto y esquema del proyecto, con una franja para alergias y restricciones.',
        brief: 'Mock honesto de una ficha imprimible aún sin respuestas. Cuatro zonas rotuladas: menú justificado, comparación de conjuntos, presupuesto y esquema del proyecto. Franja "consultar alergias, intolerancias y restricciones" y nota "precios ilustrativos del escenario". Espacio real para cálculos y revisión; no simular evidencia estudiantil.',
      },
      steps: [
        S.explain(
          { fase: 'explorar', areas: ['cnt'], cnb: ['cnt:5.1.1'], ambito: 'conocer', title: '1 min · Lean el encargo',
            prompt: '**1 min.** Revisen el encargo para 12 personas y los límites de la propuesta.' },
          { icon: 'ClipboardList', body: 'Trabajarán con alimentos posibles del escenario, no con una lista universal. Los **precios son ilustrativos**, no datos actuales del mercado. Hoy diseñan en papel; no cocinan. Una preparación posterior debe consultar alergias, intolerancias y restricciones, lavarse las manos y contar con apoyo o supervisión adulta para calor, cuchillos o cocción.' },
        ),
        S.project(
          { fase: 'construir', areas: ['l1', 'pyd'], cnb: ['l1:8.2.1', 'pyd:4.1.1'], ambito: 'hacer', title: '1 min · Abran la ficha',
            prompt: '**1 min.** Dividan la ficha en los cuatro componentes del producto.' },
          { goal: 'Preparar la estructura de una propuesta que otra persona pueda revisar.',
            steps: [
              { title: 'Cuatro zonas', detail: 'Rotulen menú justificado, comparación de conjuntos, presupuesto y esquema del proyecto.' },
              { title: 'Condiciones', detail: 'Añadan disponibilidad por confirmar y consulta de alergias, intolerancias y restricciones.' },
            ],
            evidence: 'Ficha con cuatro zonas y condiciones visibles.',
            rubric: ['Los cuatro componentes tienen espacio propio', 'La ficha no supone disponibilidad ni seguridad alimentaria'] },
        ),
        S.match(
          { fase: 'construir', areas: ['cnt'], cnb: ['cnt:5.1.1'], ambito: 'conocer', title: '2 min · Recuperen evidencia',
            prompt: '**2 min.** Relacionen cada alimento del escenario con un aporte que puede apoyar la justificación. Un alimento puede aportar más de un nutriente.' },
          { leftTitle: 'Alimento', rightTitle: 'Aporte destacado', pairs: [
            { id: 'a', left: 'Tortilla de maíz', leftIcon: 'Wheat', right: 'Carbohidratos y algo de fibra' },
            { id: 'b', left: 'Frijol cocido', leftIcon: 'Soup', right: 'Proteína vegetal, fibra y hierro' },
            { id: 'c', left: 'Banano', leftIcon: 'Banana', right: 'Carbohidratos, fibra y potasio' },
            { id: 'd', left: 'Pepitoria', leftIcon: 'Nut', right: 'Grasas, proteína y minerales' },
          ] },
        ),
        S.choice(
          { fase: 'aplicar', areas: ['mat'], cnb: ['mat:3.2.1'], ambito: 'hacer', title: '1 min · Comparen conjuntos',
            prompt: '**1 min.** L = opciones confirmadas disponibles en el escenario = {tortilla, frijol, banano, papaya}; P = opciones que pueden aportar proteína = {frijol, huevo, queso, pepitoria}. ¿Cuál es **L ∩ P**?' },
          { options: [
            { id: 'a', text: '{frijol}' },
            { id: 'b', text: '{tortilla, frijol, banano, papaya, huevo, queso, pepitoria}' },
            { id: 'c', text: '{huevo, queso, pepitoria}' },
          ], correct: ['a'] },
        ),
        S.project(
          { fase: 'aplicar', areas: ['cnt', 'l1'], cnb: ['cnt:5.1.1', 'cnt:5.3.1', 'l1:8.2.1'], ambito: 'hacer', title: '2 min · Justifiquen el menú',
            prompt: '**2 min.** Propongan el menú base del escenario y una alternativa adaptable.' },
          { goal: 'Escribir un menú justificable con lenguaje descriptivo y sin juicios morales.',
            steps: [
              { title: 'Menú base', detail: 'Propongan 2 tortillas con frijol cocido, 1 banano y agua segura. Describan aportes posibles: carbohidratos, proteína vegetal, fibra, vitaminas y minerales.' },
              { title: 'Alternativa', detail: 'Si una alergia, intolerancia, restricción o práctica familiar impide un ingrediente, anoten "consultar y sustituir por una opción disponible con aporte semejante"; no inventen que una opción es segura para todas las personas.' },
            ],
            evidence: 'Menú con una razón nutricional y una alternativa sujeta a consulta.',
            rubric: ['La razón usa lenguaje de aportes posibles', 'La alternativa respeta restricciones y disponibilidad'] },
        ),
        S.number(
          { fase: 'aplicar', areas: ['mat', 'pyd'], cnb: ['pyd:4.1.1'], ambito: 'hacer', title: '2 min · Calculen el presupuesto',
            prompt: '**2 min. Precios ilustrativos del escenario**, no precios actuales:\n- 24 tortillas a **Q0.50** cada una\n- 3 libras de frijol a **Q8** cada libra\n- 12 bananos a **Q1** cada uno\n¿Cuál es el costo total para 12 refacciones?' },
          { answer: 48, unit: 'quetzales' },
        ),
        S.number(
          { fase: 'aplicar', areas: ['mat', 'pyd'], cnb: ['pyd:4.1.1'], ambito: 'hacer', title: '1 min · Comprueben costo unitario',
            prompt: '**1 min.** El total ilustrativo es Q48 para 12 refacciones. ¿Cuál es el costo por refacción?' },
          { answer: 4, unit: 'quetzales por refacción' },
        ),
        S.project(
          { fase: 'aplicar', areas: ['pyd', 'l1'], cnb: ['pyd:4.1.1', 'pyd:4.3.1', 'l1:8.2.1'], ambito: 'emprender', title: '2 min · Tracen el esquema del proyecto',
            prompt: '**2 min.** Completen el esquema del proyecto sin pasar todavía a preparar alimentos.' },
          { goal: 'Convertir la propuesta en un proyecto verificable.',
            steps: [
              { title: 'Objetivo y actividades', detail: 'Escriban un objetivo con verbo y tres actividades: confirmar restricciones y disponibilidad, actualizar precios y presentar la propuesta.' },
              { title: 'Responsables y revisión', detail: 'Asignen responsables, fecha y criterio de revisión. La preparación real queda condicionada a autorización y apoyo adulto.' },
            ],
            evidence: 'Esquema del proyecto con objetivo, actividades, responsables, fecha y revisión.',
            rubric: ['Las actividades responden al objetivo', 'El plan distingue propuesta de preparación real'] },
        ),
        S.write(
          { fase: 'aplicar', areas: ['l1', 'cnt'], cnb: ['l1:8.2.1', 'cnt:5.1.1'], ambito: 'hacer', title: '2 min · Redacten la propuesta',
            prompt: '**2 min.** Escriban una explicación que conecte menú, nutrientes, comparación de conjuntos y costo.' },
          { minWords: 22, placeholder: 'Proponemos... porque... En el escenario, L ∩ P... El costo...',
            model: 'Proponemos tortillas con frijol, banano y agua segura por sus distintos aportes. L ∩ P muestra que el frijol cumple las dos condiciones. Los precios ilustrativos suman Q48, o Q4 por refacción. Antes de preparar, confirmaremos disponibilidad y restricciones.',
            rubric: ['Justificamos el menú con aportes', 'Explicamos los conjuntos', 'Comunicamos total y costo unitario'] },
        ),
        S.project(
          { fase: 'aplicar', areas: ['cnt', 'mat', 'l1', 'pyd'], cnb: ['cnt:5.1.1', 'mat:3.2.1', 'l1:8.2.1', 'pyd:4.1.1'], ambito: 'hacer', title: '2 min · Revisen los componentes',
            prompt: '**2 min.** Intercambien fichas y verifiquen que las cuatro partes cuentan la misma propuesta.' },
          { goal: 'Corregir incoherencias antes de entregar.',
            steps: [
              { title: 'Alineación', detail: 'Menú, conjunto, justificación y presupuesto usan los mismos ingredientes y cantidades.' },
              { title: 'Límites honestos', detail: 'La ficha dice precios ilustrativos, disponibilidad por confirmar, consulta de restricciones y apoyo adulto.' },
            ],
            evidence: 'Una corrección marcada y comprobada.',
            rubric: ['Los cuatro componentes están alineados', 'La propuesta conserva límites honestos'] },
        ),
        S.choice(
          { fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:5.3.1'], title: '1 min · Salida de cuidado',
            prompt: '**1 min.** Una compañera informa una alergia. ¿Qué debe decir la propuesta?' },
          { options: [
            { id: 'a', text: 'Confirmar la restricción con la familia o escuela y elegir una alternativa segura antes de preparar' },
            { id: 'b', text: 'Servir una porción pequeña porque así no habrá reacción' },
            { id: 'c', text: 'Quitar el rótulo para no preocupar al grupo' },
          ], correct: ['a'] },
        ),
        S.number(
          { fase: 'comprobar', areas: ['mat', 'pyd'], cnb: ['pyd:4.1.1'], title: '1 min · Salida de presupuesto',
            prompt: '**1 min.** En otro escenario ilustrativo, 10 porciones cuestan Q35. ¿Cuál es el costo por porción?' },
          { answer: 3.5, unit: 'quetzales por porción' },
        ),
        S.reflect(
          { fase: 'reflexionar', areas: ['cnt', 'mat', 'l1', 'pyd'], cnb: ['cnt:5.1.1', 'mat:3.2.1', 'l1:8.2.1', 'pyd:4.3.1'], ambito: 'ser', title: '1 min · Reflexión',
            prompt: '**1 min.** Revisa la evidencia y elige el próximo paso más honesto.' },
          { statements: [
            'Justifiqué el menú sin prometer resultados de salud',
            'Comprobé conjuntos, subtotales, total y costo por persona',
            'Incluí restricciones, disponibilidad y preparación segura',
          ], commitments: [
            'Preguntaré qué opciones y restricciones existen antes de proponer un menú real',
            'Actualizaré precios con una fuente local antes de presentar el presupuesto como real',
          ] },
        ),
      ],
    }),
    lesson({
      id: 's06-d5-reto',
      kind: 'reto',
      day: 5,
      title: 'Reto de la semana 6',
      icon: 'Trophy',
      minutes: 14,
      objetivos: ['Transferir lo aprendido en las diez áreas a situaciones nuevas'],
      resumen: ['Resolví situaciones nuevas sin pistas ni respuestas reutilizadas.'],
      media: {
        id: 's06-reto-mesa', kind: 'image', title: 'Mesa de revisión interdisciplinaria', aspect: '16:9',
        alt: 'Mesa con tarjetas de conjuntos, una propuesta, una cronología, texturas, instrucciones bilingües, un balón y una tabla de proyecto.',
        brief: 'Imagen cenital con evidencias nuevas para diez áreas: tarjetas de semillas, oración de propuesta, ficha de nutrientes, cronología, pares de palabras, instrucciones en inglés, caso ciudadano, patrón de textura, balón con flechas y tabla de proyecto. Objetos reconocibles; no usar formas genéricas como sustitutos.',
      },
      steps: [
        S.choice({ fase: 'comprobar', areas: ['mat'], cnb: ['mat:3.2.1'], prompt: 'A = {pepitoria, ajonjolí, manía} y B = {ajonjolí, cacao}. ¿Cuál es A ∩ B?' },
          { options: [{ id: 'a', text: '{ajonjolí}' }, { id: 'b', text: '{pepitoria, manía, cacao}' }, { id: 'c', text: '∅' }], correct: ['a'] }),
        S.highlight({ fase: 'comprobar', areas: ['l1'], cnb: ['l1:7.2.6'], prompt: 'Marca el sujeto de la oración: “Las familias del comité revisaron la propuesta.”' },
          { text: '{Las familias del comité} revisaron la propuesta.', target: 'sujeto' }),
        S.choice({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:5.1.1'], prompt: 'Una ficha separa nombres de alimentos y de nutrientes. ¿Cuál término nombra un nutriente?' },
          { options: [{ id: 'a', text: 'Proteína' }, { id: 'b', text: 'Pepitoria' }, { id: 'c', text: 'Güisquil' }], correct: ['a'] }),
        S.number({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:6.5.1'], prompt: 'Una cronología nueva marca el inicio de la Segunda Guerra Mundial en 1939 y su final en 1945. ¿Cuántos años separan las dos fechas?' },
          { answer: 6, unit: 'años' }),
        S.fill({ fase: 'comprobar', areas: ['l2'], cnb: ['l2:4.1.2'], prompt: 'Completa con la palabra cuya r inicial suena fuerte.' },
          { text: 'La palabra es [[rábano]].', distractors: ['pera', 'arena'] }),
        S.choice({ fase: 'comprobar', areas: ['l3'], cnb: ['l3:3.3.1'], prompt: 'A new card says: “First, wash the cup. Then, add the fruit. Finally, serve it.” What happens immediately before serving?' },
          { options: [{ id: 'a', text: 'Add the fruit' }, { id: 'b', text: 'Wash the cup' }, { id: 'c', text: 'Store the card' }], correct: ['a'] }),
        S.choice({ fase: 'comprobar', areas: ['fc'], cnb: ['fc:4.2.1'], prompt: 'Un grupo se burla cada semana de la refacción de Joel y lo excluye. ¿Qué respuesta ayuda a detener el acoso?' },
          { options: [{ id: 'a', text: 'Acompañarlo, no repetir la burla y pedir apoyo adulto' }, { id: 'b', text: 'Decirle que cambie su comida para encajar' }, { id: 'c', text: 'Grabar la escena y compartirla' }], correct: ['a'] }),
        S.match({ fase: 'comprobar', areas: ['art'], cnb: ['art:3.2.4'], prompt: 'Relaciona la intención visual con la trama.' },
          { pairs: [{ id: 'a', left: 'Sombra densa en una canasta', right: 'Líneas cruzadas cercanas' }, { id: 'b', left: 'Zona clara de una servilleta', right: 'Puntos separados' }, { id: 'c', left: 'Fibra curva de una hoja', right: 'Líneas onduladas' }] }),
        S.choice({ fase: 'comprobar', areas: ['ef'], cnb: ['ef:2.1.17'], prompt: 'En una ejecución nueva, el pase interno sale a la derecha. ¿Qué ajuste conviene probar?' },
          { options: [{ id: 'a', text: 'Orientar el pie de apoyo hacia el objetivo y mantener firme el tobillo' }, { id: 'b', text: 'Cerrar los ojos al golpear' }, { id: 'c', text: 'Pisar encima del balón' }], correct: ['a'] }),
        S.number({ fase: 'comprobar', areas: ['pyd'], cnb: ['pyd:4.1.1'], prompt: 'Un proyecto usa 5 carteles a Q3 y 2 marcadores a Q4. ¿Cuál es el presupuesto total?' },
          { answer: 23, unit: 'quetzales' }),
      ],
    }),
  ],
  bank: [
    S.number({ fase: 'comprobar', areas: ['mat'], cnb: ['mat:3.1.1'], prompt: 'Un conjunto de cuatro condimentos tiene 16 subconjuntos. ¿Cuántos tendrá uno de cinco elementos?' },
      { answer: 32, unit: 'subconjuntos' }),
    S.choice({ fase: 'comprobar', areas: ['l1'], cnb: ['l1:8.2.1'], prompt: '¿Cuál objetivo comunica con precisión un proyecto escolar?' },
      { options: [{ id: 'a', text: 'Comparar tres opciones y presentar sus costos el viernes' }, { id: 'b', text: 'El proyecto más bonito' }, { id: 'c', text: 'Que todo salga bien' }], correct: ['a'] }),
    S.choice({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:5.2.1'], prompt: 'Una familia desea apoyar la lactancia sin imponer decisiones. ¿Cuál acción ofrece apoyo práctico?' },
      { options: [{ id: 'a', text: 'Compartir tareas y facilitar descanso, agua y atención profesional cuando se necesite' }, { id: 'b', text: 'Decidir por la madre sin escucharla' }, { id: 'c', text: 'Afirmar que todas las experiencias son iguales' }], correct: ['a'] }),
    S.choice({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:6.4.4'], prompt: '¿Qué relación explica mejor los viajes europeos del siglo XV?' },
      { options: [{ id: 'a', text: 'Interés comercial y avances de navegación favorecieron la búsqueda de rutas marítimas' }, { id: 'b', text: 'Los europeos ya conocían todos los continentes' }, { id: 'c', text: 'La imprenta eliminó la necesidad de mapas' }], correct: ['a'] }),
    S.fill({ fase: 'comprobar', areas: ['l2'], cnb: ['l2:4.1.1'], prompt: 'Completa según el contexto: “El vehículo que lleva la carga es un ___”.' },
      { text: 'El vehículo que lleva la carga es un [[carro]].', distractors: ['caro', 'coro'] }),
    S.fill({ fase: 'comprobar', areas: ['l3'], cnb: ['l3:3.3.1'], prompt: 'Complete: “______, put the clean spoon on the table.”' },
      { text: '[[Finally]], put the clean spoon on the table.', distractors: ['First', 'Never'] }),
    S.choice({ fase: 'comprobar', areas: ['fc'], cnb: ['fc:4.2.1'], prompt: 'Recibes una imagen humillante de una compañera. ¿Qué acción de testigo es responsable?' },
      { options: [{ id: 'a', text: 'No reenviarla, guardar evidencia sin difundirla y pedir apoyo adulto' }, { id: 'b', text: 'Reenviarla solo al grupo cercano' }, { id: 'c', text: 'Responder con otra burla' }], correct: ['a'] }),
    S.order({ fase: 'comprobar', areas: ['art'], cnb: ['art:3.2.4'], prompt: 'Ordena una trama de la apariencia más clara a la más oscura.' },
      { items: [{ id: 'a', text: 'Cinco puntos muy separados' }, { id: 'b', text: 'Diez puntos a distancia media' }, { id: 'c', text: 'Veinte puntos muy cercanos' }] }),
    S.choice({ fase: 'comprobar', areas: ['ef'], cnb: ['ef:3.1.2'], prompt: 'Después de actividad moderada, ¿qué secuencia favorece una recuperación gradual?' },
      { options: [{ id: 'a', text: 'Caminar despacio y alargar suavemente la exhalación' }, { id: 'b', text: 'Detenerse de golpe y contener la respiración' }, { id: 'c', text: 'Acelerar sin observar cómo se siente el cuerpo' }], correct: ['a'] }),
    S.order({ fase: 'comprobar', areas: ['pyd'], cnb: ['pyd:4.3.1'], prompt: 'Ordena la preparación de una propuesta para feria.' },
      { items: [{ id: 'a', text: 'Definir el objetivo' }, { id: 'b', text: 'Asignar actividades y responsables' }, { id: 'c', text: 'Calcular los recursos' }, { id: 'd', text: 'Presentar y recoger comentarios' }] }),
  ],
});
