import { S, cierre, lesson, semana } from '../../dsl';

/**
 * SEMANA 11 · Unidad 2 "Consolidando nuestras relaciones"
 * Tema generador: Nuestra relación con la Tierra
 */
export default semana({
  id: 's11',
  unidad: 2,
  semana: 11,
  kind: 'aprendizaje',
  temaGenerador: 'Nuestra relación con la Tierra',
  title: 'Nuestra relación con la Tierra',
  subtitle: 'Gente de maíz, continentes, formas que producen y trabajo digno',
  icon: 'Sprout',
  color: 'var(--area-cnt)',
  contexto: 'En muchas comunidades de Guatemala la milpa es mucho más que comida: es historia, ciencia, trabajo y fiesta. Esta semana verás cómo el Popol Wuj explica nuestro origen, cómo la planta de maíz fabrica su alimento, qué comparten los continentes, qué formas usan los artesanos y qué derechos protegen a quienes trabajan la tierra.',
  ejes: ['multiculturalidad', 'sostenible', 'trabajo', 'equidad'],
  media: {
    id: 's11-portada', kind: 'video', title: 'Una milpa, muchas relaciones', aspect: '16:9', duration: 60,
    alt: 'Recorrido por una milpa del altiplano: maíz, frijol y ayote creciendo juntos, una familia trabajando y un volcán al fondo.',
    brief: 'Video de 60 s (tomas reales o animación 2D cálida) de una milpa del altiplano occidental al amanecer con un volcán al fondo. Mostrar en secuencia: mazorcas de colores (amarillo, blanco, negro y rojo), manos sembrando, un comal con tortillas, un tambor hecho con una lata y una señal de "Trabajo digno". Sobreimpresos breves: "Origen", "Ciencia", "Formas", "Derechos". Música de marimba suave. Sin personas identificables en primer plano. Cierre con la pregunta: "¿Cómo te relacionas tú con la Tierra?".',
  },
  badge: { id: 'medalla-s11', name: 'Guardián de la milpa', icon: 'Sprout', desc: 'Completaste la semana 11 y superaste su reto' },
  lessons: [
    /* ───────────────────────── Día 1 ───────────────────────── */
    lesson({
      id: 's11-d1-gente-de-maiz',
      title: 'Gente de maíz',
      icon: 'Wheat',
      minutes: 14,
      day: 1,
      gancho: 'Si el maíz no puede caminar ni comer, ¿de dónde saca la energía para crecer tan alto?',
      objetivos: ['Explicar el origen del mundo y de las personas según el Popol Wuj', 'Describir cómo el cloroplasto hace la fotosíntesis', 'Comparar lo que hacen la célula animal y la vegetal', 'Reconocer que los genes deciden características que se heredan'],
      resumen: [
        'Según el Popol Wuj, los creadores formaron la Tierra desde el agua y, después de intentarlo con barro y madera, formaron a las personas de maíz amarillo y blanco.',
        'En los cloroplastos, la planta usa luz del sol, agua y dióxido de carbono para fabricar su alimento (azúcar) y libera oxígeno: es la fotosíntesis.',
        'Las células animal y vegetal usan mitocondrias para obtener energía; solo la vegetal fabrica su alimento y tiene pared celular.',
        'Los genes llevan la información de características que se heredan de madre y padre, como el color de los ojos o el color de los granos de maíz.',
        'En un diálogo de saberes se escuchan y se valoran juntos el conocimiento de la comunidad y el de la ciencia.',
      ],
      media: {
        id: 's11-d1-milpa-celula', kind: 'animation', title: 'Del sol al grano de maíz', aspect: '16:9', duration: 70,
        alt: 'Animación que hace zoom en una hoja de maíz hasta llegar a un cloroplasto donde la luz, el agua y el aire se convierten en azúcar y oxígeno.',
        brief: 'Animación 2D de 70 s. Escena 1: planta de maíz en una milpa al mediodía; flechas muestran agua subiendo por la raíz y aire (CO₂) entrando por la hoja. Escena 2: zoom a una célula de la hoja: rotular pared celular, membrana, vacuola, núcleo y cloroplastos (verdes). Escena 3: dentro del cloroplasto, la luz (rayos amarillos) convierte agua + CO₂ en azúcar (cubitos) y oxígeno (burbujas que salen). Narración infantil en español con subtítulos. Colores planos, sin texto excesivo.',
      },
      steps: [
        S.explain(
          { fase: 'explorar', areas: ['cnt', 'ccss', 'l1'], cnb: ['cnt:1.1.2'], ambito: 'conocer', title: 'El origen según el Popol Wuj',
            prompt: 'Hace varias semanas conociste el relato del Génesis. Hoy toca la **cosmovisión maya**: el **Popol Wuj**, libro sagrado del pueblo k\'iche\', cuenta cómo se formó el mundo. Toca cada tarjeta.',
            media: { id: 's11-d1-popolwuj', kind: 'image', title: 'Las creaciones del Popol Wuj', aspect: '16:9',
              alt: 'Ilustración en cuatro paneles: un mar en calma bajo el cielo, montañas que salen del agua, animales en el bosque y personas formadas con mazorcas de maíz.',
              brief: 'Ilustración en 4 paneles horizontales con estilo inspirado en la cerámica maya (colores tierra, rojo, turquesa y amarillo maíz), sin copiar obras existentes: (1) mar en calma y cielo oscuro con dos figuras luminosas estilizadas que representan a los creadores; (2) montañas y árboles que emergen del agua; (3) venados y aves en el bosque; (4) cuatro siluetas humanas formadas con granos de maíz amarillo y blanco. Rótulos: "Agua y cielo", "Surge la Tierra", "Los animales", "Gente de maíz".' } },
          { icon: 'BookOpen', body: 'El Popol Wuj se escribió en idioma **k\'iche\'** y recoge relatos que se transmitían de generación en generación.', reveal: [
            { icon: 'Waves', front: 'Al principio', back: 'Solo existían el **mar en calma** y el **cielo**. Los creadores, entre ellos **Tepew** y **Q\'ukumatz** con el **Corazón del Cielo**, dialogaron.' },
            { icon: 'Mountain', front: 'Surge la Tierra', back: 'Dijeron "¡Tierra!" y de las aguas **surgieron las montañas**, los valles y los bosques.' },
            { icon: 'Bird', front: 'Los animales', back: 'Crearon venados, aves, pumas y serpientes, pero **no podían hablar** para nombrar ni agradecer a sus creadores.' },
            { icon: 'Wheat', front: 'Gente de maíz', back: 'Intentaron hacer personas de **barro** (se deshacían) y de **madera** (no tenían corazón ni memoria). Por fin las formaron de **maíz amarillo y blanco**.' },
          ] },
        ),
        S.order(
          { fase: 'construir', areas: ['cnt', 'l1'], cnb: ['cnt:1.1.2'], ambito: 'conocer',
            prompt: 'Ordena los momentos de la creación según el **Popol Wuj**, del primero al último.',
            hint: 'Recuerda: primero había agua; las personas de maíz fueron el último intento.',
            explain: 'El relato muestra una idea importante de la cosmovisión maya: el ser humano está hecho del mismo maíz que cultiva, por eso cuidar la milpa es cuidar la vida.' },
          { items: [
            { id: 'c1', text: 'Solo existen el mar en calma y el cielo' },
            { id: 'c2', text: 'De las aguas surgen montañas y bosques' },
            { id: 'c3', text: 'Se crean los animales' },
            { id: 'c4', text: 'Intento con barro: las personas se deshacen' },
            { id: 'c5', text: 'Intento con madera: no tienen corazón ni memoria' },
            { id: 'c6', text: 'Se forman las personas de maíz' },
          ], labels: { start: 'Primero', end: 'Al final' } },
        ),
        S.reading(
          { fase: 'construir', areas: ['l1', 'l2', 'cnt'], cnb: ['l1:1.1.1', 'l1:1.1.2', 'l1:1.1.3', 'l2:1.1.2', 'cnt:1.2.2', 'cnt:1.4.2'], ambito: 'conocer',
            prompt: 'Escucha (o lee) este **diálogo de saberes** grabado en la escuela. Pon atención a las **ideas importantes** y luego responde de memoria lo que puedas.',
            media: { id: 's11-d1-dialogo', kind: 'audio', title: 'Diálogo de saberes sobre la milpa', duration: 90,
              alt: 'Conversación grabada entre una abuela agricultora, una ingeniera agrónoma y un estudiante sobre el maíz.',
              brief: 'Grabación de 90 s con tres voces claramente distintas: abuela agricultora (voz pausada y cálida), ingeniera agrónoma joven (voz clara) y estudiante de 12 años. Leer el guion del texto de esta actividad con naturalidad, con sonido ambiente suave de campo (pájaros, viento). Pausa de 1 s entre intervenciones. Incluir transcripción visible.' } },
          { genre: 'Diálogo (texto oral expositivo)', heading: 'La milpa: lo que sabe la abuela y lo que sabe la ciencia', passage:
            '**Abuela Tomasa:** Mi abuela decía que el maíz "come sol". Por eso sembramos donde no hay tanta sombra y cuidamos que tenga agua.\n\n**Ingeniera Lucía:** ¡Tiene toda la razón! Las hojas del maíz tienen células con **cloroplastos**. Ahí, con la **luz del sol**, el **agua** de la raíz y el **dióxido de carbono** del aire, la planta fabrica su alimento, un azúcar. A eso le llamamos **fotosíntesis**. Además, suelta **oxígeno**, el que nosotros respiramos.\n\n**Mateo:** ¿Y por qué hay mazorcas amarillas, blancas, negras y rojas?\n\n**Abuela Tomasa:** Porque guardamos la semilla de cada color. Si siembras semilla de grano negro, vuelve a salir negro.\n\n**Ingeniera Lucía:** Eso tiene que ver con los **genes**. En el núcleo de cada célula hay genes que llevan la información de las características, como el color del grano. La nueva planta **hereda** esos genes de las plantas que le dieron origen.',
            questions: [
              { q: '¿Cuál es la idea principal de lo que explica la ingeniera?', options: [
                { id: 'a', text: 'Que la planta fabrica su alimento con luz, agua y aire en los cloroplastos' },
                { id: 'b', text: 'Que el maíz negro es mejor que el amarillo' },
                { id: 'c', text: 'Que la abuela está equivocada' },
              ], correct: 'a', why: 'La ingeniera explica la fotosíntesis y, además, confirma el saber de la abuela.' },
              { q: 'Cuando la abuela dice que el maíz "come sol", ¿qué quiere decir en realidad?', options: [
                { id: 'a', text: 'Que la planta necesita la luz del sol para fabricar su alimento' },
                { id: 'b', text: 'Que el maíz se traga los rayos del sol por la raíz' },
                { id: 'c', text: 'Que hay que sembrar solo de noche' },
              ], correct: 'a', why: 'Decodificar un mensaje es entender su sentido: "comer sol" es una forma bonita de decir que la planta usa la luz.' },
              { q: '¿Qué intención tiene este diálogo?', options: [
                { id: 'a', text: 'Exponer y explicar cómo se alimenta el maíz y por qué sus granos tienen colores' },
                { id: 'b', text: 'Vender semillas' },
                { id: 'c', text: 'Contar un chiste' },
              ], correct: 'a' },
              { q: '¿Por qué la semilla de grano negro vuelve a dar maíz negro?', options: [
                { id: 'a', text: 'Porque la nueva planta hereda los genes del color' },
                { id: 'b', text: 'Porque la tierra es negra' },
                { id: 'c', text: 'Porque se siembra con poca agua' },
              ], correct: 'a' },
            ] },
        ),
        S.match(
          { fase: 'construir', areas: ['cnt'], cnb: ['cnt:1.2.2'], ambito: 'conocer', prompt: 'Une cada parte de la **célula vegetal** con el trabajo que hace.',
            hint: 'El cloroplasto es verde porque tiene clorofila, que captura la luz.',
            explain: 'La pared celular y la vacuola grande ayudan a que la planta se mantenga firme aunque no tenga huesos.' },
          { leftTitle: 'Organelo', rightTitle: 'Función', pairs: [
            { id: 'clo', left: 'Cloroplasto', leftIcon: 'Leaf', right: 'Hace la fotosíntesis con la luz del sol' },
            { id: 'par', left: 'Pared celular', leftIcon: 'Square', right: 'Da rigidez y protege a la célula' },
            { id: 'vac', left: 'Vacuola', leftIcon: 'Droplet', right: 'Guarda agua y mantiene firme la planta' },
            { id: 'mit', left: 'Mitocondria', leftIcon: 'Zap', right: 'Libera la energía del alimento' },
          ] },
        ),
        S.sort(
          { fase: 'construir', areas: ['cnt'], cnb: ['cnt:1.3.2'], ambito: 'conocer',
            prompt: '¿Qué **trabajo** hace cada tipo de célula? Clasifica cada función.',
            hint: 'Piensa: ¿quién fabrica su propio alimento y quién tiene que comer?',
            explain: 'Ambas células respiran y obtienen energía con sus mitocondrias. La vegetal, además, fabrica su alimento; la animal lo obtiene de lo que come el cuerpo.' },
          { buckets: [
            { id: 'veg', label: 'Solo célula vegetal', icon: 'Leaf', color: 'var(--c-quetzal)' },
            { id: 'ani', label: 'Solo célula animal', icon: 'Bone', color: 'var(--area-cnt)' },
            { id: 'ambas', label: 'Las dos', icon: 'Copy', color: 'var(--area-l1)' },
          ], items: [
            { id: 'f1', text: 'Fabrica su alimento con luz', bucket: 'veg' },
            { id: 'f2', text: 'Obtiene energía en sus mitocondrias', bucket: 'ambas', feedback: 'Las plantas también necesitan energía: sus células tienen mitocondrias.' },
            { id: 'f3', text: 'Recibe el alimento que come el organismo', bucket: 'ani' },
            { id: 'f4', text: 'Guarda la información en el núcleo', bucket: 'ambas' },
            { id: 'f5', text: 'Se mantiene rígida por su pared', bucket: 'veg' },
            { id: 'f6', text: 'Controla lo que entra con su membrana', bucket: 'ambas' },
          ] },
        ),
        S.sort(
          { fase: 'aplicar', areas: ['l2', 'cnt', 'ccss'], cnb: ['l2:1.1.3', 'l2:1.1.1'], ambito: 'convivir',
            prompt: 'Vas a hacer un resumen del diálogo para el periódico mural. Organiza lo que escuchaste en **temas y subtemas**.',
            explain: 'Organizar la información en subtemas ayuda a recordarla y a mostrar que los saberes de la comunidad y de la ciencia se complementan.' },
          { buckets: [
            { id: 'ali', label: 'Subtema: cómo se alimenta la planta', icon: 'Sun', color: 'var(--area-cnt)' },
            { id: 'her', label: 'Subtema: por qué hay granos de colores', icon: 'Dna', color: 'var(--area-l2)' },
            { id: 'cui', label: 'Subtema: cómo cuida la milpa la comunidad', icon: 'Sprout', color: 'var(--area-pyd)' },
          ], items: [
            { id: 's1', text: 'Los cloroplastos usan luz, agua y dióxido de carbono', bucket: 'ali' },
            { id: 's2', text: 'La planta suelta oxígeno', bucket: 'ali' },
            { id: 's3', text: 'La nueva planta hereda genes del color', bucket: 'her' },
            { id: 's4', text: 'Se guarda la semilla de cada color', bucket: 'her', feedback: 'Guardar la semilla es un saber comunitario, pero aquí explica por qué se conservan los colores.' },
            { id: 's5', text: 'Se siembra donde no hay tanta sombra', bucket: 'cui' },
            { id: 's6', text: 'Se cuida que la milpa tenga agua', bucket: 'cui' },
          ] },
        ),
        S.fill(
          { fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:1.2.2', 'cnt:1.3.2'], prompt: 'Completa la explicación de la **fotosíntesis**.' },
          { text: 'La fotosíntesis ocurre en los [[cloroplastos]]. La planta usa la luz del [[sol]], el agua y el [[dióxido de carbono]] para fabricar su alimento y libera [[oxígeno]]. La célula animal no puede hacerlo porque no tiene cloroplastos.',
            distractors: ['núcleo', 'humo', 'huesos'] },
        ),
        S.tf(
          { fase: 'comprobar', areas: ['cnt', 'l1'], cnb: ['cnt:1.1.2', 'cnt:1.4.2'], prompt: '¿Verdadero o falso?' },
          { statements: [
            { text: 'Según el Popol Wuj, las primeras personas verdaderas fueron formadas de maíz.', answer: true },
            { text: 'En el Popol Wuj, las personas de madera tenían corazón y memoria.', answer: false, why: 'Por no tener corazón ni memoria, los creadores las destruyeron.' },
            { text: 'Los genes llevan información de características que se heredan.', answer: true },
            { text: 'Una cicatriz en la rodilla se hereda a los hijos.', answer: false, why: 'Una cicatriz se adquiere durante la vida; no está en los genes.' },
          ] },
        ),
        cierre({ areas: ['cnt', 'l2'], cnb: ['l2:1.1.1'] }, ['Puedo contar el origen del mundo según el Popol Wuj', 'Explico qué hacen los cloroplastos', 'Escucho y valoro los saberes de mi comunidad y de la ciencia'],
          ['Preguntaré a una persona mayor qué sabe sobre la siembra', 'Observaré las hojas de una planta y buscaré las más expuestas al sol', 'Contaré en casa el relato de la gente de maíz']),
      ],
    }),

    /* ───────────────────────── Día 2 ───────────────────────── */
    lesson({
      id: 's11-d2-continentes',
      title: 'Continentes, volcanes y climas',
      icon: 'Globe',
      minutes: 14,
      day: 2,
      gancho: 'Guatemala tiene más de 30 volcanes. ¿Crees que en otros continentes también viven personas junto a volcanes?',
      objetivos: ['Comparar la extensión y características de los continentes', 'Ubicar montañas, volcanes y depresiones importantes', 'Identificar las zonas climáticas y los lugares de riesgo', 'Describir un paisaje en inglés con palabras de forma y tamaño'],
      resumen: [
        'Hay seis continentes: Asia (el más extenso), América, África, Antártida, Europa y Oceanía (el más pequeño).',
        'El Everest (Asia) es la montaña más alta del mundo; el Aconcagua es la más alta de América; el Mar Muerto es una depresión: está por debajo del nivel del mar.',
        'Las zonas climáticas son: cálida (entre los trópicos), templadas y frías (cerca de los polos).',
        'Volcanes activos, laderas deforestadas en época de lluvia y desiertos son zonas de riesgo para quienes viven cerca.',
        'Los recursos naturales dan trabajo e ingresos y también forman parte de la cultura de los pueblos.',
      ],
      media: {
        id: 's11-d2-mapa-relieve', kind: 'image', title: 'Mapamundi del relieve', aspect: '16:9',
        alt: 'Mapamundi con los seis continentes coloreados, las montañas más altas, algunos volcanes famosos y las zonas climáticas en franjas.',
        brief: 'Mapamundi ilustrado con los seis continentes en colores distintos y franjas semitransparentes de zonas climáticas (cálida en naranja entre los trópicos, templadas en verde, frías en celeste). Marcar con íconos de montaña: Everest, Aconcagua, Kilimanjaro, Mont Blanc; con íconos de volcán: Tajumulco y Fuego (Guatemala), Etna (Italia), Fuji (Japón); con flecha hacia abajo: Mar Muerto. Etiquetas grandes y legibles, sin fronteras detalladas.',
      },
      steps: [
        S.explain(
          { fase: 'explorar', areas: ['ccss', 'mat'], cnb: ['ccss:1.1.1'], ambito: 'conocer', title: 'Seis continentes, muchas formas de vivir',
            prompt: 'Cada continente tiene una **extensión**, una **ubicación** y unas condiciones de vida propias. Toca cada tarjeta.' },
          { icon: 'Globe', body: 'Los continentes son grandes masas de tierra rodeadas por océanos. La **calidad de vida** de su población depende de su historia, sus recursos, la educación, la salud y el empleo.', reveal: [
            { icon: 'Maximize2', front: 'Asia', back: 'El **más extenso** y el más poblado. Tiene el Himalaya y grandes ríos.' },
            { icon: 'Earth', front: 'América', back: 'Va casi de polo a polo. Guatemala está en **América Central**.' },
            { icon: 'Sun', front: 'África', back: 'El segundo en población. Tiene el desierto del **Sahara** y grandes sabanas.' },
            { icon: 'Snowflake', front: 'Antártida', back: 'Cubierta de hielo. **No tiene población permanente**, solo personal científico.' },
            { icon: 'Castle', front: 'Europa', back: 'Pequeña pero muy poblada; en muchos de sus países la gente tiene acceso amplio a salud y educación.' },
            { icon: 'Shell', front: 'Oceanía', back: 'El **más pequeño**: Australia y miles de islas del océano Pacífico.' },
          ] },
        ),
        S.chart(
          { fase: 'construir', areas: ['ccss', 'mat'], cnb: ['ccss:1.1.1'], ambito: 'hacer',
            prompt: 'Construye la gráfica con la **superficie aproximada** de cada continente (en millones de km²). Usa los datos de la tabla.',
            hint: 'Arrastra cada barra hasta el valor de la tabla; cada línea vale 2.',
            explain: 'Asia y América son los continentes más extensos; Oceanía es el más pequeño. Los datos están redondeados.' },
          { source: 'Superficie aproximada (redondeada), millones de km²: Asia 44 · América 42 · África 30 · Antártida 14 · Europa 10 · Oceanía 8',
            unit: 'millones de km²', max: 46, step: 2,
            categories: [
              { id: 'asia', label: 'Asia', icon: 'Maximize2', color: 'var(--area-ccss)' },
              { id: 'ame', label: 'América', icon: 'Earth', color: 'var(--area-cnt)' },
              { id: 'afr', label: 'África', icon: 'Sun', color: 'var(--area-pyd)' },
              { id: 'ant', label: 'Antártida', icon: 'Snowflake', color: 'var(--area-l1)' },
              { id: 'eur', label: 'Europa', icon: 'Castle', color: 'var(--area-mat)' },
              { id: 'oce', label: 'Oceanía', icon: 'Shell', color: 'var(--area-art)' },
            ],
            data: [44, 42, 30, 14, 10, 8] },
        ),
        S.match(
          { fase: 'construir', areas: ['ccss', 'cnt'], cnb: ['ccss:1.1.2'], ambito: 'conocer',
            prompt: 'Montañas, volcanes y **depresiones** (tierras más bajas que el nivel del mar) marcan la vida de las personas. Une cada lugar con su dato.',
            explain: 'Cerca de los volcanes el suelo suele ser fértil, por eso muchas personas viven y cultivan ahí, aunque haya riesgo.' },
          { leftTitle: 'Lugar', rightTitle: 'Dato', pairs: [
            { id: 'eve', left: 'Monte Everest', leftIcon: 'MountainSnow', right: 'Asia: la montaña más alta del mundo' },
            { id: 'aco', left: 'Aconcagua', leftIcon: 'Mountain', right: 'América del Sur: la montaña más alta de América' },
            { id: 'taj', left: 'Volcán Tajumulco', leftIcon: 'Triangle', right: 'Guatemala: el volcán más alto de Centroamérica' },
            { id: 'mue', left: 'Mar Muerto', leftIcon: 'Waves', right: 'Asia: una depresión por debajo del nivel del mar' },
          ] },
        ),
        S.sort(
          { fase: 'construir', areas: ['ccss', 'cnt'], cnb: ['ccss:1.2.2'], ambito: 'conocer',
            prompt: 'Clasifica cada lugar según su **zona climática**.',
            hint: 'La zona cálida está entre los trópicos, cerca del ecuador; las frías, cerca de los polos.',
            explain: 'Guatemala está en la zona cálida (tropical); por la altitud de sus montañas también tiene lugares de clima frío.' },
          { buckets: [
            { id: 'cal', label: 'Zona cálida', icon: 'Sun', color: 'var(--area-pyd)' },
            { id: 'tem', label: 'Zona templada', icon: 'CloudSun', color: 'var(--c-quetzal)' },
            { id: 'fri', label: 'Zona fría (polar)', icon: 'Snowflake', color: 'var(--area-l1)' },
          ], items: [
            { id: 'z1', text: 'Guatemala', bucket: 'cal' },
            { id: 'z2', text: 'Selva del Amazonas', bucket: 'cal' },
            { id: 'z3', text: 'España', bucket: 'tem' },
            { id: 'z4', text: 'Centro de Argentina', bucket: 'tem', feedback: 'Argentina central está lejos del ecuador, al sur del trópico de Capricornio: zona templada.' },
            { id: 'z5', text: 'Antártida', bucket: 'fri' },
            { id: 'z6', text: 'Groenlandia', bucket: 'fri' },
          ] },
        ),
        S.fill(
          { fase: 'aplicar', areas: ['l3', 'ccss'], cnb: ['l3:1.1.4', 'l3:1.2.4'], ambito: 'hacer',
            prompt: 'English time! Look at the picture and complete the paragraph with **shapes and sizes**. (_large_ = grande, _small_ = pequeño, _round_ = redondo, _square_ = cuadrado, _tall_ = alto, _short_ = bajo/corto)',
            explain: 'Words of the same family help you describe: round → roundness, large → larger, small → smaller.',
            media: { id: 's11-d2-lake', kind: 'image', title: 'A lake and three volcanoes', aspect: '4:3',
              alt: 'Ilustración de un lago redondo con tres volcanes grandes detrás, casas cuadradas pequeñas y un árbol alto junto a una cerca baja.',
              brief: 'Ilustración plana inspirada en un lago del altiplano guatemalteco (sin copiar una foto real): un lago de forma casi redonda, tres volcanes grandes y altos al fondo, en la orilla casas pequeñas de forma cuadrada con techo de teja, un árbol alto y una cerca de madera baja. Colores claros y contornos definidos. Sin texto dentro de la imagen.' } },
          { text: 'In the picture there is a [[round]] lake (like a circle). Behind it there are three [[large]] (very big) volcanoes. The houses are [[small]] (not big) and [[square]] (four equal sides). Next to the houses there is a [[tall]] (very high) tree and a [[short]] (not high) fence.',
            distractors: ['cold', 'blue'] },
        ),
        S.match(
          { fase: 'aplicar', areas: ['ccss', 'cnt', 'fc'], cnb: ['ccss:1.3.2'], ambito: 'convivir',
            prompt: 'Algunos lugares del mundo son **zonas de riesgo**. Une cada peligro con el lugar donde es más probable.',
            explain: 'Conocer dónde están los peligros ayuda a las familias y autoridades a prevenir: no construir en laderas inestables, tener rutas de evacuación y respetar las alertas.' },
          { leftTitle: 'Peligro', rightTitle: 'Dónde ocurre', pairs: [
            { id: 'eru', left: 'Erupción volcánica', leftIcon: 'Flame', right: 'Alrededor de volcanes activos como Fuego, Pacaya o el Etna' },
            { id: 'des', left: 'Deslave', leftIcon: 'Mountain', right: 'Laderas empinadas y sin árboles en época de lluvia' },
            { id: 'seq', left: 'Falta de agua y calor extremo', leftIcon: 'Sun', right: 'Desiertos como el Sahara o el de Atacama' },
            { id: 'inu', left: 'Inundación', leftIcon: 'Droplets', right: 'Orillas de ríos en zonas bajas' },
          ] },
        ),
        S.sort(
          { fase: 'aplicar', areas: ['ccss', 'pyd'], cnb: ['ccss:1.1.5'], ambito: 'conocer',
            prompt: 'Los recursos naturales son importantes para la **economía** (trabajo e ingresos) y para la **cultura** (creencias, arte, tradiciones). Clasifica cada ejemplo de Guatemala.',
            explain: 'Muchos recursos tienen las dos importancias: el maíz, por ejemplo, alimenta, se vende y también es sagrado en la cosmovisión maya.' },
          { buckets: [
            { id: 'eco', label: 'Importancia económica', icon: 'Coins', color: 'var(--area-pyd)' },
            { id: 'cul', label: 'Importancia cultural', icon: 'Palette', color: 'var(--area-art)' },
          ], items: [
            { id: 'r1', text: 'Guatemala exporta café y cardamomo', bucket: 'eco' },
            { id: 'r2', text: 'Los mayas tallaban jade para objetos sagrados', bucket: 'cul' },
            { id: 'r3', text: 'Pescadores venden lo que pescan en el lago', bucket: 'eco' },
            { id: 'r4', text: 'Los cerros son lugares de ceremonia para algunas comunidades', bucket: 'cul' },
            { id: 'r5', text: 'Con madera de pino se fabrican muebles para vender', bucket: 'eco' },
            { id: 'r6', text: 'Los tintes naturales dan color a los tejidos tradicionales', bucket: 'cul' },
          ] },
        ),
        S.choice(
          { fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:1.1.1', 'ccss:1.2.2'], prompt: '¿Qué continente es el **más extenso** y en qué zona climática está Guatemala?' },
          { options: [
            { id: 'a', text: 'Asia · zona cálida', icon: 'Maximize2' },
            { id: 'b', text: 'América · zona fría', icon: 'Earth', feedback: 'América es muy extensa, pero Asia lo es más; y Guatemala está en la zona cálida.' },
            { id: 'c', text: 'Oceanía · zona templada', icon: 'Shell', feedback: 'Oceanía es el continente más pequeño.' },
          ], correct: ['a'] },
        ),
        S.tf(
          { fase: 'comprobar', areas: ['ccss', 'l3'], cnb: ['ccss:1.1.2', 'ccss:1.3.2', 'l3:1.2.4'], prompt: '¿Verdadero o falso?' },
          { statements: [
            { text: 'El Mar Muerto está por debajo del nivel del mar.', answer: true },
            { text: 'El Aconcagua es la montaña más alta del mundo.', answer: false, why: 'Es la más alta de América; la más alta del mundo es el Everest, en Asia.' },
            { text: 'Una ladera sin árboles en época de lluvia tiene más riesgo de deslave.', answer: true },
            { text: 'En inglés, "round" describe un tamaño.', answer: false, why: '"Round" (redondo) describe una forma; "large" o "small" describen tamaños.' },
          ] },
        ),
        cierre({ areas: ['ccss', 'l3'], cnb: ['ccss:1.3.2'] }, ['Comparo los continentes por su extensión', 'Ubico montañas, volcanes y depresiones importantes', 'Reconozco zonas de riesgo'],
          ['Buscaré en un mapa los volcanes cercanos a mi comunidad', 'Conversaré en casa sobre nuestra ruta de evacuación', 'Describiré en inglés un paisaje de mi comunidad']),
      ],
    }),

    /* ───────────────────────── Día 3 ───────────────────────── */
    lesson({
      id: 's11-d3-formas-que-suenan',
      title: 'Formas que producen y suenan',
      icon: 'Drum',
      minutes: 15,
      day: 3,
      gancho: '¿Cuánto papel necesitas para forrar una lata y convertirla en tambor? ¡Las matemáticas te lo dicen!',
      objetivos: ['Calcular el área de triángulos acutángulos y obtusángulos', 'Calcular la circunferencia y el área del círculo', 'Calcular el área de la superficie de prismas, cubos y cilindros', 'Componer un ritmo en grupo con instrumentos hechos en casa'],
      resumen: [
        'El área de cualquier triángulo es base × altura ÷ 2. En el obtusángulo, la altura puede quedar fuera del triángulo.',
        'Circunferencia = π × diámetro; área del círculo = π × radio × radio (usamos π ≈ 3.14).',
        'El área total de un sólido es la suma de las áreas de todas sus caras: el cubo tiene 6 cuadrados iguales; el cilindro, 2 círculos y un rectángulo.',
        'En la pirámide se suman la base y los triángulos; en el cono, el círculo de la base y la cara curva.',
        'Con latas, botellas y semillas se pueden construir instrumentos y crear música en grupo.',
      ],
      media: {
        id: 's11-d3-desarrollos', kind: 'animation', title: 'Sólidos que se abren', aspect: '16:9', duration: 60,
        alt: 'Animación de un cubo, una caja, una lata y una pirámide que se desdoblan hasta quedar planos mostrando todas sus caras.',
        brief: 'Animación 2D de 60 s: cuatro objetos cotidianos de Guatemala (caja de cartón de un mercado, dado de madera, lata usada como tambor, pirámide de papel) se desdoblan uno por uno hasta formar su desarrollo plano. Cada cara se colorea distinto y aparece su área. Para la lata: dos círculos (tapas) y un rectángulo cuyo largo es la circunferencia. Texto en pantalla: "Área total = suma de las caras". Narración breve en español.',
      },
      steps: [
        S.explain(
          { fase: 'explorar', areas: ['mat', 'art'], cnb: ['mat:1.2.2'], ambito: 'conocer', title: 'El área de cualquier triángulo',
            prompt: 'Para la feria patronal, el grado hará **banderines triangulares**. ¿Cuánta tela lleva cada uno? Toca las tarjetas.' },
          { icon: 'Triangle', body: 'Un triángulo es **la mitad de un rectángulo** con la misma base y altura. Por eso: **Área = base × altura ÷ 2**.', reveal: [
            { icon: 'Triangle', front: 'Acutángulo', back: 'Todos sus ángulos son agudos. La altura cae **dentro** del triángulo.' },
            { icon: 'Slash', front: 'Obtusángulo', back: 'Tiene un ángulo mayor de 90°. Si usas el lado más corto como base, la altura cae **fuera**: se prolonga la base con una línea punteada.' },
            { icon: 'Ruler', front: '¿Qué es la altura?', back: 'Es la línea **perpendicular** (forma 90°) desde la base hasta el vértice opuesto. No es el lado inclinado.' },
          ] },
        ),
        S.number(
          { fase: 'construir', areas: ['mat', 'art'], cnb: ['mat:1.2.2'], ambito: 'hacer',
            prompt: 'Un banderín **acutángulo** tiene **base de 20 cm** y **altura de 30 cm**. ¿Cuántos cm² de tela necesita?',
            hint: 'Multiplica base por altura y luego divide entre 2.',
            explain: '20 × 30 = 600; 600 ÷ 2 = 300 cm².' },
          { answer: 300, unit: 'cm²', stimulus: 'Área = 20 × 30 ÷ 2',
            misconceptions: [{ value: 600, msg: 'Olvidaste dividir entre 2: el triángulo es la mitad del rectángulo.' }, { value: 50, msg: 'Sumaste en lugar de multiplicar.' }] },
        ),
        S.number(
          { fase: 'construir', areas: ['mat', 'pyd'], cnb: ['mat:1.2.2'], ambito: 'hacer',
            prompt: 'Supongamos que un terreno para sembrar tiene forma de triángulo **obtusángulo**. Su base mide **12 m** y su altura (que cae fuera del triángulo) mide **7 m**. El lado inclinado mide 9 m. ¿Cuál es su área?',
            hint: 'El lado inclinado no es la altura: no lo necesitas.',
            explain: '12 × 7 = 84; 84 ÷ 2 = 42 m². La fórmula es la misma para todos los triángulos.' },
          { answer: 42, unit: 'm²',
            misconceptions: [{ value: 54, msg: 'Usaste el lado inclinado (9 m) como si fuera la altura.' }, { value: 84, msg: 'Falta dividir entre 2.' }] },
        ),
        S.explain(
          { fase: 'construir', areas: ['mat'], cnb: ['mat:1.2.3'], ambito: 'conocer', title: 'El círculo del comal',
            prompt: 'El comal, la tortilla y la boca de una tinaja son círculos. Descubre sus medidas.',
            media: { id: 's11-d3-comal', kind: 'diagram', title: 'Partes del círculo en un comal', aspect: '1:1',
              alt: 'Comal visto desde arriba con el centro marcado, el radio, el diámetro y la circunferencia resaltada en color.',
              brief: 'Diagrama sobre la foto o ilustración de un comal de barro visto desde arriba: punto central, radio (línea roja del centro al borde, rotulada "r = 20 cm"), diámetro (línea azul de borde a borde, "d = 40 cm") y el borde resaltado en amarillo con la etiqueta "circunferencia". Abajo, las fórmulas C = π × d y A = π × r × r, con π ≈ 3.14. Trazos gruesos, fondo claro.' } },
          { icon: 'Circle', body: 'Si divides la circunferencia de cualquier círculo entre su diámetro, siempre obtienes el mismo número: **π (pi) ≈ 3.14**.', reveal: [
            { icon: 'Ruler', front: 'Radio y diámetro', back: 'El **radio** va del centro al borde. El **diámetro** cruza todo el círculo: mide **2 radios**.' },
            { icon: 'RefreshCw', front: 'Circunferencia', back: 'Es el **borde** del círculo: **C = π × diámetro**. Un comal de 40 cm de diámetro: 3.14 × 40 = 125.6 cm.' },
            { icon: 'Circle', front: 'Área del círculo', back: 'Es la superficie: **A = π × r × r**. Con r = 20 cm: 3.14 × 20 × 20 = 1,256 cm².' },
          ] },
        ),
        S.cards(
          { fase: 'construir', areas: ['mat', 'art'], cnb: ['mat:1.4.1'], ambito: 'conocer',
            prompt: 'El **área total** de un sólido es la suma de las áreas de todas sus caras. Voltea cada tarjeta para ver cómo se calcula.' },
          { cards: [
            { icon: 'Package', front: 'Cubo (arista l)', back: '6 cuadrados iguales: **A = 6 × l × l**. Si l = 5 cm: 6 × 25 = 150 cm².' },
            { icon: 'Archive', front: 'Prisma rectangular', back: '3 pares de rectángulos: frente y atrás, arriba y abajo, lados. Se calcula cada uno y se suman.' },
            { icon: 'Drum', front: 'Cilindro (lata)', back: '2 círculos + 1 rectángulo. El rectángulo mide **circunferencia × altura** (2 × π × r × h).' },
            { icon: 'Triangle', front: 'Pirámide', back: 'Área de la **base** + área de cada **triángulo** de los lados.' },
            { icon: 'Hexagon', front: 'Cono', back: 'Área del **círculo** de la base + área de la **cara curva** (π × r × generatriz).' },
          ] },
        ),
        S.number(
          { fase: 'aplicar', areas: ['mat', 'art', 'pyd'], cnb: ['mat:1.4.1', 'art:1.1.8'], ambito: 'emprender',
            prompt: 'Para construir un **tambor**, Ixchel forrará solo la **cara curva** de una lata con papel decorado. La lata tiene **radio de 5 cm** y **altura de 20 cm**. ¿Cuántos cm² de papel necesita? (π ≈ 3.14)',
            hint: 'La cara curva es un rectángulo: circunferencia (2 × 3.14 × 5) por la altura.',
            explain: 'Circunferencia: 2 × 3.14 × 5 = 31.4 cm. Rectángulo: 31.4 × 20 = 628 cm².' },
          { answer: 628, unit: 'cm²', allowDecimal: true, tolerance: 0.5,
            misconceptions: [{ value: 314, msg: 'Multiplicaste π × r × altura: la circunferencia es 2 × π × r (o π × diámetro).' }, { value: 78.5, msg: 'Eso es el área de una tapa (círculo), no la cara curva.' }] },
        ),
        S.rhythm(
          { fase: 'aplicar', areas: ['art', 'mat'], cnb: ['art:1.1.8'], ambito: 'convivir',
            prompt: 'Con tu grupo tocarán una **composición contemporánea** con instrumentos hechos en la escuela: tambor de lata, sonaja de botella con semillas y claves de madera. Compón el compás del tambor: **4 tiempos** con al menos **una blanca y una corchea**.',
            hint: 'Blanca = 2 tiempos, negra = 1, corchea = ½. ¡Dos corcheas llenan un tiempo!',
            explain: 'En la música contemporánea se experimenta con sonidos nuevos. Cada instrumento del grupo puede tocar un ritmo distinto que encaje en los mismos 4 tiempos.',
            media: { id: 's11-d3-instrumentos', kind: 'video', title: 'Instrumentos con materiales reutilizados', aspect: '9:16', duration: 50,
              alt: 'Manos de niñas y niños construyendo un tambor de lata, una sonaja con semillas y unas claves de madera, y luego tocándolos juntos.',
              brief: 'Video vertical de 50 s, planos cerrados solo de manos (sin rostros): (1) tapar una lata con un globo o plástico grueso y ligas; (2) llenar una botella con semillas de frijol y maíz; (3) lijar dos palitos de madera para hacer claves. Final de 15 s con los tres instrumentos tocando un ritmo de 4 tiempos en un aula. Rótulos con el nombre de cada instrumento. Recordatorio de seguridad: pedir ayuda a una persona adulta al cortar.' } },
          { beats: 4, allowed: ['blanca', 'negra', 'corchea'], mustInclude: ['blanca', 'corchea'], showFractions: true },
        ),
        S.fill(
          { fase: 'comprobar', areas: ['mat'], cnb: ['mat:1.2.3'], prompt: 'Una tortilla grande tiene **10 cm de radio**. Completa sus medidas (π ≈ 3.14).' },
          { text: 'Su diámetro mide [[20]] cm. Su circunferencia mide 3.14 × 20 = [[62.8|62,8]] cm. Su área mide 3.14 × 10 × 10 = [[314]] cm².',
            distractors: ['10', '31.4', '628'] },
        ),
        S.choice(
          { fase: 'comprobar', areas: ['mat'], cnb: ['mat:1.4.1'], prompt: 'Una caja de cartón con forma de **cubo** tiene aristas de **10 cm**. ¿Cuál es el **área total** de su superficie?' },
          { options: [
            { id: 'a', text: '600 cm²', icon: 'Package' },
            { id: 'b', text: '100 cm²', icon: 'Square', feedback: 'Esa es el área de una sola cara; el cubo tiene 6.' },
            { id: 'c', text: '1,000 cm³', icon: 'Layers', feedback: 'Eso sería el volumen, que se mide en cm³. Aquí se pide el área de las caras.' },
          ], correct: ['a'] },
        ),
        cierre({ areas: ['mat', 'art'], cnb: ['art:1.1.8'] }, ['Calculo el área de cualquier triángulo', 'Calculo la circunferencia y el área de un círculo', 'Sé sumar las caras para hallar el área de un sólido'],
          ['Mediré el comal o una olla de mi casa y calcularé su circunferencia', 'Construiré un instrumento con materiales reutilizados', 'Tocaré mi ritmo con mi familia o mis amigos']),
      ],
    }),

    /* ───────────────────────── Día 4 ───────────────────────── */
    lesson({
      id: 's11-d4-trabajo-digno',
      title: 'Cuerpo que trabaja, derechos que protegen',
      icon: 'HeartPulse',
      minutes: 15,
      day: 4,
      gancho: 'Después de una mañana en la milpa, ¿por qué el corazón late más rápido? ¿Y quién cuida que el trabajo no dañe a las personas?',
      objetivos: ['Describir cómo trabajan juntos los sistemas circulatorio y respiratorio', 'Relacionar articulaciones con flexión, extensión y rotación', 'Identificar derechos laborales y derechos de las personas con discapacidad', 'Iniciar una exposición con una apertura interesante y gestos coherentes'],
      resumen: [
        'El sistema respiratorio toma oxígeno del aire en los pulmones; el circulatorio, con el corazón y la sangre, lo lleva a todo el cuerpo y recoge el dióxido de carbono.',
        'Las articulaciones permiten flexionar (doblar), extender (estirar) y rotar (girar) partes del cuerpo: el hombro rota, el codo y la rodilla se flexionan y extienden.',
        'Quienes trabajan tienen derechos: salario justo, jornada limitada, descanso, vacaciones, seguridad social y condiciones seguras.',
        'Las personas con discapacidad tienen los mismos derechos civiles y políticos; el Estado y la comunidad deben quitar barreras para que los ejerzan.',
        'Una buena exposición empieza con una apertura que atrapa (pregunta, dato o historia) y usa un tono de voz que coincide con los gestos.',
      ],
      media: {
        id: 's11-d4-corazon-pulmones', kind: 'animation', title: 'El viaje del oxígeno', aspect: '16:9', duration: 60,
        alt: 'Animación del aire entrando a los pulmones, pasando a la sangre y viajando por el corazón hasta los músculos de las piernas de una niña que corre.',
        brief: 'Animación 2D de 60 s con una silueta de niña (sin rasgos identificables) corriendo en una cancha escolar. Vista de rayos X estilizada: aire entra por nariz y tráquea a los pulmones (azul), el oxígeno pasa a la sangre (puntos rojos), el corazón bombea hacia los músculos, y la sangre regresa con dióxido de carbono (puntos morados) para ser exhalado. Contador de latidos que sube de 80 a 130 por minuto al correr. Narración sencilla en español con subtítulos.',
      },
      steps: [
        S.explain(
          { fase: 'explorar', areas: ['ef', 'cnt'], cnb: ['ef:1.1.8'], ambito: 'conocer', title: 'Dos sistemas, un equipo',
            prompt: 'Cuando trabajas o juegas, tus músculos piden más **oxígeno**. Dos sistemas trabajan en equipo para dárselo. Toca cada tarjeta.' },
          { icon: 'HeartPulse', body: 'Al hacer ejercicio respiras más rápido y el corazón late más veces por minuto: así llega más oxígeno a los músculos.', reveal: [
            { icon: 'Wind', front: 'Sistema respiratorio', back: 'Nariz, tráquea, bronquios y **pulmones**. Toma **oxígeno** del aire y expulsa **dióxido de carbono**.' },
            { icon: 'Heart', front: 'Sistema circulatorio', back: '**Corazón**, arterias, venas y capilares. La **sangre** lleva oxígeno y nutrientes a todo el cuerpo.' },
            { icon: 'Link', front: 'Trabajo en equipo', back: 'En los **pulmones** el oxígeno pasa a la sangre, y el corazón la bombea hasta cada célula, ¡donde las mitocondrias producen energía!' },
          ] },
        ),
        S.match(
          { fase: 'construir', areas: ['ef', 'cnt'], cnb: ['ef:1.1.7'], ambito: 'conocer',
            prompt: 'Las **articulaciones** son uniones entre huesos que permiten moverte. Une cada movimiento con un ejemplo.',
            hint: 'Flexionar = doblar; extender = estirar; rotar = girar.',
            explain: 'El hombro y la cadera permiten rotar en muchas direcciones; el codo y la rodilla funcionan como bisagras: se flexionan y se extienden.' },
          { leftTitle: 'Movimiento', rightTitle: 'Ejemplo', pairs: [
            { id: 'fle', left: 'Flexión', leftIcon: 'Dumbbell', right: 'Doblar el codo para levantar una canasta' },
            { id: 'ext', left: 'Extensión', leftIcon: 'Maximize2', right: 'Estirar la rodilla al patear una pelota' },
            { id: 'rot', left: 'Rotación', leftIcon: 'RotateCw', right: 'Girar el hombro al lanzar en círculo' },
          ] },
        ),
        S.pulse(
          { fase: 'construir', areas: ['ef', 'cnt'], cnb: ['ef:1.1.1', 'ef:1.1.3', 'ef:1.1.8'], ambito: 'hacer',
            prompt: 'Mide tu pulso en reposo. Luego haz la rutina de **coordinación**: mueve brazo derecho y pierna izquierda a la vez, cambia de lado; después mueve tu **eje corporal**: inclínate adelante, atrás y a los lados, y gira el tronco de pie, sentado y acostado. Vuelve a medir.' },
          { seconds: 15, rounds: [
            { label: 'En reposo' },
            { label: 'Después de coordinar brazos y piernas', exercise: { name: 'Brazo y pierna contrarios, alternando', icon: 'PersonStanding', seconds: 40 } },
            { label: 'Después de mover el eje corporal', exercise: { name: 'Inclinar y girar el tronco en tres posiciones', icon: 'RotateCw', seconds: 40 } },
          ] },
        ),
        S.reading(
          { fase: 'construir', areas: ['fc', 'pyd', 'l1'], cnb: ['fc:1.2.4', 'fc:1.2.5', 'pyd:1.1.2'], ambito: 'convivir', prompt: 'Lee el texto y responde.' },
          { genre: 'Texto informativo', heading: 'Trabajo digno para todas las personas', passage:
            'En la comunidad de Mateo hay varias **fuentes de producción**: la milpa, el café, las tiendas y el tejido. Además hay fuentes **potenciales**, que todavía no se aprovechan: un mirador para el turismo comunitario, un vivero de árboles y un taller para convertir el café en producto empacado.\n\nToda persona que trabaja tiene **derechos laborales**. La Constitución de Guatemala establece, entre otros, un **salario** que permita vivir con dignidad, una **jornada** ordinaria diurna de no más de **8 horas diarias**, un día de **descanso** a la semana, **vacaciones** pagadas y condiciones de **seguridad** en el trabajo. Estos derechos protegen a quienes trabajan en el campo, en fábricas, en casas particulares o en oficinas.\n\nLas **personas con discapacidad** también tienen derecho a trabajar, a estudiar, a **votar** y a participar en su comunidad. Para que puedan ejercer sus derechos civiles y políticos se necesitan rampas, información en lengua de señas y en braille, y, sobre todo, **respeto**. Quitar las barreras es tarea del Estado y de todos.',
            questions: [
              { q: 'Según el texto, ¿cuál es una fuente de producción **potencial** de la comunidad?', options: [
                { id: 'a', text: 'Un vivero de árboles' },
                { id: 'b', text: 'La milpa' },
                { id: 'c', text: 'Las tiendas' },
              ], correct: 'a', why: 'La milpa y las tiendas ya existen; el vivero es una posibilidad que aún no se aprovecha.' },
              { q: '¿Cuál de estos es un **derecho laboral**?', options: [
                { id: 'a', text: 'Tener un día de descanso a la semana' },
                { id: 'b', text: 'Trabajar sin límite de horas' },
                { id: 'c', text: 'No recibir pago en vacaciones' },
              ], correct: 'a' },
              { q: '¿Qué ayuda a que una persona que usa silla de ruedas pueda ir a votar?', options: [
                { id: 'a', text: 'Que el centro de votación tenga rampas y le traten con respeto' },
                { id: 'b', text: 'Que otra persona vote por ella sin preguntarle' },
                { id: 'c', text: 'Que se quede en casa' },
              ], correct: 'a', why: 'Votar es un derecho político personal; las rampas quitan una barrera para ejercerlo.' },
            ] },
        ),
        S.choice(
          { fase: 'aplicar', areas: ['l1', 'fc'], cnb: ['l1:2.2.1'], ambito: 'convivir',
            prompt: 'Vas a exponer en la asamblea escolar sobre los **derechos de quienes trabajan**. ¿Cuál es la **apertura** más interesante para atrapar a tu público?',
            explain: 'Una buena apertura despierta curiosidad: una pregunta que involucra al público, un dato sorprendente o una historia breve.' },
          { options: [
            { id: 'a', text: '"¿Alguien aquí sabe cuántas horas trabajó su mamá o su papá ayer? Hoy les contaré qué dice la ley."', icon: 'MessageCircle' },
            { id: 'b', text: '"Bueno… eh… mi tema es de derechos."', icon: 'VolumeX', feedback: 'Empezar sin preparación hace que el público pierda interés desde el inicio.' },
            { id: 'c', text: '"Voy a leer las siete páginas que copié."', icon: 'FileText', feedback: 'Anunciar una lectura larga desanima; mejor empieza con algo que despierte curiosidad.' },
          ], correct: ['a'] },
        ),
        S.sort(
          { fase: 'aplicar', areas: ['l1', 'ef'], cnb: ['l1:1.2.2', 'l1:1.1.3'], ambito: 'convivir',
            prompt: 'Cuando alguien habla, su **tono de voz** y sus **gestos** deben decir lo mismo. Observa cada caso: ¿hay **congruencia** o no?',
            explain: 'Si el tono y los gestos no coinciden con las palabras, el público se confunde o duda de la intención del mensaje.',
            media: { id: 's11-d4-gestos', kind: 'video', title: 'Voz y gestos que dicen lo mismo', aspect: '16:9', duration: 40,
              alt: 'Cuatro escenas breves de estudiantes (ilustrados) que exponen con distintos tonos de voz y gestos.',
              brief: 'Animación 2D de 40 s con 4 escenas de 10 s de estudiantes ilustrados de distintos pueblos de Guatemala (maya, garífuna, xinka y ladino), niñas y niños: (1) dice "¡Es muy importante!" con voz firme y mano en el pecho; (2) dice "Estoy feliz de estar aquí" con cara triste y voz apagada; (3) dice "Esto es un peligro" sonriendo y encogiendo hombros; (4) dice "Les invito a participar" con brazos abiertos y voz cálida. Subtítulos con cada frase.' } },
          { buckets: [
            { id: 'si', label: 'Congruente', icon: 'ThumbsUp', color: 'var(--c-ok)' },
            { id: 'no', label: 'No congruente', icon: 'X', color: 'var(--c-hint)' },
          ], items: [
            { id: 'g1', text: '"¡Es muy importante!" con voz firme y mano en el pecho', bucket: 'si' },
            { id: 'g2', text: '"Estoy feliz de estar aquí" con cara triste y voz apagada', bucket: 'no' },
            { id: 'g3', text: '"Esto es un peligro" sonriendo y encogiendo los hombros', bucket: 'no' },
            { id: 'g4', text: '"Les invito a participar" con brazos abiertos y voz cálida', bucket: 'si' },
          ] },
        ),
        S.write(
          { fase: 'aplicar', areas: ['pyd', 'l1', 'fc'], cnb: ['pyd:1.2.2', 'pyd:1.1.2'], ambito: 'emprender',
            prompt: 'Tu escuela abrió un **buzón de ideas**. Propón, con tus propias palabras, una **innovación** que aproveche una fuente de producción de tu comunidad (existente o potencial) respetando los derechos de quienes trabajen en ella.' },
          { model: 'Propongo que la escuela tenga un vivero de árboles nativos. Lo cuidaríamos por turnos después de clases, sin afectar el estudio. Venderíamos arbolitos a las familias y el dinero serviría para comprar libros. Así reforestamos, aprendemos y nadie trabaja de más.',
            rubric: ['Nombra una fuente de producción de la comunidad', 'Explica qué innovación propone', 'Dice a quién beneficia', 'Respeta los derechos y el tiempo de estudio'],
            minWords: 25, placeholder: 'Propongo que…' },
        ),
        S.tf(
          { fase: 'comprobar', areas: ['ef', 'cnt'], cnb: ['ef:1.1.8', 'ef:1.1.7'], prompt: '¿Verdadero o falso?' },
          { statements: [
            { text: 'Los pulmones toman oxígeno del aire y la sangre lo lleva a todo el cuerpo.', answer: true },
            { text: 'El corazón es parte del sistema respiratorio.', answer: false, why: 'El corazón es el órgano central del sistema circulatorio.' },
            { text: 'Doblar la rodilla es un movimiento de flexión.', answer: true },
            { text: 'Al hacer ejercicio, el corazón late más despacio.', answer: false, why: 'Late más rápido para llevar más oxígeno a los músculos.' },
          ] },
        ),
        S.choice(
          { fase: 'comprobar', areas: ['fc', 'l1'], cnb: ['fc:1.2.4', 'fc:1.2.5', 'l1:1.2.2'], prompt: 'Elige **todas** las afirmaciones correctas.', },
          { multiple: true, options: [
            { id: 'a', text: 'Las vacaciones pagadas son un derecho laboral.', icon: 'Calendar' },
            { id: 'b', text: 'Las personas con discapacidad tienen derecho a votar.', icon: 'Vote' },
            { id: 'c', text: 'Decir "estoy feliz" con cara triste es un mensaje congruente.', icon: 'Smile', feedback: 'Los gestos contradicen las palabras: no hay congruencia.' },
            { id: 'd', text: 'Un empleador puede exigir jornadas diurnas de 14 horas diarias.', icon: 'Clock', feedback: 'La jornada ordinaria diurna no debe pasar de 8 horas diarias.' },
          ], correct: ['a', 'b'] },
        ),
        cierre({ areas: ['fc', 'ef'], cnb: ['fc:1.2.5'] }, ['Explico cómo trabajan juntos el corazón y los pulmones', 'Nombro derechos de quienes trabajan', 'Inicio una exposición de forma interesante'],
          ['Preguntaré en casa qué derechos conocen del trabajo', 'Observaré si mi escuela tiene barreras para personas con discapacidad', 'Practicaré mi apertura frente al espejo']),
      ],
    }),

    /* ───────────────────────── Día 5: Reto semanal ───────────────────────── */
    lesson({
      id: 's11-d5-reto',
      title: 'Reto de la semana 11',
      icon: 'Trophy',
      minutes: 14,
      day: 5,
      kind: 'reto',
      objetivos: ['Demostrar lo que aprendiste sobre la Tierra, la vida y el trabajo', 'Obtener la medalla "Guardián de la milpa" (70 % o más)'],
      resumen: ['Superé el reto de la semana 11: Popol Wuj, fotosíntesis, continentes, áreas, cuerpo y derechos.'],
      media: {
        id: 's11-d5-reto', kind: 'image', title: 'Medalla Guardián de la milpa', aspect: '1:1',
        alt: 'Medalla dorada con una mazorca de maíz de granos de colores y un pequeño volcán al fondo.',
        brief: 'Ilustración de medalla circular dorada: al centro una mazorca con granos amarillos, blancos, negros y rojos; detrás, la silueta de un volcán y un sol. Cinta con los colores de las áreas del CNB. Estilo plano con brillo suave, fondo transparente, 1024×1024.',
      },
      steps: [
        S.choice({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:1.1.2'], prompt: 'Según el Popol Wuj, ¿por qué fueron destruidas las personas de madera?' },
          { options: [{ id: 'a', text: 'Porque no tenían corazón ni memoria de sus creadores' }, { id: 'b', text: 'Porque eran demasiado altas' }, { id: 'c', text: 'Porque se deshacían con el agua' }], correct: ['a'] }),
        S.match({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:1.2.2', 'cnt:1.3.2'], prompt: 'Une cada estructura con su función.' },
          { pairs: [{ id: 'c', left: 'Cloroplasto', right: 'Fotosíntesis' }, { id: 'v', left: 'Vacuola', right: 'Guarda agua' }, { id: 'm', left: 'Mitocondria', right: 'Energía en células animales y vegetales' }] }),
        S.sort({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:1.4.2'], prompt: '¿Se hereda por los genes o se adquiere durante la vida?' },
          { buckets: [{ id: 'h', label: 'Se hereda', icon: 'Dna' }, { id: 'a', label: 'Se adquiere', icon: 'User' }],
            items: [{ id: 'a1', text: 'Tipo de cabello', bucket: 'h' }, { id: 'a2', text: 'Saber tocar marimba', bucket: 'a' }, { id: 'a3', text: 'Color de ojos', bucket: 'h' }, { id: 'a4', text: 'Un tatuaje', bucket: 'a' }] }),
        S.order({ fase: 'comprobar', areas: ['ccss', 'mat'], cnb: ['ccss:1.1.1'], prompt: 'Ordena los continentes del **más extenso** al **menos extenso**.' },
          { items: [{ id: 'as', text: 'Asia' }, { id: 'am', text: 'América' }, { id: 'af', text: 'África' }, { id: 'eu', text: 'Europa' }, { id: 'oc', text: 'Oceanía' }], labels: { start: 'Más extenso', end: 'Menos extenso' } }),
        S.choice({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:1.2.2', 'ccss:1.3.2'], prompt: 'Una familia vive al pie de una ladera empinada que fue deforestada. Empieza la época de lluvia. ¿Qué riesgo es mayor?' },
          { options: [{ id: 'a', text: 'Un deslave' }, { id: 'b', text: 'Una nevada' }, { id: 'c', text: 'Una sequía' }], correct: ['a'] }),
        S.number({ fase: 'comprobar', areas: ['mat'], cnb: ['mat:1.2.2'], prompt: 'Un triángulo obtusángulo tiene base de 14 cm y altura de 6 cm. ¿Cuál es su área?' },
          { answer: 42, unit: 'cm²', misconceptions: [{ value: 84, msg: 'Falta dividir entre 2.' }] }),
        S.number({ fase: 'comprobar', areas: ['mat'], cnb: ['mat:1.2.3'], prompt: 'Un plato tiene 30 cm de diámetro. ¿Cuánto mide su circunferencia? (π ≈ 3.14)' },
          { answer: 94.2, unit: 'cm', allowDecimal: true, tolerance: 0.05 }),
        S.fill({ fase: 'comprobar', areas: ['l3'], cnb: ['l3:1.2.4', 'l3:1.1.4'], prompt: 'Complete in English.' },
          { text: 'The comal is [[round]]. The box is [[square]]. The volcano is very [[large]].', distractors: ['happy', 'fast'] }),
        S.tf({ fase: 'comprobar', areas: ['ef', 'fc'], cnb: ['ef:1.1.8', 'fc:1.2.4'], prompt: '¿Verdadero o falso?' },
          { statements: [{ text: 'La sangre transporta el oxígeno que entra por los pulmones.', answer: true }, { text: 'El descanso semanal es un derecho de quienes trabajan.', answer: true }, { text: 'La jornada ordinaria diurna puede ser de 12 horas diarias.', answer: false }] }),
        S.choice({ fase: 'comprobar', areas: ['l1'], cnb: ['l1:2.2.1', 'l1:1.2.2'], prompt: '¿Qué apertura mantiene mejor la atención del público?' },
          { options: [{ id: 'a', text: 'Una pregunta que invite a pensar, dicha con voz clara y mirando al público' }, { id: 'b', text: 'Leer el título en voz baja' }, { id: 'c', text: 'Pedir disculpas por no haber preparado nada' }], correct: ['a'] }),
      ],
    }),
  ],

  /* Banco de ítems para la Semana de validación de la Unidad 2 */
  bank: [
    S.choice({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:1.1.2'], prompt: '¿De qué material fueron formadas las personas verdaderas en el Popol Wuj?' },
      { options: [{ id: 'a', text: 'De maíz amarillo y blanco' }, { id: 'b', text: 'De piedra' }, { id: 'c', text: 'De barro' }], correct: ['a'] }),
    S.choice({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:1.2.2'], prompt: '¿Qué gas liberan las plantas durante la fotosíntesis?' },
      { options: [{ id: 'a', text: 'Oxígeno' }, { id: 'b', text: 'Dióxido de carbono' }, { id: 'c', text: 'Humo' }], correct: ['a'] }),
    S.tf({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:1.3.2', 'cnt:1.4.2'], prompt: '¿Verdadero o falso?' },
      { statements: [{ text: 'Las células animales también tienen mitocondrias.', answer: true }, { text: 'Los genes están en la pared celular.', answer: false }] }),
    S.match({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:1.1.2'], prompt: 'Une cada lugar con su continente.' },
      { pairs: [{ id: 'e', left: 'Everest', right: 'Asia' }, { id: 'k', left: 'Kilimanjaro', right: 'África' }, { id: 'a', left: 'Aconcagua', right: 'América' }] }),
    S.choice({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:1.2.2'], prompt: '¿En qué zona climática están los países cercanos al ecuador?' },
      { options: [{ id: 'a', text: 'Zona cálida' }, { id: 'b', text: 'Zona fría' }, { id: 'c', text: 'Zona templada' }], correct: ['a'] }),
    S.choice({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:1.1.5'], prompt: '¿Qué ejemplo muestra la importancia **cultural** de un recurso natural?' },
      { options: [{ id: 'a', text: 'Usar tintes de plantas para teñir tejidos tradicionales' }, { id: 'b', text: 'Vender madera por metro' }, { id: 'c', text: 'Exportar café' }], correct: ['a'] }),
    S.number({ fase: 'comprobar', areas: ['mat'], cnb: ['mat:1.2.3'], prompt: '¿Cuál es el área de un círculo de 10 cm de radio? (π ≈ 3.14)' },
      { answer: 314, unit: 'cm²', misconceptions: [{ value: 62.8, msg: 'Eso es la circunferencia, no el área.' }] }),
    S.number({ fase: 'comprobar', areas: ['mat'], cnb: ['mat:1.4.1'], prompt: '¿Cuál es el área total de un cubo de 4 cm de arista?' },
      { answer: 96, unit: 'cm²', misconceptions: [{ value: 16, msg: 'Esa es una sola cara; el cubo tiene 6.' }, { value: 64, msg: 'Eso es el volumen (4 × 4 × 4).' }] }),
    S.choice({ fase: 'comprobar', areas: ['ef'], cnb: ['ef:1.1.7', 'ef:1.1.1'], prompt: '¿Qué articulación permite **rotar** el brazo en círculos?' },
      { options: [{ id: 'a', text: 'El hombro' }, { id: 'b', text: 'La rodilla' }, { id: 'c', text: 'El tobillo' }], correct: ['a'] }),
    S.choice({ fase: 'comprobar', areas: ['fc'], cnb: ['fc:1.2.5'], prompt: '¿Qué medida ayuda a que las personas ciegas ejerzan su derecho a informarse?' },
      { options: [{ id: 'a', text: 'Tener información en braille o en audio' }, { id: 'b', text: 'Poner más carteles pequeños' }, { id: 'c', text: 'Pedirles que no participen' }], correct: ['a'] }),
    S.choice({ fase: 'comprobar', areas: ['pyd'], cnb: ['pyd:1.1.2'], prompt: 'En una comunidad con un mirador hermoso que nadie visita, el turismo comunitario es una fuente de producción…' },
      { options: [{ id: 'a', text: 'Potencial' }, { id: 'b', text: 'Que ya existe y funciona' }, { id: 'c', text: 'Imposible' }], correct: ['a'] }),
    S.choice({ fase: 'comprobar', areas: ['l2'], cnb: ['l2:1.1.3', 'l2:1.1.2'], prompt: 'Después de un diálogo sobre la milpa, ¿qué es un **subtema** adecuado?' },
      { options: [{ id: 'a', text: 'Cómo se alimenta la planta de maíz' }, { id: 'b', text: 'Mi color favorito' }, { id: 'c', text: 'El partido de fútbol del domingo' }], correct: ['a'] }),
  ],
});
