import { S, cierre, lesson, semana } from '../../dsl';

/**
 * SEMANA 15 · Unidad 2 "Consolidando nuestras relaciones"
 * Tema generador: Alimento y memoria que nos fortalecen
 * Nutrientes y leche materna · ciencias de la historia, poder y aportes de los pueblos antiguos ·
 * dominio colonial y Revolución Francesa · informes REMHI y CEH · gobierno escolar y proyectos.
 */
export default semana({
  id: 's15',
  unidad: 2,
  semana: 15,
  kind: 'aprendizaje',
  temaGenerador: 'Alimento y memoria que nos fortalecen',
  title: 'Alimento y memoria que nos fortalecen',
  subtitle: 'Nutrientes, historia de los pueblos y organización escolar',
  icon: 'Sprout',
  color: 'var(--area-cnt)',
  contexto: 'En una escuela de Sololá, el gobierno escolar quiere mejorar la refacción y organizar una feria de la memoria. Para lograrlo, cada comisión debe investigar: qué alimentos nos hacen crecer, cómo vivían y se organizaban los pueblos del pasado y por qué Guatemala decidió recordar su historia reciente. Esta semana descubrirás que una comunidad se fortalece con buena comida, buena memoria y buena organización.',
  ejes: ['vida-ciudadana', 'multiculturalidad', 'vida-familiar', 'valores'],
  media: {
    id: 's15-portada', kind: 'video', title: 'Una escuela que se organiza', aspect: '16:9', duration: 60,
    alt: 'Niñas y niños de una escuela del altiplano preparan una refacción nutritiva, montan una exposición de historia y votan en su gobierno escolar.',
    brief: 'Video (o animación 2D) de 60 s en una escuela rural del altiplano guatemalteco con estudiantes mayas, ladinos y garífunas representados por igual. Tres escenas cortas: (1) comisión de alimentación prepara atol, frijoles, tortillas y fruta; (2) comisión de cultura cuelga en un corredor una línea de tiempo con la Revolución Francesa, la Colonia y los Acuerdos de Paz; (3) asamblea del gobierno escolar vota a mano alzada. Sobreimpreso final: "Comida, memoria y organización: lo que nos fortalece". Música de marimba suave. Sin marcas ni rostros reales identificables.',
  },
  badge: { id: 'medalla-s15', name: 'Guardián de la memoria', icon: 'Library', desc: 'Completaste la semana 15 y superaste su reto' },
  lessons: [
    /* ───────────────────────── Día 1 ───────────────────────── */
    lesson({
      id: 's15-d1-nutrientes',
      title: 'Nutrientes que construyen',
      icon: 'Salad',
      minutes: 14,
      day: 1,
      gancho: 'Tu refacción de hoy, ¿te ayuda a crecer, a tener energía o a defenderte de enfermedades? ¿O a las tres cosas?',
      objetivos: ['Reconocer los cinco grupos de nutrientes y sus alimentos', 'Describir qué contiene la leche materna', 'Clasificar alimentos según ayuden a crecer, dar energía o proteger', 'Encontrar todos los divisores de un número'],
      resumen: [
        'Los nutrientes principales son proteínas (construyen), carbohidratos (dan energía), grasas (reserva de energía), vitaminas y minerales (regulan y protegen).',
        'La leche materna tiene agua, lactosa, grasas, proteínas, vitaminas, minerales y anticuerpos; es gratuita y protege al bebé.',
        'Para crecer en talla se necesitan proteínas y calcio; para la energía, carbohidratos y grasas; para las defensas, vitaminas y minerales.',
        'Los divisores de un número son los que lo dividen exactamente: los divisores de 24 son 1, 2, 3, 4, 6, 8, 12 y 24.',
      ],
      media: {
        id: 's15-d1-plato', kind: 'image', title: 'El plato que me hace crecer', aspect: '4:3',
        alt: 'Plato ilustrado dividido en cinco secciones con alimentos guatemaltecos: frijol, tortilla, aguacate, frutas y hierbas.',
        brief: 'Ilustración plana, vista desde arriba, de un plato de barro dividido en 5 porciones rotuladas: PROTEÍNAS (frijol negro, huevo, queso fresco), CARBOHIDRATOS (tortilla de maíz, arroz, papa), GRASAS (aguacate, pepitoria), VITAMINAS (naranja, mango, zanahoria), MINERALES (hierba mora, chipilín, vaso de leche). Íconos pequeños de "construye", "energía" y "protege" junto a cada grupo. Colores cálidos, sin marcas comerciales.',
      },
      steps: [
        S.explain(
          { fase: 'explorar', areas: ['cnt', 'l1'], cnb: ['cnt:5.1.2'], ambito: 'conocer', title: 'Cinco equipos dentro de tu comida',
            prompt: 'Los alimentos llevan **nutrientes**: sustancias que tu cuerpo usa para crecer, moverse y defenderse. Toca cada tarjeta y descubre su trabajo.' },
          { icon: 'Salad', body: 'Ningún alimento tiene todos los nutrientes. Por eso conviene **combinar** alimentos distintos en cada tiempo de comida.', reveal: [
            { icon: 'Dumbbell', front: 'Proteínas', back: '**Construyen y reparan** músculos y tejidos. Frijol, huevo, queso, carne, leche.' },
            { icon: 'Zap', front: 'Carbohidratos', back: 'Dan **energía rápida**. Tortilla, arroz, papa, pan, plátano.' },
            { icon: 'Droplet', front: 'Grasas', back: 'Guardan **energía de reserva** y ayudan a usar algunas vitaminas. Aguacate, pepitoria, aceite.' },
            { icon: 'Apple', front: 'Vitaminas', back: '**Regulan** el cuerpo y fortalecen las defensas. Frutas y verduras de colores.' },
            { icon: 'Gem', front: 'Minerales', back: 'Forman huesos (calcio) y sangre (hierro). Leche, tortilla de maíz con cal, hierbas verdes, frijol.' },
          ] },
        ),
        S.sort(
          { fase: 'construir', areas: ['cnt', 'pyd'], cnb: ['cnt:5.3.2'], ambito: 'conocer',
            prompt: 'La comisión de alimentación arma el menú de la semana. Clasifica cada alimento según lo que **más favorece**: crecer en **talla**, dar **energía** o **proteger** el cuerpo.',
            hint: 'Piensa en el nutriente principal de cada alimento: proteínas y calcio → crecer; carbohidratos y grasas → energía; vitaminas y minerales → proteger.',
            explain: 'Una niña o niño que come de los tres grupos crece bien, tiene energía para aprender y se enferma menos. La desnutrición en la niñez puede frenar el crecimiento en talla.' },
          { buckets: [
            { id: 'talla', label: 'Crecer en talla', icon: 'Ruler', color: 'var(--area-cnt)' },
            { id: 'energia', label: 'Energía', icon: 'Zap', color: 'var(--area-mat)' },
            { id: 'proteger', label: 'Proteger (defensas)', icon: 'Shield', color: 'var(--c-ok)' },
          ], items: [
            { id: 'a1', text: 'Huevo', icon: 'Egg', bucket: 'talla' },
            { id: 'a2', text: 'Vaso de leche', icon: 'Milk', bucket: 'talla' },
            { id: 'a3', text: 'Arroz', icon: 'Wheat', bucket: 'energia' },
            { id: 'a4', text: 'Papa cocida', icon: 'Carrot', bucket: 'energia', feedback: 'La papa es rica en almidón, un carbohidrato: da energía.' },
            { id: 'a5', text: 'Mango', icon: 'Apple', bucket: 'proteger' },
            { id: 'a6', text: 'Hierba mora', icon: 'Leaf', bucket: 'proteger', feedback: 'Las hierbas verdes aportan vitaminas y minerales como el hierro, que protegen contra la anemia.' },
          ] },
        ),
        S.fill(
          { fase: 'construir', areas: ['cnt', 'fc'], cnb: ['cnt:5.2.2'], ambito: 'conocer',
            prompt: 'La leche materna es el primer alimento de un bebé. Completa lo que contiene.',
            explain: 'Por eso se recomienda dar solo leche materna los primeros 6 meses. Además es gratuita: la familia no gasta en fórmulas ni pachas.',
            media: { id: 's15-d1-lactancia', kind: 'diagram', title: '¿Qué hay en la leche materna?', aspect: '1:1',
              alt: 'Gota de leche grande dividida en secciones: agua, lactosa, grasas, proteínas, vitaminas y minerales, anticuerpos.',
              brief: 'Diagrama circular dentro de una gota de leche estilizada. Secciones rotuladas: AGUA (la mayor parte, azul claro), LACTOSA (azúcar natural, amarillo), GRASAS (naranja), PROTEÍNAS (rosa), VITAMINAS Y MINERALES (verde) y ANTICUERPOS (pequeños escudos). Nota al pie: "Los primeros días se produce el calostro, muy rico en defensas". Estilo educativo, sin mostrar cuerpos.' } },
          { text: 'La leche materna es principalmente [[agua]], lo que hidrata al bebé. Su azúcar natural se llama [[lactosa]] y le da energía. También tiene grasas, proteínas, vitaminas, minerales y [[anticuerpos]], que lo defienden de infecciones. La primera leche, muy rica en defensas, se llama [[calostro]].',
            distractors: ['almidón', 'jugo', 'vacuna'] },
        ),
        S.recipe(
          { fase: 'construir', areas: ['cnt', 'mat', 'pyd'], cnb: ['cnt:5.3.2'], ambito: 'hacer',
            prompt: 'El gobierno escolar prepara **atol de elote** con frijoles y tortilla para la refacción. La receta es para **4** personas; calcula para **12**.',
            explain: 'De 4 a 12 se multiplica por 3. Esta refacción combina carbohidratos (elote, tortilla), proteínas (frijol) y calcio (leche).' },
          { dish: 'Refacción de atol de elote con frijoles', icon: 'Utensils', baseServings: 4, targetServings: 12, ingredients: [
            { name: 'Elotes desgranados', icon: 'Wheat', qty: 3, unit: 'elotes' },
            { name: 'Leche', icon: 'Milk', qty: 2, unit: 'tazas' },
            { name: 'Frijol cocido', icon: 'Utensils', qty: 1, unit: 'taza' },
            { name: 'Tortillas', icon: 'Circle', qty: 8, unit: 'tortillas' },
          ], ask: [0, 1, 3] },
        ),
        S.explain(
          { fase: 'construir', areas: ['mat', 'pyd'], cnb: ['mat:4.3.1'], ambito: 'conocer', title: 'Repartir sin que sobre: los divisores',
            prompt: 'La comisión tiene **24 tortillas** y quiere hacer grupos iguales sin que sobre ninguna. Cada tamaño de grupo que funciona es un **divisor** de 24.' },
          { icon: 'Calculator', body: 'Un **divisor** de un número lo divide **exactamente** (residuo 0). Búscalos en **parejas**: 1 × 24, 2 × 12, 3 × 8, 4 × 6. Cuando las parejas se repiten, ya terminaste.', reveal: [
            { icon: 'ListOrdered', front: 'Divisores de 24', back: '1, 2, 3, 4, 6, 8, 12 y 24 → **8 divisores**.' },
            { icon: 'X', front: '¿Y el 5?', back: '24 ÷ 5 = 4 y sobran 4. **No** es divisor.' },
            { icon: 'Sparkles', front: 'Truco', back: 'El 1 y el mismo número **siempre** son divisores.' },
          ] },
        ),
        S.choice(
          { fase: 'aplicar', areas: ['mat', 'cnt'], cnb: ['mat:4.3.1'],
            prompt: 'Hay **36 bananos** para repartir en bolsas iguales, sin que sobre ninguno. Selecciona **todas** las cantidades de bolsas posibles.',
            hint: 'Busca las parejas que multiplicadas dan 36: 1 × 36, 2 × 18…',
            explain: 'Los divisores de 36 son 1, 2, 3, 4, 6, 9, 12, 18 y 36. El 8 y el 10 dejan residuo.' },
          { multiple: true, layout: 'grid', options: [
            { id: 'a', text: '4 bolsas' },
            { id: 'b', text: '6 bolsas' },
            { id: 'c', text: '8 bolsas', feedback: '36 ÷ 8 = 4 y sobran 4.' },
            { id: 'd', text: '9 bolsas' },
            { id: 'e', text: '10 bolsas', feedback: '36 ÷ 10 = 3 y sobran 6.' },
            { id: 'f', text: '12 bolsas' },
          ], correct: ['a', 'b', 'd', 'f'] },
        ),
        S.match(
          { fase: 'aplicar', areas: ['l2', 'cnt'], cnb: ['l2:4.1.3'], ambito: 'conocer',
            prompt: 'Un **fonema** es un **sonido** que distingue palabras (no siempre es igual a la letra). Di en voz alta cada alimento y une con su **fonema inicial** y **fonema final**.',
            hint: 'Escucha, no mires las letras: "qu" suena /k/ y en Guatemala "ce" suena /s/.',
            explain: 'En "queso" se escriben dos letras (qu) pero se oye un solo sonido: /k/. En "cebolla" la c suena /s/. Por eso decimos que el fonema es el sonido y la letra es su forma escrita.' },
          { leftTitle: 'Alimento', rightTitle: 'Fonema inicial … final', pairs: [
            { id: 'que', left: 'queso', leftIcon: 'Milk', right: '/k/ … /o/' },
            { id: 'ceb', left: 'cebolla', leftIcon: 'Carrot', right: '/s/ … /a/' },
            { id: 'fri', left: 'frijol', leftIcon: 'Utensils', right: '/f/ … /l/' },
            { id: 'pan', left: 'pan', leftIcon: 'Wheat', right: '/p/ … /n/' },
          ] },
        ),
        S.sort(
          { fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:5.1.2', 'cnt:5.3.2'], prompt: 'Boleto de salida: clasifica cada alimento según su **nutriente principal**.' },
          { buckets: [
            { id: 'prot', label: 'Proteínas', icon: 'Dumbbell' },
            { id: 'carb', label: 'Carbohidratos', icon: 'Zap' },
            { id: 'vit', label: 'Vitaminas', icon: 'Apple' },
          ], items: [
            { id: 'b1', text: 'Queso fresco', bucket: 'prot' },
            { id: 'b2', text: 'Frijol', bucket: 'prot' },
            { id: 'b3', text: 'Pan', bucket: 'carb' },
            { id: 'b4', text: 'Plátano cocido', bucket: 'carb' },
            { id: 'b5', text: 'Zanahoria', bucket: 'vit' },
            { id: 'b6', text: 'Papaya', bucket: 'vit' },
          ] },
        ),
        S.choice(
          { fase: 'comprobar', areas: ['mat', 'cnt'], cnb: ['mat:4.3.1'], prompt: '¿Cuál lista tiene **todos** los divisores de 20?' },
          { options: [
            { id: 'a', text: '1, 2, 4, 5, 10, 20' },
            { id: 'b', text: '2, 4, 5, 10', feedback: 'Te faltan el 1 y el 20: siempre son divisores.' },
            { id: 'c', text: '1, 2, 3, 4, 5, 10, 20', feedback: '20 ÷ 3 no es exacto: sobran 2.' },
          ], correct: ['a'] },
        ),
        cierre({ areas: ['cnt', 'mat'], cnb: ['cnt:5.3.2'] }, ['Nombro los cinco grupos de nutrientes y un alimento de cada uno', 'Explico por qué la leche materna protege al bebé', 'Encuentro todos los divisores de un número'],
          ['Agregaré una fruta o verdura a mi refacción', 'Contaré en casa qué contiene la leche materna', 'Buscaré los divisores de la cantidad de estudiantes de mi grado']),
      ],
    }),

    /* ───────────────────────── Día 2 ───────────────────────── */
    lesson({
      id: 's15-d2-detectives-pasado',
      title: 'Detectives del pasado',
      icon: 'Search',
      minutes: 15,
      day: 2,
      gancho: 'Si dentro de mil años alguien encontrara tu mochila, ¿qué podría saber de ti sin haberte conocido?',
      objetivos: ['Reconocer las ciencias que ayudan a la Historia', 'Relacionar cómo se organiza el poder con la forma de la sociedad', 'Identificar aportes de pueblos antiguos a la humanidad', 'Multiplicar con numeración maya'],
      resumen: [
        'La Historia estudia el pasado con ayuda de ciencias auxiliares: arqueología, epigrafía, paleografía, numismática, cronología, geografía y genealogía, entre otras.',
        'Cuando el poder se concentra en pocas personas, la sociedad se ordena como una pirámide: gobernantes arriba y la mayoría campesina abajo.',
        'Los pueblos antiguos aportaron la escritura, el calendario, la democracia, el derecho, el papel y el concepto del cero.',
        'Para multiplicar en maya se multiplica cada posición y cada 20 unidades se sube una al nivel de arriba.',
      ],
      media: {
        id: 's15-d2-arqueologia', kind: 'video', title: 'Un día con un equipo de arqueología', aspect: '16:9', duration: 75,
        alt: 'Equipo de arqueólogas y arqueólogos excava con brochas junto a una estela maya en la selva de Petén.',
        brief: 'Video documental ilustrado de 75 s en un sitio arqueológico de Petén: una arqueóloga limpia con brocha un fragmento de cerámica; un epigrafista dibuja los glifos de una estela; un geógrafo mide con GPS; una cronóloga ordena fechas en una línea de tiempo. Rótulos con el nombre de cada ciencia auxiliar. Narración infantil en español con subtítulos. Personajes ficticios, diversidad de género y pueblos.',
      },
      steps: [
        S.cards(
          { fase: 'explorar', areas: ['ccss', 'l1'], cnb: ['ccss:6.1.2'], ambito: 'conocer', title: 'El equipo que ayuda a la Historia',
            prompt: 'La Historia es una **ciencia** que investiga el pasado para entender el presente. No trabaja sola: la ayudan otras ciencias. Voltea cada tarjeta.' },
          { cards: [
            { icon: 'Pickaxe', front: 'Arqueología', back: 'Estudia los **restos materiales**: cerámica, edificios, herramientas.' },
            { icon: 'ScrollText', front: 'Epigrafía', back: 'Lee **inscripciones** en piedra o metal, como los glifos de las estelas mayas.' },
            { icon: 'FileText', front: 'Paleografía', back: 'Descifra **escrituras antiguas** en papel o pergamino, como documentos coloniales.' },
            { icon: 'Coins', front: 'Numismática', back: 'Estudia **monedas y billetes** antiguos.' },
            { icon: 'Hourglass', front: 'Cronología', back: 'Ordena los hechos en el **tiempo** y calcula fechas.' },
            { icon: 'Users', front: 'Genealogía', back: 'Reconstruye el **origen de las familias** y sus parentescos.' },
            { icon: 'Map', front: 'Geografía', back: 'Estudia el **territorio**: ríos, montañas y climas donde vivieron los pueblos.' },
          ] },
        ),
        S.match(
          { fase: 'construir', areas: ['ccss'], cnb: ['ccss:6.1.2'], ambito: 'conocer',
            prompt: 'Completa el **esquema** de las ciencias auxiliares: une cada hallazgo con la ciencia que lo estudia.',
            explain: 'Cada ciencia auxiliar aporta una pieza. Juntas permiten reconstruir cómo vivían las personas del pasado.' },
          { leftTitle: 'Hallazgo', rightTitle: 'Ciencia auxiliar', pairs: [
            { id: 'est', left: 'Glifos tallados en una estela de Quiriguá', leftIcon: 'Landmark', right: 'Epigrafía' },
            { id: 'vas', left: 'Vasija de barro enterrada', leftIcon: 'Archive', right: 'Arqueología' },
            { id: 'mon', left: 'Moneda de plata de la época colonial', leftIcon: 'Coins', right: 'Numismática' },
            { id: 'car', left: 'Carta escrita a mano en 1821', leftIcon: 'Mail', right: 'Paleografía' },
            { id: 'map', left: 'Ubicación de ríos y montañas cerca de una ciudad antigua', leftIcon: 'Map', right: 'Geografía' },
          ] },
        ),
        S.explain(
          { fase: 'construir', areas: ['ccss', 'fc'], cnb: ['ccss:6.2.2'], ambito: 'conocer', title: 'El poder da forma a la sociedad',
            prompt: 'A lo largo de la historia, la manera de **organizar el poder** cambió la forma de la **sociedad**. Toca cada etapa.',
            media: { id: 's15-d2-piramide', kind: 'diagram', title: 'La pirámide social maya clásica', aspect: '3:4',
              alt: 'Pirámide dividida en niveles: ajaw arriba; nobles y sacerdotes; comerciantes y artesanos; campesinos; cautivos abajo.',
              brief: 'Diagrama vertical de una pirámide escalonada inspirada en templos mayas, con 5 niveles rotulados de arriba abajo: AJAW (gobernante), NOBLES Y SACERDOTES, COMERCIANTES Y ARTESANOS, CAMPESINOS (la mayoría), CAUTIVOS. El nivel de campesinos es el más ancho. Íconos simples por nivel (corona, libro, cesta, milpa, cuerda). Al lado, flecha "más poder" hacia arriba y "más personas" hacia abajo.' } },
          { icon: 'Landmark', body: 'Mientras más se **concentra** el poder, más **niveles** (desigualdad) tiene la sociedad.', reveal: [
            { icon: 'Footprints', front: 'Bandas nómadas', back: 'Grupos pequeños; guía quien tiene más **experiencia**. Casi no hay diferencias sociales.' },
            { icon: 'Home', front: 'Aldeas agrícolas', back: 'Con la agricultura surgen aldeas; decide un **consejo de ancianos**.' },
            { icon: 'Castle', front: 'Ciudades-Estado', back: 'Un **gobernante** (en los mayas, el _ajaw_) con nobles, sacerdotes y guerreros. La mayoría campesina paga **tributo**.' },
            { icon: 'Crown', front: 'Imperios', back: 'Un gobierno domina **muchos pueblos**, como Roma o el imperio mexica.' },
          ] },
        ),
        S.sort(
          { fase: 'construir', areas: ['ccss', 'mat'], cnb: ['ccss:6.3.2'], ambito: 'conocer',
            prompt: 'Esquematiza los **aportes de los pueblos antiguos**: coloca cada invento o idea con el pueblo que lo desarrolló.',
            explain: 'Muchas cosas que usamos a diario nacieron hace miles de años: la escritura, el papel, las leyes escritas y el cero.' },
          { layout: 'grid2', buckets: [
            { id: 'mes', label: 'Mesopotamia', icon: 'Castle' },
            { id: 'gre', label: 'Grecia', icon: 'Landmark' },
            { id: 'chi', label: 'China', icon: 'ScrollText' },
            { id: 'may', label: 'Mayas', icon: 'Sun' },
          ], items: [
            { id: 'p1', text: 'Escritura cuneiforme', bucket: 'mes' },
            { id: 'p2', text: 'La rueda', bucket: 'mes' },
            { id: 'p3', text: 'La democracia en Atenas', bucket: 'gre' },
            { id: 'p4', text: 'Los Juegos Olímpicos', bucket: 'gre' },
            { id: 'p5', text: 'El papel', bucket: 'chi' },
            { id: 'p6', text: 'La brújula', bucket: 'chi' },
            { id: 'p7', text: 'El concepto del cero', bucket: 'may', feedback: 'Los mayas usaron el cero en su sistema vigesimal hace más de 1,500 años.' },
            { id: 'p8', text: 'Calendario de 260 días (Cholq\'ij)', bucket: 'may' },
          ] },
        ),
        S.explain(
          { fase: 'construir', areas: ['mat', 'ccss'], cnb: ['mat:4.2.8'], ambito: 'conocer', title: 'Multiplicar como los ajq\'ij',
            prompt: 'El calendario sagrado maya tiene **13 números × 20 días = 260 días**. ¿Cómo se multiplica en numeración maya?' },
          { icon: 'Calculator', body: 'Multiplica **cada posición** por el factor. Si un nivel llega a **20 o más**, cada 20 sube como **1** al nivel de arriba.', reveal: [
            { icon: 'Layers', front: '20 en maya', back: 'Un **punto** en el 2.º nivel (×20) y un **caracol** (cero) abajo.' },
            { icon: 'X', front: '20 × 13', back: 'Multiplica cada nivel por 13: arriba 1 × 13 = **13** (dos barras y tres puntos); abajo 0 × 13 = **0**. Resultado: 13 × 20 = **260**.' },
            { icon: 'RefreshCw', front: '25 × 7', back: '25 = 1 veinte y 5 unidades. × 7 → **7** veintes y **35** unidades. 35 = 1 veinte + 15, así que queda **8** veintes y **15** unidades = **175**.' },
          ] },
        ),
        S.maya(
          { fase: 'aplicar', areas: ['mat', 'ccss'], cnb: ['mat:4.2.8'], ambito: 'hacer',
            prompt: 'Un año del calendario Ab\', sin sus 5 días finales, tiene **18 meses de 20 días**. Multiplica **20 × 18** y construye el resultado en numeración maya.',
            hint: '20 es un punto en el segundo nivel. Multiplica ese nivel por 18.',
            explain: '20 × 18 = 360: 18 en el nivel de los veintes (tres barras y tres puntos) y cero en las unidades. Si sumas los 5 días finales, obtienes los 365 días del año solar.' },
          { mode: 'build', target: 360, levels: 2, scaffold: true },
        ),
        S.fill(
          { fase: 'aplicar', areas: ['l3', 'ccss'], cnb: ['l3:4.3.1', 'l3:4.1.4'],
            prompt: 'English time! Para **comparar** agrega **-er + than** (old → older than). Usa **both** para una semejanza. Para los tiempos: **did** (pasado), **are + -ing** (ahora) y **will** (futuro).',
            explain: 'Tikal es mucho más antigua que Iximche\': "Tikal is **older** than Iximche\'". **Both** are Maya cities. Past: "What **did** they build?" Now: "They **are** digging." Future: "They **will** study…"' },
          { text: 'Tikal is [[older]] than Iximche\'. [[Both]] are Maya cities.\nWhat [[did]] the ancient Maya build? They built temples.\nToday, archaeologists [[are]] digging in Petén.\nNext year, they [[will]] study a new stela.', distractors: ['oldest', 'do', 'was'] },
        ),
        S.maya(
          { fase: 'comprobar', areas: ['mat'], cnb: ['mat:4.2.8'], prompt: 'Boleto de salida: multiplica **24 × 5** en numeración maya y construye el resultado (sin ayuda del valor posicional).' },
          { mode: 'build', target: 120, levels: 2 },
        ),
        S.choice(
          { fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:6.2.2'], prompt: 'En una ciudad-Estado maya, el poder estaba concentrado en el _ajaw_. ¿Cómo era entonces la sociedad?' },
          { options: [
            { id: 'a', text: 'Como una pirámide: pocos gobernantes arriba y muchos campesinos abajo', icon: 'Triangle' },
            { id: 'b', text: 'Todas las personas tenían el mismo poder', icon: 'Users', feedback: 'Eso se parece más a las bandas nómadas, no a una ciudad-Estado.' },
            { id: 'c', text: 'Los campesinos gobernaban a los nobles', icon: 'RefreshCw', feedback: 'Era al revés: los campesinos pagaban tributo a los nobles.' },
          ], correct: ['a'] },
        ),
        cierre({ areas: ['ccss', 'mat'], cnb: ['ccss:6.3.2'] }, ['Nombro ciencias auxiliares de la Historia y lo que estudian', 'Explico cómo el poder da forma a la sociedad', 'Multiplico con numeración maya'],
          ['Buscaré en casa un objeto antiguo y preguntaré su historia', 'Valoraré los aportes de los pueblos mayas', 'Practicaré una multiplicación maya con mi familia']),
      ],
    }),

    /* ───────────────────────── Día 3 ───────────────────────── */
    lesson({
      id: 's15-d3-memoria',
      title: 'Del dominio colonial a la memoria',
      icon: 'Library',
      minutes: 15,
      day: 3,
      gancho: '¿Por qué crees que un país decide escribir y guardar lo que le pasó, aunque sea doloroso?',
      objetivos: ['Comparar la vida de los pueblos indígenas antes y durante el dominio europeo', 'Ordenar las etapas que llevaron a la Revolución Francesa', 'Explicar qué son los informes REMHI y CEH y para qué sirven', 'Escribir textos con introducción, desarrollo y conclusión'],
      resumen: [
        'Durante la Colonia, los pueblos indígenas perdieron tierras y autoridades propias, pagaron tributo y fueron obligados a trabajar; aun así conservaron sus idiomas y costumbres.',
        'La Revolución Francesa (1789) empezó con las ideas de la Ilustración y una crisis económica, siguió con los Estados Generales, la Asamblea Nacional, la toma de la Bastilla y la Declaración de los Derechos del Hombre y del Ciudadano.',
        'El informe REMHI "Guatemala: Nunca Más" (1998) y el informe de la CEH "Guatemala: Memoria del Silencio" (1999) documentaron lo ocurrido en el conflicto armado interno para recordar, reparar a las víctimas y que no se repita.',
        'Un texto ordenado tiene introducción, desarrollo y conclusión; sus párrafos pueden ser principales, ejemplificadores o concluyentes.',
      ],
      media: {
        id: 's15-d3-linea', kind: 'diagram', title: 'Línea de tiempo: de la Colonia a la memoria', aspect: '16:9',
        alt: 'Línea de tiempo horizontal con cinco hitos: Colonia, Revolución Francesa en 1789, firma de la paz en 1996, informe REMHI en 1998 e informe CEH en 1999.',
        brief: 'Infografía horizontal con una línea de tiempo y 5 hitos con íconos: 1524-1821 "Colonia española en Guatemala" (ícono de iglesia colonial); 1789 "Revolución Francesa" (bastilla estilizada); 1996 "Firma del Acuerdo de Paz Firme y Duradera" (paloma); 1998 "Informe REMHI: Guatemala, Nunca Más" (libro); 1999 "Informe CEH: Memoria del Silencio" (libro con lupa). Colores sobrios, tipografía clara, sin imágenes de violencia.',
      },
      steps: [
        S.explain(
          { fase: 'explorar', areas: ['ccss', 'fc'], cnb: ['ccss:6.4.5'], ambito: 'conocer', title: 'Antes y durante el dominio europeo',
            prompt: 'Con la conquista europea de América, en el siglo XVI, la **estructura social y económica** cambió profundamente para los pueblos indígenas. Toca cada tarjeta.' },
          { icon: 'Scale', body: 'La Colonia creó una sociedad dividida por **origen**. Los pueblos indígenas quedaron en la base, obligados a sostener la economía colonial.', reveal: [
            { icon: 'Crown', front: 'Peninsulares', back: 'Nacidos en **España**. Ocupaban los cargos más altos del gobierno y la Iglesia.' },
            { icon: 'Home', front: 'Criollos', back: 'Hijos de españoles nacidos en **América**. Tenían tierras y comercio, pero menos cargos.' },
            { icon: 'Hammer', front: 'Mestizos', back: 'Hijos de europeos e indígenas. Trabajaban como artesanos, capataces o pequeños comerciantes.' },
            { icon: 'Sprout', front: 'Pueblos indígenas', back: 'Pagaban **tributo** y fueron sometidos a trabajo forzado (encomienda, repartimiento). Perdieron muchas tierras, pero **resistieron** y conservaron idiomas y costumbres.' },
            { icon: 'Link', front: 'Africanos esclavizados', back: 'Traídos a la fuerza para trabajar en haciendas e ingenios; no tenían libertad.' },
          ] },
        ),
        S.sort(
          { fase: 'construir', areas: ['ccss', 'fc'], cnb: ['ccss:6.4.5'],
            prompt: 'Compara la situación de los pueblos indígenas **antes** de la llegada europea y **durante la Colonia**.',
            explain: 'El dominio europeo cambió quién mandaba, quién era dueño de la tierra y a quién se pagaba tributo. También llegaron enfermedades como la viruela, que causaron muchísimas muertes.' },
          { buckets: [
            { id: 'antes', label: 'Antes (época prehispánica)', icon: 'Sun' },
            { id: 'colonia', label: 'Durante la Colonia', icon: 'Church' },
          ], items: [
            { id: 'c1', text: 'Autoridades propias gobernaban cada señorío', bucket: 'antes' },
            { id: 'c2', text: 'Las tierras se trabajaban según la organización de cada pueblo', bucket: 'antes' },
            { id: 'c3', text: 'Tributo obligatorio a la Corona española', bucket: 'colonia' },
            { id: 'c4', text: 'Trabajo forzado en haciendas por el repartimiento', bucket: 'colonia' },
            { id: 'c5', text: 'Epidemias de enfermedades traídas de Europa', bucket: 'colonia' },
            { id: 'c6', text: 'Ciudades como Q\'umarkaj e Iximche\' como centros de poder', bucket: 'antes', feedback: 'Eran capitales de los señoríos k\'iche\' y kaqchikel antes de la conquista.' },
          ] },
        ),
        S.order(
          { fase: 'construir', areas: ['ccss', 'l1'], cnb: ['ccss:6.4.7'], ambito: 'conocer',
            prompt: 'En Francia, en 1789, el pueblo cambió la forma de gobierno. Esquematiza las **etapas que condujeron a la Revolución Francesa** en orden.',
            hint: 'Primero surgen las ideas y los problemas; después las reuniones; al final, la declaración de derechos.',
            explain: 'Las ideas de la Ilustración (igualdad, división de poderes) y la crisis del pan y los impuestos llevaron al pueblo a exigir cambios. La Declaración de los Derechos del Hombre y del Ciudadano (agosto de 1789) inspiró luego a muchos pueblos de América.',
            media: { id: 's15-d3-bastilla', kind: 'animation', title: 'Francia, 1789: paso a paso', aspect: '16:9', duration: 60,
              alt: 'Animación con seis escenas: libros de la Ilustración, una panadería con precios altos, la reunión de los Estados Generales, el juramento de la Asamblea Nacional, una fortaleza con banderas y un pergamino de derechos.',
              brief: 'Animación 2D de 60 s, estilo recortes de papel. Escenas: (1) libros abiertos con palabras "igualdad", "libertad", "división de poderes"; (2) panadería con pan caro y campesinos pagando impuestos; (3) Estados Generales en Versalles, mayo de 1789; (4) juramento de la Asamblea Nacional, junio de 1789; (5) toma de la Bastilla, 14 de julio de 1789, sin mostrar heridos; (6) pergamino "Declaración de los Derechos del Hombre y del Ciudadano", agosto de 1789. Rótulo de fecha en cada escena, narración en español.' } },
          { items: [
            { id: 'e1', text: 'Se difunden las ideas de la Ilustración' },
            { id: 'e2', text: 'Crisis económica: deudas del rey, malas cosechas y pan caro' },
            { id: 'e3', text: 'El rey convoca a los Estados Generales (mayo de 1789)' },
            { id: 'e4', text: 'El Tercer Estado se proclama Asamblea Nacional (junio de 1789)' },
            { id: 'e5', text: 'Toma de la Bastilla (14 de julio de 1789)' },
            { id: 'e6', text: 'Declaración de los Derechos del Hombre y del Ciudadano (agosto de 1789)' },
          ], labels: { start: 'Primero', end: 'Después' } },
        ),
        S.reading(
          { fase: 'construir', areas: ['fc', 'ccss', 'l1'], cnb: ['fc:4.5.1', 'l1:5.1.2', 'l1:5.1.3'], ambito: 'conocer',
            prompt: 'Lee este texto informativo. Fíjate en cómo está organizado: **introducción, desarrollo y conclusión**.' },
          { genre: 'Texto informativo', heading: 'Dos informes para no olvidar', passage:
            'Entre 1960 y 1996, Guatemala vivió un **conflicto armado interno** que causó mucho dolor, sobre todo en comunidades indígenas del área rural. Cuando llegó la paz, el país necesitaba conocer la verdad de lo ocurrido.\n\nEl primer esfuerzo fue el proyecto **REMHI** (Recuperación de la Memoria Histórica), de la Oficina de Derechos Humanos del Arzobispado de Guatemala. Escuchó miles de testimonios y en abril de 1998 presentó el informe **"Guatemala: Nunca Más"**. Por ejemplo, recogió relatos de familias que buscaban a sus seres queridos desaparecidos.\n\nEl segundo fue el de la **Comisión para el Esclarecimiento Histórico (CEH)**, creada en 1994 dentro del proceso de paz y apoyada por las Naciones Unidas. En febrero de 1999 entregó el informe **"Guatemala: Memoria del Silencio"**. Sus recomendaciones pedían reparar a las víctimas, preservar la memoria, buscar a las personas desaparecidas, fortalecer la justicia y enseñar en las escuelas lo que pasó.\n\nEn conclusión, ambos informes buscan lo mismo: que la verdad se conozca, que las víctimas sean dignificadas y que **nunca más** se repita la violencia. Por eso, cada 25 de febrero se conmemora el Día Nacional de la Dignidad de las Víctimas del Conflicto Armado Interno.',
            questions: [
              { q: '¿Cuál es el propósito común de los informes REMHI y CEH?', options: [
                { id: 'a', text: 'Conocer la verdad, dignificar a las víctimas y evitar que la violencia se repita' },
                { id: 'b', text: 'Contar cuentos sobre Guatemala' },
                { id: 'c', text: 'Elegir a las autoridades del país' },
              ], correct: 'a' },
              { q: '¿Qué función cumple el segundo párrafo, que dice "Por ejemplo, recogió relatos…"?', options: [
                { id: 'a', text: 'Es un párrafo de desarrollo que explica y ejemplifica' },
                { id: 'b', text: 'Es la conclusión del texto' },
                { id: 'c', text: 'Es el título' },
              ], correct: 'a', why: 'Desarrolla la información y la aclara con un ejemplo: es ejemplificador.' },
              { q: 'Según el texto, ¿cuál fue una recomendación de la CEH?', options: [
                { id: 'a', text: 'Enseñar en las escuelas lo que pasó' },
                { id: 'b', text: 'Olvidar el pasado' },
                { id: 'c', text: 'Cerrar las escuelas rurales' },
              ], correct: 'a' },
              { q: '¿Por qué crees que es importante que niñas y niños conozcan estos informes?', options: [
                { id: 'a', text: 'Porque conocer la verdad ayuda a construir paz y a respetar los derechos de todas las personas' },
                { id: 'b', text: 'Porque así se puede culpar a cualquier persona' },
                { id: 'c', text: 'No es importante' },
              ], correct: 'a', why: 'La memoria sirve para aprender y proteger los derechos humanos, no para odiar.' },
            ] },
        ),
        S.match(
          { fase: 'construir', areas: ['l1'], cnb: ['l1:5.1.2', 'l1:5.1.4'],
            prompt: 'Une cada **tipo de párrafo** con lo que hace dentro de un texto.',
            explain: 'Un buen texto combina párrafos: uno presenta la idea, otros la explican con ejemplos y el último la cierra.' },
          { leftTitle: 'Tipo de párrafo', rightTitle: '¿Qué hace?', pairs: [
            { id: 'pri', left: 'Párrafo principal', leftIcon: 'Flag', right: 'Presenta la idea central del texto' },
            { id: 'eje', left: 'Párrafo ejemplificador', leftIcon: 'Lightbulb', right: 'Aclara la idea con casos concretos' },
            { id: 'con', left: 'Párrafo concluyente', leftIcon: 'Check', right: 'Resume y cierra el texto' },
          ] },
        ),
        S.highlight(
          { fase: 'construir', areas: ['l1', 'fc'], cnb: ['l1:5.2.1'], ambito: 'conocer',
            prompt: 'La **semántica** es el nivel de la lengua que estudia el **significado** de las palabras. Marca las palabras que en este texto significan lo mismo que **"recordar"** (sinónimos).',
            explain: 'Rememorar, evocar y conmemorar tienen un significado cercano a recordar (conmemorar es recordar en público, con un acto especial). "Olvidar" es su antónimo: significa lo contrario.' },
          { target: 'sinónimos de recordar', text: 'Las familias quieren {rememorar} a sus seres queridos. En la escuela aprendemos a {evocar} el pasado con respeto. Nadie quiere olvidar la verdad; por eso es valioso {conmemorar} cada 25 de febrero.' },
        ),
        S.write(
          { fase: 'aplicar', areas: ['l1', 'fc', 'ccss'], cnb: ['l1:5.1.3', 'l1:5.1.4', 'fc:4.5.1'], ambito: 'convivir',
            prompt: 'La comisión de cultura preparará un cartel para el 25 de febrero. Escribe un texto de **tres párrafos**: (1) **introducción** con la idea principal, (2) **desarrollo** con un ejemplo, (3) **conclusión**. Tema: "¿Por qué es importante recordar la verdad?"' },
          { minWords: 60, placeholder: 'Introducción: …\n\nDesarrollo: …\n\nConclusión: …',
            model: 'Recordar la verdad es importante porque nos ayuda a vivir en paz.\n\nPor ejemplo, los informes REMHI y CEH escucharon a miles de personas que sufrieron durante el conflicto armado. Gracias a ellos, sus historias no se perdieron y sus familias pueden ser escuchadas y reparadas.\n\nEn conclusión, cuando conocemos lo que pasó, aprendemos a respetar los derechos humanos y a decir "nunca más" a la violencia.',
            rubric: ['Tiene tres párrafos: introducción, desarrollo y conclusión', 'El segundo párrafo incluye un ejemplo', 'Menciona al menos uno de los informes (REMHI o CEH)', 'Usa un lenguaje respetuoso'] },
        ),
        S.order(
          { fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:6.4.7'], prompt: 'Boleto de salida: ordena estos hechos de la Revolución Francesa.' },
          { items: [
            { id: 'r1', text: 'Crisis económica y pan caro' },
            { id: 'r2', text: 'Reunión de los Estados Generales' },
            { id: 'r3', text: 'Toma de la Bastilla' },
            { id: 'r4', text: 'Declaración de los Derechos del Hombre y del Ciudadano' },
          ], labels: { start: 'Primero', end: 'Último' } },
        ),
        S.tf(
          { fase: 'comprobar', areas: ['fc', 'ccss', 'l1'], cnb: ['fc:4.5.1', 'ccss:6.4.5', 'l1:5.1.3'], prompt: '¿Verdadero o falso?' },
          { statements: [
            { text: 'El informe de la CEH se llama "Guatemala: Memoria del Silencio".', answer: true },
            { text: 'Durante la Colonia, los pueblos indígenas no pagaban ningún tributo.', answer: false, why: 'Estaban obligados a pagar tributo a la Corona y a trabajar de forma forzada.' },
            { text: 'Un texto bien organizado tiene introducción, desarrollo y conclusión.', answer: true },
            { text: 'El informe REMHI se tituló "Guatemala: Nunca Más".', answer: true },
          ] },
        ),
        cierre({ areas: ['fc', 'ccss'], cnb: ['fc:4.5.1'] }, ['Comparo la vida indígena antes y durante la Colonia', 'Ordeno las etapas de la Revolución Francesa', 'Explico para qué sirven los informes REMHI y CEH'],
          ['Conversaré con una persona mayor de mi familia sobre la paz', 'Escribiré mis textos con introducción, desarrollo y conclusión', 'Trataré con respeto los temas dolorosos de la historia']),
      ],
    }),

    /* ───────────────────────── Día 4 ───────────────────────── */
    lesson({
      id: 's15-d4-gobierno-escolar',
      title: 'Nos organizamos: gobierno escolar en acción',
      icon: 'Vote',
      minutes: 15,
      day: 4,
      gancho: 'Si tu grado pudiera cambiar una cosa de la escuela, ¿cuál sería y cómo se organizarían para lograrlo?',
      objetivos: ['Valorar el gobierno escolar y estructurar un proyecto sencillo para la escuela', 'Calcular raíces cuadradas exactas', 'Practicar bote, recepción y tiro a gol', 'Aplicar las reglas de acentuación y separar sílabas'],
      resumen: [
        'El gobierno escolar es elegido por las y los estudiantes; organiza comisiones y propone mejoras para toda la escuela.',
        'Un proyecto tiene nombre, necesidad, objetivo, actividades, recursos, responsables y tiempo.',
        'La raíz cuadrada de un número es el número que multiplicado por sí mismo da ese número: √144 = 12 porque 12 × 12 = 144.',
        'Las agudas llevan tilde si terminan en n, s o vocal; las graves, si no terminan en n, s o vocal; las esdrújulas siempre.',
      ],
      media: {
        id: 's15-d4-asamblea', kind: 'image', title: 'Asamblea del gobierno escolar', aspect: '16:9',
        alt: 'Estudiantes sentados en círculo en un patio escolar; una niña dirige la asamblea y un niño anota en un cartel las propuestas.',
        brief: 'Ilustración cálida de un patio de escuela pública con estudiantes de sexto en círculo. Una presidenta del gobierno escolar con güipil dirige; un secretario anota en un papelógrafo "Propuestas: 1. Huerto escolar 2. Torneo deportivo 3. Grupo de danza". Al fondo, mural con la palabra "Participamos". Diversidad de pueblos y géneros, sin logos.',
      },
      steps: [
        S.dilemma(
          { fase: 'explorar', areas: ['fc', 'l2'], cnb: ['fc:3.2.3'], ambito: 'convivir',
            prompt: 'El gobierno escolar va a decidir en qué usar el dinero de la feria. ¿Qué harías si fueras la presidenta o el presidente?' },
          { scene: { icon: 'Vote', text: 'La feria reunió fondos. Unos compañeros quieren una fiesta; otros, reparar los lavamanos; otros, comprar pelotas. Tú diriges el gobierno escolar.' }, options: [
            { id: 'a', icon: 'Crown', text: 'Decidir yo solo porque para eso me eligieron', consequence: 'Muchos se sienten ignorados y dejan de participar en las siguientes actividades.', values: ['Autoritarismo'], constructive: false },
            { id: 'b', icon: 'Users', text: 'Hacer una asamblea, escuchar razones y votar', consequence: 'La mayoría vota por reparar los lavamanos y hacer un torneo. Todos sienten que su voz cuenta.', values: ['Democracia', 'Participación', 'Respeto'], constructive: true },
            { id: 'c', icon: 'ClipboardList', text: 'Pedir a cada comisión una propuesta escrita con costos', consequence: 'Las propuestas son más claras y la decisión se toma con información.', values: ['Responsabilidad', 'Transparencia'], constructive: true },
          ] },
        ),
        S.order(
          { fase: 'construir', areas: ['pyd', 'fc'], cnb: ['pyd:4.1.2'], ambito: 'emprender',
            prompt: 'La comisión de ambiente quiere un **huerto escolar**. Ordena la **estructura básica** de su proyecto.',
            explain: 'Todo proyecto parte de una necesidad real, se propone un objetivo y luego se planifica qué hacer, con qué, quién y cuándo.' },
          { items: [
            { id: 'n1', text: 'Nombre: "Huerto que nutre"' },
            { id: 'n2', text: 'Necesidad: la refacción tiene pocas verduras' },
            { id: 'n3', text: 'Objetivo: cosechar hierbas y verduras para la refacción' },
            { id: 'n4', text: 'Actividades: preparar el suelo, sembrar, regar y cosechar' },
            { id: 'n5', text: 'Recursos y responsables: semillas, herramientas y turnos por grado' },
            { id: 'n6', text: 'Tiempo y evaluación: tres meses; contar lo cosechado' },
          ], labels: { start: 'Inicio', end: 'Final' } },
        ),
        S.choice(
          { fase: 'construir', areas: ['pyd', 'cnt'], cnb: ['pyd:3.1.1'], ambito: 'emprender',
            prompt: 'La investigación científica crea **tecnologías** que ayudan a las comunidades. ¿Cuáles podrían servir al huerto y a la cocina escolar? Elige **todas** las que apliquen.',
            explain: 'El riego por goteo ahorra agua; la estufa mejorada usa menos leña y saca el humo por una chimenea; el filtro de arena y carbón limpia el agua. Todas nacieron de investigar y probar.',
            media: { id: 's15-d4-tecnologias', kind: 'image', title: 'Tecnologías para la comunidad', aspect: '4:3',
              alt: 'Tres dibujos: manguera de riego por goteo en un huerto, estufa mejorada con chimenea y un filtro de agua casero en capas.',
              brief: 'Lámina en tres paneles con estilo de cuaderno de ciencias: (1) huerto escolar con manguera perforada que deja caer gotas junto a cada planta, rótulo "Riego por goteo: ahorra agua"; (2) cocina rural con estufa mejorada de ladrillo y chimenea, rótulo "Menos leña, menos humo"; (3) botella cortada con capas de piedrín, arena y carbón, rótulo "Filtro de agua". Flechas y notas a mano.' } },
          { multiple: true, options: [
            { id: 'a', text: 'Riego por goteo', icon: 'Droplets' },
            { id: 'b', text: 'Estufa mejorada con chimenea', icon: 'Flame' },
            { id: 'c', text: 'Filtro de agua con arena y carbón', icon: 'FlaskConical' },
            { id: 'd', text: 'Quemar la basura del huerto', icon: 'Trash2', feedback: 'Quemar basura contamina el aire; mejor hacer abono (compost) con los restos.' },
          ], correct: ['a', 'b', 'c'] },
        ),
        S.explain(
          { fase: 'construir', areas: ['mat', 'art'], cnb: ['mat:4.2.6', 'art:3.1.4'], ambito: 'conocer', title: 'Formaciones cuadradas y raíz cuadrada',
            prompt: 'La comisión de cultura organiza un **grupo de danza** para la feria. Si los danzantes forman un **cuadrado** (mismas filas que columnas), ¿cuántos van por fila? Eso es la **raíz cuadrada**.' },
          { icon: 'Music', body: 'La **raíz cuadrada** (√) de un número es el número que, multiplicado **por sí mismo**, da ese número.', reveal: [
            { icon: 'Square', front: '√36', back: '**6**, porque 6 × 6 = 36: seis filas de seis danzantes.' },
            { icon: 'Square', front: '√144', back: '**12**, porque 12 × 12 = 144.' },
            { icon: 'Lightbulb', front: 'Truco', back: 'Aprende los cuadrados: 10² = 100, 20² = 400, 30² = 900. Así ubicas rápido la raíz de números hasta 1,000.' },
            { icon: 'Users', front: 'Organizar la danza', back: 'Elijan una danza de su región, repartan **roles** (coordinación, música, vestuario), acuerden días de **ensayo** y preparen una **demostración** para la feria.' },
          ] },
        ),
        S.number(
          { fase: 'aplicar', areas: ['mat', 'ef'], cnb: ['mat:4.2.6'], ambito: 'hacer',
            prompt: 'Para el torneo, el gobierno escolar pinta una cancha cuadrada de **625 m²**. ¿Cuánto mide **cada lado**?',
            hint: 'Busca el número que multiplicado por sí mismo da 625. Termina en 5…',
            explain: '√625 = 25 porque 25 × 25 = 625. Cada lado mide 25 m.' },
          { answer: 25, unit: 'm', misconceptions: [{ value: 312.5, msg: 'Dividiste 625 entre 2. La raíz cuadrada no es la mitad: busca un número que multiplicado por sí mismo dé 625.' }, { value: 156.25, msg: 'Dividiste entre 4 (como si fuera el perímetro). Aquí 625 es el área.' }] },
        ),
        S.pulse(
          { fase: 'aplicar', areas: ['ef'], cnb: ['ef:2.1.10', 'ef:2.1.14', 'ef:2.1.19'], ambito: 'hacer',
            prompt: '¡Entrenamiento del torneo! Con una pelota (o una bola de papel y cinta): **bota** el balón quieto, caminando y cambiando de dirección; **recibe** con las dos manos a altura alta, media y rodada (para la rodada, flexiona las rodillas y junta las manos abajo, con los dedos hacia el suelo); y **patea** a una portería hecha con dos mochilas, desde cerca y desde lejos, con el borde interno y el empeine. Mide tu pulso antes y después.' },
          { seconds: 15, rounds: [
            { label: 'En reposo' },
            { label: 'Después del circuito de bote y recepción', exercise: { name: 'Bote con cambio de dirección + recepciones alta, media y rodada', icon: 'CircleDot', seconds: 60 } },
            { label: 'Después de los tiros a gol', exercise: { name: 'Tiros a gol con distintas partes del pie', icon: 'Footprints', seconds: 45 } },
          ] },
        ),
        S.sort(
          { fase: 'aplicar', areas: ['l2', 'fc'], cnb: ['l2:4.1.5', 'l2:4.1.7'], ambito: 'conocer',
            prompt: 'Separa en sílabas en voz alta y clasifica cada palabra del cartel de la asamblea según **dónde cae la fuerza** de voz. Fíjate en la tilde.',
            hint: 'Di la palabra despacio, sílaba por sílaba: vo-ta-ción. ¿Cuál suena más fuerte?',
            explain: 'vo-ta-**ción** y co-mi-**sión** son agudas terminadas en n: llevan tilde. a-sam-**ble**-a es grave terminada en vocal: sin tilde. **prác**-ti-ca y **mú**-si-ca son esdrújulas: siempre llevan tilde. ár-bol es grave terminada en l: lleva tilde.' },
          { buckets: [
            { id: 'aguda', label: 'Aguda (última sílaba)', icon: 'Target' },
            { id: 'grave', label: 'Grave (penúltima)', icon: 'Minus' },
            { id: 'esdr', label: 'Esdrújula (antepenúltima)', icon: 'Star' },
          ], items: [
            { id: 'w1', text: 'vo-ta-ción', bucket: 'aguda' },
            { id: 'w2', text: 'co-mi-sión', bucket: 'aguda' },
            { id: 'w3', text: 'a-sam-ble-a', bucket: 'grave' },
            { id: 'w4', text: 'ár-bol', bucket: 'grave', feedback: 'Suena ÁR-bol: fuerza en la penúltima. Es grave y lleva tilde porque termina en l.' },
            { id: 'w5', text: 'prác-ti-ca', bucket: 'esdr' },
            { id: 'w6', text: 'mú-si-ca', bucket: 'esdr' },
          ] },
        ),
        S.number(
          { fase: 'comprobar', areas: ['mat'], cnb: ['mat:4.2.6'], prompt: 'Boleto de salida: calcula **√400**.' },
          { answer: 20, misconceptions: [{ value: 200, msg: 'Dividiste entre 2. Busca el número que por sí mismo da 400.' }] },
        ),
        S.choice(
          { fase: 'comprobar', areas: ['pyd', 'fc'], cnb: ['pyd:4.1.2'], prompt: 'En la estructura de un proyecto, "Cosechar hierbas y verduras para la refacción" es…' },
          { options: [
            { id: 'a', text: 'El objetivo', icon: 'Target' },
            { id: 'b', text: 'Un recurso', icon: 'Package', feedback: 'Los recursos son materiales: semillas, herramientas, agua.' },
            { id: 'c', text: 'El responsable', icon: 'User', feedback: 'El responsable es una persona o comisión.' },
          ], correct: ['a'] },
        ),
        cierre({ areas: ['fc', 'pyd', 'ef'], cnb: ['fc:3.2.3'] }, ['Valoro al gobierno escolar como forma de participar', 'Estructuro un proyecto con sus partes', 'Calculo raíces cuadradas exactas', 'Boto, recibo y pateo con control'],
          ['Propondré una idea al gobierno escolar de mi escuela', 'Participaré en una comisión o en el grupo de danza', 'Practicaré el bote con mi mano no dominante']),
      ],
    }),

    /* ───────────────────────── Día 5: Reto semanal ───────────────────────── */
    lesson({
      id: 's15-d5-reto',
      title: 'Reto de la semana 15',
      icon: 'Trophy',
      minutes: 14,
      day: 5,
      kind: 'reto',
      objetivos: ['Demostrar lo que aprendiste esta semana', 'Obtener la medalla "Guardián de la memoria" (70 % o más)'],
      resumen: ['Superé el reto de la semana 15: nutrientes, historia de los pueblos, memoria y organización escolar.'],
      media: {
        id: 's15-d5-reto', kind: 'image', title: 'Medalla Guardián de la memoria', aspect: '1:1',
        alt: 'Medalla dorada con un libro abierto, una mazorca y una paloma.',
        brief: 'Ilustración de medalla circular dorada: al centro un libro abierto del que brota una mazorca de maíz; arriba una paloma de la paz. Cinta con franjas de los colores de las áreas del CNB. Fondo transparente, 1024×1024, estilo plano con brillo suave.',
      },
      steps: [
        S.match({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:5.1.2'], prompt: 'Une cada nutriente con su función.' },
          { pairs: [
            { id: 'p', left: 'Proteínas', right: 'Construyen y reparan tejidos' },
            { id: 'c', left: 'Carbohidratos', right: 'Dan energía rápida' },
            { id: 'm', left: 'Minerales como el calcio', right: 'Forman huesos y dientes' },
          ] }),
        S.choice({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:5.2.2'], prompt: '¿Qué componente de la leche materna defiende al bebé de infecciones?' },
          { options: [{ id: 'a', text: 'Los anticuerpos' }, { id: 'b', text: 'El agua' }, { id: 'c', text: 'La lactosa' }], correct: ['a'] }),
        S.sort({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:5.3.2'], prompt: '¿Qué favorece más cada alimento?' },
          { buckets: [{ id: 't', label: 'Crecer en talla', icon: 'Ruler' }, { id: 'e', label: 'Energía', icon: 'Zap' }],
            items: [{ id: 'a', text: 'Huevo', bucket: 't' }, { id: 'b', text: 'Tortilla', bucket: 'e' }, { id: 'c', text: 'Leche', bucket: 't' }, { id: 'd', text: 'Arroz', bucket: 'e' }] }),
        S.number({ fase: 'comprobar', areas: ['mat'], cnb: ['mat:4.3.1'], prompt: '¿Cuántos divisores tiene el número **18**? Escribe solo la cantidad.' },
          { answer: 6, stimulus: '18', misconceptions: [{ value: 4, msg: 'Recuerda incluir el 1 y el 18: 1, 2, 3, 6, 9, 18.' }] }),
        S.number({ fase: 'comprobar', areas: ['mat'], cnb: ['mat:4.2.6'], prompt: 'Calcula **√169**.' },
          { answer: 13 }),
        S.maya({ fase: 'comprobar', areas: ['mat'], cnb: ['mat:4.2.8'], prompt: 'Multiplica **30 × 6** y construye el resultado en numeración maya.' },
          { mode: 'build', target: 180, levels: 2 }),
        S.match({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:6.1.2', 'ccss:6.3.2'], prompt: 'Une cada ciencia o pueblo con lo que le corresponde.' },
          { pairs: [
            { id: 'ep', left: 'Epigrafía', right: 'Lee inscripciones en piedra' },
            { id: 'nu', left: 'Numismática', right: 'Estudia monedas antiguas' },
            { id: 'gr', left: 'Grecia', right: 'Democracia en Atenas' },
            { id: 'ma', left: 'Mayas', right: 'Uso del cero' },
          ] }),
        S.order({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:6.4.7'], prompt: 'Ordena las etapas hacia la Revolución Francesa.' },
          { items: [{ id: 'a', text: 'Ideas de la Ilustración' }, { id: 'b', text: 'Estados Generales' }, { id: 'c', text: 'Asamblea Nacional' }, { id: 'd', text: 'Toma de la Bastilla' }], labels: { start: 'Primero', end: 'Último' } }),
        S.tf({ fase: 'comprobar', areas: ['fc', 'ccss', 'pyd'], cnb: ['fc:4.5.1', 'ccss:6.4.5', 'fc:3.2.3', 'pyd:4.1.2'], prompt: '¿Verdadero o falso?' },
          { statements: [
            { text: 'La CEH fue creada dentro del proceso de paz con apoyo de las Naciones Unidas.', answer: true },
            { text: 'En la Colonia, los peninsulares ocupaban los cargos más altos.', answer: true },
            { text: 'El gobierno escolar se nombra sin votación.', answer: false },
            { text: 'Un proyecto no necesita objetivo.', answer: false },
          ] }),
        S.fill({ fase: 'comprobar', areas: ['l2', 'l1', 'l3'], cnb: ['l2:4.1.5', 'l1:5.1.2', 'l3:4.3.1'], prompt: 'Completa.' },
          { text: '"Canción" lleva tilde porque es [[aguda]] y termina en n.\nEl párrafo que cierra un texto es el [[concluyente]].\nWhat [[did]] you eat yesterday?', distractors: ['esdrújula', 'ejemplificador', 'will'] }),
      ],
    }),
  ],

  /* Banco de ítems para la Semana de validación de la Unidad 2 */
  bank: [
    S.choice({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:5.1.2'], prompt: '¿Qué nutriente abunda en el aguacate y la pepitoria?' },
      { options: [{ id: 'a', text: 'Grasas' }, { id: 'b', text: 'Vitamina C' }, { id: 'c', text: 'Agua' }], correct: ['a'] }),
    S.tf({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:5.2.2', 'cnt:5.3.2'], prompt: '¿Verdadero o falso?' },
      { statements: [{ text: 'El calostro es la primera leche materna y es rico en defensas.', answer: true }, { text: 'Los carbohidratos son los principales responsables de crecer en talla.', answer: false }] }),
    S.choice({ fase: 'comprobar', areas: ['mat'], cnb: ['mat:4.3.1'], prompt: '¿Cuál de estos números **no** es divisor de 30?' },
      { options: [{ id: 'a', text: '4' }, { id: 'b', text: '5' }, { id: 'c', text: '6' }, { id: 'd', text: '15' }], correct: ['a'] }),
    S.number({ fase: 'comprobar', areas: ['mat'], cnb: ['mat:4.2.6'], prompt: 'Un huerto cuadrado mide **81 m²**. ¿Cuántos metros mide cada lado?' },
      { answer: 9, unit: 'm' }),
    S.maya({ fase: 'comprobar', areas: ['mat'], cnb: ['mat:4.2.8'], prompt: 'Multiplica **35 × 8** y construye el resultado en numeración maya.' },
      { mode: 'build', target: 280, levels: 2 }),
    S.choice({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:6.1.2'], prompt: 'Una especialista descifra un documento colonial escrito a mano. ¿Qué ciencia auxiliar usa?' },
      { options: [{ id: 'a', text: 'Paleografía' }, { id: 'b', text: 'Numismática' }, { id: 'c', text: 'Genealogía' }], correct: ['a'] }),
    S.choice({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:6.4.5', 'ccss:6.2.2'], prompt: '¿Qué grupo sostenía con tributo y trabajo forzado la economía colonial?' },
      { options: [{ id: 'a', text: 'Los pueblos indígenas' }, { id: 'b', text: 'Los peninsulares' }, { id: 'c', text: 'Los criollos' }], correct: ['a'] }),
    S.choice({ fase: 'comprobar', areas: ['fc'], cnb: ['fc:4.5.1'], prompt: '¿Cuál fue uno de los propósitos de los informes REMHI y CEH?' },
      { options: [{ id: 'a', text: 'Esclarecer la verdad y recomendar medidas para que la violencia no se repita' }, { id: 'b', text: 'Organizar elecciones' }, { id: 'c', text: 'Promover el turismo' }], correct: ['a'] }),
    S.sort({ fase: 'comprobar', areas: ['l2'], cnb: ['l2:4.1.5', 'l2:4.1.7'], prompt: '¿Lleva tilde o no?' },
      { buckets: [{ id: 'si', label: 'Con tilde', icon: 'Check' }, { id: 'no', label: 'Sin tilde', icon: 'X' }],
        items: [{ id: 'a', text: 'lá-piz', bucket: 'si' }, { id: 'b', text: 'ca-mión', bucket: 'si' }, { id: 'c', text: 'ven-ta-na', bucket: 'no' }, { id: 'd', text: 'pa-red', bucket: 'no' }] }),
    S.choice({ fase: 'comprobar', areas: ['l1'], cnb: ['l1:5.2.1'], prompt: 'La **semántica** estudia…' },
      { options: [{ id: 'a', text: 'El significado de las palabras' }, { id: 'b', text: 'Los sonidos de las letras' }, { id: 'c', text: 'La forma de las letras' }], correct: ['a'] }),
    S.fill({ fase: 'comprobar', areas: ['l3'], cnb: ['l3:4.1.4', 'l3:4.3.1'], prompt: 'Complete in English.' },
      { text: 'An orange is [[smaller]] than a watermelon.\nWe [[are]] dancing at the school fair now.', distractors: ['small', 'is'] }),
    S.choice({ fase: 'comprobar', areas: ['ef'], cnb: ['ef:2.1.14'], prompt: 'Para recibir una pelota **rodada** con las dos manos, ¿qué es lo más seguro?' },
      { options: [{ id: 'a', text: 'Agacharse flexionando las rodillas y poner las manos juntas abajo' }, { id: 'b', text: 'Esperarla de pie con las piernas rectas' }, { id: 'c', text: 'Recibirla con una sola mano detrás de la espalda' }], correct: ['a'] }),
  ],
});
