import { S, cierre, lesson, semana } from '../../dsl';

/**
 * SEMANA 18 · Unidad 2 "Consolidando nuestras relaciones"
 * Tema generador: El aire que compartimos
 * Contaminación del aire, efecto invernadero y calentamiento global · el método científico ·
 * fuentes de información e informes · pobreza, trabajo digno y pueblos indígenas en la historia ·
 * fracciones (simplificación y operaciones combinadas) · barriletes gigantes, negociación y desarrollo sostenible.
 */
export default semana({
  id: 's18',
  unidad: 2,
  semana: 18,
  kind: 'aprendizaje',
  temaGenerador: 'El aire que compartimos',
  title: 'El aire que compartimos',
  subtitle: 'Clima, ciencia, sociedad justa y barriletes de la tradición',
  icon: 'Wind',
  color: 'var(--area-cnt)',
  contexto: 'Cada 1 de noviembre, en Sumpango y Santiago Sacatepéquez, se elevan barriletes de papel de china que llevan mensajes al cielo. Esos barriletes necesitan viento, y el viento es el mismo aire que respiramos todos. Esta semana investigarás como científico por qué el planeta se calienta, usarás las ciencias sociales para entender la pobreza y el trabajo digno, y aprenderás a dialogar para que el aire, la tierra y la tradición sean de todos.',
  ejes: ['sostenible', 'multiculturalidad', 'equidad', 'trabajo'],
  media: {
    id: 's18-portada', kind: 'video', title: 'Barriletes que tocan el cielo', aspect: '16:9', duration: 60,
    alt: 'Un campo lleno de barriletes gigantes de colores; niñas y niños vuelan barriletes pequeños mientras el viento mueve las colas de papel.',
    brief: 'Video de 60 s (o animación 2D) en un campo del altiplano central el 1 de noviembre. (1) Primer plano de manos que pegan papel de china sobre varas de bambú. (2) Barriletes gigantes circulares, de muchos colores, levantados con cuerdas por grupos de jóvenes (sin logos ni mensajes políticos). (3) Niñas y niños corren con barriletes pequeños; se ven las colas moviéndose con el viento. (4) Cierre con cielo azul y texto: "El aire que compartimos". Música de marimba. Sin rostros reales identificables en primer plano.',
  },
  badge: { id: 'medalla-s18', name: 'Guardián del aire', icon: 'Wind', desc: 'Completaste la semana 18 y superaste su reto' },
  lessons: [
    /* ───────────────────────── Día 1 ───────────────────────── */
    lesson({
      id: 's18-d1-planeta-fiebre',
      title: 'Un planeta con fiebre',
      icon: 'Thermometer',
      minutes: 14,
      day: 1,
      gancho: '¿Has notado que algunos años llueve muchísimo y otros casi nada? ¿Qué le pasa al clima?',
      objetivos: ['Relacionar la contaminación del aire con el efecto invernadero, el calentamiento global y los desastres', 'Simplificar fracciones a su mínima expresión', 'Clasificar adjetivos descriptivos y no descriptivos'],
      resumen: [
        'El efecto invernadero es natural: algunos gases atrapan parte del calor del Sol y mantienen la Tierra habitable.',
        'La contaminación (quema de combustibles, incendios, basura quemada) aumenta esos gases, como el dióxido de carbono; la Tierra se calienta más: eso es el calentamiento global.',
        'El calentamiento global hace más intensas las sequías, las lluvias fuertes y los huracanes, y aumenta el riesgo de desastres.',
        'Para simplificar una fracción, divide numerador y denominador entre el mismo número (idealmente su MCD): 18/24 = 3/4. Los adjetivos descriptivos califican o cuentan (gris, dos, primer); los no descriptivos señalan o indican posesión o cantidad imprecisa (este, nuestro, algunos).',
      ],
      media: {
        id: 's18-d1-invernadero', kind: 'animation', title: '¿Cómo funciona el efecto invernadero?', aspect: '16:9', duration: 60,
        alt: 'Animación de la Tierra rodeada por una capa de gases: la luz del Sol entra, parte del calor sale y parte queda atrapada; al aumentar el humo, queda más calor.',
        brief: 'Animación 2D de 60 s. (1) Rayos amarillos del Sol llegan a la Tierra y la calientan. (2) La Tierra devuelve calor (flechas rojas onduladas); parte sale al espacio y parte rebota en una capa translúcida de gases, rotulada "gases de efecto invernadero (CO₂, metano)". (3) Comparación con un carro al sol con las ventanas cerradas. (4) Aparecen chimeneas, buses con humo e incendios: la capa se vuelve más gruesa, menos calor escapa y un termómetro sube. (5) Consecuencias: tierra agrietada por sequía, río desbordado, huracán. Narración en español, subtítulos.',
      },
      steps: [
        S.explain(
          { fase: 'explorar', areas: ['cnt', 'ccss'], cnb: ['cnt:7.3.2'], ambito: 'conocer', title: 'Una cobija de gases',
            prompt: 'La Tierra está rodeada de una capa de gases que funciona como una **cobija**: guarda parte del calor del Sol. Toca cada tarjeta.' },
          { icon: 'Thermometer', body: 'Sin efecto invernadero, la Tierra sería demasiado fría para vivir. El problema es cuando la cobija se vuelve **demasiado gruesa**.', reveal: [
            { icon: 'Sun', front: 'Efecto invernadero natural', back: 'Gases como el **dióxido de carbono** y el **vapor de agua** atrapan parte del calor y mantienen una temperatura adecuada para la vida.' },
            { icon: 'Factory', front: 'Contaminación del aire', back: 'Quemar gasolina, diésel, leña, basura y bosques libera **más dióxido de carbono** y otros gases.' },
            { icon: 'TrendingUp', front: 'Calentamiento global', back: 'Con más gases, se atrapa **más calor** y la temperatura promedio del planeta sube.' },
            { icon: 'CloudRain', front: 'Más desastres', back: 'Sequías más largas (como en el **Corredor Seco**), lluvias más fuertes, huracanes más intensos y deshielo de glaciares.' },
          ] },
        ),
        S.order(
          { fase: 'construir', areas: ['cnt'], cnb: ['cnt:7.3.2'], ambito: 'conocer',
            prompt: 'Ordena la **cadena de causa y efecto** que va de la contaminación del aire a los desastres.',
            explain: 'Cada eslabón causa el siguiente. Si reducimos la contaminación al inicio de la cadena, disminuye el riesgo al final.' },
          { items: [
            { id: 'k1', text: 'Se queman combustibles, basura y bosques' },
            { id: 'k2', text: 'Aumentan los gases de efecto invernadero en el aire' },
            { id: 'k3', text: 'Se atrapa más calor en la atmósfera' },
            { id: 'k4', text: 'Sube la temperatura promedio del planeta' },
            { id: 'k5', text: 'Sequías e inundaciones más intensas' },
          ], labels: { start: 'Causa', end: 'Efecto' } },
        ),
        S.sort(
          { fase: 'construir', areas: ['cnt', 'pyd'], cnb: ['cnt:7.3.2'], ambito: 'ser',
            prompt: '¿Esta acción **aumenta** o **reduce** los gases de efecto invernadero? Clasifica.',
            hint: 'Piensa si la acción quema algo o si ayuda a absorber dióxido de carbono.',
            explain: 'Los árboles absorben dióxido de carbono; el transporte público, la bicicleta y la energía solar evitan quemar combustibles.' },
          { buckets: [
            { id: 'sube', label: 'Aumenta los gases', icon: 'TrendingUp', color: 'var(--c-bad)' },
            { id: 'baja', label: 'Reduce los gases', icon: 'Leaf', color: 'var(--c-ok)' },
          ], items: [
            { id: 'a1', text: 'Quemar la basura', icon: 'Flame', bucket: 'sube' },
            { id: 'a2', text: 'Provocar incendios para limpiar terrenos', icon: 'Flame', bucket: 'sube' },
            { id: 'a3', text: 'Usar el carro para ir a la tienda de la esquina', icon: 'Car', bucket: 'sube' },
            { id: 'a4', text: 'Reforestar laderas', icon: 'TreePine', bucket: 'baja' },
            { id: 'a5', text: 'Ir a pie o en bicicleta', icon: 'Bike', bucket: 'baja' },
            { id: 'a6', text: 'Usar energía solar', icon: 'Sun', bucket: 'baja' },
          ] },
        ),
        S.explain(
          { fase: 'construir', areas: ['mat', 'cnt'], cnb: ['mat:4.4.1'], ambito: 'conocer', title: 'Fracciones más sencillas',
            prompt: '**Supongamos** que en una revisión de **24 buses**, **18** echaban humo negro. Eso es 18/24 de los buses. ¿Se puede decir de forma más sencilla?' },
          { icon: 'Slash', body: 'Para **simplificar**, divide el numerador y el denominador **entre el mismo número**. Si usas el **MCD**, llegas directo a la **mínima expresión**.', reveal: [
            { icon: 'Minus', front: 'Paso a paso', back: '18/24 → ÷2 → 9/12 → ÷3 → **3/4**.' },
            { icon: 'Zap', front: 'Directo con el MCD', back: 'MCD(18, 24) = 6. 18 ÷ 6 = 3 y 24 ÷ 6 = 4 → **3/4**.' },
            { icon: 'Check', front: '¿Cuándo termino?', back: 'Cuando numerador y denominador ya no tienen divisores comunes, salvo el 1. Entonces es **irreducible**.' },
          ] },
        ),
        S.slider(
          { fase: 'construir', areas: ['mat', 'cnt'], cnb: ['mat:4.4.1'], ambito: 'hacer',
            prompt: '**Supongamos** que en 16 días de observación, el aire de la ciudad estuvo contaminado **12 días**. Simplifica **12/16** y márcalo en la barra dividida en cuartos.',
            hint: 'MCD(12, 16) = 4.',
            explain: '12 ÷ 4 = 3 y 16 ÷ 4 = 4, así que 12/16 = 3/4: tres de cada cuatro días hubo aire contaminado.' },
          { min: 0, max: 1, step: 0.25, answer: 0.75, start: 0, visual: 'fraction', parts: 4, display: 'fraction' },
        ),
        S.sort(
          { fase: 'aplicar', areas: ['l2', 'cnt'], cnb: ['l2:5.1.3'], ambito: 'conocer',
            prompt: 'Los **adjetivos descriptivos** dicen cómo es algo (calificativos: _gris_) o cuántos/qué orden (numerales: _dos, primer_). Los **no descriptivos** señalan (demostrativos: _este_), indican de quién es (posesivos: _nuestro_) o una cantidad imprecisa (indefinidos: _algunos_). Clasifica el adjetivo **en negrita**.',
            explain: 'Calificativos y numerales (cardinales como "dos" y ordinales como "primer") describen. Posesivos, demostrativos e indefinidos no describen: determinan al sustantivo.' },
          { buckets: [
            { id: 'cal', label: 'Descriptivo calificativo', icon: 'Palette' },
            { id: 'num', label: 'Descriptivo numeral', icon: 'ListOrdered' },
            { id: 'nod', label: 'No descriptivo', icon: 'Signpost' },
          ], items: [
            { id: 'j1', text: 'humo **gris**', bucket: 'cal' },
            { id: 'j2', text: 'aire **caliente**', bucket: 'cal' },
            { id: 'j3', text: '**dos** volcanes', bucket: 'num' },
            { id: 'j4', text: '**primer** lugar', bucket: 'num', feedback: '"Primer" indica orden: es numeral ordinal.' },
            { id: 'j5', text: '**nuestro** planeta', bucket: 'nod' },
            { id: 'j6', text: '**esos** buses', bucket: 'nod' },
            { id: 'j7', text: '**algunos** árboles', bucket: 'nod' },
          ] },
        ),
        S.choice(
          { fase: 'aplicar', areas: ['cnt', 'ccss'], cnb: ['cnt:7.3.2'], ambito: 'conocer',
            prompt: 'En el **Corredor Seco** (oriente de Guatemala), muchas familias dependen de la lluvia para su milpa. Según lo que aprendiste, ¿qué riesgo aumenta con el calentamiento global?',
            explain: 'El calentamiento global hace más probables las sequías prolongadas, que dañan las cosechas y afectan la alimentación de las familias.' },
          { options: [
            { id: 'a', text: 'Sequías más largas que dañan las cosechas', icon: 'Sun' },
            { id: 'b', text: 'Que nunca vuelva a llover en el mundo', icon: 'CloudRain', feedback: 'Es una exageración: el clima se vuelve más extremo, no desaparece la lluvia.' },
            { id: 'c', text: 'Nevadas todos los días', icon: 'Snowflake', feedback: 'El calentamiento sube la temperatura; no provoca nevadas diarias.' },
          ], correct: ['a'] },
        ),
        S.choice(
          { fase: 'comprobar', areas: ['mat'], cnb: ['mat:4.4.1'], prompt: 'Boleto de salida: ¿cuál es la **mínima expresión** de 20/30?' },
          { options: [
            { id: 'a', text: '2/3' },
            { id: 'b', text: '10/15', feedback: 'Todavía se puede dividir entre 5.' },
            { id: 'c', text: '4/6', feedback: 'Todavía se puede dividir entre 2.' },
            { id: 'd', text: '1/2', feedback: '20/30 no es la mitad: 15/30 sería la mitad.' },
          ], correct: ['a'] },
        ),
        S.tf(
          { fase: 'comprobar', areas: ['cnt', 'l2'], cnb: ['cnt:7.3.2', 'l2:5.1.3'], prompt: '¿Verdadero o falso?' },
          { statements: [
            { text: 'El efecto invernadero natural ayuda a que la Tierra no sea demasiado fría.', answer: true },
            { text: 'Quemar basura reduce el calentamiento global.', answer: false, why: 'Quemar basura libera gases que aumentan el efecto invernadero.' },
            { text: 'El calentamiento global puede hacer más intensas las sequías y los huracanes.', answer: true },
            { text: 'En "nuestro barrilete", "nuestro" es un adjetivo posesivo.', answer: true },
          ] },
        ),
        cierre({ areas: ['cnt', 'mat'], cnb: ['cnt:7.3.2'] }, ['Explico cómo la contaminación del aire calienta el planeta', 'Relaciono el calentamiento global con los desastres', 'Simplifico fracciones a su mínima expresión'],
          ['No quemaré basura y lo explicaré en casa', 'Caminaré cuando el trayecto sea corto y seguro', 'Simplificaré las fracciones que encuentre en mis tareas']),
      ],
    }),

    /* ───────────────────────── Día 2 ───────────────────────── */
    lesson({
      id: 's18-d2-cientificos',
      title: 'Pensar como científicos',
      icon: 'FlaskConical',
      minutes: 15,
      day: 2,
      gancho: '¿Por qué algunos barriletes vuelan firmes y otros dan vueltas y caen? ¿Cómo lo averiguarías?',
      objetivos: ['Categorizar los momentos de la investigación científica', 'Explicar fenómenos naturales con conocimiento científico', 'Buscar información en fuentes adecuadas y elegir el tipo de informe', 'Sumar y restar fracciones con distinto denominador'],
      resumen: [
        'La investigación científica tiene grandes momentos: observación, hipótesis, experimentación y conclusión.',
        'La ciencia explica los fenómenos naturales con evidencias: el viento se forma por diferencias de temperatura y presión del aire; los sismos, por el movimiento de las placas.',
        'Cada fuente sirve para algo: diccionario (significados), enciclopedia (temas generales), atlas (mapas), periódico (noticias), hemeroteca (periódicos antiguos), manuales (instrucciones), libros especializados y sitios confiables de internet. Informes: el resumen o síntesis presenta las ideas principales; el técnico, el procedimiento y los resultados; el de contenido explica un tema investigado.',
        'Para sumar o restar fracciones con distinto denominador, busca un denominador común (el MCM) y luego opera los numeradores.',
      ],
      media: {
        id: 's18-d2-experimento', kind: 'video', title: 'El experimento de las colas', aspect: '16:9', duration: 75,
        alt: 'Un grupo de estudiantes prueba tres barriletes iguales con colas de distinto largo y anota los resultados en una tabla.',
        brief: 'Video de 75 s en un campo escolar. Rótulos en pantalla para cada momento: OBSERVACIÓN (un barrilete sin cola gira y cae), HIPÓTESIS (una niña escribe: "Si le ponemos cola más larga, volará más estable"), EXPERIMENTACIÓN (tres barriletes iguales con colas de 1, 2 y 3 m, mismo lugar y hora; un niño cronometra cuánto tiempo se mantiene cada uno), CONCLUSIÓN (tabla en un cartel y la frase del grupo). Narración infantil en español con subtítulos. Datos de la tabla marcados como "ejemplo".',
      },
      steps: [
        S.explain(
          { fase: 'explorar', areas: ['cnt', 'l1'], cnb: ['cnt:8.1.2'], ambito: 'conocer', title: 'Los momentos de una investigación',
            prompt: 'Los científicos no adivinan: **investigan**. Toca cada momento, siguiendo el ejemplo de un barrilete que no vuela bien.' },
          { icon: 'FlaskConical', body: 'Una buena investigación empieza con una pregunta y termina con una respuesta basada en **evidencias**.', reveal: [
            { icon: 'Eye', front: '1. Observación', back: 'Mirar con atención y hacer una pregunta: "Nuestro barrilete sin cola **gira y cae**. ¿Por qué?"' },
            { icon: 'Lightbulb', front: '2. Hipótesis', back: 'Una **posible respuesta** que se puede comprobar: "Si le ponemos una cola más larga, será más estable".' },
            { icon: 'Beaker', front: '3. Experimentación', back: 'Probar la hipótesis **cambiando una sola cosa** (el largo de la cola) y dejando igual lo demás. Medir y anotar.' },
            { icon: 'ClipboardCheck', front: '4. Conclusión', back: 'Decir si los **resultados** apoyan o no la hipótesis y compartirlo en un informe.' },
          ] },
        ),
        S.sort(
          { fase: 'construir', areas: ['cnt', 'mat'], cnb: ['cnt:8.1.2', 'cnt:8.2.2'], ambito: 'hacer',
            prompt: 'Categoriza cada frase del cuaderno del grupo según el **momento de la investigación**.',
            hint: 'Una hipótesis suele empezar con "Si…, entonces…". Una conclusión habla de los resultados.',
            explain: 'Observar lleva a una pregunta; la hipótesis propone una respuesta; el experimento la pone a prueba; la conclusión dice lo que se aprendió.' },
          { layout: 'grid2', buckets: [
            { id: 'obs', label: 'Observación', icon: 'Eye' },
            { id: 'hip', label: 'Hipótesis', icon: 'Lightbulb' },
            { id: 'exp', label: 'Experimentación', icon: 'Beaker' },
            { id: 'con', label: 'Conclusión', icon: 'ClipboardCheck' },
          ], items: [
            { id: 'f1', text: 'El barrilete sin cola da vueltas y se cae.', bucket: 'obs' },
            { id: 'f2', text: 'Si la cola es más larga, entonces el barrilete será más estable.', bucket: 'hip' },
            { id: 'f3', text: 'Probamos colas de 1, 2 y 3 m, en el mismo lugar y a la misma hora.', bucket: 'exp' },
            { id: 'f4', text: 'Medimos con un reloj cuántos segundos se mantuvo cada barrilete.', bucket: 'exp' },
            { id: 'f5', text: 'Los resultados apoyan la hipótesis: la cola larga dio más estabilidad.', bucket: 'con' },
          ] },
        ),
        S.match(
          { fase: 'construir', areas: ['cnt', 'ccss'], cnb: ['cnt:8.2.2'], ambito: 'conocer',
            prompt: 'La investigación científica permite **explicar los fenómenos naturales**. Une cada fenómeno con su explicación científica.',
            explain: 'Estas explicaciones se obtuvieron observando, midiendo y experimentando durante muchos años. Por eso nos ayudan a prevenir riesgos.',
            media: { id: 's18-d2-fenomenos', kind: 'diagram', title: 'La ciencia explica la naturaleza', aspect: '4:3',
              alt: 'Cuatro viñetas: aire caliente que sube y aire frío que llega (viento), placas que chocan (sismo), un rayo que calienta el aire (trueno), agua que se evapora y forma nubes (lluvia).',
              brief: 'Diagrama en cuatro viñetas con flechas y rótulos: (1) VIENTO: el suelo calienta el aire, que sube; aire más frío llega a ocupar su lugar. (2) SISMO: corte de la Tierra con dos placas que se empujan bajo Centroamérica. (3) TRUENO: un rayo calienta el aire de golpe y este se expande con un estruendo. (4) LLUVIA: el sol evapora el agua del lago, se forman nubes y cae la lluvia. Estilo de libro de ciencias, colores claros.' } },
          { leftTitle: 'Fenómeno', rightTitle: 'Explicación científica', pairs: [
            { id: 'vie', left: 'El viento', leftIcon: 'Wind', right: 'El aire se mueve por diferencias de temperatura y presión' },
            { id: 'sis', left: 'Los sismos', leftIcon: 'Activity', right: 'Movimiento y choque de las placas tectónicas' },
            { id: 'tru', left: 'El trueno', leftIcon: 'Zap', right: 'El rayo calienta el aire, que se expande de golpe' },
            { id: 'llu', left: 'La lluvia', leftIcon: 'CloudRain', right: 'El vapor de agua se enfría, forma nubes y cae' },
          ] },
        ),
        S.sort(
          { fase: 'construir', areas: ['l1', 'ccss'], cnb: ['l1:8.1.1', 'l1:8.1.2'], ambito: 'hacer',
            prompt: 'Para su informe, el grupo necesita información. ¿En qué **fuente** buscarías cada cosa?',
            hint: 'El atlas tiene mapas; la hemeroteca guarda periódicos y revistas antiguos.',
            explain: 'En las fuentes escritas y tecnológicas se usa el índice, el orden alfabético o las palabras clave para ubicar la información. En internet, prefiere sitios de instituciones, universidades o museos.' },
          { layout: 'grid2', buckets: [
            { id: 'dic', label: 'Diccionario', icon: 'BookOpen' },
            { id: 'atl', label: 'Atlas', icon: 'Map' },
            { id: 'hem', label: 'Hemeroteca', icon: 'Newspaper' },
            { id: 'enc', label: 'Enciclopedia o libro especializado', icon: 'Library' },
          ], items: [
            { id: 'q1', text: 'Qué significa la palabra "barlovento"', bucket: 'dic' },
            { id: 'q2', text: 'Dónde queda Sumpango en el mapa de Sacatepéquez', bucket: 'atl' },
            { id: 'q3', text: 'Una noticia de hace 30 años sobre el festival de barriletes', bucket: 'hem' },
            { id: 'q4', text: 'Cómo se forma el viento, explicado a fondo', bucket: 'enc' },
            { id: 'q5', text: 'Cómo se escribe correctamente "aerodinámica"', bucket: 'dic' },
            { id: 'q6', text: 'Las cordilleras y volcanes de Guatemala', bucket: 'atl' },
          ] },
        ),
        S.choice(
          { fase: 'construir', areas: ['l1', 'cnt'], cnb: ['l1:8.2.6'], ambito: 'hacer',
            prompt: 'Hay distintos **informes escritos**: el **resumen o síntesis** (ideas principales en pocas líneas), el **técnico** (objetivo, materiales, procedimiento, resultados y conclusión de un experimento) y el **de contenido** (explica un tema investigado). El grupo quiere contar **cómo hizo el experimento de las colas y qué resultados obtuvo**. ¿Qué informe le conviene?',
            explain: 'El informe técnico describe paso a paso lo que se hizo y presenta los datos medidos, para que otros puedan repetir el experimento.' },
          { options: [
            { id: 'a', text: 'Informe técnico', icon: 'Wrench' },
            { id: 'b', text: 'Resumen o síntesis', icon: 'FileText', feedback: 'Un resumen solo da las ideas principales; no detalla procedimiento ni datos.' },
            { id: 'c', text: 'Informe de contenido', icon: 'BookOpen', feedback: 'El de contenido explica un tema, como la historia de los barriletes; no un experimento.' },
          ], correct: ['a'] },
        ),
        S.explain(
          { fase: 'construir', areas: ['mat', 'art'], cnb: ['mat:4.4.2'], ambito: 'conocer', title: 'Sumar y restar fracciones distintas',
            prompt: 'Para un barrilete se usa **1/2 pliego** de papel rojo y **3/4 pliego** de papel amarillo, pero sobra **1/3 pliego** en total. ¿Cuánto papel se usó? 1/2 + 3/4 − 1/3.' },
          { icon: 'PieChart', body: 'Solo se pueden sumar o restar fracciones con el **mismo denominador**. Busca el **MCM** de los denominadores.', reveal: [
            { icon: 'Search', front: '1. Denominador común', back: 'MCM(2, 4, 3) = **12**.' },
            { icon: 'RefreshCw', front: '2. Fracciones equivalentes', back: '1/2 = 6/12, 3/4 = 9/12, 1/3 = 4/12.' },
            { icon: 'Calculator', front: '3. Opera de izquierda a derecha', back: '6/12 + 9/12 − 4/12 = **11/12** de pliego.' },
            { icon: 'X', front: 'Error común', back: 'No sumes numeradores y denominadores por separado: 1/2 + 3/4 **no** es 4/6.' },
          ] },
        ),
        S.number(
          { fase: 'aplicar', areas: ['mat', 'art'], cnb: ['mat:4.4.2', 'mat:4.4.1'], ambito: 'hacer',
            prompt: 'Tenías **5/6** de un rollo de pita. Usaste **1/4** para el barrilete y **1/3** para la cola. ¿Cuánto queda? Escribe la fracción **simplificada**.',
            hint: 'MCM(6, 4, 3) = 12. Convierte cada fracción a doceavos.',
            explain: '10/12 − 3/12 − 4/12 = 3/12, que simplificado es 1/4 del rollo.' },
          { answer: 1 / 4, allowFraction: true, allowDecimal: true, stimulus: '5/6 − 1/4 − 1/3 = ?' },
        ),
        S.order(
          { fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:8.1.2'], prompt: 'Boleto de salida: ordena los grandes momentos de la investigación científica.' },
          { items: [
            { id: 'm1', text: 'Observación' },
            { id: 'm2', text: 'Hipótesis' },
            { id: 'm3', text: 'Experimentación' },
            { id: 'm4', text: 'Conclusión' },
          ], labels: { start: 'Primero', end: 'Último' } },
        ),
        S.number(
          { fase: 'comprobar', areas: ['mat'], cnb: ['mat:4.4.2'], prompt: 'Calcula **2/3 + 1/2 − 3/4**. Escribe la fracción.' },
          { answer: 5 / 12, allowFraction: true, allowDecimal: true, stimulus: '2/3 + 1/2 − 3/4 = ?' },
        ),
        cierre({ areas: ['cnt', 'l1'], cnb: ['cnt:8.2.2'] }, ['Reconozco los momentos de una investigación', 'Explico un fenómeno natural con ciencia', 'Elijo la fuente y el informe adecuados', 'Sumo y resto fracciones con distinto denominador'],
          ['Haré un experimento sencillo en casa y anotaré mis resultados', 'Visitaré la biblioteca de mi escuela o municipio', 'Revisaré que mis fuentes de internet sean confiables']),
      ],
    }),

    /* ───────────────────────── Día 3 ───────────────────────── */
    lesson({
      id: 's18-d3-sociedad-justa',
      title: 'Entender la sociedad para transformarla',
      icon: 'Scale',
      minutes: 15,
      day: 3,
      gancho: 'Si la ciencia explica el viento, ¿qué ciencia explica por qué algunas familias tienen tanto y otras tan poco?',
      objetivos: ['Describir el aporte de las Ciencias Sociales e identificar causas y consecuencias de la pobreza', 'Relacionar las leyes laborales de Guatemala con convenios internacionales', 'Reconocer la situación de los pueblos indígenas en distintos momentos de la historia', 'Revisar la concordancia y distinguir determinantes de pronombres demostrativos'],
      resumen: [
        'Las Ciencias Sociales (historia, geografía, economía, sociología, antropología, ciencia política) ayudan a entender por qué ocurren los problemas sociales y cómo resolverlos. La pobreza tiene causas como la falta de empleo digno, de educación y de acceso a la tierra, y la discriminación; sus consecuencias incluyen desnutrición, trabajo infantil, abandono escolar y migración.',
        'La Constitución limita la jornada diurna a 8 horas diarias y 44 semanales y protege a la niñez del trabajo; Guatemala ratificó los convenios 138 y 182 de la OIT contra el trabajo infantil.',
        'Los pueblos indígenas han vivido exclusión desde la Colonia; los Acuerdos de Paz reconocieron su identidad y sus derechos, aunque persisten desafíos.',
        'Artículo, sustantivo y adjetivo concuerdan en género y número; sujeto y verbo, en número y persona. "Este libro" (determinante) acompaña; "este es mío" (pronombre) sustituye.',
      ],
      media: {
        id: 's18-d3-ciencias-sociales', kind: 'diagram', title: 'Las Ciencias Sociales miran la realidad', aspect: '4:3',
        alt: 'Una lupa sobre una comunidad, rodeada de seis ciencias sociales con íconos: historia, geografía, economía, sociología, antropología y ciencia política.',
        brief: 'Diagrama radial: al centro, una lupa grande sobre una aldea guatemalteca (casas, milpa, escuela, mercado). Alrededor, seis burbujas con ícono y pregunta: HISTORIA ("¿Qué pasó antes?"), GEOGRAFÍA ("¿Dónde y en qué ambiente?"), ECONOMÍA ("¿Cómo se produce y reparte la riqueza?"), SOCIOLOGÍA ("¿Cómo se organiza la gente?"), ANTROPOLOGÍA ("¿Qué cultura y costumbres tiene?"), CIENCIA POLÍTICA ("¿Quién decide y cómo?"). Colores de Ciencias Sociales.',
      },
      steps: [
        S.cards(
          { fase: 'explorar', areas: ['ccss', 'fc'], cnb: ['ccss:8.1.2'], ambito: 'conocer', title: 'Ciencias para entender a la sociedad',
            prompt: 'Así como la ciencia natural explica el viento, las **Ciencias Sociales** explican cómo vivimos juntos. Voltea las tarjetas.' },
          { cards: [
            { icon: 'History', front: 'Historia', back: 'Estudia el **pasado** para entender el presente: ¿por qué hay desigualdad en la tierra?' },
            { icon: 'Map', front: 'Geografía', back: 'Estudia el **territorio**: dónde vive la gente y cómo usa sus recursos.' },
            { icon: 'Coins', front: 'Economía', back: 'Estudia cómo se **produce y reparte** la riqueza.' },
            { icon: 'Users', front: 'Sociología', back: 'Estudia cómo se **organizan** los grupos y comunidades.' },
            { icon: 'Landmark', front: 'Ciencia Política', back: 'Estudia el **poder**, el gobierno y las leyes.' },
            { icon: 'Languages', front: 'Antropología', back: 'Estudia las **culturas**: costumbres, idiomas y formas de vida de los pueblos.' },
          ] },
        ),
        S.sort(
          { fase: 'construir', areas: ['ccss', 'fc', 'cnt'], cnb: ['ccss:8.3.2'], ambito: 'conocer',
            prompt: 'Con los datos e informes, las Ciencias Sociales estudian la **pobreza**. Clasifica cada situación como **causa** o **consecuencia** de la pobreza.',
            hint: 'Una causa ocurre antes y provoca la pobreza; una consecuencia es lo que la pobreza provoca.',
            explain: 'Causas y consecuencias forman un círculo: por ejemplo, sin educación es difícil conseguir empleo digno, y sin ingresos los hijos pueden dejar la escuela. Romper el círculo requiere acciones del Estado, de las comunidades y de las familias.',
            media: { id: 's18-d3-circulo', kind: 'diagram', title: 'El círculo de la pobreza', aspect: '1:1',
              alt: 'Diagrama circular con flechas: pocos ingresos, desnutrición, abandono escolar, empleo mal pagado, y de nuevo pocos ingresos. Al centro, una flecha verde que rompe el círculo con el texto "Educación, empleo digno y derechos".',
              brief: 'Diagrama circular de 5 pasos unidos con flechas curvas: "Pocos ingresos" → "Mala alimentación y salud" → "Abandono escolar" → "Empleo mal pagado" → vuelve a "Pocos ingresos". Al centro, una flecha verde que atraviesa el círculo con el texto "Educación, empleo digno y derechos". Íconos simples, sin fotos de personas en situación de pobreza (evitar estigmatizar).' } },
          { buckets: [
            { id: 'causa', label: 'Causa', icon: 'Search', color: 'var(--area-ccss)' },
            { id: 'cons', label: 'Consecuencia', icon: 'TrendingUp', color: 'var(--area-fc)' },
          ], items: [
            { id: 'p1', text: 'Falta de empleos con salario justo', bucket: 'causa' },
            { id: 'p2', text: 'Poco acceso a la educación', bucket: 'causa' },
            { id: 'p3', text: 'Discriminación por origen o idioma', bucket: 'causa' },
            { id: 'p4', text: 'Desnutrición infantil', bucket: 'cons' },
            { id: 'p5', text: 'Niñas y niños que trabajan en lugar de estudiar', bucket: 'cons' },
            { id: 'p6', text: 'Migración de familias en busca de trabajo', bucket: 'cons' },
          ] },
        ),
        S.reading(
          { fase: 'construir', areas: ['ccss', 'fc', 'l1'], cnb: ['ccss:8.4.2'], ambito: 'conocer',
            prompt: 'Lee sobre las leyes del trabajo y responde.' },
          { genre: 'Texto informativo', heading: 'Trabajo digno: leyes de Guatemala y del mundo', passage:
            'Guatemala tiene leyes que protegen a las personas trabajadoras. El **Código de Trabajo**, aprobado por primera vez en 1947, y la **Constitución Política** de 1985 establecen derechos como un **salario mínimo**, **vacaciones pagadas** y una jornada diurna que no puede pasar de **8 horas diarias ni 44 horas a la semana**.\n\nEstas leyes se relacionan con **convenios internacionales**. La **Organización Internacional del Trabajo (OIT)** reúne a gobiernos, empresas y trabajadores para acordar normas. Cuando Guatemala **ratifica** un convenio, se compromete a cumplirlo. Por ejemplo, ratificó el **Convenio 138** sobre la edad mínima para trabajar y el **Convenio 182** contra las peores formas de trabajo infantil.\n\nLa Constitución también protege a la niñez: las personas menores de 14 años no pueden ser ocupadas en ningún trabajo, salvo las excepciones que establece la ley. Lo más importante para una niña o un niño es **estudiar, jugar y crecer sano**.',
            questions: [
              { q: 'Según el texto, ¿cuál es la jornada diurna máxima en Guatemala?', options: [
                { id: 'a', text: '8 horas diarias y 44 a la semana' },
                { id: 'b', text: '12 horas diarias' },
                { id: 'c', text: 'No hay límite' },
              ], correct: 'a' },
              { q: '¿Qué significa que Guatemala "ratifique" un convenio de la OIT?', options: [
                { id: 'a', text: 'Que se compromete a cumplirlo en sus leyes' },
                { id: 'b', text: 'Que lo rechaza' },
                { id: 'c', text: 'Que solo lo lee' },
              ], correct: 'a' },
              { q: '¿Qué ley nacional se relaciona con el Convenio 138 de la OIT?', options: [
                { id: 'a', text: 'La norma de la Constitución que protege a menores de 14 años del trabajo' },
                { id: 'b', text: 'La ley de tránsito' },
                { id: 'c', text: 'El calendario escolar' },
              ], correct: 'a', why: 'Ambas buscan proteger a la niñez fijando una edad mínima para trabajar.' },
            ] },
        ),
        S.explain(
          { fase: 'construir', areas: ['fc', 'ccss'], cnb: ['fc:5.2.2'], ambito: 'conocer', title: 'Los pueblos indígenas a través de la historia',
            prompt: 'La situación de los pueblos indígenas ha cambiado en distintos momentos. Toca cada época. Recuerda: hablamos con **respeto**, para entender y no repetir las injusticias.' },
          { icon: 'History', body: 'Los pueblos mayas, xinka y garífuna han **resistido** y conservado su cultura en todas las épocas.', reveal: [
            { icon: 'Sun', front: 'Época prehispánica', back: 'Pueblos mayas con **gobiernos propios**, ciudades, ciencia y arte.' },
            { icon: 'Church', front: 'Colonia (1524-1821)', back: '**Tributo** a la Corona, trabajo forzado y pérdida de tierras.' },
            { icon: 'Train', front: 'Reforma Liberal (1871)', back: 'Pérdida de **tierras comunales** y leyes de trabajo obligatorio en fincas.' },
            { icon: 'Feather', front: 'Conflicto armado (1960-1996)', back: 'La CEH documentó que la **mayoría de las víctimas** identificadas pertenecían a pueblos mayas.' },
            { icon: 'Handshake', front: 'Acuerdos de Paz y hoy', back: 'En 1995 se firmó el **Acuerdo sobre Identidad y Derechos de los Pueblos Indígenas**. Hoy se reconocen sus idiomas, pero persisten la discriminación y la desigualdad.' },
          ] },
        ),
        S.fill(
          { fase: 'aplicar', areas: ['l1', 'fc'], cnb: ['l1:7.3.1'], ambito: 'hacer',
            prompt: 'Revisa el texto del periódico mural. La **concordancia** exige que artículo, sustantivo y adjetivo coincidan en **género y número**, y que sujeto y verbo coincidan en **número, persona y tiempo**. Completa correctamente.',
            hint: '"Comunidades" es femenino plural: su artículo y su adjetivo también.',
            explain: 'Las comunidades indígenas (femenino plural) exigen (plural) respeto. Los trabajadores (masculino plural) tienen (plural) derechos.' },
          { text: '[[Las]] comunidades [[indígenas]] [[exigen]] respeto a sus derechos.\nLos trabajadores del campo [[tienen]] derecho a un salario [[justo]].',
            distractors: ['Los', 'exige', 'tiene', 'justa'] },
        ),
        S.sort(
          { fase: 'aplicar', areas: ['l2', 'l1'], cnb: ['l2:5.1.4'], ambito: 'conocer',
            prompt: 'Los **demostrativos** (este, ese, aquel y sus formas) pueden ser **determinantes** (acompañan a un sustantivo: _este convenio_) o **pronombres** (lo sustituyen: _este es el mío_). Antes, los pronombres llevaban tilde (_éste_); hoy la norma no la exige. Clasifica la palabra **en negrita**.',
            hint: '¿Hay un sustantivo justo después? Entonces es determinante.',
            explain: 'En "esta ley protege…", "esta" acompaña a "ley": es determinante. En "Esa es la mejor", "esa" reemplaza al sustantivo: es pronombre.' },
          { buckets: [
            { id: 'det', label: 'Determinante (acompaña)', icon: 'Link' },
            { id: 'pro', label: 'Pronombre (sustituye)', icon: 'RefreshCw' },
          ], items: [
            { id: 'x1', text: '**Esta** ley protege a la niñez.', bucket: 'det' },
            { id: 'x2', text: '**Aquellos** convenios fueron ratificados.', bucket: 'det' },
            { id: 'x3', text: '**Ese** informe es técnico.', bucket: 'det' },
            { id: 'x4', text: 'De todos los derechos, **este** es el que más me importa.', bucket: 'pro' },
            { id: 'x5', text: '¿Cuál barrilete es tuyo? **Aquel**.', bucket: 'pro' },
            { id: 'x6', text: '**Esa** es la ley que buscábamos.', bucket: 'pro' },
          ] },
        ),
        S.order(
          { fase: 'comprobar', areas: ['fc', 'ccss'], cnb: ['fc:5.2.2'], prompt: 'Boleto de salida: ordena estos momentos de la historia de los pueblos indígenas en Guatemala.' },
          { items: [
            { id: 'h1', text: 'Señoríos mayas con gobiernos propios' },
            { id: 'h2', text: 'Tributo a la Corona española' },
            { id: 'h3', text: 'Pérdida de tierras comunales en la Reforma Liberal' },
            { id: 'h4', text: 'Acuerdo sobre Identidad y Derechos de los Pueblos Indígenas' },
          ], labels: { start: 'Más antiguo', end: 'Más reciente' } },
        ),
        S.choice(
          { fase: 'comprobar', areas: ['ccss', 'l1'], cnb: ['ccss:8.3.2', 'l1:7.3.1'], prompt: '¿Cuál oración tiene **concordancia correcta** y además es verdadera?' },
          { options: [
            { id: 'a', text: 'La falta de educación es una causa de la pobreza.' },
            { id: 'b', text: 'Los convenio de la OIT protege a los trabajadores.', feedback: '"Los convenios… protegen": falta concordancia de número.' },
            { id: 'c', text: 'La migración es una causa del trabajo digno.', feedback: 'Tiene concordancia, pero no es verdadera: la migración suele ser consecuencia de la pobreza.' },
          ], correct: ['a'] },
        ),
        cierre({ areas: ['ccss', 'fc'], cnb: ['ccss:8.1.2'] }, ['Explico cómo las Ciencias Sociales ayudan a entender la realidad', 'Distingo causas y consecuencias de la pobreza', 'Relaciono leyes laborales de Guatemala con convenios de la OIT', 'Hablo con respeto de la historia de los pueblos indígenas'],
          ['Defenderé que niñas y niños estudien en lugar de trabajar', 'Revisaré la concordancia de mis textos antes de entregarlos', 'Trataré a todas las personas con igualdad, sin importar su origen']),
      ],
    }),

    /* ───────────────────────── Día 4 ───────────────────────── */
    lesson({
      id: 's18-d4-barriletes',
      title: 'Barriletes: tradición, diálogo y futuro',
      icon: 'Wind',
      minutes: 15,
      day: 4,
      gancho: 'Si pudieras escribir un mensaje en un barrilete gigante, ¿qué le dirías al cielo y a tu comunidad?',
      objetivos: ['Investigar y publicar sobre el origen y significado de una tradición', 'Resolver un problema por medio de la negociación y planificar una actividad económica sostenible', 'Usar preposiciones y conjunciones, y dialogar en inglés con cortesía', 'Organizar juegos donde todas y todos participan por igual'],
      resumen: [
        'Los barriletes gigantes de Sumpango y Santiago Sacatepéquez se elevan el 1 de noviembre; se elaboran en grupo con papel de china y bambú y llevan mensajes para los seres queridos y la comunidad.',
        'Negociar es dialogar para llegar a un acuerdo justo: escuchar, identificar intereses, proponer opciones, acordar y cumplir.',
        'Un emprendimiento sostenible cuida el ambiente, usa bien los recursos y reparte con justicia.',
        'Las preposiciones (con, de, desde, hacia, para, sobre…) enlazan palabras; las conjunciones (y, o, pero, porque…) enlazan palabras u oraciones.',
      ],
      media: {
        id: 's18-d4-barrilete-gigante', kind: 'image', title: 'Un barrilete gigante de cerca', aspect: '1:1',
        alt: 'Barrilete gigante circular de papel de china con un diseño de flores, un quetzal y una mazorca, sostenido por una estructura de bambú.',
        brief: 'Ilustración frontal de un barrilete gigante circular (proporción: una persona a su pie mide una décima parte de su altura). Diseño en papel de china de colores con un quetzal, mazorcas, flores y un sol; borde de flecos de papel. Detrás, la estructura de bambú amarrada con pita. Recuadro pequeño con el reverso para mostrar las varas cruzadas. Sin textos políticos ni marcas.',
      },
      steps: [
        S.explain(
          { fase: 'explorar', areas: ['art', 'ccss', 'l1'], cnb: ['art:4.3.3'], ambito: 'conocer', title: 'Una tradición que vuela',
            prompt: 'Antes de publicar una investigación, hay que conocer bien la tradición. Toca cada tarjeta.',
            media: { id: 's18-d4-taller', kind: 'video', title: 'Así se hace un barrilete gigante', aspect: '16:9', duration: 60,
              alt: 'Un grupo de jóvenes corta y pega papel de china durante semanas, arma la estructura de bambú y levanta el barrilete en el campo.',
              brief: 'Video de 60 s tipo documental ilustrado, con cámara rápida: (1) jóvenes y adultos dibujan el diseño en papel; (2) cortan y pegan miles de piezas de papel de china con engrudo de harina; (3) amarran varas de bambú; (4) el 1 de noviembre levantan el barrilete entre varias personas con cuerdas. Rótulos: "Meses de trabajo en equipo", "Materiales: papel, bambú, pita, engrudo". Personajes ficticios, diversidad de género.' } },
          { icon: 'Wind', body: 'Los barriletes gigantes son parte de la **tradición cultural** de Sacatepéquez y hoy los admira gente de todo el mundo.', reveal: [
            { icon: 'CalendarDays', front: '¿Cuándo?', back: 'El **1 de noviembre**, Día de Todos los Santos, en **Sumpango** y **Santiago Sacatepéquez**.' },
            { icon: 'Heart', front: '¿Qué significan?', back: 'Muchas familias los relacionan con el **recuerdo de sus seres queridos** fallecidos; sus diseños llevan mensajes de identidad, paz y comunidad.' },
            { icon: 'Users', front: '¿Quiénes los hacen?', back: 'Grupos de jóvenes y adultos que trabajan **durante meses** en equipo.' },
            { icon: 'Search', front: '¿Y su origen?', back: 'Hay **varias versiones** contadas por las comunidades. Por eso, al investigar, conviene **entrevistar** a personas mayores y comparar fuentes.' },
          ] },
        ),
        S.order(
          { fase: 'construir', areas: ['ccss', 'fc'], cnb: ['ccss:8.2.2'], ambito: 'convivir',
            prompt: 'Dos grupos de barrileteros quieren el **mismo espacio** del campo y se enojaron. Ordena los pasos de una **negociación** para resolver el problema.',
            explain: 'Negociar no es ganarle al otro: es buscar un acuerdo en el que ambas partes obtengan algo justo. Así se resuelven también problemas complejos entre comunidades o países.' },
          { items: [
            { id: 'n1', text: 'Calmarse y aceptar dialogar' },
            { id: 'n2', text: 'Escuchar a cada grupo sin interrumpir' },
            { id: 'n3', text: 'Identificar qué necesita realmente cada grupo' },
            { id: 'n4', text: 'Proponer varias opciones (turnos, dividir el espacio…)' },
            { id: 'n5', text: 'Elegir un acuerdo justo y cumplirlo' },
          ], labels: { start: 'Primero', end: 'Último' } },
        ),
        S.highlight(
          { fase: 'construir', areas: ['l2', 'art'], cnb: ['l2:5.1.5'], ambito: 'conocer',
            prompt: 'Las **preposiciones** (a, con, de, desde, en, hacia, hasta, para, por, sin, sobre…) enlazan palabras. Las **conjunciones** (y, e, o, u, ni, pero, sino, aunque, porque…) enlazan palabras u oraciones. Marca **solo las conjunciones**.',
            explain: 'Y, pero, porque y o son conjunciones. Con, de, hacia, sobre y para son preposiciones.' },
          { target: 'conjunciones', text: 'Pegamos el papel con engrudo {y} amarramos el bambú. El viento soplaba fuerte, {pero} el barrilete subió hacia las nubes {porque} tenía una cola larga. ¿Lo volamos sobre el campo {o} cerca de la escuela? Lo hicimos para nuestras abuelas.' },
        ),
        S.sort(
          { fase: 'aplicar', areas: ['pyd', 'cnt', 'mat'], cnb: ['pyd:5.4.1'], ambito: 'emprender',
            prompt: 'Tu grado quiere **vender barriletes pequeños** para reunir fondos. Planifica una actividad económica **sostenible y justa**: clasifica cada decisión.',
            explain: 'Un emprendimiento sostenible gana dinero sin dañar el ambiente y reparte con justicia. Así, el desarrollo económico beneficia a toda la comunidad.' },
          { buckets: [
            { id: 'si', label: 'Sostenible y justa', icon: 'Sprout', color: 'var(--c-ok)' },
            { id: 'no', label: 'No sostenible o injusta', icon: 'X', color: 'var(--c-bad)' },
          ], items: [
            { id: 'e1', text: 'Usar papel reciclado y engrudo de harina', bucket: 'si' },
            { id: 'e2', text: 'Comprar varas de bambú a un productor local que resiembra', bucket: 'si' },
            { id: 'e3', text: 'Repartir las tareas y las ganancias por igual entre niñas y niños', bucket: 'si' },
            { id: 'e4', text: 'Cortar árboles jóvenes del bosque para las varas', bucket: 'no' },
            { id: 'e5', text: 'Hacer las colas con bolsas plásticas que quedarán tiradas', bucket: 'no' },
            { id: 'e6', text: 'Que solo quien tiene más amigos se quede con las ganancias', bucket: 'no' },
          ] },
        ),
        S.write(
          { fase: 'aplicar', areas: ['art', 'l1', 'ccss'], cnb: ['art:4.3.3', 'l1:8.2.6'], ambito: 'hacer',
            prompt: 'Escribe un **artículo breve de contenido** para el periódico escolar sobre una tradición de **tu región** (barriletes, convites, cofradías, una danza, una comida del Día de Todos los Santos…). Incluye: origen, significado, quiénes participan y **al menos una fuente** (una persona entrevistada, un libro o un sitio confiable).' },
          { minWords: 60, placeholder: 'Título…\n\nOrigen: …\nSignificado: …\nParticipantes: …\nFuente: …',
            model: 'Barriletes que recuerdan\n\nEn Sumpango, cada 1 de noviembre, se elevan barriletes gigantes. Según don Pedro, un vecino de 70 años que entrevisté, la tradición se relaciona con recordar a los seres queridos que ya murieron. Los grupos trabajan durante meses con papel de china y bambú, y sus diseños llevan mensajes de paz y de identidad. Es una tradición que une a jóvenes y adultos.\n\nFuente: entrevista a un vecino de la comunidad.',
            rubric: ['Tiene título', 'Explica el origen y el significado de la tradición', 'Menciona quiénes participan', 'Cita al menos una fuente', 'Usa mayúsculas, puntos y concordancia correctos'] },
        ),
        S.fill(
          { fase: 'aplicar', areas: ['l3', 'art'], cnb: ['l3:5.3.2'], ambito: 'convivir',
            prompt: 'English time! A visitor at the kite festival asks you a question. Completa el **diálogo** con expresiones de cortesía: _Excuse me_ (disculpe), _please_ (por favor), _Thank you_ (gracias), _You\'re welcome_ (de nada).',
            explain: '"Excuse me" sirve para llamar la atención con respeto; "You\'re welcome" es la respuesta a "Thank you".' },
          { text: 'Visitor: [[Excuse me]], what is this kite for?\nYou: It is a message for our grandparents.\nVisitor: Can I take a picture, [[please]]?\nYou: Yes, of course!\nVisitor: [[Thank you]]!\nYou: [[You\'re welcome]]!', distractors: ['Goodbye', 'Sorry'] },
        ),
        S.dilemma(
          { fase: 'aplicar', areas: ['ef', 'fc', 'l2'], cnb: ['ef:4.1.13', 'ef:4.2.4', 'ef:4.2.8'], ambito: 'convivir',
            prompt: 'Tu grupo organiza los juegos de la tarde en el festival. ¿Qué harías?' },
          { scene: { icon: 'Users', text: 'Organizas una carrera de barriletes pequeños. Unos compañeros dicen que las niñas no deben correr y se burlan de Ixchel porque habla kaqchikel con su abuela.' }, options: [
            { id: 'a', icon: 'EyeOff', text: 'Dejar que ellos decidan quién juega', consequence: 'Varias niñas y Ixchel se quedan fuera. El juego termina rápido y sin alegría.', values: ['Exclusión'], constructive: false },
            { id: 'b', icon: 'HeartHandshake', text: 'Formar equipos mixtos, con reglas claras para todos, y pedir a Ixchel que enseñe cómo se dice "viento" en kaqchikel', consequence: 'Todos participan por igual, aprenden una palabra nueva y el juego es más divertido.', values: ['Equidad', 'Respeto a la diversidad', 'Organización'], constructive: true },
            { id: 'c', icon: 'Megaphone', text: 'Decir con calma que todas las personas tienen derecho a jugar y que las burlas no se permiten', consequence: 'Los compañeros reflexionan y piden disculpas. El juego continúa con respeto.', values: ['Valentía', 'Respeto'], constructive: true },
          ] },
        ),
        S.choice(
          { fase: 'comprobar', areas: ['ccss', 'pyd'], cnb: ['ccss:8.2.2'], prompt: 'Boleto de salida: en una negociación, ¿qué se busca?' },
          { options: [
            { id: 'a', text: 'Un acuerdo justo en el que ambas partes obtengan algo', icon: 'Handshake' },
            { id: 'b', text: 'Que gane quien grite más fuerte', icon: 'Megaphone', feedback: 'Gritar no resuelve el problema; el diálogo sí.' },
            { id: 'c', text: 'Evitar hablar del problema', icon: 'EyeOff', feedback: 'Si no se habla, el conflicto sigue.' },
          ], correct: ['a'] },
        ),
        S.match(
          { fase: 'comprobar', areas: ['l2', 'l3', 'art'], cnb: ['l2:5.1.5', 'l3:5.3.2', 'art:4.3.3'], prompt: 'Une cada palabra o expresión con lo que es.' },
          { pairs: [
            { id: 'pre', left: 'hacia', right: 'Preposición' },
            { id: 'con', left: 'pero', right: 'Conjunción' },
            { id: 'eng', left: 'You\'re welcome', right: 'Respuesta cortés a "Thank you"' },
            { id: 'bar', left: '1 de noviembre', right: 'Día de los barriletes gigantes' },
          ] },
        ),
        cierre({ areas: ['art', 'ef'], cnb: ['art:4.3.3'] }, ['Investigo y comparto el origen y significado de una tradición', 'Negocio para resolver un conflicto', 'Planifico un emprendimiento que cuida el ambiente', 'Organizo juegos donde todas y todos participan'],
          ['Entrevistaré a una persona mayor sobre una tradición de mi comunidad', 'Usaré el diálogo antes de enojarme', 'Invitaré a jugar a quien se quede fuera']),
      ],
    }),

    /* ───────────────────────── Día 5: Reto semanal ───────────────────────── */
    lesson({
      id: 's18-d5-reto',
      title: 'Reto de la semana 18',
      icon: 'Trophy',
      minutes: 14,
      day: 5,
      kind: 'reto',
      objetivos: ['Demostrar lo que aprendiste esta semana', 'Obtener la medalla "Guardián del aire" (70 % o más)'],
      resumen: ['Superé el reto de la semana 18: clima, investigación científica, sociedad justa, fracciones y tradición.'],
      media: {
        id: 's18-d5-reto', kind: 'image', title: 'Medalla Guardián del aire', aspect: '1:1',
        alt: 'Medalla dorada con un barrilete de colores volando sobre un volcán y una hoja verde.',
        brief: 'Ilustración de medalla circular dorada: al centro un barrilete pequeño de papel de china de colores con su cola al viento, sobre la silueta de un volcán; abajo una hoja verde. Líneas curvas que representan el viento. Cinta con los colores de las áreas del CNB. Fondo transparente, 1024×1024, estilo plano con brillo suave.',
      },
      steps: [
        S.choice({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:7.3.2'], prompt: '¿Qué provoca el aumento del efecto invernadero?' },
          { options: [{ id: 'a', text: 'Más gases como el dióxido de carbono por quemar combustibles, basura y bosques' }, { id: 'b', text: 'Sembrar más árboles' }, { id: 'c', text: 'Usar energía solar' }], correct: ['a'] }),
        S.sort({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:8.1.2'], prompt: '¿Hipótesis o conclusión?' },
          { buckets: [{ id: 'h', label: 'Hipótesis', icon: 'Lightbulb' }, { id: 'c', label: 'Conclusión', icon: 'ClipboardCheck' }],
            items: [{ id: 'a', text: 'Si riego la planta cada día, crecerá más.', bucket: 'h' }, { id: 'b', text: 'Los datos muestran que la planta regada creció 5 cm más.', bucket: 'c' }, { id: 'e', text: 'Si pongo el hielo al sol, se derretirá más rápido.', bucket: 'h' }, { id: 'd', text: 'Comprobamos que el hielo al sol se derritió primero.', bucket: 'c' }] }),
        S.choice({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:8.2.2'], prompt: '¿Cuál es la explicación científica de los sismos?' },
          { options: [{ id: 'a', text: 'El movimiento de las placas tectónicas' }, { id: 'b', text: 'El enojo de los volcanes' }, { id: 'c', text: 'Las lluvias fuertes' }], correct: ['a'] }),
        S.slider({ fase: 'comprobar', areas: ['mat'], cnb: ['mat:4.4.1'], prompt: 'Simplifica **6/12** y márcalo en la barra.' },
          { min: 0, max: 1, step: 0.5, answer: 0.5, start: 0, visual: 'fraction', parts: 2, display: 'fraction' }),
        S.number({ fase: 'comprobar', areas: ['mat'], cnb: ['mat:4.4.2'], prompt: 'Calcula **3/4 − 1/6 + 1/3**. Escribe la fracción.' },
          { answer: 11 / 12, allowFraction: true, allowDecimal: true, stimulus: '3/4 − 1/6 + 1/3 = ?' }),
        S.match({ fase: 'comprobar', areas: ['l1'], cnb: ['l1:8.1.2', 'l1:8.1.1', 'l1:8.2.6'], prompt: 'Une cada necesidad con la fuente o informe adecuado.' },
          { pairs: [
            { id: 'a', left: 'Ubicar un río en un mapa', right: 'Atlas' },
            { id: 'b', left: 'Leer periódicos de hace 50 años', right: 'Hemeroteca' },
            { id: 'c', left: 'Contar el procedimiento y los resultados de un experimento', right: 'Informe técnico' },
          ] }),
        S.sort({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:8.3.2'], prompt: '¿Causa o consecuencia de la pobreza?' },
          { buckets: [{ id: 'c', label: 'Causa', icon: 'Search' }, { id: 'k', label: 'Consecuencia', icon: 'TrendingUp' }],
            items: [{ id: 'a', text: 'Falta de acceso a la educación', bucket: 'c' }, { id: 'b', text: 'Desnutrición', bucket: 'k' }, { id: 'd', text: 'Desempleo', bucket: 'c' }, { id: 'e', text: 'Abandono escolar', bucket: 'k' }] }),
        S.tf({ fase: 'comprobar', areas: ['ccss', 'fc'], cnb: ['ccss:8.4.2', 'fc:5.2.2'], prompt: '¿Verdadero o falso?' },
          { statements: [
            { text: 'Guatemala ratificó convenios de la OIT contra el trabajo infantil.', answer: true },
            { text: 'En 1995 se firmó el Acuerdo sobre Identidad y Derechos de los Pueblos Indígenas.', answer: true },
            { text: 'La Constitución permite jornadas diurnas de 12 horas diarias.', answer: false },
          ] }),
        S.fill({ fase: 'comprobar', areas: ['l1', 'l2'], cnb: ['l1:7.3.1', 'l2:5.1.3', 'l2:5.1.5'], prompt: 'Completa con concordancia y el conector correcto.' },
          { text: 'Los barriletes [[rojos]] vuelan alto, [[pero]] los azules no.', distractors: ['roja', 'hacia'] }),
        S.choice({ fase: 'comprobar', areas: ['pyd'], cnb: ['pyd:5.4.1'], prompt: '¿Cuál es una decisión **sostenible y justa** para un emprendimiento escolar?' },
          { options: [{ id: 'a', text: 'Usar materiales reciclados y repartir tareas y ganancias por igual' }, { id: 'b', text: 'Talar árboles jóvenes para ahorrar dinero' }, { id: 'c', text: 'Dejar fuera a quien habla otro idioma' }], correct: ['a'] }),
      ],
    }),
  ],

  /* Banco de ítems para la Semana de validación de la Unidad 2 */
  bank: [
    S.choice({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:7.3.2'], prompt: '¿Qué gas de efecto invernadero aumenta al quemar gasolina y leña?' },
      { options: [{ id: 'a', text: 'Dióxido de carbono' }, { id: 'b', text: 'Oxígeno' }, { id: 'c', text: 'Helio' }], correct: ['a'] }),
    S.order({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:8.1.2', 'cnt:8.2.2'], prompt: 'Ordena los momentos de esta investigación.' },
      { items: [{ id: 'a', text: 'Veo que el pan se llena de moho en lugares húmedos' }, { id: 'b', text: 'Pienso: "Si guardo el pan en un lugar seco, tardará más en tener moho"' }, { id: 'c', text: 'Guardo un pan en lugar seco y otro en lugar húmedo, y observo 5 días' }, { id: 'd', text: 'El pan en lugar seco tardó más: la hipótesis se cumplió' }], labels: { start: 'Primero', end: 'Último' } }),
    S.choice({ fase: 'comprobar', areas: ['mat'], cnb: ['mat:4.4.1'], prompt: '¿Cuál es la mínima expresión de 18/27?' },
      { options: [{ id: 'a', text: '2/3' }, { id: 'b', text: '6/9' }, { id: 'c', text: '9/13' }], correct: ['a'] }),
    S.number({ fase: 'comprobar', areas: ['mat'], cnb: ['mat:4.4.2'], prompt: 'Calcula **1/2 + 1/3 − 1/4**. Escribe la fracción.' },
      { answer: 7 / 12, allowFraction: true, allowDecimal: true, stimulus: '1/2 + 1/3 − 1/4 = ?' }),
    S.choice({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:8.1.2'], prompt: '¿Qué ciencia social estudia cómo se produce y reparte la riqueza?' },
      { options: [{ id: 'a', text: 'Economía' }, { id: 'b', text: 'Geografía' }, { id: 'c', text: 'Astronomía' }], correct: ['a'] }),
    S.choice({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:8.4.2'], prompt: '¿Qué organismo internacional acuerda normas sobre el trabajo digno?' },
      { options: [{ id: 'a', text: 'La OIT (Organización Internacional del Trabajo)' }, { id: 'b', text: 'Un equipo de fútbol' }, { id: 'c', text: 'La biblioteca municipal' }], correct: ['a'] }),
    S.choice({ fase: 'comprobar', areas: ['fc'], cnb: ['fc:5.2.2'], prompt: 'Durante la Reforma Liberal, muchas comunidades indígenas…' },
      { options: [{ id: 'a', text: 'Perdieron sus tierras comunales' }, { id: 'b', text: 'Recibieron más tierras' }, { id: 'c', text: 'Dejaron de trabajar' }], correct: ['a'] }),
    S.choice({ fase: 'comprobar', areas: ['l1'], cnb: ['l1:8.2.6'], prompt: '¿Qué informe presenta solo las ideas principales de un texto en pocas líneas?' },
      { options: [{ id: 'a', text: 'Resumen o síntesis' }, { id: 'b', text: 'Informe técnico' }, { id: 'c', text: 'Atlas' }], correct: ['a'] }),
    S.sort({ fase: 'comprobar', areas: ['l2'], cnb: ['l2:5.1.4'], prompt: 'La palabra en negrita, ¿es determinante o pronombre?' },
      { buckets: [{ id: 'd', label: 'Determinante', icon: 'Link' }, { id: 'p', label: 'Pronombre', icon: 'RefreshCw' }],
        items: [{ id: 'a', text: '**Este** barrilete es mío.', bucket: 'd' }, { id: 'b', text: 'Quiero **ese**.', bucket: 'p' }, { id: 'c', text: '**Aquella** montaña es alta.', bucket: 'd' }, { id: 'e', text: '**Esta** es mi casa.', bucket: 'p' }] }),
    S.fill({ fase: 'comprobar', areas: ['l3'], cnb: ['l3:5.3.2'], prompt: 'Complete the dialogue.' },
      { text: 'A: [[Thank you]] for your help!\nB: [[You\'re welcome]]!', distractors: ['Excuse me'] }),
    S.choice({ fase: 'comprobar', areas: ['art'], cnb: ['art:4.3.3'], prompt: 'Para investigar el origen de una tradición de tu comunidad, ¿qué fuente es muy valiosa?' },
      { options: [{ id: 'a', text: 'Entrevistar a personas mayores y comparar con libros' }, { id: 'b', text: 'Inventar la historia' }, { id: 'c', text: 'Copiar sin citar' }], correct: ['a'] }),
    S.choice({ fase: 'comprobar', areas: ['ef'], cnb: ['ef:4.2.4', 'ef:4.1.13'], prompt: 'Al organizar un juego, ¿qué muestra respeto por las diferencias?' },
      { options: [{ id: 'a', text: 'Formar equipos mixtos y no permitir burlas por idioma u origen' }, { id: 'b', text: 'Que solo jueguen los más rápidos' }, { id: 'c', text: 'Separar a quienes hablan otro idioma' }], correct: ['a'] }),
  ],
});
