import { S, cierre, lesson, semana } from '../../dsl';

/**
 * SEMANA 36 · Unidad 4 "Fortaleciendo nuestro futuro"
 * Tema generador: Noticias para un futuro verde
 * Ambiente, desastres, reforestación, temperatura y cumbres · desarrollo, democracia, integración y convivencia ·
 * variaciones lingüísticas, verbos y rima · periódico del aula, Cuenta Larga maya, luces y sombras, higiene y juegos.
 */
export default semana({
  id: 's36',
  unidad: 4,
  semana: 36,
  kind: 'aprendizaje',
  temaGenerador: 'Noticias para un futuro verde',
  title: 'Noticias para un futuro verde',
  subtitle: 'Un periódico escolar sobre bosques, mundo, palabras y tiempo',
  icon: 'Newspaper',
  color: 'var(--c-quetzal)',
  contexto: 'En Totonicapán, los bosques comunales se cuidan desde hace generaciones y en diciembre las heladas pueden bajar la temperatura por debajo de 0 °C. Sexto grado decidió publicar su propio periódico, "El Eco del Futuro", con noticias sobre reforestación y prevención de desastres, sobre cómo se une y se organiza el mundo, con una sección de palabras y poemas, y una página cultural sobre la cuenta del tiempo maya. Esta semana serás parte de la redacción.',
  ejes: ['sostenible', 'vida-ciudadana', 'multiculturalidad', 'seguridad'],
  media: {
    id: 's36-portada', kind: 'video', title: 'La redacción de El Eco del Futuro', aspect: '16:9', duration: 60,
    alt: 'Estudiantes de Totonicapán siembran árboles, miden la temperatura en una mañana helada, escriben en el aula y arman las páginas de un periódico escolar.',
    brief: 'Video o animación 2D de 60 s en Totonicapán: (1) amanecer con escarcha sobre el pasto y un termómetro que marca bajo cero; (2) estudiantes con pala y arbolitos de pino en un bosque comunal; (3) en el aula, una "redacción" con mesas rotuladas EDITORIAL, NOTICIAS, CULTURA, DEPORTES; (4) una niña dibuja la Cuenta Larga maya para la página cultural; (5) el periódico impreso pasa de mano en mano en el mercado. Sobreimpreso: "Las buenas noticias también se construyen". Estudiantes k’iche’ y ladinos, niñas y niños por igual. Marimba suave.',
  },
  badge: { id: 'medalla-s36', name: 'Redactor del futuro verde', icon: 'Newspaper', desc: 'Completaste la semana 36 y superaste su reto' },
  lessons: [
    /* ───────────────────────── Día 1 ───────────────────────── */
    lesson({
      id: 's36-d1-bosques-protegen',
      title: 'Bosques que nos protegen',
      icon: 'Trees',
      minutes: 15,
      day: 1,
      gancho: '¿Qué pasa con el agua de lluvia en un cerro sin árboles? ¿Y en uno con bosque?',
      objetivos: ['Relacionar la situación del ambiente con la calidad de vida', 'Describir acciones para prevenir desastres e identificar actividades que se favorecen con la reforestación', 'Interpretar temperaturas sobre cero y bajo cero', 'Investigar actividades de desarrollo sostenible y las cumbres ambientales'],
      resumen: [
        'Un ambiente sano (agua limpia, aire puro, bosques, suelos fértiles) da salud y bienestar; un ambiente contaminado causa enfermedades y pobreza.',
        'Para prevenir un desastre: conocer los riesgos del lugar, no construir en laderas ni orillas de ríos, reforestar, tener un plan familiar y una mochila de emergencia, participar en simulacros y atender los avisos de CONRED.',
        'La reforestación favorece actividades productivas (agua para riego, café bajo sombra, miel), sociales (agua potable), culturales (plantas medicinales, lugares sagrados) y recreativas (caminatas, observar aves).',
        'En el termómetro, las temperaturas bajo cero se escriben con signo menos (−3 °C) y están por debajo del 0; las de sobre cero, por encima.',
        'La Cumbre de la Tierra (Río de Janeiro, 1992) y el Acuerdo de París (2015) buscan un desarrollo económico, justo con las personas y que cuide el ambiente: desarrollo sostenible.',
      ],
      media: {
        id: 's36-d1-ladera', kind: 'animation', title: 'Cerro con bosque, cerro sin bosque', aspect: '16:9', duration: 55,
        alt: 'Animación en pantalla dividida: en un cerro con árboles la lluvia se infiltra; en un cerro deforestado el agua baja con lodo y provoca un deslave.',
        brief: 'Animación 2D de 55 s, pantalla dividida con dos cerros iguales bajo la misma lluvia. IZQUIERDA "Con bosque": las copas frenan las gotas, las raíces sostienen el suelo, el agua se infiltra y sale limpia en un nacimiento. DERECHA "Sin bosque": el agua corre rápido, arrastra lodo, se forma un deslave pequeño que tapa un camino (sin personas heridas, sin casas destruidas en detalle). Cierre: estudiantes siembran arbolitos en el cerro derecho y este se vuelve verde. Rótulos: infiltración, erosión, deslave. Narración y subtítulos.',
      },
      steps: [
        S.explain(
          { fase: 'explorar', areas: ['cnt', 'ccss'], cnb: ['cnt:6.1.4'], ambito: 'conocer', title: 'Ambiente sano, vida sana',
            prompt: 'La primera noticia del periódico trata del **ambiente y la calidad de vida**. Toca cada tarjeta.' },
          { icon: 'Leaf', body: 'La **calidad de vida** depende mucho del ambiente donde vivimos: el agua que tomamos, el aire que respiramos y los alimentos que produce la tierra.', reveal: [
            { icon: 'Droplets', front: 'Agua', back: 'Agua limpia = menos **diarreas** y más salud. Ríos con basura o drenajes = enfermedades.' },
            { icon: 'Wind', front: 'Aire', back: 'El humo de basura quemada y de vehículos causa **enfermedades respiratorias**.' },
            { icon: 'Sprout', front: 'Suelo', back: 'Un suelo fértil y protegido da **cosechas**; uno erosionado produce poco y aumenta la pobreza.' },
            { icon: 'Trees', front: 'Bosque', back: 'Regula el agua, da sombra, oxígeno y protege de **deslaves**. Los bosques comunales de Totonicapán cuidan cientos de nacimientos de agua.' },
          ] },
        ),
        S.sort(
          { fase: 'construir', areas: ['cnt', 'pyd'], cnb: ['cnt:6.3.4'], ambito: 'conocer',
            prompt: 'La reforestación beneficia muchas actividades. Clasifica cada una según su tipo.',
            explain: 'Reforestar no solo previene desastres: también da trabajo, agua, medicina, cultura y diversión a la comunidad.' },
          { layout: 'grid2', buckets: [
            { id: 'pro', label: 'Productivas', icon: 'Tractor', color: 'var(--area-pyd)' },
            { id: 'soc', label: 'Sociales', icon: 'Users', color: 'var(--area-fc)' },
            { id: 'cul', label: 'Culturales', icon: 'Flower2', color: 'var(--area-art)' },
            { id: 'rec', label: 'Recreativas', icon: 'Bike', color: 'var(--area-ef)' },
          ], items: [
            { id: 'r1', text: 'Producir café bajo sombra de árboles', bucket: 'pro' },
            { id: 'r2', text: 'Criar abejas para vender miel', bucket: 'pro' },
            { id: 'r3', text: 'Asegurar agua potable para toda la aldea', bucket: 'soc' },
            { id: 'r4', text: 'Recolectar plantas medicinales tradicionales', bucket: 'cul' },
            { id: 'r5', text: 'Cuidar los lugares sagrados en el bosque', bucket: 'cul' },
            { id: 'r6', text: 'Hacer caminatas y observar aves', bucket: 'rec' },
          ] },
        ),
        S.order(
          { fase: 'construir', areas: ['cnt', 'fc'], cnb: ['cnt:6.2.4'], ambito: 'hacer',
            prompt: 'La segunda noticia enseña a **prevenir un desastre**. Ordena los pasos del **plan familiar de emergencia**.',
            explain: 'La prevención empieza antes de que ocurra algo: conocer los riesgos, organizarse y practicar. CONRED (Coordinadora Nacional para la Reducción de Desastres) emite avisos que hay que atender.' },
          { items: [
            { id: 'p1', text: 'Identificar los riesgos: ¿vivimos cerca de un río, una ladera o un volcán?', icon: 'Search' },
            { id: 'p2', text: 'Dibujar un mapa con rutas de evacuación y un punto de reunión', icon: 'Map' },
            { id: 'p3', text: 'Preparar la mochila de emergencia: agua, linterna, botiquín, documentos', icon: 'Backpack' },
            { id: 'p4', text: 'Practicar un simulacro con toda la familia', icon: 'Users' },
            { id: 'p5', text: 'Estar atentos a los avisos de CONRED en radio y otros medios', icon: 'Radio' },
          ], labels: { start: 'Primero', end: 'Siempre' } },
        ),
        S.slider(
          { fase: 'construir', areas: ['mat', 'cnt'], cnb: ['mat:7.2.1'], ambito: 'hacer',
            prompt: 'La sección del clima informa: supongamos que en una madrugada de diciembre, en Totonicapán, el termómetro marcó **3 grados bajo cero**. Mueve el termómetro hasta esa temperatura.',
            hint: 'Bajo cero está por debajo del 0 y se escribe con signo menos.',
            explain: '3 grados bajo cero se escribe −3 °C. Cuando la temperatura baja de 0 °C, el agua se congela y se forma la helada que quema los cultivos.',
            media: { id: 's36-d1-termometro', kind: 'image', title: 'Mañana de helada', aspect: '4:3',
              alt: 'Termómetro de pared en un corredor de adobe marcando −3 °C, con escarcha blanca sobre el pasto y una milpa al fondo.',
              brief: 'Ilustración realista-suave: corredor de una casa de adobe en el altiplano al amanecer; termómetro de pared con escala de −10 a 40 °C, el líquido llega a −3 (zona azul bajo el 0 muy marcada). Escarcha blanca sobre el pasto y hojas de milpa quemadas por la helada al fondo. Una niña con chumpa y gorro señala el termómetro. Rótulos: "sobre cero" (arriba del 0, naranja) y "bajo cero" (abajo del 0, azul).' } },
          { min: -10, max: 40, step: 1, start: 10, answer: -3, unit: '°C', visual: 'thermometer', ticks: [{ value: -10, label: '−10' }, { value: 0, label: '0' }, { value: 20, label: '20' }, { value: 40, label: '40' }] },
        ),
        S.match(
          { fase: 'aplicar', areas: ['pyd', 'ccss'], cnb: ['pyd:5.1.1'], ambito: 'conocer',
            prompt: 'La redacción **investigó** sobre las **cumbres del ambiente** y el desarrollo sostenible. Une cada dato con su descripción.',
            explain: 'El desarrollo sostenible tiene tres partes: económica (producir y ganar), social (que beneficie a todas las personas con equidad e inclusión) y ambiental (sin agotar ni contaminar la naturaleza).' },
          { leftTitle: 'Dato', rightTitle: 'Qué es', pairs: [
            { id: 'rio', left: 'Cumbre de la Tierra, Río de Janeiro, 1992', leftIcon: 'Globe', right: 'Reunión mundial que impulsó el desarrollo sostenible' },
            { id: 'par', left: 'Acuerdo de París, 2015', leftIcon: 'Thermometer', right: 'Compromiso de los países para frenar el calentamiento global' },
            { id: 'sos', left: 'Desarrollo sostenible', leftIcon: 'Recycle', right: 'Progreso económico, justo con las personas y que cuida el ambiente' },
            { id: 'coo', left: 'Cooperativa que vende café orgánico bajo sombra', leftIcon: 'Coffee', right: 'Ejemplo local de actividad económica sostenible e incluyente' },
          ] },
        ),
        S.number(
          { fase: 'aplicar', areas: ['mat', 'cnt'], cnb: ['mat:7.2.1'], ambito: 'hacer',
            prompt: 'Ese mismo día, al mediodía, el termómetro subió a **18 °C**. Si en la madrugada marcó **−3 °C**, ¿cuántos grados **subió** la temperatura?',
            hint: 'Del −3 al 0 hay 3 grados; del 0 al 18, otros 18.',
            explain: '3 + 18 = 21 grados. Entre una temperatura bajo cero y otra sobre cero, suma las distancias al 0.' },
          { answer: 21, unit: '°C', misconceptions: [{ value: 15, msg: 'Restaste 18 − 3, pero el −3 está por debajo del 0: suma las distancias al cero.' }] },
        ),
        S.number(
          { fase: 'comprobar', areas: ['mat'], cnb: ['mat:7.2.1'], prompt: 'Boleto de salida: en San Marcos, la temperatura estaba en **2 °C** y bajó **5 grados** durante la noche. ¿Qué temperatura marcó? (usa el signo menos si es bajo cero)' },
          { answer: -3, unit: '°C', allowNegative: true, misconceptions: [{ value: 3, msg: 'Pasó por el 0 y siguió bajando: la temperatura queda bajo cero, con signo menos.' }, { value: 7, msg: 'La temperatura bajó: resta, no sumes.' }] },
        ),
        S.choice(
          { fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:6.2.4', 'cnt:6.3.4'], prompt: '¿Qué acción **previene** mejor los deslaves en una aldea?' },
          { options: [
            { id: 'a', text: 'Reforestar las laderas y no construir en ellas' },
            { id: 'b', text: 'Talar árboles para tener más espacio', feedback: 'Sin árboles, las raíces no sostienen el suelo y el riesgo aumenta.' },
            { id: 'c', text: 'Esperar a que pase y luego limpiar', feedback: 'Eso es responder, no prevenir.' },
          ], correct: ['a'] },
        ),
        cierre({ areas: ['cnt', 'pyd'], cnb: ['pyd:5.1.1'] }, ['Relaciono el ambiente con la calidad de vida', 'Sé qué hacer para prevenir un desastre', 'Leo temperaturas bajo cero y sobre cero'],
          ['Haré con mi familia un plan de emergencia', 'Sembraré o cuidaré un árbol', 'Anotaré la temperatura de mi comunidad durante una semana']),
      ],
    }),

    /* ───────────────────────── Día 2 ───────────────────────── */
    lesson({
      id: 's36-d2-mundo-integra',
      title: 'Un mundo que se integra y convive',
      icon: 'Handshake',
      minutes: 15,
      day: 2,
      gancho: '¿Sabías que con tu DPI (cuando seas mayor) podrás viajar a El Salvador, Honduras y Nicaragua sin pasaporte?',
      objetivos: ['Identificar zonas de mayor y menor desarrollo en el mundo', 'Reconocer esfuerzos de las naciones y de los pueblos indígenas por fortalecer la democracia', 'Investigar efectos de los procesos de integración', 'Identificar valores de convivencia pacífica y señales de otras culturas'],
      resumen: [
        'El desarrollo se mide con educación, salud, esperanza de vida, ingresos y servicios. Hay zonas de mayor desarrollo (como Norteamérica, Europa occidental, Japón y Australia) y zonas con menor desarrollo en partes de África, Asia y América Latina.',
        'Las naciones fortalecen la democracia con elecciones libres, observación electoral, constituciones, acuerdos como la Carta Democrática Interamericana (2001) y el respeto a los derechos humanos.',
        'Los procesos de integración (como el SICA y el acuerdo CA-4 en Centroamérica, o la Unión Europea) facilitan el comercio, el libre tránsito y la cooperación, pero también traen retos para los pequeños productores.',
        'Los pueblos indígenas han participado en movimientos sociales: el levantamiento de Totonicapán de 1820 (Atanasio Tzul y Lucas Aguilar) contra los tributos y la participación en los Acuerdos de Paz, como el Acuerdo sobre Identidad y Derechos de los Pueblos Indígenas (1995).',
        'Principios de convivencia pacífica: respeto, diálogo, tolerancia, solidaridad, justicia y equidad.',
      ],
      media: {
        id: 's36-d2-mapa', kind: 'image', title: 'Mapa del desarrollo en el mundo', aspect: '16:9',
        alt: 'Mapamundi coloreado en tres tonos de verde según el nivel de desarrollo humano, con íconos de escuela, hospital y esperanza de vida.',
        brief: 'Mapamundi (proyección amigable) coloreado en tres tonos de un mismo color: verde oscuro "desarrollo alto", verde medio "desarrollo medio", verde claro "desarrollo bajo", basado en rangos generales del Índice de Desarrollo Humano (sin cifras por país). Leyenda con tres íconos: birrete (educación), corazón (salud y esperanza de vida), moneda (ingresos). Centroamérica destacada con un recuadro. Evitar imágenes de pobreza o estereotipos; solo el mapa y los íconos.',
      },
      steps: [
        S.explain(
          { fase: 'explorar', areas: ['ccss', 'mat'], cnb: ['ccss:6.6.9'], ambito: 'conocer', title: '¿Cómo se mide el desarrollo?',
            prompt: 'La sección internacional del periódico explica por qué algunas zonas del mundo tienen **más desarrollo** que otras. Toca cada tarjeta.' },
          { icon: 'Globe', body: 'El desarrollo no se mide solo con dinero: importa que las personas vivan **sanas**, **estudien** y tengan **oportunidades**.', reveal: [
            { icon: 'GraduationCap', front: 'Educación', back: '¿Cuántos años estudian, en promedio, las personas?' },
            { icon: 'HeartPulse', front: 'Salud', back: '¿Cuántos años vive, en promedio, una persona (esperanza de vida)?' },
            { icon: 'Coins', front: 'Ingresos', back: '¿Alcanza lo que gana una familia para vivir dignamente?' },
            { icon: 'Map', front: 'Zonas', back: '**Mayor desarrollo**: Norteamérica, Europa occidental, Japón, Australia. **Menor desarrollo**: partes de África, Asia y América Latina. Guatemala tiene un desarrollo **medio**, con grandes diferencias entre regiones.' },
          ] },
        ),
        S.reading(
          { fase: 'construir', areas: ['fc', 'ccss'], cnb: ['ccss:6.7.3', 'fc:5.1.7'], ambito: 'conocer',
            prompt: 'Lee el artículo de la sección "Mundo y democracia" y responde.' },
          { genre: 'Artículo periodístico', heading: 'Pueblos que luchan por la democracia', passage:
            'En muchas partes del mundo, las personas han luchado para elegir a sus gobernantes y hacer respetar sus derechos. En **1989** cayó el Muro de Berlín y varios países de Europa del Este eligieron gobiernos por voto. En **1994**, Sudáfrica celebró sus primeras elecciones en las que votaron todas las personas sin importar su color de piel, y Nelson Mandela fue elegido presidente.\n\nEn América, los países firmaron en **2001** la **Carta Democrática Interamericana**, que dice que los pueblos tienen derecho a la democracia. En Guatemala, la Constitución de **1985** abrió una nueva etapa democrática.\n\nLos **pueblos indígenas** también han participado en movimientos sociales. En **1820**, en Totonicapán, **Atanasio Tzul** y **Lucas Aguilar** encabezaron un levantamiento contra los tributos injustos. En el proceso de paz, las organizaciones indígenas impulsaron el **Acuerdo sobre Identidad y Derechos de los Pueblos Indígenas** (1995).',
            questions: [
              { q: '¿Qué ocurrió en Sudáfrica en 1994?', options: [
                { id: 'a', text: 'Primeras elecciones en las que votaron todas las personas sin importar su color de piel' },
                { id: 'b', text: 'Cayó el Muro de Berlín' },
                { id: 'c', text: 'Se firmó la Carta Democrática Interamericana' },
              ], correct: 'a' },
              { q: '¿Contra qué se levantaron Atanasio Tzul y Lucas Aguilar en 1820?', options: [
                { id: 'a', text: 'Contra los tributos injustos' },
                { id: 'b', text: 'Contra la Carta Democrática' },
                { id: 'c', text: 'Contra la reforestación' },
              ], correct: 'a' },
              { q: '¿Qué idea tienen en común todos los hechos del artículo?', options: [
                { id: 'a', text: 'Son esfuerzos de los pueblos por la democracia y la justicia' },
                { id: 'b', text: 'Todos ocurrieron el mismo año' },
                { id: 'c', text: 'Son hechos deportivos' },
              ], correct: 'a', why: 'Comparar los hechos permite concluir que la democracia se fortalece con la participación de los pueblos.' },
            ] },
        ),
        S.sort(
          { fase: 'construir', areas: ['fc', 'ccss', 'pyd'], cnb: ['fc:5.2.4'], ambito: 'conocer',
            prompt: 'Investiga los **efectos de la integración centroamericana** (SICA, acuerdo CA-4). ¿Cada efecto es una **ventaja** o un **reto**?',
            explain: 'La integración trae oportunidades, pero exige políticas que protejan a quienes pueden quedar en desventaja, como los pequeños productores.',
            media: { id: 's36-d2-ca4', kind: 'diagram', title: 'Centroamérica integrada', aspect: '4:3',
              alt: 'Mapa de Centroamérica con Guatemala, El Salvador, Honduras y Nicaragua unidos por una línea punteada y un documento de identidad; flechas de comercio entre los países del SICA.',
              brief: 'Mapa esquemático de Centroamérica. Guatemala, El Salvador, Honduras y Nicaragua resaltados en un mismo color con un ícono de documento de identidad y el rótulo "CA-4: libre tránsito con documento de identidad". Todos los países del SICA (incluidos Belice, Costa Rica, Panamá y República Dominicana en un recuadro) con flechas de comercio (camiones, barcos). Leyenda: "SICA: Sistema de la Integración Centroamericana". Colores suaves, sin banderas detalladas.' } },
          { buckets: [
            { id: 'ven', label: 'Ventaja', icon: 'ThumbsUp', color: 'var(--c-ok)' },
            { id: 'ret', label: 'Reto', icon: 'Construction', color: 'var(--c-hint)' },
          ], items: [
            { id: 'i1', text: 'Viajar entre los países del CA-4 solo con documento de identidad', bucket: 'ven' },
            { id: 'i2', text: 'Vender productos guatemaltecos en más mercados de la región', bucket: 'ven' },
            { id: 'i3', text: 'Cooperar entre países ante huracanes y otros desastres', bucket: 'ven' },
            { id: 'i4', text: 'Pequeños productores compiten con empresas grandes de otros países', bucket: 'ret' },
            { id: 'i5', text: 'Controlar juntos el paso de mercancías ilegales por las fronteras', bucket: 'ret' },
          ] },
        ),
        S.dilemma(
          { fase: 'aplicar', areas: ['ccss', 'fc'], cnb: ['ccss:7.1.1'], ambito: 'convivir',
            prompt: 'En la redacción también hay que **convivir en paz**. ¿Qué harías?' },
          { scene: { icon: 'Newspaper', text: 'Dos equipos quieren la portada: uno con la noticia de la reforestación y otro con el campeonato de fútbol. **Brenda** y **Óscar** discuten a gritos.' }, options: [
            { id: 'a', icon: 'Megaphone', text: 'Que gane quien grite más fuerte', consequence: 'Un equipo se siente humillado y deja de trabajar. El periódico sale tarde.', values: ['Imposición'], constructive: false },
            { id: 'b', icon: 'MessagesSquare', text: 'Proponer que cada equipo explique sus razones y votar con toda la redacción', consequence: 'Todos escuchan con respeto; la mayoría elige la reforestación para la portada y el fútbol va en la contraportada con foto grande. Nadie queda fuera.', values: ['Diálogo', 'Respeto', 'Democracia'], constructive: true },
            { id: 'c', icon: 'Handshake', text: 'Buscar una solución creativa: una portada dividida con las dos noticias', consequence: 'Los dos equipos colaboran en el diseño. La solución justa fortalece la amistad.', values: ['Solidaridad', 'Equidad', 'Creatividad'], constructive: true },
          ] },
        ),
        S.match(
          { fase: 'aplicar', areas: ['l3', 'ccss'], cnb: ['l3:5.1.1'], ambito: 'conocer',
            prompt: 'English time! La sección internacional muestra **symbols and signs** que se usan en otras culturas y en todo el mundo. Une cada símbolo con su significado en inglés.',
            explain: 'Algunos símbolos se entienden en casi todo el mundo. La Cruz Roja y la Media Luna Roja (usada en muchos países musulmanes) significan ayuda humanitaria.' },
          { leftTitle: 'Symbol', rightTitle: 'Meaning', pairs: [
            { id: 'rec', left: 'Three green arrows in a triangle', leftIcon: 'Recycle', right: 'Recycle' },
            { id: 'cru', left: 'Red cross or red crescent', leftIcon: 'Plus', right: 'Medical and humanitarian help' },
            { id: 'ext', left: 'Green sign with a running person', leftIcon: 'PersonStanding', right: 'Emergency exit' },
            { id: 'oli', left: 'Five interlaced rings', leftIcon: 'Circle', right: 'Olympic Games: union of the continents' },
          ] },
        ),
        S.choice(
          { fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:6.6.9', 'ccss:6.7.3'], prompt: 'Boleto de salida: ¿qué indicadores se usan para saber si una zona tiene mayor o menor desarrollo?' },
          { options: [
            { id: 'a', text: 'Educación, salud (esperanza de vida) e ingresos' },
            { id: 'b', text: 'La cantidad de volcanes y lagos', feedback: 'El paisaje no mide el desarrollo de las personas.' },
            { id: 'c', text: 'El color de la bandera', feedback: 'La bandera no dice nada sobre la calidad de vida.' },
          ], correct: ['a'] },
        ),
        S.tf(
          { fase: 'comprobar', areas: ['fc', 'ccss'], cnb: ['fc:5.1.7', 'fc:5.2.4', 'ccss:7.1.1'], prompt: '¿Verdadero o falso?' },
          { statements: [
            { text: 'Atanasio Tzul participó en un levantamiento indígena en Totonicapán en 1820.', answer: true },
            { text: 'El acuerdo CA-4 obliga a usar pasaporte para viajar entre Guatemala y Honduras.', answer: false, why: 'Permite viajar con documento de identidad.' },
            { text: 'El diálogo y la tolerancia son principios de la convivencia pacífica.', answer: true },
          ] },
        ),
        cierre({ areas: ['fc', 'ccss'], cnb: ['ccss:7.1.1'] }, ['Explico cómo se mide el desarrollo', 'Doy ejemplos de esfuerzos por la democracia', 'Valoro la participación de los pueblos indígenas', 'Resuelvo desacuerdos con diálogo'],
          ['Buscaré en casa un producto de otro país centroamericano', 'Preguntaré qué sabe mi familia de Atanasio Tzul', 'Propondré una votación cuando mi grupo no se ponga de acuerdo']),
      ],
    }),

    /* ───────────────────────── Día 3 ───────────────────────── */
    lesson({
      id: 's36-d3-palabras-viajan',
      title: 'Palabras que viajan y riman',
      icon: 'Languages',
      minutes: 15,
      day: 3,
      gancho: '¿Sabías que "chocolate", "tomate" y "aguacate" vienen de un idioma de Mesoamérica, y "almohada", del árabe?',
      objetivos: ['Reconocer variaciones lingüísticas y ampliar tu vocabulario con palabras de otras culturas', 'Conjugar verbos regulares e irregulares en tiempos simples y compuestos', 'Identificar la rima consonante y asonante y crear un poema respetando las normas del idioma', 'Escribir párrafos en inglés con conectores'],
      resumen: [
        'Neologismo: palabra nueva (chatear, wifi). Tecnicismo: palabra de una ciencia u oficio (reforestación, fotosíntesis). Regionalismo: palabra de una región (en Guatemala: patojo, chucho, pisto). Modismo: expresión con sentido especial (echar la mano, estar en la luna).',
        'El español se enriqueció con palabras de otras culturas: del náhuatl (chocolate, tomate), del taíno (huracán, canoa), del árabe (almohada, azúcar) y del inglés (fútbol).',
        'Cada idioma tiene sus normas: en español se usan las tildes y la ortografía de la RAE; los idiomas mayas tienen alfabetos oficiales de la Academia de Lenguas Mayas de Guatemala. Respetarlas es respetar a sus hablantes.',
        'Verbos: tiempos simples (sembramos, sembraremos) y compuestos con haber (hemos sembrado); regulares (plantar) e irregulares (ir, tener, hacer).',
        'Rima consonante: se repiten vocales y consonantes desde la última vocal acentuada (flores / colores). Rima asonante: solo las vocales (montaña / mañana).',
      ],
      media: {
        id: 's36-d3-viaje', kind: 'animation', title: 'El viaje de las palabras', aspect: '16:9', duration: 60,
        alt: 'Animación de un mapa donde palabras viajan como barcos y aviones: "chocolate" sale de México, "huracán" del Caribe, "almohada" de la península ibérica y "fútbol" de Inglaterra.',
        brief: 'Animación 2D de 60 s con mapamundi estilo antiguo. Globos de texto con palabras salen de su lugar de origen y llegan a Guatemala: CHOCOLATE y TOMATE (náhuatl, centro de México), HURACÁN y CANOA (taíno, Caribe), ALMOHADA y AZÚCAR (árabe, llegan a través de España), FÚTBOL (inglés, Inglaterra). Al final, todas forman una nube de palabras sobre Guatemala junto a palabras regionales (patojo, chucho, pisto). Narración infantil y subtítulos.',
      },
      steps: [
        S.explain(
          { fase: 'explorar', areas: ['l1'], cnb: ['l1:6.1.4'], ambito: 'conocer', title: 'Palabras nuevas, técnicas y nuestras',
            prompt: 'La sección "Palabras" del periódico presenta las **variaciones lingüísticas**. Toca cada tarjeta.' },
          { icon: 'MessageCircle', body: 'La lengua **cambia** y **varía** según la época, el lugar y el tema.', reveal: [
            { icon: 'Sparkles', front: 'Neologismo', back: 'Palabra **nueva**: chatear, wifi, bloguero.' },
            { icon: 'FlaskConical', front: 'Tecnicismo', back: 'Palabra de una **ciencia u oficio**: reforestación, erosión, fotosíntesis.' },
            { icon: 'MapPin', front: 'Regionalismo', back: 'Palabra propia de una **región**: en Guatemala, patojo (niño), chucho (perro), pisto (dinero), chumpa (chaqueta).' },
            { icon: 'Smile', front: 'Modismo', back: 'Expresión con **sentido especial**, no literal: "echar la mano" (ayudar), "estar en la luna" (estar distraído).' },
          ] },
        ),
        S.sort(
          { fase: 'construir', areas: ['l1'], cnb: ['l1:6.1.4'], ambito: 'conocer',
            prompt: 'Clasifica las palabras y expresiones que usaron los redactores.',
            hint: '¿Es nueva por la tecnología? ¿Es de una ciencia? ¿Se usa sobre todo en Guatemala? ¿Es una frase con sentido figurado?' },
          { layout: 'grid2', buckets: [
            { id: 'neo', label: 'Neologismo', icon: 'Sparkles' },
            { id: 'tec', label: 'Tecnicismo', icon: 'FlaskConical' },
            { id: 'reg', label: 'Regionalismo', icon: 'MapPin' },
            { id: 'mod', label: 'Modismo', icon: 'Smile' },
          ], items: [
            { id: 'w1', text: 'tuitear', bucket: 'neo' },
            { id: 'w2', text: 'deforestación', bucket: 'tec' },
            { id: 'w3', text: 'patojo', bucket: 'reg' },
            { id: 'w4', text: 'echar la mano', bucket: 'mod' },
            { id: 'w5', text: 'infiltración', bucket: 'tec' },
            { id: 'w6', text: 'pisto', bucket: 'reg' },
            { id: 'w7', text: 'estar en la luna', bucket: 'mod' },
            { id: 'w8', text: 'wifi', bucket: 'neo' },
          ] },
        ),
        S.match(
          { fase: 'construir', areas: ['l1', 'ccss'], cnb: ['l1:6.3.2'], ambito: 'conocer',
            prompt: 'Amplía tu vocabulario: une cada palabra con la **cultura** de la que llegó al español.',
            explain: 'El español que hablamos en Guatemala es una mezcla de aportes de muchas culturas. Además, convive con 22 idiomas mayas, el garífuna y el xinka, que también nos prestan palabras.' },
          { leftTitle: 'Palabra', rightTitle: 'Origen', pairs: [
            { id: 'cho', left: 'chocolate, tomate, aguacate', leftIcon: 'Coffee', right: 'Náhuatl (Mesoamérica)' },
            { id: 'hur', left: 'huracán, canoa, hamaca', leftIcon: 'Wind', right: 'Taíno (Caribe)' },
            { id: 'alm', left: 'almohada, azúcar, ojalá', leftIcon: 'Moon', right: 'Árabe' },
            { id: 'fut', left: 'fútbol, sándwich', leftIcon: 'Trophy', right: 'Inglés' },
          ] },
        ),
        S.fill(
          { fase: 'construir', areas: ['l1', 'cnt'], cnb: ['l1:7.1.3'], ambito: 'hacer',
            prompt: 'Completa la noticia con los **verbos** conjugados en modo indicativo. Fíjate en el tiempo: ayer (pretérito), hasta hoy (compuesto con "haber"), el próximo año (futuro).',
            explain: '"Sembramos" y "sembraremos" son tiempos simples; "hemos sembrado" es un tiempo compuesto (haber + participio). "Ir" y "tener" son irregulares: cambian su raíz (fuimos, tendrá).' },
          { text: 'Ayer los estudiantes de sexto [[sembraron]] 200 pinos en el bosque comunal.\nHasta hoy, la escuela [[ha sembrado]] más de mil árboles.\nEl sábado pasado [[fuimos]] a regar los arbolitos.\nEl próximo año, el bosque [[tendrá]] más sombra y agua.', distractors: ['siembra', 'iremos', 'tuvo'] },
        ),
        S.explain(
          { fase: 'construir', areas: ['l2', 'l1'], cnb: ['l2:5.3.6'], ambito: 'conocer', title: 'Dos clases de rima',
            prompt: 'La página de poesía del periódico usa **rima**. Descubre sus dos clases.' },
          { icon: 'Music2', body: 'La rima es la repetición de sonidos al **final** de los versos, desde la **última vocal acentuada**.', reveal: [
            { icon: 'Copy', front: 'Rima consonante', back: 'Se repiten **vocales y consonantes**: flor**es** / col**ores**, cam**ino** / dest**ino**.' },
            { icon: 'Volume2', front: 'Rima asonante', back: 'Solo se repiten las **vocales**: mont**a**ñ**a** / mañ**a**n**a** → a-a; b**o**squ**e** / n**o**ch**e** → o-e.' },
            { icon: 'Languages', front: 'En idiomas mayas', back: 'Más que la rima, la poesía maya usa el **paralelismo** y el ritmo que da el orden de las palabras.' },
          ] },
        ),
        S.write(
          { fase: 'aplicar', areas: ['l2', 'l1', 'cnt'], cnb: ['l2:5.3.7', 'l1:6.3.3'], ambito: 'hacer',
            prompt: 'Crea un **poema** de 4 versos sobre el bosque para el periódico. Usa al menos una **rima** (consonante o asonante), una imagen o comparación, y cuida las **normas** del idioma (tildes, mayúsculas). Si hablas un idioma maya, puedes agregar un paralelismo en ese idioma.' },
          { minWords: 16, placeholder: 'Verso 1…\nVerso 2…\nVerso 3…\nVerso 4…',
            model: 'En el cerro canta el pino,\nverde abrazo del camino;\nsi lo cuidas, da agua clara,\nsi lo cuidas, nos ampara.',
            rubric: ['Escribí 4 versos', 'Usé al menos una rima (pino / camino es consonante)', 'Incluí una imagen, comparación o paralelismo', 'Revisé tildes, mayúsculas y puntuación'] },
        ),
        S.order(
          { fase: 'aplicar', areas: ['l3', 'cnt'], cnb: ['l3:4.2.4'], ambito: 'hacer',
            prompt: 'English time! Ordena las oraciones para formar un **párrafo coherente**. Fíjate en los conectores: _First_, _Then_, _Because_, _Finally_.',
            explain: 'Los conectores dan orden y lógica: _First_ (primero), _Then_ (luego), _because_ (porque), _Finally_ (finalmente).' },
          { items: [
            { id: 'e1', text: 'First, we dug small holes on the hill.' },
            { id: 'e2', text: 'Then, we planted fifty young pine trees.' },
            { id: 'e3', text: 'We watered them because the soil was dry.' },
            { id: 'e4', text: 'Finally, we wrote a news story for our school paper.' },
          ], labels: { start: 'Start', end: 'End' } },
        ),
        S.sort(
          { fase: 'comprobar', areas: ['l2'], cnb: ['l2:5.3.6'], prompt: 'Boleto de salida: ¿rima consonante o asonante?' },
          { buckets: [
            { id: 'con', label: 'Consonante', icon: 'Copy' },
            { id: 'aso', label: 'Asonante', icon: 'Volume2' },
          ], items: [
            { id: 'q1', text: 'canción / corazón', bucket: 'con' },
            { id: 'q2', text: 'montaña / mañana', bucket: 'aso' },
            { id: 'q3', text: 'ventana / campana', bucket: 'con' },
            { id: 'q4', text: 'bosque / noche', bucket: 'aso' },
          ] },
        ),
        S.choice(
          { fase: 'comprobar', areas: ['l1'], cnb: ['l1:6.1.4', 'l1:6.3.2'], prompt: 'En "Los patojos echaron la mano para sembrar", ¿qué tipo de palabras son "patojos" y "echaron la mano"?' },
          { options: [
            { id: 'a', text: 'Un regionalismo y un modismo' },
            { id: 'b', text: 'Un tecnicismo y un neologismo', feedback: '"Patojo" no es de una ciencia ni es nueva: es una palabra de Guatemala.' },
            { id: 'c', text: 'Dos palabras del árabe', feedback: 'Son formas propias del español de Guatemala.' },
          ], correct: ['a'] },
        ),
        cierre({ areas: ['l1', 'l2'], cnb: ['l1:6.3.3'] }, ['Reconozco neologismos, tecnicismos, regionalismos y modismos', 'Conjugo verbos regulares e irregulares', 'Distingo rima consonante y asonante', 'Escribo un párrafo en inglés con conectores'],
          ['Anotaré tres palabras de otro idioma que uso a diario', 'Respetaré las normas de escritura de los idiomas que hablo', 'Escribiré otro poema con rima para el periódico']),
      ],
    }),

    /* ───────────────────────── Día 4 ───────────────────────── */
    lesson({
      id: 's36-d4-periodico-tiempo',
      title: 'Nuestro periódico y la cuenta del tiempo',
      icon: 'CalendarDays',
      minutes: 15,
      day: 4,
      gancho: 'Si los mayas hubieran tenido periódico, ¿cómo habrían escrito la fecha de hoy?',
      objetivos: ['Organizar el periódico del aula con editorial y secciones, y participar con entusiasmo en los proyectos de la escuela', 'Calcular fechas en la Cuenta Larga maya', 'Usar zonas de luz y sombra en una ilustración', 'Organizar juegos con hábitos de higiene, buena postura y relajación'],
      resumen: [
        'Un periódico del aula tiene editorial (la opinión del periódico), noticias, entrevistas, cultura, deportes y entretenimiento.',
        'Cuenta Larga maya: k’in = 1 día; winal = 20 k’in; tun = 18 winal = 360 días; k’atun = 20 tun = 7,200 días; b’ak’tun = 20 k’atun = 144,000 días.',
        'El 21 de diciembre de 2012 terminó el b’ak’tun 13: la fecha fue 13.0.0.0.0. Para otra fecha, cuenta los días desde entonces y agrúpalos en tun, winal y k’in.',
        'Zonas de luz y sombra: zona iluminada, penumbra, sombra propia, reflejo y sombra arrojada.',
        'Antes del juego: calentar, hidratarse y usar ropa cómoda; durante: tomar agua y respetar las reglas; después: estirar, relajarse y asearse (lavarse, cambiarse la camisa).',
      ],
      media: {
        id: 's36-d4-cuentalarga', kind: 'diagram', title: 'Las unidades de la Cuenta Larga', aspect: '4:3',
        alt: 'Escalera de cinco peldaños con glifos simplificados: k’in, winal, tun, k’atun y b’ak’tun, cada uno con su número de días.',
        brief: 'Diagrama en forma de escalera o columna maya con 5 niveles, de abajo hacia arriba: K’IN (1 día, sol estilizado), WINAL (20 días), TUN (360 días), K’ATUN (7,200 días), B’AK’TUN (144,000 días). Flechas entre niveles con "× 20", excepto entre winal y tun con "× 18". A un lado, la fecha 13.0.0.0.0 = "21 de diciembre de 2012" con numeración maya de barras y puntos. Glifos simplificados y respetuosos, no copias de estelas reales. Colores tierra y turquesa.',
      },
      steps: [
        S.match(
          { fase: 'explorar', areas: ['l2', 'l1'], cnb: ['l2:5.4.4'], ambito: 'conocer',
            prompt: 'Es hora de armar **El Eco del Futuro**. Une cada **sección** del periódico con lo que va en ella.',
            explain: 'El editorial se diferencia de las noticias: en la noticia se informan hechos; en el editorial, el periódico da su opinión y la argumenta.' },
          { leftTitle: 'Sección', rightTitle: 'Contenido', pairs: [
            { id: 'edi', left: 'Editorial', leftIcon: 'PenLine', right: 'Opinión del periódico: "Cuidar el bosque es cuidar el agua"' },
            { id: 'not', left: 'Noticias', leftIcon: 'Newspaper', right: 'Sexto grado sembró 200 pinos el sábado' },
            { id: 'ent', left: 'Entrevista', leftIcon: 'Mic', right: 'Preguntas y respuestas con el guardabosques comunal' },
            { id: 'cul', left: 'Cultura', leftIcon: 'Palette', right: 'La Cuenta Larga maya y un poema sobre el bosque' },
            { id: 'dep', left: 'Deportes', leftIcon: 'Trophy', right: 'Resultados del torneo de juegos tradicionales' },
          ] },
        ),
        S.cards(
          { fase: 'construir', areas: ['mat', 'ccss'], cnb: ['mat:7.3.1'], ambito: 'conocer', title: 'Las unidades de la Cuenta Larga',
            prompt: 'La página cultural explica la **Cuenta Larga**, el sistema maya para contar muchísimos días desde una fecha inicial. Voltea cada tarjeta.' },
          { cards: [
            { icon: 'Sun', front: 'K’in', back: '**1 día**.' },
            { icon: 'Calendar', front: 'Winal', back: '**20 k’in** = 20 días.' },
            { icon: 'CalendarDays', front: 'Tun', back: '**18 winal** = 360 días (¡aquí se multiplica por 18, no por 20!).' },
            { icon: 'Layers', front: 'K’atun', back: '**20 tun** = 7,200 días (casi 20 años).' },
            { icon: 'Hourglass', front: 'B’ak’tun', back: '**20 k’atun** = 144,000 días (casi 400 años).' },
            { icon: 'Star', front: '13.0.0.0.0', back: 'El **21 de diciembre de 2012** se completó el b’ak’tun 13. ¡No fue el fin del mundo, sino el inicio de un nuevo ciclo!' },
            { icon: 'Calculator', front: 'Ejemplo: un año después', back: 'Del 21-12-2012 al 21-12-2013 pasaron **365 días** = 1 tun (360) + 0 winal + 5 k’in. La fecha maya fue **13.0.1.0.5**.' },
          ] },
        ),
        S.match(
          { fase: 'construir', areas: ['art', 'cnt'], cnb: ['art:3.2.6'], ambito: 'conocer',
            prompt: 'La ilustración de portada muestra una **jícara** iluminada por el sol. Une cada **zona de luz y sombra** con su descripción.',
            explain: 'Observar las zonas de luz y sombra hace que un dibujo se vea con volumen, como si se pudiera tocar.',
            media: { id: 's36-d4-luces', kind: 'diagram', title: 'Luces y sombras en una jícara', aspect: '4:3',
              alt: 'Jícara redonda sobre una mesa, iluminada desde arriba a la izquierda, con cinco zonas señaladas: iluminada, penumbra, sombra propia, reflejo y sombra arrojada.',
              brief: 'Ilustración a lápiz o carboncillo de una jícara (o esfera) sobre una mesa de madera, con una fuente de luz (sol) arriba a la izquierda. Cinco flechas y rótulos: ZONA ILUMINADA (parte más clara, frente a la luz), PENUMBRA (transición gris suave), SOMBRA PROPIA (lado opuesto a la luz, sobre el objeto), REFLEJO (franja un poco más clara en el borde oscuro, por la luz que rebota de la mesa), SOMBRA ARROJADA (sombra sobre la mesa, hacia la derecha). Fondo neutro.' } },
          { leftTitle: 'Zona', rightTitle: 'Descripción', pairs: [
            { id: 'ilu', left: 'Zona iluminada', right: 'La parte más clara, de frente a la luz' },
            { id: 'pen', left: 'Penumbra', right: 'El paso suave de la luz a la sombra' },
            { id: 'pro', left: 'Sombra propia', right: 'La parte oscura del mismo objeto, opuesta a la luz' },
            { id: 'ref', left: 'Reflejo', right: 'Luz que rebota de la mesa y aclara el borde oscuro' },
            { id: 'arr', left: 'Sombra arrojada', right: 'La sombra que el objeto proyecta sobre la mesa' },
          ] },
        ),
        S.maya(
          { fase: 'aplicar', areas: ['mat', 'ccss'], cnb: ['mat:7.3.1'], ambito: 'hacer',
            prompt: 'Del 21 de diciembre de 2012 al 21 de diciembre de **2022** pasaron **3,652 días** (10 años con dos años bisiestos). Construye 3,652 en la Cuenta Larga.',
            hint: 'Primero, ¿cuántos tun de 360 caben en 3,652? Luego reparte lo que sobra en winal de 20.',
            explain: '3,652 = 10 tun (3,600) + 2 winal (40) + 12 k’in. La fecha maya del 21 de diciembre de 2022 fue 13.0.10.2.12.' },
          { mode: 'build', target: 3652, levels: 3, scaffold: true, longCount: true },
        ),
        S.sort(
          { fase: 'aplicar', areas: ['ef', 'cnt'], cnb: ['ef:3.1.1', 'ef:3.1.5', 'ef:2.2.3'], ambito: 'hacer',
            prompt: 'La sección de deportes organiza un **torneo de juegos tradicionales** (tenta, cincos, salto de cuerda). Promueve la higiene: ¿cuándo va cada hábito?',
            explain: 'Organizar un juego también es cuidar la salud de todos: calentar evita lesiones, el agua evita la deshidratación y el aseo después evita enfermedades de la piel y resfríos.' },
          { buckets: [
            { id: 'ant', label: 'Antes', icon: 'AlarmClock' },
            { id: 'dur', label: 'Durante', icon: 'Activity' },
            { id: 'des', label: 'Después', icon: 'Droplets' },
          ], items: [
            { id: 'h1', text: 'Calentar articulaciones y usar ropa cómoda', bucket: 'ant' },
            { id: 'h2', text: 'Revisar que la cancha no tenga piedras ni vidrios', bucket: 'ant' },
            { id: 'h3', text: 'Tomar agua en las pausas', bucket: 'dur' },
            { id: 'h4', text: 'Respetar las reglas y los turnos', bucket: 'dur' },
            { id: 'h5', text: 'Estirar y respirar profundo para relajarse', bucket: 'des' },
            { id: 'h6', text: 'Lavarse cara y manos y cambiarse la camisa sudada', bucket: 'des' },
          ] },
        ),
        S.pulse(
          { fase: 'aplicar', areas: ['ef', 'pyd'], cnb: ['ef:2.2.3', 'ef:3.1.5'], ambito: 'hacer',
            prompt: 'Organiza con tu grupo una ronda de **tenta**: elijan quién la lleva, marquen los límites y acuerden la regla de "casa". Jueguen, y luego haz la **relajación**: siéntate con la **espalda recta**, hombros relajados, inhala contando 4 y exhala contando 4. Mide tu pulso antes, después del juego y después de relajarte.' },
          { seconds: 15, rounds: [
            { label: 'En reposo' },
            { label: 'Después de la tenta', exercise: { name: 'Juego de tenta organizado por el grupo', icon: 'Footprints', seconds: 90 } },
            { label: 'Después de la relajación', exercise: { name: 'Respiración 4-4 con postura correcta', icon: 'Wind', seconds: 60 } },
          ] },
        ),
        S.write(
          { fase: 'aplicar', areas: ['l2', 'pyd', 'cnt'], cnb: ['l2:5.4.4', 'pyd:4.2.2'], ambito: 'emprender',
            prompt: 'Escribe el **editorial** de El Eco del Futuro: la opinión del periódico sobre el proyecto escolar de reforestación. Da tu opinión, una razón y una invitación a participar.' },
          { minWords: 40, placeholder: 'En El Eco del Futuro creemos que…',
            model: 'En El Eco del Futuro creemos que el proyecto de reforestación es lo más importante que hace nuestra escuela este año. Cada pino que sembramos protege un nacimiento de agua y evita deslaves en la época de lluvias. Por eso invitamos a todos los grados y a sus familias a sumarse el próximo sábado: traigan una pala, agua y muchas ganas. El futuro verde se construye entre todos.',
            rubric: ['Expreso una opinión clara del periódico', 'Doy al menos una razón con datos de la semana', 'Invito a participar en el proyecto', 'Uso un tono respetuoso y entusiasta'] },
        ),
        S.maya(
          { fase: 'comprobar', areas: ['mat'], cnb: ['mat:7.3.1'], prompt: 'Boleto de salida: lee este numeral de la **Cuenta Larga** (tun, winal, k’in) y escribe cuántos días representa.' },
          { mode: 'read', target: 405, longCount: true },
        ),
        S.choice(
          { fase: 'comprobar', areas: ['art', 'l2'], cnb: ['art:3.2.6'], prompt: 'En la ilustración de portada, ¿cómo se llama la sombra que la jícara proyecta **sobre la mesa**?' },
          { options: [
            { id: 'a', text: 'Sombra arrojada' },
            { id: 'b', text: 'Sombra propia', feedback: 'La sombra propia está sobre el mismo objeto.' },
            { id: 'c', text: 'Zona iluminada', feedback: 'La zona iluminada es la parte más clara del objeto.' },
          ], correct: ['a'] },
        ),
        cierre({ areas: ['mat', 'pyd'], cnb: ['pyd:4.2.2'] }, ['Organizo un periódico con editorial y secciones', 'Calculo fechas en la Cuenta Larga', 'Dibujo con luces y sombras', 'Organizo juegos cuidando la higiene y la postura'],
          ['Participaré con entusiasmo en el proyecto de reforestación de mi escuela', 'Calcularé la fecha maya de mi próximo cumpleaños', 'Me asearé siempre después de hacer ejercicio']),
      ],
    }),

    /* ───────────────────────── Día 5: Reto semanal ───────────────────────── */
    lesson({
      id: 's36-d5-reto',
      title: 'Reto de la semana 36',
      icon: 'Trophy',
      minutes: 14,
      day: 5,
      kind: 'reto',
      objetivos: ['Demostrar lo que aprendiste como redactor del futuro verde', 'Obtener la medalla "Redactor del futuro verde" (70 % o más)'],
      resumen: ['Superé el reto de la semana 36: ambiente, desastres, temperatura, mundo, democracia, palabras, rima, periódico, Cuenta Larga y luces y sombras.'],
      media: {
        id: 's36-d5-reto', kind: 'image', title: 'Medalla Redactor del futuro verde', aspect: '1:1',
        alt: 'Medalla dorada con un periódico enrollado del que brota un pino, y un pequeño glifo solar.',
        brief: 'Ilustración de medalla circular dorada 1024×1024: al centro un periódico enrollado del que brota un pino joven; arriba, un sol estilizado inspirado en el glifo k’in (simplificado, no copia de un original). Cinta con los colores de las áreas del CNB. Fondo transparente, sin texto.',
      },
      steps: [
        S.choice({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:6.1.4'], prompt: '¿Qué relación hay entre el ambiente y la calidad de vida?' },
          { options: [
            { id: 'a', text: 'Un ambiente contaminado causa enfermedades y afecta el bienestar' },
            { id: 'b', text: 'No hay ninguna relación' },
            { id: 'c', text: 'La basura quemada mejora el aire' },
          ], correct: ['a'] }),
        S.sort({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:6.3.4', 'cnt:6.2.4'], prompt: 'Clasifica: ¿actividad que se favorece con la reforestación o acción de prevención de desastres?' },
          { buckets: [{ id: 'r', label: 'Favorecida por reforestar', icon: 'Trees' }, { id: 'p', label: 'Prevención de desastres', icon: 'ShieldCheck' }],
            items: [
              { id: 'a', text: 'Producción de miel', bucket: 'r' },
              { id: 'b', text: 'Preparar una mochila de emergencia', bucket: 'p' },
              { id: 'c', text: 'Caminatas para observar aves', bucket: 'r' },
              { id: 'd', text: 'Practicar un simulacro', bucket: 'p' },
            ] }),
        S.slider({ fase: 'comprobar', areas: ['mat'], cnb: ['mat:7.2.1'], prompt: 'Marca en el termómetro **5 grados bajo cero**.' },
          { min: -10, max: 30, step: 1, start: 10, answer: -5, unit: '°C', visual: 'thermometer' }),
        S.choice({ fase: 'comprobar', areas: ['pyd'], cnb: ['pyd:5.1.1'], prompt: '¿Dónde y cuándo fue la Cumbre de la Tierra que impulsó el desarrollo sostenible?' },
          { options: [{ id: 'a', text: 'Río de Janeiro, 1992' }, { id: 'b', text: 'París, 1789' }, { id: 'c', text: 'Totonicapán, 1820' }], correct: ['a'] }),
        S.tf({ fase: 'comprobar', areas: ['ccss', 'fc'], cnb: ['ccss:6.6.9', 'ccss:6.7.3', 'fc:5.2.4'], prompt: '¿Verdadero o falso?' },
          { statements: [
            { text: 'La esperanza de vida es un indicador de desarrollo.', answer: true },
            { text: 'La Carta Democrática Interamericana dice que los pueblos de América tienen derecho a la democracia.', answer: true },
            { text: 'La integración centroamericana no tiene ninguna ventaja.', answer: false },
          ] }),
        S.match({ fase: 'comprobar', areas: ['l1'], cnb: ['l1:6.1.4', 'l1:6.3.2'], prompt: 'Une cada palabra con lo que es.' },
          { pairs: [
            { id: 'a', left: 'chucho', right: 'Regionalismo de Guatemala' },
            { id: 'b', left: 'erosión', right: 'Tecnicismo' },
            { id: 'c', left: 'huracán', right: 'Palabra de origen taíno' },
          ] }),
        S.fill({ fase: 'comprobar', areas: ['l1'], cnb: ['l1:7.1.3'], prompt: 'Completa con el verbo en el tiempo correcto.' },
          { text: 'Mañana nosotros [[iremos]] al bosque. Ya [[hemos sembrado]] cien árboles.', distractors: ['fuimos', 'sembrando'] }),
        S.choice({ fase: 'comprobar', areas: ['l2'], cnb: ['l2:5.3.6'], prompt: '"Sol" y "farol" riman porque repiten "-ol" (vocal y consonante). ¿Qué rima es?' },
          { options: [{ id: 'a', text: 'Consonante' }, { id: 'b', text: 'Asonante' }, { id: 'c', text: 'No riman' }], correct: ['a'] }),
        S.maya({ fase: 'comprobar', areas: ['mat'], cnb: ['mat:7.3.1'], prompt: 'Construye **730 días** en la Cuenta Larga (tun, winal, k’in).' },
          { mode: 'build', target: 730, levels: 3, longCount: true }),
        S.choice({ fase: 'comprobar', areas: ['l3'], cnb: ['l3:5.1.1'], prompt: 'What does a green sign with a running person mean?' },
          { options: [{ id: 'a', text: 'Emergency exit' }, { id: 'b', text: 'Recycle' }, { id: 'c', text: 'No running' }], correct: ['a'] }),
      ],
    }),
  ],

  /* Banco de ítems para la Semana de validación de la Unidad 4 (el primer área = área principal) */
  bank: [
    S.choice({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:6.2.4'], prompt: '¿Qué institución de Guatemala emite avisos para la reducción de desastres?' },
      { options: [{ id: 'a', text: 'CONRED' }, { id: 'b', text: 'El Tribunal Supremo Electoral' }, { id: 'c', text: 'La Contraloría General de Cuentas' }], correct: ['a'] }),
    S.number({ fase: 'comprobar', areas: ['mat'], cnb: ['mat:7.2.1'], prompt: 'En la madrugada la temperatura fue −4 °C y a mediodía 16 °C. ¿Cuántos grados subió?' },
      { answer: 20, unit: '°C' }),
    S.number({ fase: 'comprobar', areas: ['mat'], cnb: ['mat:7.3.1'], prompt: '¿Cuántos días tiene un k’atun?' },
      { answer: 7200, unit: 'días' }),
    S.choice({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:6.6.9'], prompt: '¿Cuál de estas zonas tiene, en general, un desarrollo humano alto?' },
      { options: [{ id: 'a', text: 'Europa occidental' }, { id: 'b', text: 'Ninguna zona del mundo' }, { id: 'c', text: 'Todas las zonas son iguales' }], correct: ['a'] }),
    S.choice({ fase: 'comprobar', areas: ['fc'], cnb: ['fc:5.1.7'], prompt: '¿Qué acuerdo de paz impulsaron las organizaciones indígenas en 1995?' },
      { options: [{ id: 'a', text: 'El Acuerdo sobre Identidad y Derechos de los Pueblos Indígenas' }, { id: 'b', text: 'El Acuerdo de París' }, { id: 'c', text: 'La Carta Democrática Interamericana' }], correct: ['a'] }),
    S.choice({ fase: 'comprobar', areas: ['fc', 'ccss'], cnb: ['fc:5.2.4', 'ccss:7.1.1'], prompt: '¿Qué permite el acuerdo CA-4?' },
      { options: [{ id: 'a', text: 'Viajar entre Guatemala, El Salvador, Honduras y Nicaragua con documento de identidad' }, { id: 'b', text: 'Usar la misma moneda en toda América' }, { id: 'c', text: 'Cerrar las fronteras' }], correct: ['a'] }),
    S.sort({ fase: 'comprobar', areas: ['l1'], cnb: ['l1:6.1.4'], prompt: '¿Modismo o neologismo?' },
      { buckets: [{ id: 'm', label: 'Modismo', icon: 'Smile' }, { id: 'n', label: 'Neologismo', icon: 'Sparkles' }],
        items: [{ id: 'a', text: 'estar en la luna', bucket: 'm' }, { id: 'b', text: 'chatear', bucket: 'n' }, { id: 'c', text: 'echar la mano', bucket: 'm' }, { id: 'd', text: 'bloguero', bucket: 'n' }] }),
    S.choice({ fase: 'comprobar', areas: ['l2'], cnb: ['l2:5.3.6'], prompt: '¿Qué par de palabras tiene rima asonante?' },
      { options: [{ id: 'a', text: 'casa / mañana' }, { id: 'b', text: 'camino / destino' }, { id: 'c', text: 'flores / colores' }], correct: ['a'] }),
    S.choice({ fase: 'comprobar', areas: ['l2'], cnb: ['l2:5.4.4'], prompt: '¿En qué sección del periódico va la opinión del periódico sobre un tema?' },
      { options: [{ id: 'a', text: 'Editorial' }, { id: 'b', text: 'Deportes' }, { id: 'c', text: 'Clasificados' }], correct: ['a'] }),
    S.choice({ fase: 'comprobar', areas: ['art'], cnb: ['art:3.2.6'], prompt: 'La parte más clara de un objeto, de frente a la luz, se llama…' },
      { options: [{ id: 'a', text: 'Zona iluminada' }, { id: 'b', text: 'Sombra arrojada' }, { id: 'c', text: 'Penumbra' }], correct: ['a'] }),
    S.choice({ fase: 'comprobar', areas: ['ef'], cnb: ['ef:3.1.1', 'ef:3.1.5', 'ef:2.2.3'], prompt: '¿Qué hábito conviene DESPUÉS de jugar?' },
      { options: [{ id: 'a', text: 'Estirar, relajarse y asearse' }, { id: 'b', text: 'Quedarse con la camisa sudada todo el día' }, { id: 'c', text: 'No tomar agua' }], correct: ['a'] }),
    S.order({ fase: 'comprobar', areas: ['l3'], cnb: ['l3:4.2.4'], prompt: 'Order the paragraph.' },
      { items: [{ id: 'a', text: 'First, we read the news.' }, { id: 'b', text: 'Then, we wrote our story.' }, { id: 'c', text: 'Finally, we printed the paper.' }] }),
  ],
});
