import { S, cierre, lesson, semana } from '../../dsl';

/**
 * SEMANA 38 · Unidad 4 "Fortaleciendo nuestro futuro"
 * Tema generador: Pronosticar el futuro, cuidarlo hoy
 * Predicciones, mitos y acciones contra el calentamiento global · calidad de vida, dinero y mapas
 * conceptuales · instituciones de la Constitución, fuentes en internet, puntuación y ortografía ·
 * historia del pueblo ladino, épocas de la música, juegos, roles y expresiones en inglés.
 */
export default semana({
  id: 's38',
  unidad: 4,
  semana: 38,
  kind: 'aprendizaje',
  temaGenerador: 'Pronosticar el futuro, cuidarlo hoy',
  title: 'Pronosticar el futuro, cuidarlo hoy',
  subtitle: 'Predecir con ciencia, vivir bien y conocer quién nos protege',
  icon: 'CloudSun',
  color: 'var(--area-cnt)',
  contexto: 'Zacapa está en el Corredor Seco de Guatemala: allí hace mucho calor, llueve poco y las familias cultivan melón, tomate y maíz a la orilla del río Motagua. Sexto grado de una escuela de Estanzuela organiza el "Festival del Futuro" con la municipalidad, el centro de salud y la Casa de la Cultura. Esta semana aprenderás a predecir con datos, a separar mitos de ciencia, a medir la calidad de vida, a conocer las instituciones que protegen tus derechos y a celebrar la historia, la música y los juegos que nos unen.',
  ejes: ['sostenible', 'vida-ciudadana', 'multiculturalidad', 'tecnologia'],
  media: {
    id: 's38-portada', kind: 'video', title: 'Festival del Futuro en Zacapa', aspect: '16:9', duration: 60,
    alt: 'Valle seco con cerros y cactus, un río, campos de melón, una escuela que prepara un festival con un termómetro gigante, carteles y una marimba.',
    brief: 'Video o animación 2D de 60 s. Escenas: (1) toma aérea del valle del Motagua en Zacapa: cerros secos con cactus y un río verde en medio; rótulo "Corredor Seco"; (2) niñas y niños de sexto con gorras miden la temperatura de dos frascos al sol y anotan en un cuaderno; (3) un aula donde pegan un mapa conceptual "Calidad de vida" y un cartel con los organismos del Estado; (4) el patio con una marimba, un trompo girando y un grupo que juega cambiando de rol (capitana, árbitro, anotador). Cierre con el texto "Pronosticar el futuro, cuidarlo hoy". Música de marimba alegre. Personajes ficticios, ladinos, mayas y garífunas, sin marcas comerciales.',
  },
  badge: { id: 'medalla-s38', name: 'Pronosticador del futuro', icon: 'CloudSun', desc: 'Completaste la semana 38 y superaste su reto' },
  lessons: [
    /* ───────────────────────── Día 1 ───────────────────────── */
    lesson({
      id: 's38-d1-predecir',
      title: 'Predecir con ciencia',
      icon: 'Thermometer',
      minutes: 14,
      day: 1,
      gancho: 'Cuando ves nubes negras sobre el cerro, dices "va a llover". ¿Cómo lo sabes? ¿Siempre aciertas?',
      objetivos: ['Formular predicciones a partir de lo que observas', 'Comprobar una predicción con un experimento', 'Explicar mitos con investigación científica', 'Proponer acciones contra el calentamiento global'],
      resumen: [
        'Una predicción es lo que esperas que ocurra, basada en observaciones o datos. Se comprueba con un experimento y puede resultar correcta o no.',
        'La investigación científica sigue pasos: observar, preguntar, predecir, experimentar, analizar resultados y concluir.',
        'Un mito es una creencia que no está comprobada. La ciencia lo revisa buscando evidencia: por ejemplo, un rayo sí puede caer dos veces en el mismo lugar.',
        'El efecto invernadero aumenta cuando quemamos combustibles, basura o bosques. Lo reducimos sembrando árboles, ahorrando energía, caminando o usando bicicleta y no quemando basura.',
      ],
      media: {
        id: 's38-d1-invernadero', kind: 'diagram', title: 'El efecto invernadero', aspect: '16:9',
        alt: 'La Tierra rodeada por una capa de gases: la luz del sol entra, parte del calor rebota hacia el espacio y parte queda atrapada.',
        brief: 'Infografía horizontal sencilla. Izquierda: el Sol envía flechas amarillas hacia la Tierra. Centro: la Tierra con una capa semitransparente rotulada "gases de efecto invernadero (dióxido de carbono, metano)". Flechas rojas de calor salen del suelo: unas escapan al espacio y otras rebotan en la capa y regresan. Derecha: dos columnas de íconos: "Aumenta la capa" (chimenea de fábrica, carro, basura quemándose, tronco talado) y "La reduce" (arbolito, foco ahorrador, bicicleta, reciclaje). Texto grande, fondo claro, sin marcas.',
      },
      steps: [
        S.explain(
          { fase: 'explorar', areas: ['cnt', 'ccss'], cnb: ['cnt:7.3.4'], ambito: 'conocer', title: 'Una manta de gases alrededor de la Tierra',
            prompt: 'En Zacapa las temperaturas pasan de 35 °C en los días más calurosos. Para entender el clima del futuro, repasa el **efecto invernadero**. Toca cada tarjeta.' },
          { icon: 'CloudSun', body: 'Algunos gases del aire funcionan como una **manta**: dejan entrar la luz del Sol y atrapan parte del calor. Sin ellos la Tierra sería helada; con demasiados, se calienta de más.', reveal: [
            { icon: 'Sun', front: '¿Qué es el efecto invernadero?', back: 'Es el calentamiento natural del planeta porque gases como el **dióxido de carbono** y el **metano** retienen calor.' },
            { icon: 'Flame', front: '¿Qué lo aumenta?', back: 'Quemar gasolina, leña, **basura** y **bosques**. Así sube la cantidad de gases y la Tierra se calienta más: es el **calentamiento global**.' },
            { icon: 'Sprout', front: '¿Qué lo reduce?', back: '**Sembrar árboles**, ahorrar energía, caminar o usar bicicleta, reciclar y **no quemar basura**.' },
            { icon: 'Users', front: '¿Quién puede actuar?', back: 'Todos: las familias, la escuela, la municipalidad y el país. Contarlo a otros (**socializar**) multiplica las acciones.' },
          ] },
        ),
        S.order(
          { fase: 'construir', areas: ['cnt', 'l1'], cnb: ['cnt:8.1.4', 'cnt:8.2.4'], ambito: 'conocer',
            prompt: 'La ciencia avanza con pasos ordenados. Ordena los pasos de una **investigación científica**, del primero al último.',
            hint: 'Antes de experimentar necesitas saber qué esperas que pase.',
            explain: 'Primero se observa y se pregunta. Luego se **predice** (hipótesis) y se **experimenta** para comprobar. Al final se analizan los datos y se comunica la conclusión.' },
          { items: [
            { id: 'obs', text: 'Observar lo que ocurre' },
            { id: 'pre', text: 'Hacer una pregunta' },
            { id: 'pred', text: 'Formular una predicción' },
            { id: 'exp', text: 'Experimentar para comprobarla' },
            { id: 'ana', text: 'Analizar los resultados' },
            { id: 'con', text: 'Concluir y comunicar' },
          ], labels: { start: 'Primero', end: 'Último' } },
        ),
        S.choice(
          { fase: 'construir', areas: ['cnt', 'ccss'], cnb: ['cnt:8.1.4'], ambito: 'hacer',
            prompt: 'Experimento del grupo: ponen **dos frascos iguales** con un termómetro al sol. El frasco A queda **destapado**; el frasco B se **cubre con una bolsa plástica transparente**. Observaron que dentro de un carro cerrado al sol hace más calor. **Predice**: después de 30 minutos, ¿qué frasco estará más caliente?',
            explain: 'La bolsa funciona como los gases de efecto invernadero: deja entrar la luz y atrapa el calor. Tu predicción se basó en una observación (el carro cerrado). Ahora hay que comprobarla con datos.',
            media: { id: 's38-d1-frascos', kind: 'animation', title: 'Los frascos invernadero', aspect: '16:9', duration: 40,
              alt: 'Dos frascos al sol con un termómetro cada uno; el frasco tapado con plástico sube más rápido de temperatura.',
              brief: 'Animación 2D de 40 s. Sobre una mesa en el patio soleado de una escuela, dos frascos de vidrio iguales, cada uno con un termómetro de pared adentro. El frasco A está abierto; el frasco B tiene una bolsa plástica transparente amarrada con un hule. Un reloj en la esquina avanza de 0 a 30 minutos. Las columnas rojas suben: A llega a 30 °C y B a 33 °C (rótulo "datos de ejemplo"). Flechas amarillas de luz entran en ambos; en B, flechas rojas de calor rebotan en la bolsa. Narración infantil: "Observo, predigo y compruebo".' } },
          { options: [
            { id: 'a', text: 'El frasco B, el tapado con la bolsa', icon: 'Thermometer' },
            { id: 'b', text: 'El frasco A, el destapado', icon: 'Wind', feedback: 'En el frasco destapado el aire caliente sale. Recuerda lo que pasa en un carro cerrado al sol.' },
            { id: 'c', text: 'Los dos tendrán la misma temperatura', icon: 'Scale', feedback: 'Están en el mismo lugar, pero la bolsa cambia algo importante: atrapa el calor.' },
          ], correct: ['a'] },
        ),
        S.chart(
          { fase: 'construir', areas: ['cnt', 'mat'], cnb: ['cnt:8.1.4'], ambito: 'hacer',
            prompt: 'Supongamos que el grupo anotó la temperatura del **frasco tapado** cada 10 minutos: al inicio 24 °C, a los 10 min 27 °C, a los 20 min 30 °C y a los 30 min 33 °C. Construye la gráfica con esos datos.',
            explain: 'La gráfica muestra un **patrón**: la temperatura sube 3 °C cada 10 minutos. Encontrar patrones en los datos observados es lo que permite hacer predicciones.' },
          { categories: [
            { id: 't0', label: '0 min', icon: 'Clock', color: 'var(--area-cnt)' },
            { id: 't10', label: '10 min', icon: 'Clock', color: 'var(--area-cnt)' },
            { id: 't20', label: '20 min', icon: 'Clock', color: 'var(--area-cnt)' },
            { id: 't30', label: '30 min', icon: 'Clock', color: 'var(--area-cnt)' },
          ], data: [24, 27, 30, 33], max: 40, step: 1, unit: '°C', source: 'Datos hipotéticos del experimento' },
        ),
        S.cards(
          { fase: 'construir', areas: ['cnt', 'l1', 'ccss'], cnb: ['cnt:8.2.4'], ambito: 'conocer',
            prompt: 'En el festival habrá un puesto de **"Mitos y ciencia"**. Un mito es una creencia que se repite sin estar comprobada. Voltea cada tarjeta para ver qué dice la investigación.' },
          { cards: [
            { icon: 'Zap', front: 'Mito: "Un rayo nunca cae dos veces en el mismo lugar".', back: '**Falso.** Los rayos caen con frecuencia en los lugares altos, como torres y cerros, una y otra vez. Por eso se instalan pararrayos.' },
            { icon: 'Snowflake', front: 'Mito: "Si hoy hace frío, el calentamiento global no existe".', back: '**Falso.** Un día frío es el **tiempo** de hoy. El **clima** es el promedio de muchos años, y ese promedio está subiendo en el planeta.' },
            { icon: 'Bird', front: 'Mito: "Los murciélagos son ratones ciegos".', back: '**Falso.** No son roedores: son mamíferos voladores. Ven y además se orientan con el eco de sus sonidos. Muchos polinizan plantas y comen insectos.' },
            { icon: 'Leaf', front: 'Mito: "Una planta en el cuarto te quita todo el aire de noche".', back: '**Falso.** De noche la planta respira y usa un poquito de oxígeno, mucho menos que una persona. No es peligrosa.' },
          ] },
        ),
        S.slider(
          { fase: 'aplicar', areas: ['cnt', 'mat'], cnb: ['cnt:8.1.4'], ambito: 'hacer',
            prompt: 'Usa el patrón de la gráfica para **predecir**: si el experimento sigue igual, ¿qué temperatura marcará el frasco tapado a los **40 minutos**?',
            hint: 'Cada 10 minutos la temperatura subió la misma cantidad. ¿Cuánto?',
            explain: '33 °C + 3 °C = 36 °C. Es una **predicción**: para saber si es cierta hay que seguir midiendo. Si una nube tapa el sol, el resultado podría cambiar.' },
          { min: 20, max: 45, step: 1, start: 20, answer: 36, unit: '°C', visual: 'thermometer' },
        ),
        S.sort(
          { fase: 'aplicar', areas: ['cnt', 'ccss', 'pyd'], cnb: ['cnt:7.3.4'], ambito: 'emprender',
            prompt: 'El grupo quiere **socializar** acciones en el festival. Clasifica cada acción: ¿ayuda a **contrarrestar** el calentamiento global o lo **aumenta**?',
            explain: 'Las acciones que reducen la quema de combustibles, leña o basura, y las que siembran árboles, disminuyen los gases que atrapan el calor.' },
          { buckets: [
            { id: 'ayuda', label: 'Lo contrarresta', icon: 'Sprout', color: 'var(--c-ok)' },
            { id: 'aumenta', label: 'Lo aumenta', icon: 'Flame', color: 'var(--area-cnt)' },
          ], items: [
            { id: 'a1', text: 'Sembrar árboles en la orilla del río', icon: 'TreePine', bucket: 'ayuda' },
            { id: 'a2', text: 'Quemar la basura en el patio', icon: 'Flame', bucket: 'aumenta' },
            { id: 'a3', text: 'Ir a la escuela caminando o en bicicleta', icon: 'Bike', bucket: 'ayuda' },
            { id: 'a4', text: 'Dejar luces encendidas todo el día', icon: 'Lightbulb', bucket: 'aumenta', feedback: 'Mucha energía eléctrica se produce quemando combustibles: desperdiciarla aumenta los gases.' },
            { id: 'a5', text: 'Usar una estufa mejorada que gasta menos leña', icon: 'Home', bucket: 'ayuda' },
            { id: 'a6', text: 'Talar el bosque para quemar el terreno', icon: 'Trees', bucket: 'aumenta' },
          ] },
        ),
        S.choice(
          { fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:8.1.4'], prompt: 'Boleto de salida: Ana observó que en su cuaderno la temperatura del aula subió 2 °C cada hora desde las 8:00 (20 °C a las 8:00, 22 °C a las 9:00, 24 °C a las 10:00). ¿Cuál es la mejor **predicción** para las 11:00?' },
          { options: [
            { id: 'a', text: 'Unos 26 °C, si el patrón sigue igual' },
            { id: 'b', text: '20 °C, porque así empezó', feedback: 'La temperatura ha subido cada hora; una buena predicción usa ese patrón.' },
            { id: 'c', text: '40 °C, porque en Zacapa hace calor', feedback: 'Una predicción científica se basa en los datos observados, no en una impresión.' },
          ], correct: ['a'] },
        ),
        S.tf(
          { fase: 'comprobar', areas: ['cnt', 'ccss'], cnb: ['cnt:8.2.4', 'cnt:7.3.4'], prompt: '¿Verdadero o falso?' },
          { statements: [
            { text: 'Un mito se puede revisar buscando evidencia con investigación científica.', answer: true },
            { text: 'Un día frío demuestra que no existe el calentamiento global.', answer: false, why: 'Un día es el tiempo atmosférico; el clima es el promedio de muchos años.' },
            { text: 'Quemar basura ayuda a enfriar el planeta.', answer: false, why: 'Quemar basura libera gases que atrapan calor y contaminan el aire.' },
            { text: 'Sembrar árboles ayuda a contrarrestar el calentamiento global.', answer: true },
          ] },
        ),
        cierre({ areas: ['cnt', 'pyd'], cnb: ['cnt:7.3.4'] }, ['Formulo predicciones a partir de datos observados', 'Explico un mito con evidencia científica', 'Propongo acciones contra el calentamiento global'],
          ['Contaré a mi familia una acción para no calentar el planeta', 'Anotaré la temperatura de mi casa tres días y haré una predicción', 'No compartiré una creencia sin revisar si está comprobada']),
      ],
    }),

    /* ───────────────────────── Día 2 ───────────────────────── */
    lesson({
      id: 's38-d2-vivir-bien',
      title: '¿Qué necesitamos para vivir bien?',
      icon: 'Home',
      minutes: 15,
      day: 2,
      gancho: 'Si pudieras mejorar una sola cosa de tu comunidad, ¿qué elegirías: la escuela, el centro de salud, las casas o la cancha?',
      objetivos: ['Identificar las condiciones que determinan la calidad de vida', 'Organizar ideas en un mapa conceptual', 'Resolver problemas con quetzales', 'Analizar si las imágenes ayudan o engañan en un mensaje'],
      resumen: [
        'La calidad de vida de un país se mide con condiciones como la educación, la salud, la vivienda, la recreación, el empleo y el acceso al agua.',
        'Un mapa conceptual va de lo general a lo específico: un concepto central, conceptos que se derivan de él y palabras de enlace que los unen.',
        'Para resolver problemas con quetzales se suma, resta, multiplica o divide, y se revisa si el resultado tiene sentido.',
        'El lenguaje icónico (imágenes, íconos, colores, tamaños) puede favorecer un mensaje si es fiel a los datos, o distorsionarlo si exagera o no corresponde a la realidad.',
      ],
      media: {
        id: 's38-d2-calidad', kind: 'image', title: 'Una comunidad que vive bien', aspect: '16:9',
        alt: 'Ilustración de un barrio con escuela, centro de salud, casas con agua entubada, un parque y personas trabajando.',
        brief: 'Ilustración plana, vista en perspectiva de un barrio de un municipio de Zacapa: escuela con niñas y niños entrando, centro de salud con una enfermera, casas de block con tinaco de agua, un parque con cancha y árboles, un mercado con vendedoras. Sobre cada lugar, un ícono circular y una etiqueta: "Educación", "Salud", "Vivienda", "Agua", "Recreación", "Empleo". Personas diversas (ladinas, mayas y garífunas; una persona mayor con bastón). Colores cálidos y cielo despejado.',
      },
      steps: [
        S.explain(
          { fase: 'explorar', areas: ['ccss', 'fc'], cnb: ['ccss:8.3.5'], ambito: 'conocer', title: 'Calidad de vida',
            prompt: 'Los informes sobre la población del mundo comparan cómo viven las personas en cada país. Para eso miran varias **condiciones**. Toca cada una.' },
          { icon: 'Home', body: 'La **calidad de vida** es el conjunto de condiciones que permiten a una persona vivir con dignidad, salud y bienestar.', reveal: [
            { icon: 'GraduationCap', front: 'Educación', back: 'Escuelas cercanas, maestros y años de estudio de la población.' },
            { icon: 'Stethoscope', front: 'Salud', back: 'Centros de salud, vacunas, buena nutrición y agua segura.' },
            { icon: 'Home', front: 'Vivienda', back: 'Una casa segura, con piso firme, agua, drenaje y electricidad.' },
            { icon: 'Bike', front: 'Recreación', back: 'Parques, canchas, deporte, arte y tiempo libre para descansar y convivir.' },
            { icon: 'Briefcase', front: 'Empleo e ingresos', back: 'Trabajo digno que permita cubrir las necesidades de la familia.' },
          ] },
        ),
        S.sort(
          { fase: 'construir', areas: ['ccss', 'fc'], cnb: ['ccss:8.3.5'], ambito: 'conocer',
            prompt: 'El grupo hizo una lista de lo que tiene su comunidad. Clasifica cada dato según la **condición de calidad de vida** que describe.',
            explain: 'Cuando se estudia la población de un país, estos datos se cuentan en todo el territorio para saber dónde hace falta invertir.' },
          { layout: 'grid2', buckets: [
            { id: 'edu', label: 'Educación', icon: 'GraduationCap', color: 'var(--area-l1)' },
            { id: 'sal', label: 'Salud', icon: 'Stethoscope', color: 'var(--area-cnt)' },
            { id: 'viv', label: 'Vivienda', icon: 'Home', color: 'var(--area-pyd)' },
            { id: 'rec', label: 'Recreación', icon: 'Bike', color: 'var(--area-ef)' },
          ], items: [
            { id: 'q1', text: 'Hay una escuela de básicos a 2 km', bucket: 'edu' },
            { id: 'q2', text: 'La jornada de vacunación llega cada mes', bucket: 'sal' },
            { id: 'q3', text: 'Las casas tienen techo de lámina y piso de cemento', bucket: 'viv' },
            { id: 'q4', text: 'El parque tiene una cancha y juegos', bucket: 'rec' },
            { id: 'q5', text: 'La biblioteca municipal presta libros', bucket: 'edu' },
            { id: 'q6', text: 'El puesto de salud atiende a las embarazadas', bucket: 'sal' },
            { id: 'q7', text: 'Los domingos hay torneo de fútbol', bucket: 'rec' },
            { id: 'q8', text: 'Las casas nuevas tienen drenaje', bucket: 'viv' },
          ] },
        ),
        S.order(
          { fase: 'construir', areas: ['l1', 'ccss'], cnb: ['l1:8.3.2', 'ccss:8.3.5'], ambito: 'hacer',
            prompt: 'Un **mapa conceptual** organiza ideas de lo **más general** a lo **más específico**, y las une con palabras de enlace ("se mide con", "por ejemplo", "necesita"). Ordena los conceptos de esta rama del mapa, de arriba (general) hacia abajo (específico).',
            hint: 'Empieza por el concepto que abarca a todos los demás.',
            explain: 'Calidad de vida → se mide con → condiciones → por ejemplo → salud → necesita → centro de salud → que ofrece → vacunas. Cada nivel es más concreto que el anterior.',
            media: { id: 's38-d2-mapa', kind: 'diagram', title: 'Mapa conceptual: calidad de vida', aspect: '4:3',
              alt: 'Mapa conceptual con "Calidad de vida" arriba, cinco condiciones en el segundo nivel y ejemplos concretos abajo, unidos con flechas y palabras de enlace.',
              brief: 'Diagrama de mapa conceptual hecho a mano sobre papel cuadriculado (estilo cuaderno). Arriba, en un óvalo grande: "Calidad de vida". Flecha con la palabra de enlace "se mide con" hacia el óvalo "Condiciones". De ahí salen cinco óvalos: Educación, Salud, Vivienda, Recreación, Empleo, cada uno con su ícono. Bajo "Salud": "necesita" → "Centro de salud" → "que ofrece" → "Vacunas". Palabras de enlace en cursiva y color gris; conceptos en negrita y con colores de área. Letra grande y legible en celular.' } },
          { items: [
            { id: 'm1', text: 'Calidad de vida' },
            { id: 'm2', text: 'Condiciones' },
            { id: 'm3', text: 'Salud' },
            { id: 'm4', text: 'Centro de salud' },
            { id: 'm5', text: 'Vacunas' },
          ], labels: { start: 'Más general', end: 'Más específico' } },
        ),
        S.explain(
          { fase: 'construir', areas: ['l2', 'mat', 'ccss'], cnb: ['l2:5.4.9'], ambito: 'conocer', title: 'Imágenes que ayudan… o que engañan',
            prompt: 'Carteles, anuncios y noticias usan **lenguaje icónico**: fotos, íconos, colores y tamaños. Toca cada tarjeta para aprender a mirarlo con ojo crítico.' },
          { icon: 'Eye', body: 'Una imagen **favorece** el mensaje cuando lo aclara y es fiel a los datos. Lo **distorsiona** cuando exagera, esconde información o muestra algo que no corresponde.', reveal: [
            { icon: 'ThumbsUp', front: 'Favorece', back: 'Un ícono de gota junto a "Cuida el agua"; una gráfica con barras **proporcionales** a los datos.' },
            { icon: 'BarChart3', front: 'Distorsiona: tamaños', back: 'Una barra de 60 dibujada el triple de alta que una de 50, para que la diferencia parezca enorme.' },
            { icon: 'Image', front: 'Distorsiona: fotos', back: 'Un río limpio y cristalino en un cartel sobre un río que en realidad está contaminado.' },
            { icon: 'Search', front: 'Pregúntate', back: '¿La imagen dice lo mismo que los datos? ¿Qué quiere que yo sienta o haga?' },
          ] },
        ),
        S.choice(
          { fase: 'aplicar', areas: ['l2', 'ccss', 'mat'], cnb: ['l2:5.4.9', 'ccss:8.3.5'], ambito: 'conocer',
            prompt: 'Supongamos que un informe dice: **"En el municipio, 6 de cada 10 viviendas tienen agua entubada"**. El grupo encuentra dos carteles sobre ese dato. ¿Cuál **distorsiona** el mensaje?',
            explain: 'El cartel 2 muestra 10 casas con agua y una familia feliz: hace creer que todas las viviendas tienen agua, cuando faltan 4 de cada 10. El cartel 1 usa íconos fieles al dato.',
            media: { id: 's38-d2-carteles', kind: 'image', title: 'Dos carteles, un mismo dato', aspect: '16:9',
              alt: 'Dos carteles lado a lado: el primero con 10 casitas, 6 azules con gota y 4 grises; el segundo con 10 casitas todas azules y una familia sonriendo.',
              brief: 'Ilustración de dos carteles escolares pegados en una pared. Cartel 1 (rotulado "1"): título "Agua en nuestras casas", 10 íconos de casa en fila, 6 azules con una gota y 4 grises sin gota, texto "6 de cada 10". Cartel 2 (rotulado "2"): mismo título, 10 casas todas azules con gota, un grifo enorme y una familia sonriente, texto pequeño "6 de cada 10" casi ilegible. Estilo plano, colores vivos, sin marcas ni logotipos.' } },
          { options: [
            { id: 'a', text: 'El cartel 2: pinta todas las casas con agua y esconde el dato', icon: 'EyeOff' },
            { id: 'b', text: 'El cartel 1: sus casas grises se ven tristes', icon: 'Home', feedback: 'Las casas grises representan a las 4 viviendas sin agua: el cartel 1 es fiel al dato.' },
            { id: 'c', text: 'Ninguno: las imágenes nunca cambian el mensaje', icon: 'Image', feedback: 'Las imágenes influyen mucho en lo que entendemos; por eso hay que revisarlas.' },
          ], correct: ['a'] },
        ),
        S.number(
          { fase: 'aplicar', areas: ['mat', 'ccss', 'fc'], cnb: ['mat:7.5.1', 'ccss:8.3.5'], ambito: 'hacer',
            prompt: 'Supongamos que una familia de Estanzuela recibe **Q4,200** al mes. Gasta en comida Q1,850, en vivienda Q800, en transporte Q350, en luz y agua Q275 y en útiles escolares Q225. ¿Cuántos quetzales le **quedan** para ahorro y recreación?',
            hint: 'Primero suma todos los gastos. Luego resta ese total del ingreso.',
            explain: 'Gastos: 1,850 + 800 + 350 + 275 + 225 = Q3,500. Quedan 4,200 − 3,500 = **Q700**. Planificar el dinero ayuda a cubrir la educación, la salud y también la recreación.' },
          { answer: 700, unit: 'quetzales', stimulus: 'Ingreso: Q4,200 · Gastos: Q1,850 + Q800 + Q350 + Q275 + Q225', misconceptions: [
            { value: 3500, msg: 'Ese es el total de gastos. Falta restarlo del ingreso.' },
            { value: 7700, msg: 'Sumaste el ingreso y los gastos. Los gastos se restan.' },
          ] },
        ),
        S.match(
          { fase: 'aplicar', areas: ['pyd', 'fc', 'ccss'], cnb: ['pyd:5.5.1'], ambito: 'emprender',
            prompt: 'Para el **Festival del Futuro** el grupo debe **coordinarse con varias instituciones** de la comunidad. Une cada institución con la forma en que puede apoyar.',
            explain: 'La **coordinación interinstitucional** consiste en que varias instituciones se pongan de acuerdo, cada una con su función, para lograr una actividad comunitaria. Se hace con cartas, reuniones y un calendario compartido.' },
          { leftTitle: 'Institución', rightTitle: 'Apoyo', pairs: [
            { id: 'muni', left: 'Municipalidad', leftIcon: 'Building2', right: 'Presta el parque y autoriza el evento' },
            { id: 'salud', left: 'Centro de salud', leftIcon: 'Stethoscope', right: 'Da una charla sobre agua segura y calor' },
            { id: 'cultura', left: 'Casa de la Cultura', leftIcon: 'Music', right: 'Organiza la marimba y la muestra de historia' },
            { id: 'bomb', left: 'Bomberos voluntarios', leftIcon: 'ShieldCheck', right: 'Cuidan la seguridad y los primeros auxilios' },
            { id: 'cocode', left: 'COCODE', leftIcon: 'Users', right: 'Invita a las familias y reúne a los vecinos' },
          ] },
        ),
        S.number(
          { fase: 'comprobar', areas: ['mat', 'cnt'], cnb: ['mat:7.5.1', 'cnt:7.3.4'], prompt: 'Boleto de salida: supongamos que cambiar un foco común por uno ahorrador reduce el pago de luz en **Q6 al mes**. Si una familia cambia **5 focos**, ¿cuántos quetzales ahorra en **un año** (12 meses)?' },
          { answer: 360, unit: 'quetzales', misconceptions: [
            { value: 30, msg: 'Ese es el ahorro de un mes. Multiplica también por los 12 meses.' },
            { value: 72, msg: 'Ese es el ahorro de un solo foco en un año. Son 5 focos.' },
          ] },
        ),
        S.choice(
          { fase: 'comprobar', areas: ['ccss', 'l1'], cnb: ['ccss:8.3.5', 'l1:8.3.2'], prompt: 'En un mapa conceptual sobre **calidad de vida**, ¿cuáles irían como **condiciones** en el segundo nivel? Elige todas las correctas.' },
          { multiple: true, options: [
            { id: 'a', text: 'Educación', icon: 'GraduationCap' },
            { id: 'b', text: 'Vivienda', icon: 'Home' },
            { id: 'c', text: 'Recreación', icon: 'Bike' },
            { id: 'd', text: 'El color favorito de cada persona', icon: 'Palette', feedback: 'Un gusto personal no es una condición para medir la calidad de vida de un país.' },
          ], correct: ['a', 'b', 'c'] },
        ),
        cierre({ areas: ['ccss', 'mat', 'pyd'], cnb: ['ccss:8.3.5'] }, ['Explico qué condiciones determinan la calidad de vida y las organizo en un mapa conceptual', 'Resuelvo problemas con quetzales', 'Reviso si una imagen ayuda o engaña'],
          ['Haré un mapa conceptual de lo que necesita mi comunidad', 'Ayudaré a mi familia a anotar los gastos de una semana', 'Antes de creer un cartel, compararé la imagen con los datos']),
      ],
    }),

    /* ───────────────────────── Día 3 ───────────────────────── */
    lesson({
      id: 's38-d3-instituciones',
      title: 'Instituciones que nos protegen',
      icon: 'Landmark',
      minutes: 15,
      day: 3,
      gancho: 'Si alguien no respetara tus derechos, ¿a quién acudirías? ¿Quién hace las leyes y quién cuida que se cumplan?',
      objetivos: ['Identificar las funciones que la Constitución asigna a los organismos del Estado y a otras instituciones', 'Comprender un texto formal y académico', 'Buscar información confiable en internet', 'Revisar la puntuación y la ortografía de tus textos'],
      resumen: [
        'Organismo Legislativo (Congreso): crea, reforma y deroga leyes. Organismo Ejecutivo (Presidencia y ministerios): ejecuta las leyes y administra los servicios. Organismo Judicial: juzga y hace cumplir lo juzgado.',
        'La Corte de Constitucionalidad defiende la Constitución; el Ministerio Público investiga los delitos; la Procuraduría de los Derechos Humanos defiende los derechos humanos; el Tribunal Supremo Electoral organiza las elecciones; la Procuraduría General de la Nación representa y asesora al Estado.',
        'Para buscar en internet: usa palabras clave, prefiere sitios oficiales o educativos, revisa autor y fecha y compara al menos dos fuentes.',
        'En español los signos de pregunta y de exclamación se abren y se cierran (¿? ¡!); en inglés solo se cierran. Escribimos m antes de b y p (cambio, tiempo) y n antes de v (invierno). En los idiomas mayas el apóstrofo marca un sonido (k\', q\', ch\').',
      ],
      media: {
        id: 's38-d3-estado', kind: 'diagram', title: 'Quién hace qué en el Estado', aspect: '4:3',
        alt: 'Esquema con tres columnas para los organismos del Estado y, debajo, cinco instituciones con su función principal.',
        brief: 'Esquema institucional limpio. Arriba, tres columnas con edificios estilizados: "Organismo Legislativo – hace las leyes" (ícono de pergamino), "Organismo Ejecutivo – ejecuta y administra" (ícono de engranaje), "Organismo Judicial – juzga" (ícono de mazo). Abajo, cinco tarjetas: "Corte de Constitucionalidad – defiende la Constitución" (escudo), "Ministerio Público – investiga delitos" (lupa), "Procuraduría de los Derechos Humanos – defiende los derechos" (manos), "Tribunal Supremo Electoral – organiza elecciones" (urna), "Procuraduría General de la Nación – representa y asesora al Estado" (maletín). Sin logotipos oficiales ni fotografías de personas.',
      },
      steps: [
        S.explain(
          { fase: 'explorar', areas: ['ccss', 'fc'], cnb: ['ccss:8.4.3'], ambito: 'conocer', title: 'Tres organismos que se equilibran',
            prompt: 'La **Constitución Política de la República** (1985) reparte el poder del Estado en **tres organismos** para que ninguno mande solo. Toca cada uno.' },
          { icon: 'Landmark', body: 'Cada organismo tiene funciones propias y se controlan entre sí. Eso protege a la población de los abusos de poder.', reveal: [
            { icon: 'ScrollText', front: 'Organismo Legislativo', back: 'Es el **Congreso de la República**. Crea, reforma y deroga **leyes** y aprueba el presupuesto del Estado.' },
            { icon: 'Building', front: 'Organismo Ejecutivo', back: 'Lo dirige la **Presidencia** con los ministerios. **Ejecuta** las leyes y administra servicios como escuelas, hospitales y carreteras.' },
            { icon: 'Gavel', front: 'Organismo Judicial', back: 'Lo encabeza la **Corte Suprema de Justicia**. Sus jueces **juzgan** los casos y hacen cumplir lo que resuelven.' },
          ] },
        ),
        S.reading(
          { fase: 'construir', areas: ['l2', 'ccss', 'fc'], cnb: ['l2:5.4.8', 'ccss:8.4.3'], ambito: 'conocer',
            prompt: 'Lee este **texto formal y académico**, como los que encontrarás en libros de consulta. Luego responde.' },
          { genre: 'Texto académico', heading: 'Instituciones que garantizan el Estado de derecho', passage:
            'Además de los tres organismos del Estado, la Constitución Política de la República de Guatemala establece instituciones con funciones específicas de control y protección.\n\nLa **Corte de Constitucionalidad** es un tribunal permanente cuya función esencial es la **defensa del orden constitucional**: revisa que las leyes y los actos de las autoridades no contradigan la Constitución. El **Ministerio Público** vela por el cumplimiento de las leyes y **dirige la investigación de los delitos**. La **Procuraduría de los Derechos Humanos**, dirigida por un comisionado del Congreso, **investiga denuncias** de violaciones a los derechos humanos y promueve su respeto.\n\nPor su parte, el **Tribunal Supremo Electoral** es la máxima autoridad en materia electoral: **organiza las elecciones** y declara sus resultados. La **Procuraduría General de la Nación** ejerce la **representación del Estado** y lo asesora en asuntos legales. En conjunto, estas instituciones permiten que la población viva bajo reglas claras y pueda defender sus derechos.',
            questions: [
              { q: 'Según el texto, ¿qué institución investiga los delitos?', options: [
                { id: 'a', text: 'El Ministerio Público' },
                { id: 'b', text: 'El Tribunal Supremo Electoral' },
                { id: 'c', text: 'La Corte de Constitucionalidad' },
              ], correct: 'a' },
              { q: 'Si una ley nueva contradijera la Constitución, ¿qué institución podría revisarla?', options: [
                { id: 'a', text: 'La Procuraduría General de la Nación' },
                { id: 'b', text: 'La Corte de Constitucionalidad' },
                { id: 'c', text: 'El Tribunal Supremo Electoral' },
              ], correct: 'b', why: 'Su función esencial es defender el orden constitucional.' },
              { q: '¿Qué rasgo muestra que es un texto **formal y académico**?', options: [
                { id: 'a', text: 'Usa vocabulario preciso y explica sin dar opiniones personales' },
                { id: 'b', text: 'Cuenta una historia con personajes y diálogos' },
                { id: 'c', text: 'Usa palabras coloquiales como "chilero" y "a la gran"' },
              ], correct: 'a', why: 'Los textos académicos informan con términos precisos, en tercera persona y con orden lógico.' },
              { q: '¿Por qué es importante que existan instituciones distintas con funciones distintas?', options: [
                { id: 'a', text: 'Para que una sola persona decida todo' },
                { id: 'b', text: 'Para que haya control, se respeten las leyes y la población pueda defender sus derechos' },
                { id: 'c', text: 'Para que haya más edificios en la capital' },
              ], correct: 'b' },
            ] },
        ),
        S.match(
          { fase: 'construir', areas: ['ccss', 'fc'], cnb: ['ccss:8.4.3'], ambito: 'conocer',
            prompt: 'Arma la ficha del **manual de instituciones** del festival. Une cada institución con su función según la Constitución.',
            explain: 'Conocer qué hace cada institución te permite saber a dónde acudir: por ejemplo, a la PDH si se violan tus derechos o al Ministerio Público para denunciar un delito.' },
          { leftTitle: 'Institución', rightTitle: 'Función', pairs: [
            { id: 'ol', left: 'Organismo Legislativo', leftIcon: 'ScrollText', right: 'Crea, reforma y deroga leyes' },
            { id: 'oj', left: 'Organismo Judicial', leftIcon: 'Gavel', right: 'Juzga y hace cumplir lo juzgado' },
            { id: 'cc', left: 'Corte de Constitucionalidad', leftIcon: 'Shield', right: 'Defiende el orden constitucional' },
            { id: 'mp', left: 'Ministerio Público', leftIcon: 'Search', right: 'Investiga los delitos' },
            { id: 'pdh', left: 'Procuraduría de los Derechos Humanos', leftIcon: 'HandHeart', right: 'Investiga denuncias de violaciones a los derechos humanos' },
            { id: 'tse', left: 'Tribunal Supremo Electoral', leftIcon: 'Vote', right: 'Organiza las elecciones' },
            { id: 'pgn', left: 'Procuraduría General de la Nación', leftIcon: 'Briefcase', right: 'Representa y asesora legalmente al Estado' },
          ] },
        ),
        S.sort(
          { fase: 'construir', areas: ['l1', 'l2', 'ccss'], cnb: ['l1:8.1.3'], ambito: 'hacer',
            prompt: 'Para completar el manual, el grupo **busca en internet**. Un buen buscador usa **palabras clave** ("funciones Tribunal Supremo Electoral Guatemala"), prefiere sitios **oficiales o educativos**, revisa **autor y fecha** y **compara** fuentes. Clasifica estos resultados.',
            explain: 'Un sitio oficial o un libro digital con autor y fecha es más confiable que un mensaje en cadena sin autor. Aun así, siempre conviene comparar dos fuentes.' },
          { buckets: [
            { id: 'si', label: 'Fuente confiable para la tarea', icon: 'BadgeCheck', color: 'var(--c-ok)' },
            { id: 'duda', label: 'Hay que dudar', icon: 'EyeOff', color: 'var(--c-hint)' },
          ], items: [
            { id: 'f1', text: 'Texto de la Constitución publicado en el sitio oficial del Congreso (.gob.gt)', bucket: 'si' },
            { id: 'f2', text: 'Libro digital de Ciencias Sociales con autor, editorial y año', bucket: 'si' },
            { id: 'f3', text: 'Página de una universidad que explica las funciones del TSE', bucket: 'si' },
            { id: 'f4', text: 'Mensaje reenviado en cadena, sin autor ni fecha', bucket: 'duda' },
            { id: 'f5', text: 'Video de una cuenta anónima que dice "la PDH hace las leyes"', bucket: 'duda', feedback: 'Además de ser anónimo, el dato es falso: las leyes las hace el Congreso.' },
            { id: 'f6', text: 'Blog con el título "¡Lo que nadie te dice!" y sin fuentes', bucket: 'duda' },
          ] },
        ),
        S.explain(
          { fase: 'construir', areas: ['l1', 'l3', 'l2'], cnb: ['l1:7.3.4', 'l1:7.3.5'], ambito: 'conocer', title: 'Revisar antes de publicar',
            prompt: 'Antes de imprimir el manual hay que **revisar** la puntuación y la ortografía. Cada idioma tiene sus propias reglas. Toca cada tarjeta.' },
          { icon: 'PenLine', body: 'Los **signos de puntuación** marcan pausas y la **entonación** (pregunta, exclamación). La **ortografía literal** cuida qué letras se combinan.', reveal: [
            { icon: 'MessageCircle', front: 'Pregunta y exclamación', back: 'En español se **abren y se cierran**: ¿Qué hace el MP? ¡Qué importante! En inglés solo se cierran: _What does it do?_' },
            { icon: 'List', front: 'Coma y dos puntos', back: 'La **coma** separa elementos de una lista. Los **dos puntos** anuncian una enumeración o explicación: "Hay tres organismos: Legislativo, Ejecutivo y Judicial."' },
            { icon: 'PenLine', front: 'm antes de b y p', back: 'Siempre **m** antes de **b** y **p**: ca**mb**io, ti**emp**o, co**mp**romiso.' },
            { icon: 'PenTool', front: 'n antes de v', back: 'Siempre **n** antes de **v**: i**nv**ierno, e**nv**ase, co**nv**ivencia.' },
            { icon: 'Languages', front: 'En idiomas mayas', back: 'El alfabeto de los idiomas mayas usa el **apóstrofo** para marcar sonidos propios: k\', q\', ch\', tz\'. Por eso escribimos **k\'iche\'** y **q\'eqchi\'**.' },
          ] },
        ),
        S.fill(
          { fase: 'aplicar', areas: ['l1', 'ccss'], cnb: ['l1:7.3.4', 'ccss:8.4.3'], ambito: 'hacer',
            prompt: 'Completa los **signos de puntuación** del texto del manual.',
            hint: 'Una pregunta en español se abre y se cierra. Antes de una lista se usan dos puntos.',
            explain: 'Los signos guían la entonación: al leer en voz alta, la pregunta sube al final y la lista hace pausas en cada coma.' },
          { text: '[[¿]]Quién organiza las elecciones[[?]] El Tribunal Supremo Electoral[[.]] Sus tareas principales son[[:]] inscribir a los partidos[[,]] organizar las votaciones y declarar los resultados.',
            distractors: [';', '¡'] },
        ),
        S.highlight(
          { fase: 'aplicar', areas: ['l1', 'fc'], cnb: ['l1:7.3.5'], ambito: 'hacer',
            prompt: 'Un compañero escribió este párrafo con prisa. Toca las **palabras mal escritas** (errores de ortografía literal).',
            explain: 'Correcciones: "canbio" → cambio, "tienpo" → tiempo, "imbierno" → invierno, "conbivencia" → convivencia. Recuerda: m antes de b y p; n antes de v.' },
          { target: 'palabras mal escritas', text: 'En el festival hablaremos del {canbio} climático. Con el {tienpo}, el {imbierno} trae menos lluvia al Corredor Seco. Por eso proponemos acciones de {conbivencia} y cuidado del ambiente.' },
        ),
        S.choice(
          { fase: 'comprobar', areas: ['ccss', 'fc'], cnb: ['ccss:8.4.3'], prompt: 'Boleto de salida: en la comunidad quieren **denunciar un delito** para que se investigue. ¿A qué institución corresponde investigarlo?' },
          { options: [
            { id: 'a', text: 'Al Ministerio Público', icon: 'Search' },
            { id: 'b', text: 'Al Tribunal Supremo Electoral', icon: 'Vote', feedback: 'El TSE organiza las elecciones; no investiga delitos comunes.' },
            { id: 'c', text: 'Al Organismo Legislativo', icon: 'ScrollText', feedback: 'El Congreso hace las leyes; la investigación de delitos la dirige el Ministerio Público.' },
          ], correct: ['a'] },
        ),
        S.choice(
          { fase: 'comprobar', areas: ['l1', 'l2'], cnb: ['l1:7.3.4', 'l1:7.3.5'], prompt: '¿Qué oración está escrita **correctamente**?' },
          { options: [
            { id: 'a', text: '¿Sabías que en invierno cambia el tiempo?' },
            { id: 'b', text: 'Sabías que en imbierno cambia el tienpo?', feedback: 'Falta abrir la pregunta con ¿ y hay errores: invierno (n antes de v) y tiempo (m antes de p).' },
            { id: 'c', text: '¿Sabías que en invierno canbia el tiempo', feedback: 'Falta cerrar la pregunta y "cambia" lleva m antes de b.' },
          ], correct: ['a'] },
        ),
        cierre({ areas: ['ccss', 'l1'], cnb: ['ccss:8.4.3'] }, ['Explico las funciones de los organismos del Estado y de otras instituciones', 'Busco información confiable en internet', 'Reviso la puntuación y la ortografía de mis textos'],
          ['Contaré en casa a qué institución se puede acudir para defender los derechos', 'Compararé dos fuentes antes de copiar un dato', 'Revisaré mis tareas buscando m antes de b y p']),
      ],
    }),

    /* ───────────────────────── Día 4 ───────────────────────── */
    lesson({
      id: 's38-d4-historia-juego',
      title: 'Historia, música y juego que nos unen',
      icon: 'Music',
      minutes: 15,
      day: 4,
      gancho: '¿Qué juego te enseñaron tus abuelos? ¿Qué canción suena en las fiestas de tu comunidad?',
      objetivos: ['Reconocer la cooperación y los intercambios en la historia del pueblo ladino', 'Ordenar hechos y procesos importantes de la historia de Guatemala', 'Diferenciar la música según épocas y compositores', 'Jugar intercambiando roles y comunicándote bien, también con expresiones en inglés'],
      resumen: [
        'El pueblo ladino se formó a partir del encuentro y la mezcla de pueblos indígenas, españoles y africanos. Su historia está hecha de cooperación e intercambios: el idioma, la comida, la marimba y las fiestas.',
        'Hechos importantes de Guatemala: 1821 Independencia; 1871 Revolución Liberal; 1944 Revolución de Octubre; 1985 Constitución vigente; 1996 Firma de la Paz.',
        'La música académica se agrupa por épocas: Barroco (Bach, Vivaldi), Clasicismo (Mozart, Haydn), Romanticismo (Chopin, Chaikovski). En Guatemala destacan Jesús Castillo y la marimba de concierto del siglo XX.',
        'El juego es parte de la cultura. Al jugar, cambiar de rol y comunicarse con respeto ayudan a convivir. En inglés: "What\'s up?" (¿qué onda?), "All right" (está bien) y "Come on!" (¡vamos!).',
      ],
      media: {
        id: 's38-d4-feria', kind: 'image', title: 'Una tarde de juegos y marimba', aspect: '16:9',
        alt: 'Patio escolar con una marimba, niñas y niños jugando trompo, capirucho y tenta, y una línea del tiempo colgada en un muro.',
        brief: 'Ilustración plana y colorida del patio de una escuela de Zacapa por la tarde. Izquierda: tres marimbistas tocan una marimba de madera. Centro: niñas y niños (ladinos, mayas y garífunas; una niña en silla de ruedas) juegan trompo, capirucho y tenta; uno lleva un chaleco que dice "árbitro". Derecha: una línea del tiempo de papel con cinco fechas (1821, 1871, 1944, 1985, 1996) y dibujos sencillos. Sin marcas ni personas reales.',
      },
      steps: [
        S.explain(
          { fase: 'explorar', areas: ['fc', 'ccss', 'l1'], cnb: ['fc:5.3.3'], ambito: 'convivir', title: 'La historia del pueblo ladino',
            prompt: 'En Guatemala conviven cuatro pueblos: **maya, garífuna, xinka y ladino**. En Zacapa y otros departamentos del oriente, la mayoría de la población se identifica como **ladina**. Toca cada tarjeta para conocer cómo se formó.' },
          { icon: 'Handshake', body: 'La historia del pueblo ladino es una historia de **encuentros, intercambios y cooperación** entre pueblos.', reveal: [
            { icon: 'Users', front: 'Su origen', back: 'Se formó durante la época colonial con la **mezcla** de pueblos indígenas, españoles y africanos: el **mestizaje**.' },
            { icon: 'Languages', front: 'El idioma', back: 'Habla **español**, con palabras que vienen de idiomas originarios, como _aguacate_, _elote_ y _tecolote_.' },
            { icon: 'Music', front: 'La marimba', back: 'Tiene raíces africanas e indígenas y la tocan todos los pueblos. En 1999 el Congreso la declaró **instrumento nacional**.' },
            { icon: 'Utensils', front: 'La comida y las fiestas', back: 'Tamales, atol de elote, quesos del oriente y ferias patronales mezclan tradiciones de varios pueblos.' },
            { icon: 'HeartHandshake', front: 'Hoy', back: 'Los Acuerdos de Paz reconocen que Guatemala es un país **multiétnico, pluricultural y multilingüe**: todos los pueblos construimos juntos la historia.' },
          ] },
        ),
        S.order(
          { fase: 'construir', areas: ['fc', 'ccss'], cnb: ['fc:5.3.4'], ambito: 'conocer',
            prompt: 'La Casa de la Cultura arma una **línea del tiempo** para el festival. Ordena estos hechos y procesos históricos de Guatemala, del más antiguo al más reciente.',
            hint: 'Fíjate en los años: 1821, 1871, 1944, 1985, 1996.',
            explain: 'Estos hechos marcan procesos largos: la independencia de España, las reformas liberales, la Revolución de Octubre con nuevos derechos, la Constitución que nos rige y la paz tras el conflicto armado interno.' },
          { items: [
            { id: 'h1', text: '1821: Independencia de Centroamérica' },
            { id: 'h2', text: '1871: Revolución Liberal' },
            { id: 'h3', text: '1944: Revolución de Octubre' },
            { id: 'h4', text: '1985: Se promulga la Constitución vigente' },
            { id: 'h5', text: '1996: Firma de la Paz Firme y Duradera' },
          ], labels: { start: 'Más antiguo', end: 'Más reciente' } },
        ),
        S.explain(
          { fase: 'construir', areas: ['art', 'ccss'], cnb: ['art:4.3.1'], ambito: 'conocer', title: 'La música tiene épocas',
            prompt: 'La música cambia con el tiempo. La **música académica** (o de concierto) se agrupa en **épocas**, cada una con sus compositores. Escucha la muestra y toca cada tarjeta.',
            media: { id: 's38-d4-epocas', kind: 'audio', title: 'Viaje musical por las épocas', duration: 60,
              alt: 'Cuatro fragmentos cortos: un clavecín barroco, una orquesta clásica, un piano romántico y una marimba de concierto guatemalteca.',
              brief: 'Audio de 60 s con cuatro fragmentos de 12 s de obras de dominio público (grabación propia), separados por una voz infantil que anuncia la época: (1) "Barroco": clavecín con melodía ornamentada al estilo de Bach; (2) "Clasicismo": cuarteto de cuerdas equilibrado al estilo de Mozart; (3) "Romanticismo": piano expresivo al estilo de Chopin; (4) "Guatemala, siglo XX": marimba de concierto tocando un son. No usar grabaciones con derechos de autor.' } },
          { icon: 'Music2', body: 'Además de las épocas, hay **clases de música**: académica, popular, tradicional (folclórica) y religiosa.', reveal: [
            { icon: 'Church', front: 'Barroco (1600-1750)', back: 'Música muy adornada, con órgano y clavecín. **Johann Sebastian Bach** y **Antonio Vivaldi** ("Las cuatro estaciones").' },
            { icon: 'Crown', front: 'Clasicismo (1750-1820)', back: 'Melodías claras y equilibradas. **Wolfgang Amadeus Mozart** y **Joseph Haydn**.' },
            { icon: 'Heart', front: 'Romanticismo (1820-1900)', back: 'Música que expresa emociones intensas. **Frédéric Chopin** (piano) y **Piotr Chaikovski** ("El lago de los cisnes").' },
            { icon: 'Music', front: 'Guatemala, siglo XX', back: '**Jesús Castillo** recopiló melodías indígenas y las usó en obras de concierto. La marimba sonó en todo el país con piezas como **"Luna de Xelajú"**, de Paco Pérez.' },
          ] },
        ),
        S.sort(
          { fase: 'construir', areas: ['art', 'ccss'], cnb: ['art:4.3.1'], ambito: 'conocer',
            prompt: 'El grupo prepara carteles para la muestra de música. Clasifica a cada compositor en su **época**.',
            explain: 'Ordenar a los compositores por época ayuda a entender cómo cambió la música: del adorno del Barroco al equilibrio clásico, a la emoción romántica y a la búsqueda de raíces propias en Guatemala.' },
          { layout: 'grid2', buckets: [
            { id: 'bar', label: 'Barroco', icon: 'Church', color: 'var(--area-art)' },
            { id: 'cla', label: 'Clasicismo', icon: 'Crown', color: 'var(--area-l1)' },
            { id: 'rom', label: 'Romanticismo', icon: 'Heart', color: 'var(--area-cnt)' },
            { id: 'gt', label: 'Guatemala, siglo XX', icon: 'Music', color: 'var(--area-pyd)' },
          ], items: [
            { id: 'c1', text: 'Johann Sebastian Bach', bucket: 'bar' },
            { id: 'c2', text: 'Antonio Vivaldi', bucket: 'bar' },
            { id: 'c3', text: 'Wolfgang Amadeus Mozart', bucket: 'cla' },
            { id: 'c4', text: 'Joseph Haydn', bucket: 'cla' },
            { id: 'c5', text: 'Frédéric Chopin', bucket: 'rom' },
            { id: 'c6', text: 'Piotr Chaikovski', bucket: 'rom' },
            { id: 'c7', text: 'Jesús Castillo', bucket: 'gt' },
            { id: 'c8', text: 'Paco Pérez, "Luna de Xelajú"', bucket: 'gt' },
          ] },
        ),
        S.match(
          { fase: 'construir', areas: ['ef', 'ccss', 'fc'], cnb: ['ef:4.2.6'], ambito: 'convivir',
            prompt: 'El juego es un **fenómeno social y cultural**: se aprende de los mayores, cambia con el tiempo y une a la comunidad. Une cada juego con su descripción.',
            explain: 'Muchos juegos tradicionales pasan de generación en generación. El juego de pelota maya, por ejemplo, era a la vez deporte y ceremonia, y hoy se practica en demostraciones y torneos.' },
          { leftTitle: 'Juego', rightTitle: 'Descripción', pairs: [
            { id: 'j1', left: 'Trompo', leftIcon: 'RotateCw', right: 'Se enrolla una pita y se lanza para que gire en el suelo' },
            { id: 'j2', left: 'Capirucho', leftIcon: 'Target', right: 'Se lanza un carrete amarrado a un palito para ensartarlo' },
            { id: 'j3', left: 'Cincos', leftIcon: 'CircleDot', right: 'Se lanzan canicas para golpear las de los demás' },
            { id: 'j4', left: 'Juego de pelota maya', leftIcon: 'Landmark', right: 'Se golpeaba una pelota de hule con la cadera en una cancha de piedra' },
            { id: 'j5', left: 'Tenta', leftIcon: 'Footprints', right: 'Una persona corre para tocar a otra, que pasa a perseguir' },
          ] },
        ),
        S.fill(
          { fase: 'aplicar', areas: ['l3', 'ef'], cnb: ['l3:5.3.1', 'l3:5.3.3'], ambito: 'convivir',
            prompt: 'Una estudiante de intercambio llega al festival y juega con el grupo. Completa el diálogo con expresiones en inglés que se escuchan en el juego: **"What\'s up?"** = ¿qué onda? / ¿qué tal?; **"All right"** = está bien, de acuerdo; **"Come on!"** = ¡vamos!, ¡ánimo!; **"Thank you"** = gracias.',
            explain: '"What\'s up?" es un saludo informal entre amigos; en una situación formal diríamos "Good afternoon". "Come on!" anima a alguien a intentarlo.' },
          { text: 'Emily: Hi! [[What\'s up?]]\nLuis: Hi, Emily! Do you want to play tenta?\nEmily: [[All right]]! Let\'s play.\nLuis: You can do it! [[Come on!]]\nEmily: That was fun. [[Thank you]]!',
            distractors: ['Good night', 'Sorry'] },
        ),
        S.dilemma(
          { fase: 'aplicar', areas: ['ef', 'fc', 'l1'], cnb: ['ef:4.2.2', 'ef:4.2.10'], ambito: 'convivir', prompt: 'En el torneo del festival surge un problema. ¿Qué harías tú?' },
          { scene: { icon: 'Users', text: 'Tu equipo juega capirucho y tenta por estaciones. **Kevin** quiere ser siempre el capitán y **Dulce** siempre es la anotadora, aunque ella quiere jugar. Algunos empiezan a gritarse.' }, options: [
            { id: 'a', icon: 'Crown', text: 'Dejar que Kevin decida todo para no discutir', consequence: 'El juego sigue, pero Dulce se aburre y otros dejan de participar. El equipo se divide.', values: ['Conformismo'], constructive: false },
            { id: 'b', icon: 'RefreshCw', text: 'Proponer que los roles roten cada partida: capitán, árbitro, anotador y jugador', consequence: 'Todos prueban cada rol. Dulce juega y descubre que es muy rápida; Kevin aprende lo difícil que es ser árbitro. El equipo se comunica mejor.', values: ['Equidad', 'Cooperación', 'Tolerancia'], constructive: true },
            { id: 'c', icon: 'MessagesSquare', text: 'Pedir una pausa, que cada quien diga cómo se siente sin gritar y acordar reglas juntos', consequence: 'Al escucharse, el equipo acuerda turnos y una señal para pedir la palabra. El juego vuelve a ser divertido.', values: ['Diálogo', 'Respeto', 'Comunicación efectiva'], constructive: true },
          ] },
        ),
        S.choice(
          { fase: 'comprobar', areas: ['fc', 'ccss'], cnb: ['fc:5.3.3', 'fc:5.3.4'], prompt: 'Boleto de salida: ¿qué afirmación sobre la historia de Guatemala es correcta?' },
          { options: [
            { id: 'a', text: 'El pueblo ladino se formó por la mezcla e intercambio de pueblos indígenas, españoles y africanos', icon: 'Handshake' },
            { id: 'b', text: 'La Firma de la Paz ocurrió antes de la Independencia', icon: 'History', feedback: 'La Independencia fue en 1821 y la Firma de la Paz en 1996.' },
            { id: 'c', text: 'La marimba pertenece solo a un pueblo de Guatemala', icon: 'Music', feedback: 'La marimba tiene raíces africanas e indígenas y la tocan todos los pueblos.' },
          ], correct: ['a'] },
        ),
        S.match(
          { fase: 'comprobar', areas: ['art', 'l3'], cnb: ['art:4.3.1', 'l3:5.3.1'], prompt: 'Une cada elemento con lo que le corresponde.' },
          { pairs: [
            { id: 'x1', left: 'Mozart', right: 'Clasicismo' },
            { id: 'x2', left: 'Vivaldi', right: 'Barroco' },
            { id: 'x3', left: '"Come on!"', right: '¡Vamos!, ¡ánimo!' },
            { id: 'x4', left: '"All right"', right: 'Está bien, de acuerdo' },
          ] },
        ),
        cierre({ areas: ['ef', 'fc', 'art'], cnb: ['ef:4.2.10'] }, ['Reconozco los intercambios que formaron al pueblo ladino y ordeno hechos de la historia de Guatemala', 'Diferencio épocas y compositores de la música', 'Juego intercambiando roles y comunicándome con respeto'],
          ['Preguntaré a mis abuelos qué juegos jugaban', 'Escucharé una pieza de marimba y otra de otra época y las compararé', 'Propondré turnos para que todos prueben cada rol en el juego']),
      ],
    }),

    /* ───────────────────────── Día 5: Reto semanal ───────────────────────── */
    lesson({
      id: 's38-d5-reto',
      title: 'Reto de la semana 38',
      icon: 'Trophy',
      minutes: 14,
      day: 5,
      kind: 'reto',
      objetivos: ['Demostrar lo que aprendiste esta semana', 'Obtener la medalla "Pronosticador del futuro" (70 % o más)'],
      resumen: ['Superé el reto de la semana 38: predicciones, calidad de vida, instituciones, historia, música y juego.'],
      media: {
        id: 's38-d5-reto', kind: 'image', title: 'Medalla Pronosticador del futuro', aspect: '1:1',
        alt: 'Medalla dorada con un sol detrás de una nube, un termómetro y un quetzal.',
        brief: 'Ilustración de medalla circular dorada con relieve: un sol que asoma detrás de una nube, un termómetro a la izquierda y un quetzal estilizado a la derecha, sobre la silueta de un valle con cerros. Cinta con los colores de las áreas del CNB. Fondo transparente, 1024×1024, estilo plano con brillos suaves.',
      },
      steps: [
        S.choice({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:8.1.4', 'cnt:8.2.4'], prompt: 'Una niña dice: "Predigo que la semilla regada crecerá más que la que no se riega". ¿Qué debe hacer para saber si su predicción es correcta?' },
          { options: [{ id: 'a', text: 'Hacer un experimento con dos semillas iguales, regar solo una y medir' }, { id: 'b', text: 'Preguntar a sus amigos qué opinan' }, { id: 'c', text: 'Repetir la predicción en voz alta muchas veces' }], correct: ['a'] }),
        S.sort({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:8.3.5'], prompt: '¿Qué condición de calidad de vida describe cada dato?' },
          { buckets: [{ id: 'e', label: 'Educación', icon: 'GraduationCap' }, { id: 's', label: 'Salud', icon: 'Stethoscope' }, { id: 'v', label: 'Vivienda', icon: 'Home' }],
            items: [{ id: 'a', text: 'Años de estudio de la población', bucket: 'e' }, { id: 'b', text: 'Niñas y niños vacunados', bucket: 's' }, { id: 'c', text: 'Casas con piso firme y drenaje', bucket: 'v' }, { id: 'd', text: 'Escuelas cercanas', bucket: 'e' }] }),
        S.match({ fase: 'comprobar', areas: ['fc', 'ccss'], cnb: ['ccss:8.4.3'], prompt: 'Une cada institución con su función.' },
          { pairs: [{ id: 'a', left: 'Tribunal Supremo Electoral', right: 'Organiza las elecciones' }, { id: 'b', left: 'Corte de Constitucionalidad', right: 'Defiende el orden constitucional' }, { id: 'c', left: 'Procuraduría de los Derechos Humanos', right: 'Investiga denuncias de violaciones a derechos humanos' }, { id: 'd', left: 'Organismo Legislativo', right: 'Crea, reforma y deroga leyes' }] }),
        S.number({ fase: 'comprobar', areas: ['mat'], cnb: ['mat:7.5.1'], prompt: 'Supongamos que el COCODE reunió **Q1,680** para comprar arbolitos a **Q7** cada uno. ¿Cuántos arbolitos puede comprar?' },
          { answer: 240, unit: 'arbolitos', misconceptions: [{ value: 1687, msg: 'Sumaste. Para saber cuántos caben, divide el dinero entre el precio de cada uno.' }] }),
        S.fill({ fase: 'comprobar', areas: ['l1'], cnb: ['l1:7.3.4', 'l1:7.3.5'], prompt: 'Completa con los signos y las letras correctas.' },
          { text: '[[¿]]Qué [[cambio]] notas en el clima[[?]] En [[invierno]] llueve menos.', distractors: ['canbio', 'imbierno', '¡'] }),
        S.choice({ fase: 'comprobar', areas: ['l2', 'mat'], cnb: ['l2:5.4.9'], prompt: 'Una gráfica muestra dos barras con 50 y 55 votos, pero la de 55 está dibujada el triple de alta. ¿Qué ocurre?' },
          { options: [{ id: 'a', text: 'La imagen distorsiona el mensaje: exagera una diferencia pequeña' }, { id: 'b', text: 'La imagen favorece el mensaje porque es llamativa' }, { id: 'c', text: 'No importa cómo se dibujen las barras' }], correct: ['a'] }),
        S.match({ fase: 'comprobar', areas: ['l3'], cnb: ['l3:5.3.1', 'l3:5.3.3'], prompt: 'Match each expression with its meaning.' },
          { pairs: [{ id: 'a', left: 'What\'s up?', right: '¿Qué onda? / ¿Qué tal?' }, { id: 'b', left: 'Come on!', right: '¡Vamos! / ¡Ánimo!' }, { id: 'c', left: 'All right', right: 'Está bien / De acuerdo' }] }),
        S.order({ fase: 'comprobar', areas: ['fc'], cnb: ['fc:5.3.4'], prompt: 'Ordena del más antiguo al más reciente.' },
          { items: [{ id: 'a', text: 'Independencia (1821)' }, { id: 'b', text: 'Revolución de Octubre (1944)' }, { id: 'c', text: 'Constitución vigente (1985)' }, { id: 'd', text: 'Firma de la Paz (1996)' }] }),
        S.sort({ fase: 'comprobar', areas: ['art'], cnb: ['art:4.3.1'], prompt: 'Clasifica a los compositores por época.' },
          { buckets: [{ id: 'b', label: 'Barroco', icon: 'Church' }, { id: 'r', label: 'Romanticismo', icon: 'Heart' }],
            items: [{ id: 'a', text: 'Bach', bucket: 'b' }, { id: 'c', text: 'Chopin', bucket: 'r' }, { id: 'd', text: 'Vivaldi', bucket: 'b' }, { id: 'e', text: 'Chaikovski', bucket: 'r' }] }),
        S.choice({ fase: 'comprobar', areas: ['ef', 'pyd'], cnb: ['ef:4.2.2', 'pyd:5.5.1'], prompt: '¿Qué muestra mejor cooperación en un juego o en un evento comunitario?' },
          { options: [{ id: 'a', text: 'Rotar los roles y que cada persona o institución aporte según su función' }, { id: 'b', text: 'Que una sola persona decida y haga todo' }, { id: 'c', text: 'Que cada quien trabaje sin avisar a los demás' }], correct: ['a'] }),
      ],
    }),
  ],

  /* Banco de ítems para la Semana de validación de la Unidad 4 (el primer área = área principal) */
  bank: [
    S.tf({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:8.2.4'], prompt: '¿Verdadero o falso?' },
      { statements: [{ text: 'Los murciélagos son roedores ciegos.', answer: false }, { text: 'Un rayo puede caer más de una vez en el mismo lugar.', answer: true }, { text: 'El clima es el promedio del tiempo atmosférico de muchos años.', answer: true }] }),
    S.choice({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:7.3.4'], prompt: '¿Qué acción ayuda a contrarrestar el efecto invernadero?' },
      { options: [{ id: 'a', text: 'Reforestar las orillas de los ríos' }, { id: 'b', text: 'Quemar rastrojos y basura' }, { id: 'c', text: 'Dejar aparatos encendidos sin usarlos' }], correct: ['a'] }),
    S.number({ fase: 'comprobar', areas: ['cnt', 'mat'], cnb: ['cnt:8.1.4'], prompt: 'Supongamos que el nivel del agua de un tonel baja 4 cm cada día sin lluvia. Hoy mide 60 cm. Si el patrón sigue, ¿cuánto medirá en 5 días?' },
      { answer: 40, unit: 'cm', misconceptions: [{ value: 80, msg: 'El nivel baja, no sube: resta.' }] }),
    S.choice({ fase: 'comprobar', areas: ['ccss'], cnb: ['ccss:8.3.5'], prompt: '¿Qué dato ayuda a conocer la **calidad de vida** de un país?' },
      { options: [{ id: 'a', text: 'El porcentaje de viviendas con agua potable' }, { id: 'b', text: 'El número de canciones populares' }, { id: 'c', text: 'El color de su bandera' }], correct: ['a'] }),
    S.choice({ fase: 'comprobar', areas: ['ccss', 'fc'], cnb: ['ccss:8.4.3'], prompt: '¿Qué institución representa al Estado y lo asesora en asuntos legales?' },
      { options: [{ id: 'a', text: 'La Procuraduría General de la Nación' }, { id: 'b', text: 'El Tribunal Supremo Electoral' }, { id: 'c', text: 'El Organismo Judicial' }], correct: ['a'] }),
    S.number({ fase: 'comprobar', areas: ['mat'], cnb: ['mat:7.5.1'], prompt: 'Supongamos que la entrada al festival cuesta Q5 por estudiante y Q10 por persona adulta. Llegan 36 estudiantes y 18 adultos. ¿Cuántos quetzales se reúnen?' },
      { answer: 360, unit: 'quetzales', misconceptions: [{ value: 270, msg: 'Revisa: 36 × 5 = 180 y 18 × 10 = 180. Suma los dos.' }] }),
    S.order({ fase: 'comprobar', areas: ['l1'], cnb: ['l1:8.3.2'], prompt: 'Ordena los conceptos de un mapa conceptual, del más general al más específico.' },
      { items: [{ id: 'a', text: 'Estado de Guatemala' }, { id: 'b', text: 'Organismos del Estado' }, { id: 'c', text: 'Organismo Legislativo' }, { id: 'd', text: 'Congreso de la República' }] }),
    S.choice({ fase: 'comprobar', areas: ['l1', 'l2'], cnb: ['l1:8.1.3'], prompt: 'Buscas en internet cuándo se firmó la paz en Guatemala. ¿Qué haces para que tu dato sea confiable?' },
      { options: [{ id: 'a', text: 'Comparo al menos dos fuentes con autor y fecha, como un sitio oficial y un libro' }, { id: 'b', text: 'Copio el primer mensaje que aparece' }, { id: 'c', text: 'Creo lo que dice un video anónimo' }], correct: ['a'] }),
    S.choice({ fase: 'comprobar', areas: ['l2'], cnb: ['l2:5.4.8'], prompt: '¿Cuál oración pertenece a un **texto formal y académico**?' },
      { options: [{ id: 'a', text: 'El Organismo Judicial ejerce la función de juzgar y promover la ejecución de lo juzgado.' }, { id: 'b', text: '¡Púchica, los jueces sí trabajan un montón!' }, { id: 'c', text: 'Había una vez un juez que vivía en un castillo.' }], correct: ['a'] }),
    S.fill({ fase: 'comprobar', areas: ['l3'], cnb: ['l3:5.3.1'], prompt: 'Complete the dialogue.' },
      { text: 'Ana: Hi, Tom! [[What\'s up?]]\nTom: Not much! Let\'s run. [[Come on!]]', distractors: ['Goodbye'] }),
    S.choice({ fase: 'comprobar', areas: ['ef'], cnb: ['ef:4.2.6', 'ef:4.2.10'], prompt: '¿Por qué decimos que el juego es un **fenómeno social y cultural**?' },
      { options: [{ id: 'a', text: 'Porque se transmite entre generaciones y une a las personas de una comunidad' }, { id: 'b', text: 'Porque solo sirve para ganar' }, { id: 'c', text: 'Porque se juega siempre a solas' }], correct: ['a'] }),
    S.choice({ fase: 'comprobar', areas: ['fc'], cnb: ['fc:5.3.3'], prompt: '¿Qué ejemplo muestra el **intercambio cultural** en la historia del pueblo ladino?' },
      { options: [{ id: 'a', text: 'Hablar un español con palabras de origen indígena como "aguacate" y "elote"' }, { id: 'b', text: 'Vivir sin contacto con otros pueblos' }, { id: 'c', text: 'Olvidar todas las tradiciones' }], correct: ['a'] }),
  ],
});
