// Behavioral fixture: real activity components, grading, and low-activity store.
import assert from 'node:assert/strict';
import { build } from 'esbuild';
import { resolve } from 'node:path';
import { chromium } from 'playwright';
const types = ['reading','true-false','reflection','project','leadership-simulation','cultural-conservation-practice','short-answer','worked-example','explain','flashcards','low-activity-mode'];
const options = [{id:'yes',text:'Una decisión compartida',correct:true},{id:'no',text:'Decidir sin escuchar',correct:false}];
const fixtures = {
 reading:{passage:'El río atraviesa nuestra comunidad.',questions:[{q:'¿Qué atraviesa la comunidad?',options:[{id:'a',text:'El río'},{id:'b',text:'El camino'}],correct:'a'},{q:'¿Dónde está el río?',options:[{id:'a',text:'En la comunidad'},{id:'b',text:'Lejos'}],correct:'a'}]},
 'true-false':{statements:[{text:'Primera afirmación',answer:true},{text:'Segunda afirmación',answer:false}]},
 reflection:{statements:['Escucho a mis compañeros','Comparto mis ideas'],commitments:['Seguir escuchando']},
 project:{goal:'Crear un cartel',steps:[{title:'Preparar',detail:'Buscar papel'},{title:'Dibujar',detail:'Dibujar el río'}],evidence:'Mi cartel',rubric:['Es claro','Tiene imágenes']},
 'leadership-simulation':{scenario:'Organizamos el equipo.',instructions:options,rolePlans:options,adaptations:options,sequences:options,response:'Equipo organizado'},
 'cultural-conservation-practice':{rubric:['Contexto real','Recurso','Acción','Verificación'],example:{}},
 'short-answer':{model:'Escuchar permite aprender las ideas de otras personas.',rubric:['Explica la idea','Usa un ejemplo'],minWords:3},
 'worked-example':{problem:'Sumar dos más dos',steps:[{text:'Contar dos'},{text:'Agregar dos'},{text:'Obtener cuatro'}]},
 explain:{body:'Descubre los símbolos',reveal:[{front:'Punto',back:'Vale uno'},{front:'Barra',back:'Vale cinco'}]},
 flashcards:{cards:[{front:'Uno',back:'1'},{front:'Dos',back:'2'},{front:'Tres',back:'3'}]},
 'low-activity-mode':{}
};
const source = `import React,{useState} from 'react';import{createRoot}from'react-dom/client';import '@/design-system/global.css';import '@/activities/activities.css';import '@/ui/activity-journey.css';${types.map((t,i)=>`import a${i} from '@/activities/${t}';`).join('')}
const definitions=[${types.map((_,i)=>`a${i}`).join(',')}];const fixtures=${JSON.stringify(fixtures)};
function App(){const type=location.hash.slice(1)||'true-false';const def=definitions.find(d=>d.type===type);const[value,setValue]=useState();const[ready,setReady]=useState(false);const[status,setStatus]=useState('answering');window.setActivityStatus=setStatus;const props=fixtures[type];const C=def.Component;return <main style={{padding:16,maxWidth:700,margin:'auto'}}><C props={props} value={value} onChange={setValue} api={{setReady}} status={status} attempt={0} step={{id:'fixture',type,props}}/><output data-testid="value">{JSON.stringify(value)}</output><output data-testid="ready">{String(def.isReady?def.isReady(props,value):ready)}</output></main>}createRoot(document.getElementById('root')).render(<App/>);`;
const bundle = await build({stdin:{contents:source,loader:'tsx',resolveDir:process.cwd()},bundle:true,minify:true,write:false,outdir:'/tmp/stages-bundle',format:'iife',jsx:'automatic',alias:{'@':resolve('src')},define:{'process.env.NODE_ENV':'"production"'},logLevel:'silent'});
const js=bundle.outputFiles.find(f=>f.path.endsWith('.js')).text.replace(/<\/script/gi,'<\\/script');
const css=bundle.outputFiles.find(f=>f.path.endsWith('.css')).text;
const html=`<!doctype html><html lang="es"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}output{display:none}</style><body><div id="root"></div><script>${js}</script></body></html>`;
const browser=await chromium.launch(process.env.CHROMIUM ? {executablePath:process.env.CHROMIUM} : {});const errors=[];
const page=await browser.newPage({viewport:{width:320,height:844},reducedMotion:'reduce',hasTouch:true});page.setDefaultTimeout(3000);page.on('pageerror',e=>errors.push(e.message));
await page.route('**/*',r=>r.fulfill({contentType:'text/html',body:html}));
const go=async type=>{await page.goto(`http://stages.test/${type}?run=${Date.now()}#${type}`);await page.locator('main').waitFor();};
const button=name=>page.getByRole('button',{name,exact:true});
const focused=async text=>page.waitForFunction(expected=>document.activeElement?.textContent===expected,text);
const val=async()=>JSON.parse(await page.getByTestId('value').textContent());
const ready=async()=>{await page.waitForFunction(()=>document.querySelector('[data-testid=ready]').textContent==='true');return page.getByTestId('ready').textContent();};
try {
await go('true-false');assert.equal(await page.getByRole('radiogroup').count(),1,'Show only the current statement');
const truth=page.getByRole('radio',{name:'Verdadero',exact:true});const truthBounds=await truth.boundingBox();assert.ok(truthBounds.y>=0&&truthBounds.y+truthBounds.height<=844);await page.touchscreen.tap(truthBounds.x+truthBounds.width/2,truthBounds.y+truthBounds.height/2);assert.equal(await page.getByText('Primera afirmación',{exact:true}).count(),1,'Do not auto-advance');await button('Siguiente').focus();await page.keyboard.press('Enter');await page.getByRole('radio',{name:'Falso',exact:true}).click();await button('Revisar mis respuestas').click();await button('Editar respuesta 1').focus();await page.keyboard.press('Enter');await focused('Afirmación 1 de 2');assert.equal(await page.getByRole('radio',{name:'Verdadero',exact:true}).getAttribute('aria-checked'),'true');assert.deepEqual(await val(),[true,false]);await page.getByRole('radio',{name:'Falso',exact:true}).click();await page.evaluate(()=>window.setActivityStatus('incorrect'));await button('Revisar mis respuestas').click();await page.getByText('Revisar esta respuesta',{exact:true}).waitFor();await page.evaluate(()=>window.setActivityStatus('correct'));await button('Ver respuesta 1').waitFor();assert.equal(await button('Editar respuesta 1').count(),0);await button('Ver respuesta 1').click();assert.equal(await page.getByRole('radio',{name:'Verdadero',exact:true}).isDisabled(),true);
await go('reading');assert.equal(await page.locator('.ds-tile').count(),0);await button('Comenzar preguntas').click();await focused('Pregunta 1 de 2');await button('El río').click();await page.getByText('Consultar texto',{exact:true}).click();await page.getByText('El río atraviesa nuestra comunidad.',{exact:true}).waitFor();await page.getByText('Consultar texto',{exact:true}).click();await button('Siguiente').click();await button('Anterior').click();assert.deepEqual(await val(),{'0':'a'});
await go('reflection');assert.equal(await page.getByRole('radiogroup').count(),1);await page.getByRole('radio',{name:'Con ayuda'}).click();await button('Siguiente').click();await page.getByRole('radio',{name:'¡Sí, solo!'}).click();await button('Siguiente').click();await button('Seguir escuchando').click();await button('Revisar mis respuestas').click();assert.equal(await ready(),'true');await button('Editar respuesta 1').click();await focused('Autoevaluación 1 de 3');
await go('project');assert.equal(await page.getByRole('checkbox').count(),0);await button('Siguiente').click();await page.getByRole('checkbox').first().check();await button('Anterior').click();await button('Siguiente').click();assert.equal(await page.getByRole('checkbox').first().isChecked(),true);await button('Siguiente').click();assert.equal(await page.getByRole('radiogroup').count(),2);
await go('leadership-simulation');assert.equal(await page.getByRole('group').count(),1);assert.equal(await button('Ejecutar indicaciones y verificar respuesta').count(),0);for(let i=0;i<4;i++){await page.getByRole('radio').first().check();await button(i===3?'Revisar mis respuestas':'Siguiente').click();}await button('Ejecutar indicaciones y verificar respuesta').click();assert.equal((await val()).verified,true);await button('Editar respuesta 1').click();await focused('Decisión 1 de 4');await page.getByRole('radio').last().check();assert.equal((await val()).verified,false);
await go('short-answer');await page.getByRole('textbox').fill('Escucho otras ideas');await button('Comparar con una respuesta modelo').focus();await page.keyboard.press('Enter');await focused('Paso 2 de 3');assert.equal(await page.getByRole('textbox').count(),0);await button('Siguiente').click();await page.getByRole('checkbox').first().check();await button('Editar mi respuesta').click();await page.waitForFunction(()=>document.activeElement?.tagName==='TEXTAREA');assert.equal(await page.getByRole('textbox').inputValue(),'Escucho otras ideas');assert.equal((await val()).checks[0],true);
await go('worked-example');await button('Ver el primer paso').click();await button('Siguiente paso (2 de 3)').click();assert.equal(await page.getByText('Contar dos',{exact:true}).isVisible(),false);await page.getByText('Consultar pasos anteriores',{exact:true}).click();await page.getByText('Contar dos',{exact:true}).waitFor();
await go('explain');await page.getByRole('button',{name:/Punto/}).click();await page.getByRole('button',{name:/Barra/}).click();assert.equal(await ready(),'true');await page.getByRole('button',{name:/Punto/}).click();assert.equal(await page.getByText('Vale uno',{exact:true}).count(),0);assert.equal(await ready(),'true','Closing seen disclosure keeps completion');
await go('flashcards');await button('Voltear tarjeta').click();await button('¡Ya la sé!').click();await button('Anterior').click();await page.getByText('Uno',{exact:true}).waitFor();assert.equal((await val()).seen[0],true);
await go('low-activity-mode');assert.equal(await page.getByRole('region',{name:'Estado actual'}).isVisible(),false);await page.getByText('Detalles del estado',{exact:true}).click();await page.getByRole('region',{name:'Estado actual'}).waitFor();await button('Activar modo de baja actividad').click();
await go('cultural-conservation-practice');await page.getByRole('radio',{name:'Necesito consultar una práctica'}).check();await page.getByRole('textbox').fill('Consultaré a mi abuela sobre el cuidado del río');await button('Confirmar que necesito consulta').click();assert.equal(await ready(),'true');
await go('cultural-conservation-practice');await page.getByRole('radio',{name:'Conozco una práctica de mi contexto'}).check();assert.equal(await page.getByRole('textbox').count(),2);await page.getByRole('textbox').first().fill('Cuidar nuestro río');await button('Siguiente').click();assert.equal(await page.getByRole('textbox').count(),3);await button('Anterior').click();assert.equal(await page.getByRole('textbox').first().inputValue(),'Cuidar nuestro río');
// Keep the genuine maintenance control mounted while its stage is hidden.
await button('Siguiente').click();await page.clock.install();await button('Iniciar mantenimiento de 25 segundos').click();
await button('Siguiente').click();await page.clock.fastForward(26000);
await page.waitForFunction(()=>JSON.parse(document.querySelector('[data-testid=value]').textContent).practice?.maintenanceCompleted===true);
assert.equal((await val()).practice.verified,true,'Hidden action timer completes and preserves its live receipt');
await button('Anterior').click();await button('Mantenimiento completado').waitFor();await page.clock.resume();
// Bounds of visible controls, including enlarged text and landscape.
for(const type of types) for(const [width,height] of [[320,844],[375,844],[390,844],[430,844],[768,900],[1280,900],[844,390]]) {await go(type);await page.setViewportSize({width,height});await page.evaluate(()=>document.documentElement.style.fontSize='200%');if(type==='cultural-conservation-practice'){await page.getByRole('radio',{name:'Conozco una práctica de mi contexto'}).check();await button('Siguiente').click();}if(type==='reading')await button('Comenzar preguntas').click();if(type==='project')await button('Siguiente').click();const outside=await page.locator('main button,main input,main textarea,main summary').evaluateAll(nodes=>nodes.filter(el=>el.checkVisibility()).filter(el=>{const r=el.getBoundingClientRect();return r.left < -1 || r.right > innerWidth+1;}).map(el=>el.textContent));assert.deepEqual(outside,[],`${type} fits ${width}`);}
assert.deepEqual(errors,[]);console.log('Mobile staged activities: all behavioral and layout assertions passed.');
} finally {await browser.close();}
