/** Ciencias Naturales y Tecnologia · Unidad 1 · Semana 4. */
import { lesson, S } from '../../../../dsl';

export default [
  lesson({
    id: 's04-cnt-1', title: 'Estructura del aparato reproductor masculino', icon: 'ScanLine', minutes: 14,
    gancho: 'Una ruta anatomica se comprende al relacionar cada estructura con su funcion.',
    objetivos: ['Explicar la estructura del aparato reproductor masculino mediante la ubicacion, funcion y recorrido de sus partes'],
    resumen: ['Los testiculos forman espermatozoides.', 'El epididimo los almacena temporalmente y el conducto deferente los transporta.', 'Las vesiculas seminales y la prostata aportan liquidos; la uretra atraviesa el pene y conduce el semen al exterior.'],
    media: { id: 's04-cnt-1-estructura', kind: 'diagram', title: 'Aparato reproductor masculino', aspect: '4:3', alt: 'Diagrama anatomico esquematico y no explicito con las estructuras internas rotuladas.', brief: 'Diagrama anatomico educativo 1200x900, vista lateral esquematica y no explicita. Rotular testiculos, epididimo, conducto deferente, vesiculas seminales, prostata, uretra y pene; usar flechas para el recorrido sin representar actividad sexual. Texto grande, alto contraste, patron ademas de color y descripcion lineal accesible.' },
    steps: [
      S.explain({ fase: 'explorar', areas: ['cnt'], cnb: ['cnt:3.1.1'], prompt: 'Relaciona la estructura, funcion y recorrido de testiculos, epididimo, conducto deferente, vesiculas seminales, prostata, uretra y pene.' }, { icon: 'Route', body: 'La anatomia se estudia con lenguaje cientifico: cada parte tiene una ubicacion y una funcion dentro de un recorrido.' }),
      S.explain({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:3.1.1'], title: 'Partes y funciones', prompt: 'Ubica y explica testiculos, epididimo, conducto deferente, vesiculas seminales, prostata, uretra y pene.' }, { icon: 'ListTree', body: '**Testiculos:** forman espermatozoides. **Epididimo:** maduracion y almacenamiento temporal. **Conducto deferente:** transporte. **Vesiculas seminales y prostata:** aportan liquidos. **Uretra:** conducto de salida que atraviesa el **pene**.' }),
      S.ejemplo({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:3.1.1'], title: 'Modelo de recorrido', prompt: 'Observa como explicar la estructura, funcion y recorrido de todas las partes.' }, { icon: 'MapPinned', problem: '¿Como se organiza el trayecto de las celulas reproductoras?', steps: [{ text: 'Se forman en los testiculos y pasan al epididimo.' }, { text: 'Viajan por el conducto deferente; vesiculas seminales y prostata aportan liquidos.' }, { text: 'El semen pasa por la uretra, que atraviesa el pene, hacia el exterior.' }], answer: 'Testiculos → epididimo → conducto deferente → aportes glandulares → uretra en el pene.' }),
      S.order({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:3.1.1'], prompt: 'Con ayuda, ordena la estructura, funcion y recorrido: testiculos, epididimo, conducto deferente, vesiculas seminales, prostata, uretra y pene.', hint: 'Empieza donde se forman los espermatozoides y termina en el conducto de salida.', explain: 'Las glandulas aportan liquidos antes de que el semen recorra la uretra.' }, { labels: { start: 'Inicio', end: 'Salida' }, items: [{ id: 'a', text: 'Testiculos: formacion' }, { id: 'b', text: 'Epididimo: maduracion y almacenamiento' }, { id: 'c', text: 'Conducto deferente: transporte' }, { id: 'd', text: 'Vesiculas seminales y prostata: liquidos' }, { id: 'e', text: 'Uretra a traves del pene: salida' }] }),
      S.match({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:3.1.1'], prompt: 'Relaciona funcion y estructura de testiculos, epididimo, conducto deferente, vesiculas seminales, prostata, uretra y pene.', hint: 'Distingue formacion, almacenamiento, transporte, aporte de liquidos y salida.', explain: 'Cada relacion ayuda a reconstruir el recorrido anatomico.' }, { pairs: [{ id: 'a', left: 'Testiculos y epididimo', right: 'Formacion, maduracion y almacenamiento temporal' }, { id: 'b', left: 'Conducto deferente', right: 'Transporte' }, { id: 'c', left: 'Vesiculas seminales y prostata', right: 'Aporte de liquidos' }, { id: 'd', left: 'Uretra y pene', right: 'Conducto y estructura de salida' }] }),
      S.write({ fase: 'aplicar', areas: ['cnt'], cnb: ['cnt:3.1.1'], prompt: 'Explica de forma independiente la estructura, funcion y recorrido de testiculos, epididimo, conducto deferente, vesiculas seminales, prostata, uretra y pene.' }, { minWords: 24, placeholder: 'El recorrido inicia...', model: 'Los testiculos forman celulas; el epididimo las almacena; el deferente transporta; vesiculas y prostata aportan liquidos; la uretra atraviesa el pene.', rubric: ['Nombre todas las estructuras', 'Relacione funcion y ubicacion', 'Ordene el recorrido'] }),
      S.choice({ fase: 'aplicar', areas: ['cnt'], cnb: ['cnt:3.1.1'], prompt: 'Al explicar la estructura, funcion y recorrido de testiculos, epididimo, conducto deferente, vesiculas seminales, prostata, uretra y pene, ¿que secuencia es correcta?' }, { options: [{ id: 'a', text: 'Formacion y epididimo; transporte; liquidos glandulares; uretra a traves del pene' }, { id: 'b', text: 'Uretra; testiculos; epididimo; sin glandulas' }, { id: 'c', text: 'Prostata forma todos los espermatozoides' }], correct: ['a'] }),
      S.choice({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:3.1.1'], prompt: 'Salida: identifica la explicacion correcta de estructura, funcion y recorrido de testiculos, epididimo, conducto deferente, vesiculas seminales, prostata, uretra y pene.' }, { options: [{ id: 'a', text: 'Testiculos forman; epididimo almacena; deferente transporta; glandulas aportan; uretra atraviesa el pene' }, { id: 'b', text: 'El pene forma espermatozoides y la uretra los almacena' }, { id: 'c', text: 'Todas las partes cumplen la misma funcion' }], correct: ['a'] }),
      S.tf({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:3.1.1'], prompt: 'Salida nueva: comprueba estructura, funcion y recorrido de testiculos, epididimo, conducto deferente, vesiculas seminales, prostata, uretra y pene.' }, { statements: [{ text: 'El epididimo participa en maduracion y almacenamiento temporal.', answer: true }, { text: 'Vesiculas seminales y prostata aportan liquidos.', answer: true }, { text: 'La uretra no tiene relacion con el pene.', answer: false }] }),
    ],
  }),

  lesson({
    id: 's04-cnt-2', title: 'Ovogenesis y espermatogenesis', icon: 'GitCompare', minutes: 15,
    gancho: 'Dos procesos producen celulas reproductoras, pero no siguen el mismo patron.',
    objetivos: ['Distinguir ovogenesis y espermatogenesis por lugar, proceso y celulas resultantes'],
    resumen: ['La ovogenesis ocurre en los ovarios y produce una celula funcional grande y cuerpos polares.', 'La espermatogenesis ocurre en los testiculos y produce espermatozoides.', 'En lenguaje comun se dice ovulo; con precision, suele liberarse un ovocito secundario y la meiosis II se completa solo si ocurre fecundacion.'],
    media: { id: 's04-cnt-2-gametogenesis', kind: 'diagram', title: 'Comparacion de gametogenesis', aspect: '16:9', alt: 'Dos columnas comparan ovogenesis y espermatogenesis con celulas esquematicas.', brief: 'Diagrama educativo 1600x900 en dos columnas. Ovogenesis: ovario, una celula funcional grande, cuerpos polares, ovocito secundario y nota de meiosis II. Espermatogenesis: testiculo y varios espermatozoides pequenos y moviles. Sin anatomia explicita; texto grande, alto contraste y formas ademas de color.' },
    steps: [
      S.explain({ fase: 'explorar', areas: ['cnt'], cnb: ['cnt:3.2.1'], prompt: 'Compara y distingue ovogenesis en ovarios y espermatogenesis en testiculos por proceso y celulas resultantes.' }, { icon: 'GitCompare', body: 'Ambas usan division celular, pero cambian el lugar, el ritmo y el resultado.' }),
      S.explain({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:3.2.1'], prompt: 'Distingue ovogenesis y espermatogenesis: ovarios, testiculos, ovocito y espermatozoides.' }, { icon: 'Microscope', body: 'La **ovogenesis** ocurre en ovarios y distribuye el citoplasma de manera desigual: una celula funcional grande y cuerpos polares. La **espermatogenesis** ocurre en testiculos y forma espermatozoides pequenos. Suele liberarse un **ovocito secundario**; la meiosis II se completa solo si ocurre la fecundacion. "Ovulo" es un termino comun simplificado.' }),
      S.ejemplo({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:3.2.1'], title: 'Modelo comparativo', prompt: 'Observa como comparar y distinguir ovogenesis y espermatogenesis.' }, { icon: 'Columns2', problem: 'Completa lugar, celula resultante y diferencia.', steps: [{ text: 'Ovogenesis: ovarios; una celula funcional grande y cuerpos polares.' }, { text: 'Espermatogenesis: testiculos; espermatozoides pequenos.' }, { text: 'La diferencia no es solo el nombre: cambia la distribucion del citoplasma y el resultado.' }], answer: 'Los dos procesos forman gametos mediante rutas diferentes.' }),
      S.match({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:3.2.1'], prompt: 'Con ayuda, compara y distingue ovogenesis en ovarios y espermatogenesis en testiculos, incluido ovocito y espermatozoides.', hint: 'Busca lugar y producto.', explain: 'La ovogenesis no produce cuatro celulas funcionales iguales.' }, { pairs: [{ id: 'a', left: 'Ovogenesis en ovarios', right: 'Una celula funcional grande y cuerpos polares' }, { id: 'b', left: 'Espermatogenesis en testiculos', right: 'Espermatozoides pequenos' }, { id: 'c', left: 'Ovocito secundario', right: 'Puede ser liberado; meiosis II solo si ocurre fecundacion' }] }),
      S.choice({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:3.2.1'], prompt: 'Compara ovogenesis y espermatogenesis por ovarios, testiculos, ovocito y espermatozoides.', hint: 'No confundas el termino comun ovulo con la etapa celular precisa.', explain: 'La opcion correcta diferencia lugar y resultado.' }, { options: [{ id: 'a', text: 'Ovogenesis-ovarios-ovocito; espermatogenesis-testiculos-espermatozoides' }, { id: 'b', text: 'Ambas ocurren solo en ovarios' }, { id: 'c', text: 'Ambas producen celulas identicas' }], correct: ['a'] }),
      S.write({ fase: 'aplicar', areas: ['cnt'], cnb: ['cnt:3.2.1'], prompt: 'Compara y distingue de forma independiente ovogenesis en ovarios y espermatogenesis en testiculos; incluye ovocito, celula funcional grande, cuerpos polares y espermatozoides.' }, { minWords: 24, placeholder: 'Ovogenesis... Espermatogenesis...', model: 'La ovogenesis ocurre en ovarios y deja una celula funcional grande con cuerpos polares; la espermatogenesis ocurre en testiculos y forma espermatozoides.', rubric: ['Compare lugar', 'Diferencie resultados', 'Use terminos precisos'] }),
      S.choice({ fase: 'aplicar', areas: ['cnt'], cnb: ['cnt:3.2.1'], prompt: 'Al comparar y distinguir ovogenesis y espermatogenesis en ovarios y testiculos, con ovocito y espermatozoides, ¿que diferencia importa?' }, { options: [{ id: 'a', text: 'Lugar y tipo de celulas resultantes' }, { id: 'b', text: 'Solo el color de la celula' }, { id: 'c', text: 'No existe ninguna diferencia' }], correct: ['a'] }),
      S.choice({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:3.2.1'], prompt: 'Salida: compara y distingue ovogenesis en ovarios y espermatogenesis en testiculos, ovocito y espermatozoides.' }, { options: [{ id: 'a', text: 'Ovogenesis: una celula funcional grande y cuerpos polares; espermatogenesis: espermatozoides' }, { id: 'b', text: 'Ovogenesis: testiculos; espermatogenesis: ovarios' }, { id: 'c', text: 'Los procesos producen resultados identicos' }], correct: ['a'] }),
      S.tf({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:3.2.1'], prompt: 'Salida nueva: distingue ovogenesis y espermatogenesis en ovarios y testiculos, ovocito y espermatozoides.' }, { statements: [{ text: 'La ovogenesis ocurre en ovarios.', answer: true }, { text: 'La espermatogenesis forma espermatozoides en testiculos.', answer: true }, { text: 'La meiosis II del ovocito siempre termina antes de cualquier fecundacion.', answer: false }] }),
    ],
  }),

  lesson({
    id: 's04-cnt-3', title: 'Cuidado sexual informado y respetuoso', icon: 'HeartHandshake', minutes: 15,
    gancho: 'Cuidarse exige informacion precisa, respeto y responsabilidades compartidas.',
    objetivos: ['Evaluar decisiones de salud sexual que integren conducta etica, paternidad responsable y la diferencia entre VIH y SIDA'],
    resumen: ['Las decisiones eticas respetan consentimiento, intimidad, limites y ausencia de presion; cada cuerpo cambia a su ritmo.', 'La paternidad responsable comparte cuidado, tiempo, proteccion y recursos.', 'VIH es el virus; SIDA es una fase avanzada de la infeccion por VIH y no son sinonimos. El tratamiento puede evitar esa progresion.'],
    media: { id: 's04-cnt-3-cuidado', kind: 'diagram', title: 'Decisiones de cuidado', aspect: '16:9', alt: 'Tarjetas sobre respeto, responsabilidad compartida e informacion precisa de VIH y SIDA.', brief: 'Diagrama educativo 1600x900 con tres paneles: consentimiento e intimidad, paternidad responsable compartida, y VIH versus SIDA. Incluir "VIH = virus" y "SIDA = fase avanzada; no son sinonimos". Sin estigma, anatomia explicita ni imagenes de enfermedad; texto grande, alto contraste e iconos descriptivos.' },
    steps: [
      S.explain({ fase: 'explorar', areas: ['cnt'], cnb: ['cnt:3.3.1', 'cnt:3.5.1'], prompt: 'Evalua una decision responsable que una conducta etica, paternidad responsable y la diferencia cientifica entre VIH y SIDA.' }, { icon: 'ShieldCheck', body: 'El cuidado combina **respeto y consentimiento**, **responsabilidad compartida** e **informacion confiable**. VIH es el virus; SIDA es una fase avanzada, no un sinonimo.' }),
      S.explain({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:3.3.1', 'cnt:3.5.1'], title: 'Etica, responsabilidad y precision', prompt: 'Relaciona conducta etica y paternidad responsable con informacion correcta sobre el virus VIH y el sindrome SIDA.' }, { icon: 'BookOpenCheck', body: 'Una conducta etica respeta limites, consentimiento, intimidad y decisiones sin presion; **cada cuerpo cambia a su ritmo**. La **paternidad responsable** comparte crianza, tiempo, proteccion y recursos. El **VIH** es un virus que afecta el sistema inmunitario; el **SIDA** es una fase avanzada que puede aparecer sin tratamiento. Tener VIH no significa tener SIDA, y el tratamiento puede impedir esa progresion. El VIH no se transmite por abrazar, compartir pupitre ni convivir. Una persona adulta de confianza y un profesional de salud son fuentes confiables para dudas personales.' }),
      S.ejemplo({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:3.3.1', 'cnt:3.5.1'], title: 'Modelo de decision', prompt: 'Observa como evaluar conducta etica, paternidad responsable y la diferencia entre virus VIH y sindrome SIDA.' }, { icon: 'SearchCheck', problem: 'Un rumor dice que VIH y SIDA son iguales y que el cuidado corresponde a una sola persona.', steps: [{ text: 'Se corrige: VIH es el virus; SIDA es una fase avanzada, no son sinonimos.' }, { text: 'Se rechaza la culpa y se busca informacion de un profesional de salud.' }, { text: 'La paternidad responsable implica cuidado compartido y respeto.' }], answer: 'La respuesta precisa evita estigma y propone responsabilidades eticas.' }),
      S.choice({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:3.3.1', 'cnt:3.5.1'], prompt: 'Con ayuda, evalua conducta etica, paternidad responsable y la diferencia entre el virus VIH y el sindrome SIDA.', hint: 'Busca respeto, responsabilidad compartida y precision cientifica.', explain: 'VIH y SIDA no son sinonimos; el cuidado no se basa en culpa ni presion.' }, { options: [{ id: 'a', text: 'Respetar limites, compartir la crianza y explicar que VIH es el virus y SIDA una fase avanzada' }, { id: 'b', text: 'Presionar, culpar y decir que VIH siempre significa SIDA' }, { id: 'c', text: 'Ocultar informacion y dejar todo el cuidado a una persona' }], correct: ['a'] }),
      S.tf({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:3.3.1', 'cnt:3.5.1'], prompt: 'Revisa conducta etica, paternidad responsable y diferencia entre virus VIH y sindrome SIDA.', hint: 'Distingue virus de fase avanzada.', explain: 'El tratamiento y la orientacion profesional importan; la apariencia no permite determinar la condicion de salud de una persona.' }, { statements: [{ text: 'El consentimiento y la intimidad forman parte del respeto.', answer: true }, { text: 'La paternidad responsable comparte cuidado y recursos.', answer: true }, { text: 'VIH y SIDA son exactamente lo mismo.', answer: false }] }),
      S.write({ fase: 'aplicar', areas: ['cnt'], cnb: ['cnt:3.3.1', 'cnt:3.5.1'], prompt: 'Evalua de forma independiente un consejo de salud sexual: incluye conducta etica, paternidad responsable y explica que VIH es un virus y SIDA una fase avanzada, no sinonimos.' }, { minWords: 18, placeholder: 'La decision responsable...', model: 'Una decision etica respeta limites y comparte responsabilidades. VIH es el virus; SIDA es una fase avanzada.', rubric: ['Inclui respeto y consentimiento', 'Explique responsabilidad compartida', 'Diferencie VIH y SIDA sin estigma'] }),
      S.choice({ fase: 'aplicar', areas: ['cnt'], cnb: ['cnt:3.3.1', 'cnt:3.5.1'], prompt: 'Al evaluar conducta etica y paternidad responsable con la diferencia entre virus VIH y sindrome SIDA, ¿que respuesta es correcta?' }, { options: [{ id: 'a', text: 'Respeto y cuidado compartido; VIH es el virus y SIDA una fase avanzada que el tratamiento puede prevenir' }, { id: 'b', text: 'La presion es valida y VIH siempre equivale a SIDA' }, { id: 'c', text: 'La apariencia revela la condicion de salud y una persona carga todo el cuidado' }], correct: ['a'] }),
      S.choice({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:3.3.1', 'cnt:3.5.1'], prompt: 'Salida: identifica conducta etica y paternidad responsable junto con la diferencia entre el virus VIH y el sindrome SIDA.' }, { options: [{ id: 'a', text: 'Consentimiento y crianza compartida; VIH es virus y SIDA una fase avanzada, no sinonimos' }, { id: 'b', text: 'Presion y abandono; VIH y SIDA son sinonimos' }, { id: 'c', text: 'Rumores y culpa sustituyen la informacion profesional' }], correct: ['a'] }),
      S.tf({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:3.3.1', 'cnt:3.5.1'], prompt: 'Salida nueva: comprueba conducta etica, paternidad responsable y diferencia entre virus VIH y sindrome SIDA.' }, { statements: [{ text: 'Respetar limites y compartir la crianza son decisiones responsables.', answer: true }, { text: 'Una persona con VIH necesariamente tiene SIDA.', answer: false }, { text: 'Una fuente confiable o profesional de salud orienta mejor que un rumor.', answer: true }] }),
    ],
  }),
];
