/** Ciencias Naturales y Tecnologia · Unidad 1 · Semana 5. */
import { lesson, S } from '../../../../dsl';

export default [
  lesson({
    id: 's05-cnt-1', title: 'Tipos de drogas y sus efectos', icon: 'Brain', minutes: 14,
    gancho: '¿Por que una sustancia legal tambien puede alterar el sistema nervioso?',
    objetivos: ['Diferenciar tipos de drogas segun sus efectos en el sistema nervioso'],
    resumen: ['Una droga altera funciones del organismo y puede causar dependencia.', 'Por su efecto, puede clasificarse como depresora, estimulante o perturbadora.', 'La clasificacion por efecto no indica que una sustancia sea segura ni coincide siempre con su situacion legal.'],
    media: { id: 's05-cnt-1-defensas', kind: 'diagram', title: 'Tres efectos en el sistema nervioso', aspect: '16:9', alt: 'Tres paneles muestran actividad mas lenta, mas rapida y percepcion alterada, sin representar consumo.', brief: 'Diagrama educativo 1600x900 con tres paneles rotulados DEPRESORAS, ESTIMULANTES y PERTURBADORAS. Usar un cerebro esquematico y flechas de ritmo; incluir ejemplos escritos y la advertencia "legal no significa inocua". No mostrar personas consumiendo, marcas ni envases reconocibles. Texto grande, contraste alto y patrones ademas de color.' },
    steps: [
      S.explain({ fase: 'explorar', areas: ['cnt'], cnb: ['cnt:4.1.1'], prompt: 'Diferencia los tipos de drogas por el efecto que producen, no por si son legales o ilegales.' }, { icon: 'Brain', body: 'Una **droga** altera funciones del organismo. Por su efecto nervioso se clasifica como **depresora, estimulante o perturbadora**.' }),
      S.explain({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:4.1.1'], title: 'Tres tipos por efecto', prompt: 'Clasifica sustancias por su efecto principal en el sistema nervioso.' }, { icon: 'ListTree', body: 'Las **depresoras** vuelven mas lenta la actividad; las **estimulantes** la aceleran; las **perturbadoras o alucinogenas** alteran percepcion y pensamiento. Alcohol: depresora; cafeina y nicotina: estimulantes; algunos alucinogenos: perturbadores. Ningun tipo es inocuo por ser legal.' }),
      S.ejemplo({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:4.1.1'], title: 'Modelo: clasificar por evidencia', prompt: 'Observa como diferenciar depresora, estimulante y perturbadora por el efecto descrito.' }, { icon: 'SearchCheck', problem: 'Tres fichas dicen: A enlentece reflejos; B aumenta alerta; C altera la percepcion.', steps: [{ text: 'A corresponde a una droga depresora.' }, { text: 'B corresponde a una droga estimulante.' }, { text: 'C corresponde a una droga perturbadora o alucinogena.' }], answer: 'El efecto descrito, no la legalidad, determina esta clasificacion.' }),
      S.sort({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:4.1.1'], prompt: 'Clasifica cada droga o sustancia como depresora, estimulante o perturbadora segun el efecto indicado.', hint: 'Lento = depresora; rapido o alerta = estimulante; percepcion alterada = perturbadora.', explain: 'La clasificacion describe el efecto principal y no afirma que una sustancia sea segura.' }, { buckets: [{ id: 'd', label: 'Depresora', icon: 'Gauge', color: 'var(--area-cnt)' }, { id: 'e', label: 'Estimulante', icon: 'Zap', color: 'var(--c-maiz-strong)' }, { id: 'p', label: 'Perturbadora', icon: 'Waves', color: 'var(--area-art)' }], items: [{ id: 'a', text: 'Alcohol: enlentece reflejos', bucket: 'd' }, { id: 'b', text: 'Cafeina: aumenta alerta', bucket: 'e' }, { id: 'c', text: 'Alucinogeno: altera percepcion', bucket: 'p' }] }),
      S.choice({ fase: 'aplicar', areas: ['cnt'], cnb: ['cnt:4.1.1'], prompt: 'Caso nuevo: una ficha describe una droga que acelera la actividad nerviosa. Al diferenciar depresoras, estimulantes y perturbadoras, ¿que tipo corresponde?' }, { options: [{ id: 'a', text: 'Estimulante' }, { id: 'b', text: 'Depresora' }, { id: 'c', text: 'Perturbadora' }], correct: ['a'] }),
      S.write({ fase: 'aplicar', areas: ['cnt'], cnb: ['cnt:4.1.1'], prompt: 'Diferencia los tres tipos de drogas: depresora, estimulante y perturbadora. Describe el efecto que permite clasificar cada una.' }, { minWords: 18, placeholder: 'Depresora... Estimulante... Perturbadora...', model: 'Depresora: enlentece. Estimulante: acelera. Perturbadora: altera la percepcion.', rubric: ['Nombre los tres tipos', 'Use el efecto para diferenciarlos', 'No confundi legalidad con seguridad'] }),
      S.choice({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:4.1.1'], prompt: 'Al clasificar drogas como depresoras, estimulantes y perturbadoras, ¿que criterio las diferencia?' }, { options: [{ id: 'a', text: 'Su efecto principal en el sistema nervioso' }, { id: 'b', text: 'El color del envase' }, { id: 'c', text: 'Que todas producen el mismo efecto' }], correct: ['a'] }),
      S.tf({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:4.1.1'], prompt: 'Diferencia drogas depresoras, estimulantes y perturbadoras por sus efectos.' }, { statements: [{ text: 'Una depresora puede enlentecer reflejos.', answer: true }, { text: 'Una estimulante y una perturbadora siempre producen el mismo efecto.', answer: false }, { text: 'Una perturbadora puede alterar la percepcion.', answer: true }] }),
      S.reflect({ fase: 'reflexionar', areas: ['cnt'], cnb: ['cnt:4.1.1'], prompt: 'Revisa como clasificaste las sustancias.' }, { statements: ['Use evidencia del efecto', 'Diferencie los tres tipos', 'No trate legal como sinonimo de seguro'], commitments: ['Pedire informacion confiable a una persona adulta responsable'] }),
    ],
  }),

  lesson({
    id: 's05-cnt-2', title: 'Tiempo libre saludable y libre de drogas', icon: 'Activity', minutes: 14,
    gancho: '¿Como puede un plan de tiempo libre reunir movimiento, diversion y convivencia?',
    objetivos: ['Ilustrar practicas saludables de tiempo libre libres del consumo de drogas'],
    resumen: ['Deportes, juegos, actividades sociales y recreacion pueden formar parte de una vida saludable.', 'Una practica protectora es voluntaria, segura, inclusiva y libre del consumo de drogas.', 'Tener opciones y apoyo no elimina todos los riesgos, pero fortalece decisiones de cuidado.'],
    media: { id: 's05-cnt-2-cerebro', kind: 'image', title: 'Cuatro formas de tiempo libre saludable', aspect: '16:9', alt: 'Estudiantes practican un deporte, un juego de mesa, una actividad social y una actividad recreativa artistica.', brief: 'Ilustracion escolar 1600x900 dividida en cuatro escenas: deporte adaptado, juego cooperativo, conversacion social respetuosa y recreacion artistica. Mostrar diversidad corporal y participacion voluntaria. Incluir el rotulo "actividades seguras y libres del consumo de drogas". Sin marcas, sustancias ni mensajes que culpabilicen. Alto contraste y texto legible.' },
    steps: [
      S.explain({ fase: 'explorar', areas: ['cnt'], cnb: ['cnt:4.2.1'], prompt: 'Ilustra como deporte, juego, actividad social y recreacion pueden apoyar practicas saludables libres del consumo de drogas.' }, { icon: 'HeartPulse', body: 'Un plan saludable puede combinar **deporte, juego, actividad social y recreacion**, con seguridad, inclusion, eleccion voluntaria y **sin consumo de drogas**.' }),
      S.explain({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:4.2.1'], title: 'Cuatro opciones protectoras', prompt: 'Usa e ilustra deporte, juego, actividad social y recreacion en un plan libre de drogas.' }, { icon: 'CalendarRange', body: '**Deporte:** movimiento con reglas adaptadas. **Juego:** reto cooperativo. **Actividad social:** convivencia con apoyo. **Recreacion:** arte, lectura, musica o paseo seguro. Las cuatro se realizan sin consumo de drogas.' }),
      S.ejemplo({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:4.2.1'], title: 'Modelo: una tarde con opciones', prompt: 'Observa como ilustrar las cuatro practicas saludables en un plan libre de drogas.' }, { icon: 'PanelsTopLeft', problem: 'Un centro juvenil prepara cuatro estaciones.', steps: [{ text: 'Deporte: pases suaves con pelota.' }, { text: 'Juego: rompecabezas cooperativo.' }, { text: 'Actividad social: circulo de conversacion.' }, { text: 'Recreacion: dibujo o lectura.' }, { text: 'Acuerdo: participacion voluntaria, segura y sin consumo de drogas.' }], answer: 'El plan ofrece cuatro maneras concretas de cuidar el tiempo libre.' }),
      S.match({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:4.2.1'], prompt: 'Relaciona cada practica saludable libre de drogas con deporte, juego, actividad social o recreacion.', hint: 'Pregunta si predomina ejercicio, reglas ludicas, convivencia o disfrute creativo.', explain: 'Las categorias pueden relacionarse, pero el ejemplo destaca una funcion principal.' }, { pairs: [{ id: 'a', left: 'Caminata con ritmo adaptable', right: 'Deporte' }, { id: 'b', left: 'Memoria cooperativa', right: 'Juego' }, { id: 'c', left: 'Conversatorio entre amistades', right: 'Actividad social' }, { id: 'd', left: 'Taller breve de dibujo', right: 'Recreacion' }] }),
      S.choice({ fase: 'aplicar', areas: ['cnt'], cnb: ['cnt:4.2.1'], prompt: '¿Que plan ilustra deporte, juego, actividad social y recreacion como practicas saludables libres del consumo de drogas?' }, { options: [{ id: 'a', text: 'Caminata adaptada, loteria cooperativa, conversacion y dibujo, con acuerdo de seguridad y sin consumo' }, { id: 'b', text: 'Una sola competencia obligatoria sin descansos' }, { id: 'c', text: 'Una reunion que ofrece sustancias para integrarse' }], correct: ['a'] }),
      S.write({ fase: 'aplicar', areas: ['cnt'], cnb: ['cnt:4.2.1'], prompt: 'Ilustra con palabras un plan breve que use deporte, juego, actividad social y recreacion como practicas saludables libres de drogas.' }, { minWords: 22, placeholder: 'Deporte... Juego... Actividad social... Recreacion...', model: 'Deporte: caminata. Juego: domino. Actividad social: charla. Recreacion: dibujo. Todo es voluntario, seguro y sin consumo.', rubric: ['Inclui las cuatro practicas', 'Indique seguridad e inclusion', 'Declare que es libre del consumo de drogas'] }),
      S.choice({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:4.2.1'], prompt: 'Un plan combina deporte, juego, actividad social y recreacion. ¿Que condicion lo presenta como practica saludable libre de drogas?' }, { options: [{ id: 'a', text: 'Es seguro, inclusivo, voluntario y no incluye consumo' }, { id: 'b', text: 'Obliga a todas las personas a competir' }, { id: 'c', text: 'Usa una sustancia para aumentar energia' }], correct: ['a'] }),
      S.tf({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:4.2.1'], prompt: 'Evalua el uso de deporte, juego, actividad social y recreacion como practicas saludables sin consumo de drogas.' }, { statements: [{ text: 'Las cuatro practicas pueden adaptarse a intereses y capacidades.', answer: true }, { text: 'Una actividad debe incluir consumo para ser social.', answer: false }, { text: 'Ofrecer opciones seguras puede apoyar decisiones de cuidado.', answer: true }] }),
      S.reflect({ fase: 'reflexionar', areas: ['cnt'], cnb: ['cnt:4.2.1'], prompt: 'Revisa la variedad y seguridad de tu plan.' }, { statements: ['Inclui movimiento y convivencia', 'Respete la participacion voluntaria', 'Mantuve el plan libre de drogas'], commitments: ['Propondre una opcion inclusiva para el recreo'] }),
    ],
  }),

  lesson({
    id: 's05-cnt-3', title: 'Nutricion desde los primeros meses', icon: 'Baby', minutes: 15,
    gancho: '¿Que tienen en comun los nutrientes de los alimentos y la leche materna durante el crecimiento?',
    objetivos: ['Explicar la nutricion desde los primeros meses mediante nutrientes y beneficios de la lactancia'],
    resumen: ['Los alimentos aportan carbohidratos, proteinas, grasas, vitaminas y minerales con funciones distintas.', 'La leche materna aporta nutricion, componentes inmunitarios y apoyo al crecimiento y desarrollo del bebe.', 'La lactancia tambien puede favorecer el vinculo; cada familia merece informacion respetuosa y orientacion sanitaria individual cuando la necesite.'],
    media: { id: 's05-cnt-3-tiempo-libre', kind: 'diagram', title: 'Nutricion desde el inicio', aspect: '16:9', alt: 'Diagrama respetuoso con una tarjeta sobre lactancia y cinco tarjetas de nutrientes presentes en alimentos.', brief: 'Diagrama educativo 1600x900. A la izquierda, una escena respetuosa de lactancia o extraccion de leche sin mostrar anatomia explicita; rotulos: nutricion, componentes inmunitarios, crecimiento/desarrollo y vinculo. A la derecha, alimentos reconocibles vinculados con carbohidratos, proteinas, grasas, vitaminas y minerales. Incluir nota: "Informacion general; las situaciones individuales requieren orientacion sanitaria". Alto contraste, texto grande y sin juicios sobre familias.' },
    steps: [
      S.explain({ fase: 'explorar', areas: ['cnt'], cnb: ['cnt:5.1.1', 'cnt:5.2.1'], prompt: 'Relaciona la clasificacion de nutrientes en alimentos con los beneficios humanos de la lactancia.' }, { icon: 'Sprout', body: 'Clasificamos nutrientes de alimentos en **carbohidratos, proteinas, grasas, vitaminas y minerales**; la **lactancia** aporta nutricion y componentes inmunitarios, y favorece crecimiento, desarrollo y vinculo.' }),
      S.explain({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:5.1.1', 'cnt:5.2.1'], title: 'Nutrientes y lactancia', prompt: 'Clasifica nutrientes nombrados y describe beneficios suministrados de la leche materna.' }, { icon: 'TableProperties', body: '**Carbohidratos** aportan energia; **proteinas**, materiales para tejidos; **grasas**, energia y componentes celulares; **vitaminas y minerales**, apoyo a procesos corporales. La **leche materna** contiene nutrientes y componentes inmunitarios; apoya crecimiento y desarrollo y puede favorecer el vinculo. Son beneficios generales, no una promesa sobre cada caso.' }),
      S.ejemplo({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:5.1.1', 'cnt:5.2.1'], title: 'Modelo: dos etapas de nutricion', prompt: 'Observa como clasificar nutrientes nombrados y explicar beneficios de la lactancia.' }, { icon: 'GitCompare', problem: 'Ficha A: tortilla, frijol y aguacate. Ficha B: leche materna durante los primeros meses.', steps: [{ text: 'Tortilla: principalmente carbohidratos; frijol: proteinas, carbohidratos, vitaminas y minerales; aguacate: grasas y vitaminas.' }, { text: 'La leche materna aporta nutricion y componentes inmunitarios.' }, { text: 'Tambien apoya crecimiento y desarrollo y puede favorecer el vinculo.' }], answer: 'La explicacion clasifica nutrientes y describe beneficios sin convertirlos en garantias individuales.' }),
      S.match({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:5.1.1', 'cnt:5.2.1'], prompt: 'Guia: clasifica nutrientes en alimentos y relaciona beneficios de la lactancia con nutricion, defensas, desarrollo y vinculo.', hint: 'Usa la funcion nombrada en cada tarjeta.', explain: 'Los alimentos pueden aportar varios nutrientes; la actividad destaca uno. Los beneficios de la lactancia son generales y respetan situaciones individuales.' }, { pairs: [{ id: 'a', left: 'Arroz: energia', right: 'Carbohidratos' }, { id: 'b', left: 'Huevo: formacion de tejidos', right: 'Proteinas' }, { id: 'c', left: 'Semillas: energia concentrada', right: 'Grasas' }, { id: 'd', left: 'Leche materna', right: 'Nutricion, componentes inmunitarios, desarrollo y vinculo' }] }),
      S.choice({ fase: 'aplicar', areas: ['cnt'], cnb: ['cnt:5.1.1', 'cnt:5.2.1'], prompt: 'Caso nuevo: clasifica carbohidratos, proteinas, grasas, vitaminas y minerales en alimentos nombrados, y explica que la lactancia aporta nutricion, componentes inmunitarios, desarrollo y vinculo. ¿Que respuesta cumple ambas tareas?' }, { options: [{ id: 'a', text: 'Papa: carbohidratos; lenteja: proteinas y minerales; aceite: grasas; fruta: vitaminas. La leche materna nutre, aporta componentes inmunitarios, apoya desarrollo y puede favorecer el vinculo.' }, { id: 'b', text: 'Todos los alimentos contienen exactamente el mismo nutriente y la lactancia solo aporta agua.' }, { id: 'c', text: 'La clasificacion depende del color y la lactancia garantiza que nunca habra enfermedad.' }], correct: ['a'] }),
      S.write({ fase: 'aplicar', areas: ['cnt'], cnb: ['cnt:5.1.1', 'cnt:5.2.1'], prompt: 'Clasifica en alimentos nombrados carbohidratos, proteinas, grasas, vitaminas y minerales; luego explica beneficios suministrados de la lactancia: nutricion, componentes inmunitarios, crecimiento o desarrollo y vinculo.' }, { minWords: 28, placeholder: 'Alimento y nutriente... Lactancia y beneficios...', model: 'Maiz: carbohidratos; frijol: proteinas y minerales; aguacate: grasas; fruta: vitaminas. La lactancia nutre, aporta componentes inmunitarios, apoya el desarrollo y puede favorecer el vinculo.', rubric: ['Clasifique nutrientes nombrados', 'Explique beneficios de la lactancia', 'Use lenguaje respetuoso y no absoluto'] }),
      S.choice({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:5.1.1', 'cnt:5.2.1'], prompt: '¿Que opcion clasifica carbohidratos, proteinas, grasas, vitaminas y minerales en alimentos y explica beneficios de la lactancia para nutricion, defensas, desarrollo y vinculo?' }, { options: [{ id: 'a', text: 'Cereal-carbohidrato, frijol-proteina/mineral, semilla-grasa y fruta-vitamina; la leche materna nutre, aporta componentes inmunitarios, apoya desarrollo y puede favorecer vinculo' }, { id: 'b', text: 'Todo alimento es solo vitamina; la lactancia no aporta nutrientes' }, { id: 'c', text: 'Los nutrientes se clasifican por tamano; la lactancia garantiza salud perfecta' }], correct: ['a'] }),
      S.tf({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:5.1.1', 'cnt:5.2.1'], prompt: 'Comprueba la clasificacion de carbohidratos, proteinas, grasas, vitaminas y minerales en alimentos y los beneficios de lactancia para nutricion, defensas, desarrollo y vinculo.' }, { statements: [{ text: 'Un alimento puede aportar mas de un nutriente.', answer: true }, { text: 'La leche materna aporta nutrientes y componentes inmunitarios.', answer: true }, { text: 'Los beneficios generales de la lactancia garantizan el mismo resultado en toda situacion individual.', answer: false }] }),
      S.reflect({ fase: 'reflexionar', areas: ['cnt'], cnb: ['cnt:5.1.1', 'cnt:5.2.1'], prompt: 'Revisa tu explicacion de nutricion desde los primeros meses.' }, { statements: ['Clasifique nutrientes por funcion', 'Describi beneficios sin prometer resultados', 'Use lenguaje respetuoso con las familias'], commitments: ['Consultare a personal de salud ante una situacion individual'] }),
    ],
  }),
];
