/** Ciencias Naturales y Tecnología · Unidad 1 · Semana 6. */
import { lesson, S } from '../../../../dsl';

export default [
  lesson({
    id: 's06-cnt-1', title: 'Hábitos nutricionales que podemos practicar', icon: 'Salad', minutes: 14,
    gancho: '¿Cómo se evalúa una refacción sin llamar “buena” o “mala” a la comida ni a quien la elige?',
    objetivos: ['Evaluar hábitos nutricionales cotidianos con criterios adaptables'],
    resumen: ['Un hábito nutricional es una práctica repetida relacionada con alimentos y bebidas.', 'Variedad, agua segura, higiene, regularidad y restricciones personales son criterios para comparar prácticas.', 'Una decisión posible depende de cultura, disponibilidad, presupuesto y orientación profesional cuando corresponda.'],
    media: {
      id: 's06-cnt-1-habitos', kind: 'diagram', title: 'Cinco criterios para una refacción', aspect: '16:9',
      alt: 'Mesa con tortilla, frijol, banano y agua junto a cinco rótulos: variedad, agua segura, higiene, regularidad y restricciones.',
      brief: 'Diagrama horizontal 1600×900. Mostrar alimentos guatemaltecos reconocibles y cinco criterios con iconos descriptivos. Incluir la nota “Las opciones dependen de disponibilidad, cultura, presupuesto y necesidades”. Texto grande, contraste alto, sin marcas ni juicios corporales.',
    },
    steps: [
      S.explain({ fase: 'explorar', areas: ['cnt'], cnb: ['cnt:5.3.1'], title: 'Un hábito es una práctica repetida', prompt: 'Los hábitos nutricionales incluyen qué, cuándo y cómo comemos o bebemos.' }, { icon: 'CalendarDays', body: 'No se juzga a una persona por una comida. Se comparan **prácticas** con criterios y se elige una mejora posible según los recursos disponibles.' }),
      S.explain({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:5.3.1'], title: 'Criterios adaptables', prompt: 'Evalúa hábitos nutricionales con variedad, agua segura, higiene, regularidad y atención a restricciones.' }, { icon: 'ListChecks', body: '**Variedad** reúne opciones distintas; **agua segura** evita exposiciones; **higiene** reduce contaminación; **regularidad** ayuda a organizar; y las **restricciones** requieren consulta. La decisión cambia según cultura, temporada, disponibilidad y presupuesto.' }),
      S.ejemplo({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:5.3.1'], title: 'Modelo: comparar una práctica', prompt: 'Observa cómo evaluar un hábito nutricional sin prometer resultados de salud.' }, { icon: 'ClipboardCheck', problem: 'Escenario: Ana toma agua segura y lleva tortilla con frijol; hoy hay banano disponible.', steps: [{ text: 'Variedad: puede agregar el banano si lo desea y está disponible.' }, { text: 'Higiene: manos y recipiente limpios.' }, { text: 'Restricciones: confirmar alergias o indicaciones personales.' }, { text: 'Decisión posible: mantener el agua y agregar la fruta, sin atribuirle un resultado médico a una sola comida.' }], answer: 'La mejora usa criterios y respeta disponibilidad y necesidades.' }),
      S.sort({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:5.3.1'], prompt: 'Clasifica prácticas del escenario.', hint: 'Busca agua segura, higiene, variedad y respeto a restricciones.', explain: 'Una práctica puede mejorarse sin etiquetar a la persona ni prohibir alimentos.' }, { buckets: [{ id: 'apoya', label: 'Apoya el hábito', icon: 'BadgeCheck', color: 'var(--c-ok)' }, { id: 'revisar', label: 'Conviene revisar', icon: 'Search', color: 'var(--c-maiz-strong)' }], items: [{ id: 'a', text: 'Lavarse las manos antes de comer', bucket: 'apoya' }, { id: 'b', text: 'Suponer que una opción es segura para todas las alergias', bucket: 'revisar' }, { id: 'c', text: 'Llevar agua de una fuente confirmada como segura', bucket: 'apoya' }, { id: 'd', text: 'Omitir siempre la comida por falta de planificación', bucket: 'revisar' }] }),
      S.match({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:5.3.1'], prompt: 'Relaciona cada criterio con una decisión posible.', hint: 'La decisión debe ser realizable y no universal.', explain: 'Los criterios orientan; la disponibilidad y las necesidades personales modifican la elección.' }, { pairs: [{ id: 'a', left: 'Variedad', right: 'Combinar opciones disponibles de más de un grupo' }, { id: 'b', left: 'Higiene', right: 'Usar manos y recipiente limpios' }, { id: 'c', left: 'Restricción', right: 'Consultar y elegir una alternativa segura' }, { id: 'd', left: 'Agua segura', right: 'Confirmar la fuente antes de beber' }] }),
      S.choice({ fase: 'aplicar', areas: ['cnt'], cnb: ['cnt:5.3.1'], prompt: 'Caso nuevo: Luis repite la misma refacción, lleva agua segura y mantiene higiene; hay otra opción local disponible. ¿Qué decisión evalúa sus hábitos nutricionales con variedad, agua segura, higiene y disponibilidad?' }, { options: [{ id: 'a', text: 'Conservar el agua y la higiene, y considerar alternar la opción disponible' }, { id: 'b', text: 'Decir que su comida es mala y prohibirla' }, { id: 'c', text: 'Afirmar que una sola opción garantiza todas sus necesidades' }], correct: ['a'] }),
      S.write({ fase: 'aplicar', areas: ['cnt'], cnb: ['cnt:5.3.1'], prompt: 'Evalúa un hábito nutricional del caso suministrado y escribe una mejora posible usando dos criterios entre variedad, agua segura, higiene, regularidad y restricciones.' }, { minWords: 18, placeholder: 'El hábito... Una mejora posible...', model: 'El hábito conserva agua segura e higiene. Una mejora posible es alternar opciones disponibles y confirmar restricciones antes de cambiar.', rubric: ['Nombré el hábito', 'Usé dos criterios', 'Propuse una decisión adaptable'] }),
      S.choice({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:5.3.1'], prompt: '¿Qué evaluación de hábitos nutricionales usa variedad, agua segura, higiene y una decisión adaptable?' }, { options: [{ id: 'a', text: 'Comparar esos criterios y ajustar la práctica según disponibilidad y restricciones' }, { id: 'b', text: 'Clasificar a la persona por una sola comida' }, { id: 'c', text: 'Eliminar cualquier alimento que no sea perfecto' }], correct: ['a'] }),
      S.tf({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:5.3.1'], prompt: 'Evalúa decisiones sobre hábitos nutricionales con variedad, agua segura, higiene y contexto.' }, { statements: [{ text: 'Una mejora posible puede conservar prácticas útiles y cambiar solo un aspecto realizable.', answer: true }, { text: 'La misma opción debe imponerse aunque cambien cultura, disponibilidad o restricciones.', answer: false }] }),
      S.reflect({ fase: 'reflexionar', areas: ['cnt'], cnb: ['cnt:5.3.1'], prompt: 'Revisa cómo tomaste la decisión.' }, { statements: ['Comparé prácticas con criterios', 'Evité juzgar alimentos o personas', 'Reconocí límites de disponibilidad'], commitments: ['Propondré cambios posibles y respetuosos'] }),
    ],
  }),

  lesson({
    id: 's06-cnt-2', title: 'Ambiente sano y ambiente contaminado', icon: 'ShieldCheck', minutes: 13,
    gancho: 'Un lugar puede verse ordenado y aun tener agua, aire o suelo contaminados. ¿Qué evidencia permite distinguirlo?',
    objetivos: ['Diferenciar ambientes sanos y contaminados mediante evidencia observable'],
    resumen: ['Un ambiente sano reduce exposiciones y maneja de forma segura agua, aire, suelo y residuos.', 'Un ambiente contaminado contiene agentes o residuos que pueden dañar seres vivos.', 'Una señal aislada orienta una revisión, pero la clasificación necesita evidencia suficiente.'],
    media: { id: 's06-cnt-2-ambientes', kind: 'diagram', title: 'Dos ambientes para comparar', aspect: '16:9', alt: 'Dos patios ficticios: uno con residuos contenidos, aire ventilado y agua protegida; otro con humo, aguas residuales y basura dispersa.', brief: 'Diagrama comparativo 1600×900 de dos escenarios ficticios, rotulados A y B. Mostrar fuentes concretas de evidencia en agua, aire, suelo y residuos. Evitar indicar la respuesta solo con color; usar rótulos legibles, patrones y alto contraste.' },
    steps: [
      S.explain({ fase: 'explorar', areas: ['cnt'], cnb: ['cnt:6.1.1'], title: 'Distinguir requiere evidencia', prompt: 'Un ambiente sano y uno contaminado se diferencian por condiciones del agua, aire, suelo y manejo de residuos.' }, { icon: 'Search', body: 'Ambiente **sano**: reduce exposiciones y protege recursos. Ambiente **contaminado**: presenta humo, aguas residuales, sustancias o residuos que pueden afectar seres vivos.' }),
      S.explain({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:6.1.1'], title: 'Cuatro campos de observación', prompt: 'Compara agua, aire, suelo y residuos antes de clasificar.' }, { icon: 'TableProperties', body: 'Pregunta: ¿hay una fuente de contaminación?, ¿qué recurso alcanza?, ¿qué evidencia se observa?, ¿qué dato faltaría confirmar? Un olor o color por sí solo no identifica siempre la sustancia.' }),
      S.ejemplo({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:6.1.1'], title: 'Modelo: evidencia y clasificación', prompt: 'Diferencia dos ambientes ficticios.' }, { icon: 'GitCompare', problem: 'Patio A: agua cubierta y residuos en contenedores. Patio B: humo constante y agua residual descargada al suelo.', steps: [{ text: 'A muestra prácticas que reducen exposición.' }, { text: 'B presenta fuentes observables de contaminación del aire y suelo.' }, { text: 'No afirmamos qué sustancia contiene el agua sin analizarla.' }], answer: 'A reúne señales de ambiente sano; B, evidencia de ambiente contaminado.' }),
      S.sort({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:6.1.1'], prompt: 'Clasifica la evidencia suministrada.', hint: 'Ubica la condición del recurso, no la apariencia general.', explain: 'Manejo seguro apoya un ambiente sano; descargas, humo y residuos dispersos evidencian contaminación.' }, { buckets: [{ id: 'sano', label: 'Ambiente sano', icon: 'ShieldCheck', color: 'var(--c-ok)' }, { id: 'cont', label: 'Ambiente contaminado', icon: 'CloudFog', color: 'var(--c-maiz-strong)' }], items: [{ id: 'a', text: 'Agua almacenada en recipiente limpio y cubierto', bucket: 'sano' }, { id: 'b', text: 'Humo de quema entra al aula', bucket: 'cont' }, { id: 'c', text: 'Residuos separados y contenidos', bucket: 'sano' }, { id: 'd', text: 'Aguas residuales corren sobre el suelo', bucket: 'cont' }] }),
      S.match({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:6.1.1'], prompt: 'Relaciona evidencia y recurso afectado.', hint: 'Pregunta dónde se observa la exposición.', explain: 'Nombrar el recurso evita clasificaciones vagas.' }, { pairs: [{ id: 'a', left: 'Quema con humo persistente', right: 'Aire contaminado' }, { id: 'b', left: 'Descarga de aguas residuales', right: 'Agua o suelo contaminado' }, { id: 'c', left: 'Residuos cerrados y retiro organizado', right: 'Condición que apoya un ambiente sano' }] }),
      S.choice({ fase: 'aplicar', areas: ['cnt'], cnb: ['cnt:6.1.1'], prompt: 'Caso nuevo: un patio tiene residuos contenidos, pero recibe humo. ¿Cómo diferencias ambiente sano y contaminado con evidencia de aire y residuos?' }, { options: [{ id: 'a', text: 'El manejo de residuos es favorable, pero el humo evidencia contaminación del aire' }, { id: 'b', text: 'Es totalmente sano porque está ordenado' }, { id: 'c', text: 'Es contaminado solo porque el suelo es oscuro' }], correct: ['a'] }),
      S.write({ fase: 'aplicar', areas: ['cnt'], cnb: ['cnt:6.1.1'], prompt: 'Diferencia los ambientes C y D usando una evidencia de agua, aire, suelo o residuos y un límite de lo que no puede concluirse.' }, { minWords: 18, placeholder: 'C muestra... D muestra... No puede concluirse...', model: 'C reduce exposición al contener residuos. D muestra contaminación por humo. Sin análisis no puede nombrarse una sustancia específica.', rubric: ['Diferencié ambos ambientes', 'Usé evidencia concreta', 'Reconocí un límite'] }),
      S.choice({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:6.1.1'], prompt: '¿Qué comparación distingue un ambiente sano de uno contaminado mediante evidencia de agua, aire, suelo o residuos?' }, { options: [{ id: 'a', text: 'Agua protegida y residuos contenidos reducen exposición; humo y descargas muestran contaminación' }, { id: 'b', text: 'Un lugar bonito siempre es sano' }, { id: 'c', text: 'Todo olor demuestra la misma sustancia' }], correct: ['a'] }),
      S.tf({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:6.1.1'], prompt: 'Diferencia ambiente sano y contaminado con evidencia de agua, aire, suelo o residuos.' }, { statements: [{ text: 'Una descarga de agua residual al suelo es evidencia de contaminación.', answer: true }, { text: 'Un rótulo limpio demuestra por sí solo que todo el ambiente es sano.', answer: false }] }),
      S.reflect({ fase: 'reflexionar', areas: ['cnt'], cnb: ['cnt:6.1.1'], prompt: 'Revisa tu clasificación.' }, { statements: ['Usé evidencia observable', 'Diferencié recurso y apariencia', 'Evité afirmar una sustancia sin análisis'], commitments: ['Pediré verificación cuando la evidencia no alcance'] }),
    ],
  }),

  lesson({
    id: 's06-cnt-3', title: 'Cobertura del suelo, vivienda y agua', icon: 'Trees', minutes: 15,
    gancho: 'Si una zona urbana crece sobre un bosque, ¿qué podemos inferir sobre el agua y qué todavía debemos comprobar?',
    objetivos: ['Explicar con evidencia cómo el uso del suelo relaciona expansión urbana, cobertura vegetal y protección del agua'],
    resumen: ['El crecimiento poblacional puede ampliar la frontera urbana y aumentar presión para vivienda.', 'Eliminar bosque o ubicar vivienda en suelos inadecuados puede cambiar erosión, escorrentía e infiltración según condiciones locales.', 'Reforestar o restaurar vegetación puede contribuir a proteger recursos hídricos, pero no garantiza por sí solo cantidad o calidad de agua.'],
    media: { id: 's06-cnt-3-suelo-agua', kind: 'diagram', title: 'Escenario de cobertura y agua', aspect: '16:9', alt: 'Mapa ficticio con bosque, nueva frontera urbana, viviendas en una ladera y un cauce, acompañado por flechas de escorrentía e infiltración.', brief: 'Mapa-diagrama 1600×900 de un escenario ficticio. Dos fechas: cobertura boscosa disminuye y área construida aumenta. Mostrar viviendas en pendiente, cauce, suelo cubierto y expuesto; flechas como posibles procesos, no garantías. Nota: “Se requieren datos locales de suelo, pendiente, lluvia y agua”. Alto contraste.' },
    steps: [
      S.explain({ fase: 'explorar', areas: ['cnt'], cnb: ['cnt:6.2.1', 'cnt:6.3.1'], title: 'Una relación con varias condiciones', prompt: 'El crecimiento poblacional puede ampliar la frontera urbana mediante eliminación de bosque y uso inadecuado del suelo para vivienda; reforestar puede contribuir a proteger el agua.' }, { icon: 'GitBranch', body: 'La relación depende de pendiente, suelo, lluvia, especies, ubicación y manejo. Reforestar **no garantiza** que un nacimiento no se seque ni que el agua sea potable.' }),
      S.explain({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:6.2.1', 'cnt:6.3.1'], title: 'Cadena de evidencia', prompt: 'Relaciona crecimiento poblacional, frontera urbana, bosque, vivienda, reforestación y recurso hídrico sin afirmar una causa única.' }, { icon: 'Workflow', body: 'Más demanda de vivienda → posible expansión urbana → remoción de cobertura o construcción en suelo inadecuado → posibles cambios en erosión, escorrentía e infiltración. Reforestar vegetación apropiada puede contribuir a proteger el agua; hacen falta mediciones locales.' }),
      S.ejemplo({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:6.2.1', 'cnt:6.3.1'], title: 'Modelo con datos simulados', prompt: 'Interpreta el escenario sin convertir una coincidencia en prueba causal.' }, { icon: 'Map', problem: 'Aumenta el área construida, disminuye el bosque y aparecen viviendas en una pendiente cercana al cauce.', steps: [{ text: 'Observación: cambió la cobertura y avanzó la frontera urbana.' }, { text: 'Inferencia: la eliminación de bosque y el uso inadecuado para vivienda pueden aumentar erosión o escorrentía.' }, { text: 'Acción: reforestar sitios adecuados y medir suelo, lluvia y agua.' }, { text: 'Límite: plantar árboles no garantiza caudal ni calidad.' }], answer: 'La explicación conecta uso del suelo y protección hídrica con lenguaje condicional.' }),
      S.order({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:6.2.1', 'cnt:6.3.1'], prompt: 'Ordena una cadena posible del escenario.', hint: 'Empieza con demanda y termina con verificación.', explain: 'Es una relación posible, no una secuencia inevitable.' }, { items: [{ id: 'a', text: 'Crece la demanda de vivienda' }, { id: 'b', text: 'Se amplía la frontera urbana y se elimina bosque' }, { id: 'c', text: 'Cambian erosión o infiltración según el sitio' }, { id: 'd', text: 'Se reforesta con vegetación apropiada y se verifican suelo y agua' }] }),
      S.sort({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:6.2.1', 'cnt:6.3.1'], prompt: 'Clasifica afirmaciones del caso.', hint: 'Una inferencia prudente usa “puede”.', explain: 'La reforestación puede contribuir a proteger agua, pero requiere ubicación, especies, mantenimiento y verificación.' }, { buckets: [{ id: 'e', label: 'Evidencia o inferencia prudente', icon: 'Search', color: 'var(--c-ok)' }, { id: 'g', label: 'Garantía no sustentada', icon: 'TriangleAlert', color: 'var(--c-maiz-strong)' }], items: [{ id: 'a', text: 'El bosque disminuyó mientras creció el área construida', bucket: 'e' }, { id: 'b', text: 'La tala prueba la causa de todo cambio del agua', bucket: 'g' }, { id: 'c', text: 'Reforestar puede reducir suelo expuesto según pendiente y manejo', bucket: 'e' }, { id: 'd', text: 'Sembrar árboles garantiza que un nacimiento nunca se secará', bucket: 'g' }] }),
      S.choice({ fase: 'aplicar', areas: ['cnt'], cnb: ['cnt:6.2.1', 'cnt:6.3.1'], prompt: 'Caso nuevo: crece la población, avanza la frontera urbana, se elimina bosque y aparecen viviendas en suelo inadecuado. Se propone reforestación para proteger el recurso hídrico. ¿Qué explicación relaciona todo con evidencia?' }, { options: [{ id: 'a', text: 'La expansión puede cambiar erosión e infiltración; reforestar puede contribuir, pero deben verificarse suelo, lluvia y agua' }, { id: 'b', text: 'Las viviendas prueban por sí solas la causa de cualquier cambio' }, { id: 'c', text: 'Plantar cualquier árbol garantiza agua limpia y abundante' }], correct: ['a'] }),
      S.write({ fase: 'aplicar', areas: ['cnt'], cnb: ['cnt:6.2.1', 'cnt:6.3.1'], prompt: 'Explica el escenario relacionando crecimiento poblacional, frontera urbana, eliminación de bosque, uso inadecuado para vivienda, reforestación y protección del recurso hídrico. Incluye un dato por verificar.' }, { minWords: 28, placeholder: 'La expansión puede... Reforestar puede... Habría que verificar...', model: 'La expansión puede remover bosque y ubicar vivienda en suelos inadecuados. Reforestar puede proteger el agua, pero hay que verificar pendiente, suelo y lluvia.', rubric: ['Relacioné población, frontera, bosque y vivienda', 'Califiqué la reforestación', 'Propuse verificación'] }),
      S.choice({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:6.2.1', 'cnt:6.3.1'], prompt: '¿Qué relación conecta crecimiento poblacional, frontera urbana, eliminación de bosque, vivienda, reforestación y recurso hídrico?' }, { options: [{ id: 'a', text: 'La presión de vivienda puede remover bosque; reforestar puede apoyar el agua según suelo, lluvia, especies y manejo' }, { id: 'b', text: 'Toda vivienda causa por sí sola pérdida de agua' }, { id: 'c', text: 'La reforestación garantiza caudal permanente' }], correct: ['a'] }),
      S.tf({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:6.2.1', 'cnt:6.3.1'], prompt: 'Evalúa crecimiento poblacional, frontera urbana, bosque, vivienda, reforestación y protección del agua.' }, { statements: [{ text: 'Eliminar bosque para vivienda puede influir en erosión según condiciones locales.', answer: true }, { text: 'Reforestar puede contribuir a proteger agua, pero no garantiza cantidad o calidad.', answer: true }, { text: 'Observar tala y menor caudal prueba una causa única.', answer: false }] }),
      S.reflect({ fase: 'reflexionar', areas: ['cnt'], cnb: ['cnt:6.2.1', 'cnt:6.3.1'], prompt: 'Revisa los límites de tu explicación.' }, { statements: ['Separé observación e inferencia', 'Usé lenguaje condicional', 'Pedí datos locales'], commitments: ['No presentaré reforestación como garantía'] }),
    ],
  }),
];
