/** Ciencias Naturales y Tecnología · Unidad 1 · Semana 7. */
import { lesson, S } from '../../../../dsl';

export default [
  lesson({
    id: 's07-cnt-1', title: 'Morbilidad, ambiente y explicaciones posibles', icon: 'Stethoscope', minutes: 14,
    gancho: 'Si dos datos cambian al mismo tiempo, ¿eso basta para afirmar que uno causó el otro?',
    objetivos: ['Interpretar un índice de morbilidad sin confundir asociación con causa'],
    resumen: [
      'La morbilidad cuenta casos de enfermedad en una población y un periodo; no cuenta fallecimientos.',
      'Índice por cada 1,000 habitantes = casos ÷ habitantes × 1,000.',
      'El humo doméstico puede aumentar el riesgo de enfermedad respiratoria, pero una asociación no prueba por sí sola la causa de cada caso.',
      'La influenza o gripe es una infección viral; al interpretar un patrón se conservan explicaciones alternativas.',
    ],
    media: {
      id: 's07-cnt-1-dos-aldeas', kind: 'image', title: 'Dos escenarios para formular hipótesis', aspect: '16:9',
      alt: 'Dos escenas hipotéticas con distinta exposición al humo, ventilación y registros respiratorios, sin marcar una respuesta causal.',
      brief: 'Composición horizontal 1600×900, rotulada CASO HIPOTÉTICO. Dos viviendas guatemaltecas comparables: una cocina con humo acumulado y poca ventilación; otra con salida de humo y ventana abierta. Incluir fichas separadas de casos respiratorios simulados, temperatura, ventilación y convivencia. La pieza visual debe apoyar preguntas, no conclusiones causales. Rótulos grandes, contraste alto y texto legible; sin marcas comerciales.',
    },
    steps: [
      S.explain({ fase: 'explorar', areas: ['cnt'], cnb: ['cnt:6.1.1', 'cnt:6.5.1'], title: 'Datos, riesgo y cautela', prompt: 'Una ilustración ayuda a comparar condiciones de un ambiente sano o contaminado y formular una hipótesis. Para explicar casos de enfermedad hacen falta registros y deben considerarse otras explicaciones.' }, { icon: 'Search', body: 'Trabajaremos con un **caso simulado**. La exposición al humo puede aumentar el riesgo respiratorio; no permite diagnosticar ni probar la causa de cada caso.' }),
      S.choice({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:6.1.1', 'cnt:6.5.1'], prompt: 'Una casa con más humo registra más consultas respiratorias. ¿Cuál es la conclusión prudente?', explain: 'Los datos apoyan una asociación entre una condición contaminante y el riesgo. No descartan virus, ventilación, hacinamiento, edad o época fría.' }, { options: [{ id: 'a', text: 'El humo puede aumentar el riesgo; hacen falta más datos y explicaciones alternativas' }, { id: 'b', text: 'El humo explica necesariamente todos los casos', feedback: 'Una escena y un conteo no atribuyen la causa individual.' }, { id: 'c', text: 'El ambiente nunca se relaciona con la salud', feedback: 'La exposición puede influir en el riesgo, aunque no sea la única explicación.' }], correct: ['a'] }),
      S.explain({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:6.5.1'], title: 'Qué mide la morbilidad', prompt: 'Distingue el conteo, el índice y la explicación causal.' }, { icon: 'ClipboardList', body: 'El índice permite comparar poblaciones de distinto tamaño.', reveal: [{ icon: 'Stethoscope', front: 'Morbilidad', back: 'Número de casos registrados en una población durante un periodo.' }, { icon: 'Calculator', front: 'Índice', back: 'Casos ÷ habitantes × 1,000.' }, { icon: 'HeartPulse', front: 'No es mortalidad', back: 'La mortalidad cuenta fallecimientos.' }, { icon: 'ShieldAlert', front: 'No prueba causa', back: 'Un patrón apoya preguntas e hipótesis; se contrastan exposiciones y explicaciones alternativas.' }] }),
      S.ejemplo({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:6.5.1'], title: 'Ejemplo con datos simulados', prompt: 'Calcula e interpreta sin exagerar la evidencia.' }, { icon: 'Calculator', problem: 'En una población simulada de 2,000 habitantes hubo 160 consultas respiratorias en un año.', steps: [{ text: '160 ÷ 2,000 = 0.08.' }, { text: '0.08 × 1,000 = 80 casos por cada 1,000 habitantes.' }, { text: 'El registro describe frecuencia, no demuestra qué causó cada consulta.', why: 'También pueden influir virus, ventilación, hacinamiento, edad y temporada.' }], answer: 'Índice: **80 por cada 1,000 habitantes**.', tip: 'Separa siempre dato, asociación e inferencia.' }),
      S.number({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:6.5.1'], prompt: 'Caso simulado: 90 consultas en 3,000 habitantes. Calcula el índice por cada 1,000.', hint: 'Divide 90 entre 3,000 y multiplica por 1,000.', explain: 'El índice es 30 por cada 1,000; todavía no identifica una causa.' }, { answer: 30, unit: 'por cada 1,000' }),
      S.sort({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:6.5.1'], prompt: 'Clasifica cada afirmación.', hint: 'Dato = registro; hipótesis = explicación por comprobar.', explain: 'Una hipótesis debe poder contrastarse y conservar alternativas.' }, { buckets: [{ id: 'dato', label: 'Dato del escenario', icon: 'Table2', color: 'var(--area-cnt)' }, { id: 'hip', label: 'Hipótesis', icon: 'Search', color: 'var(--c-maiz-strong)' }], items: [{ id: 'd1', text: 'Hubo 90 consultas en el registro simulado', bucket: 'dato' }, { id: 'd2', text: 'La exposición al humo pudo aumentar el riesgo', bucket: 'hip' }, { id: 'd3', text: 'La influenza es causada por virus', bucket: 'dato' }, { id: 'd4', text: 'La poca ventilación pudo contribuir al patrón', bucket: 'hip' }] }),
      S.reading({ fase: 'aplicar', areas: ['cnt'], cnb: ['cnt:6.5.1'], prompt: 'Interpreta el registro hipotético sin convertir una asociación en prueba.' }, { genre: 'Registro simulado', heading: 'Sector A y sector B', passage: 'En un mes frío, el sector A registró 48 consultas respiratorias entre 800 habitantes y el sector B, 24 entre 800. En A se reportó más humo dentro de las viviendas. No se registraron pruebas virales, ventilación, edades ni número de personas por casa.', questions: [{ q: '¿Qué observación permite el registro?', options: [{ id: 'a', text: 'A tuvo más consultas y más exposición reportada al humo' }, { id: 'b', text: 'El humo causó las 48 consultas' }, { id: 'c', text: 'En B no circulaban virus' }], correct: 'a' }, { q: '¿Qué limita la inferencia?', options: [{ id: 'a', text: 'Faltan datos sobre virus, ventilación, edades y convivencia' }, { id: 'b', text: 'Los dos sectores tienen habitantes' }, { id: 'c', text: 'El registro usa números' }], correct: 'a' }] }),
      S.choice({ fase: 'aplicar', areas: ['cnt'], cnb: ['cnt:6.5.1'], prompt: '¿Qué afirmación escribirías en el informe?', explain: 'Describe la asociación y sus límites.' }, { options: [{ id: 'a', text: 'En el escenario, más humo coincidió con más consultas; podría influir, pero faltan datos para atribuir causalidad' }, { id: 'b', text: 'El humo produjo exactamente 24 casos adicionales', feedback: 'La diferencia no demuestra la causa.' }, { id: 'c', text: 'La gripe apareció porque la cocina tenía humo', feedback: 'La influenza es viral; el humo no crea el virus.' }], correct: ['a'] }),
      S.number({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:6.5.1'], prompt: 'Caso nuevo: 120 consultas entre 4,000 habitantes. ¿Cuál es el índice por cada 1,000?' }, { answer: 30, unit: 'por cada 1,000' }),
      S.choice({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:6.5.1'], prompt: 'Un gráfico muestra más influenza en viviendas con humo. ¿Qué interpretación es científicamente adecuada?' }, { options: [{ id: 'a', text: 'La influenza es viral; el patrón permite estudiar si el humo aumenta el riesgo o agrava síntomas, junto con otras explicaciones' }, { id: 'b', text: 'El humo fabrica el virus de la influenza' }, { id: 'c', text: 'El gráfico prueba la causa de cada caso' }], correct: ['a'] }),
    ],
  }),

  lesson({
    id: 's07-cnt-2', title: 'Crecimiento urbano y áreas verdes', icon: 'Trees', minutes: 13,
    gancho: '¿Qué cambia cuando un barrio crece sobre parques, suelos vegetados o laderas?',
    objetivos: ['Explicar con evidencia cómo el crecimiento urbano puede reducir áreas verdes'],
    resumen: ['El crecimiento urbano transforma usos del suelo y puede reducir áreas verdes si no se planifica.', 'La vegetación puede influir en sombra, erosión, escorrentía e infiltración según suelo, pendiente, lluvia, especies y manejo.', 'Un cambio observado no prueba por sí solo una causa única.'],
    media: {
      id: 's07-cnt-2-frontera', kind: 'animation', title: 'Cambios de uso del suelo', aspect: '16:9', duration: 45,
      alt: 'Animación de un valle hipotético donde el área construida aumenta y parte de la cobertura vegetal disminuye, con comparación planificada.',
      brief: 'Animación 2D de 45 s, 1600×900, rotulada MODELO HIPOTÉTICO. Vista aérea del mismo valle en 2000, 2010 y 2020: el área construida avanza sobre una parte de la vegetación. Comparar al final un crecimiento con parques y laderas protegidas. Flechas y leyenda legibles; narración en español, subtítulos y contraste alto. No afirmar que un solo cambio prueba inundaciones o pérdida de agua.',
    },
    steps: [
      S.explain({ fase: 'explorar', areas: ['cnt'], cnb: ['cnt:6.2.1', 'cnt:6.4.1'], title: 'Leer un cambio del territorio', prompt: 'Compara fechas, identifica cómo el crecimiento poblacional y la frontera urbana coinciden con superficies que aumentaron o disminuyeron, y separa observación de explicación.' }, { icon: 'Map', body: 'Un mapa temporal muestra **cambios**; para explicar sus causas hacen falta más fuentes.' }),
      S.choice({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:6.2.1', 'cnt:6.4.1'], prompt: 'En el modelo, aumentan las casas y disminuye una zona vegetada. ¿Qué sí se puede afirmar?', explain: 'La comparación documenta avance de la superficie urbana y cambio de uso del suelo, no una causa única.' }, { options: [{ id: 'a', text: 'Parte del área verde fue reemplazada por superficie construida' }, { id: 'b', text: 'Las casas causaron por sí solas una inundación', feedback: 'Eso requeriría datos de lluvia, drenaje, suelo y pendiente.' }, { id: 'c', text: 'Ya no existe vegetación en todo el municipio', feedback: 'El mapa representa solo el área mostrada.' }], correct: ['a'] }),
      S.explain({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:6.3.1', 'cnt:6.4.1'], title: 'Relaciones condicionadas', prompt: 'Los bosques y otras coberturas vegetales pueden cambiar procesos del suelo y del agua, pero el resultado depende del lugar.' }, { icon: 'Sprout', body: 'Según el **suelo, pendiente, lluvia, especies y manejo**, la cobertura vegetal puede favorecer infiltración y reducir erosión o escorrentía. No garantiza cantidad ni calidad de agua.', reveal: [{ icon: 'Sun', front: 'Sombra', back: 'Puede moderar la temperatura local.' }, { icon: 'Layers', front: 'Suelo', back: 'Raíces y cobertura pueden reducir erosión bajo ciertas condiciones.' }, { icon: 'CloudRain', front: 'Agua', back: 'La infiltración, escorrentía y caudal dependen también del suelo, lluvia, pendiente, extracción y estación.' }] }),
      S.ejemplo({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:6.4.1'], title: 'Ejemplo: observación e inferencia', prompt: 'Mira cómo se limita una conclusión.' }, { icon: 'Search', problem: 'Entre dos mapas simulados desaparecen 3 de 8 parches verdes.', steps: [{ text: '**Observación:** quedan 5 parches donde antes había 8.' }, { text: '**Inferencia posible:** parte del cambio coincide con nuevas construcciones.' }, { text: '**Límite:** los mapas solos no explican permisos, causas ni efectos sobre el agua.' }], answer: 'Se informa el cambio y se pide evidencia adicional.' }),
      S.sort({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:6.4.1'], prompt: 'Clasifica las frases.', hint: 'Observación: visible en el mapa. Inferencia: explicación que debe contrastarse.', explain: 'La distinción evita presentar suposiciones como hechos.' }, { buckets: [{ id: 'o', label: 'Observación', icon: 'Eye', color: 'var(--area-cnt)' }, { id: 'i', label: 'Inferencia', icon: 'Search', color: 'var(--c-maiz-strong)' }], items: [{ id: 'a', text: 'El parque pasa de 4 a 2 hectáreas en los datos simulados', bucket: 'o' }, { id: 'b', text: 'La expansión de calles pudo contribuir a la reducción', bucket: 'i' }, { id: 'c', text: 'Aparecen 12 nuevas manzanas construidas', bucket: 'o' }, { id: 'd', text: 'La menor vegetación pudo modificar la escorrentía local', bucket: 'i' }] }),
      S.match({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:6.4.1'], prompt: 'Relaciona cada pregunta con el dato que ayudaría a responderla.', hint: 'Busca la medida directamente relacionada.', explain: 'Combinar mapas, lluvia, suelo y drenaje permite evaluar explicaciones.' }, { leftTitle: 'Pregunta', rightTitle: 'Dato útil', pairs: [{ id: 'a', left: '¿Cuánto cambió el área verde?', right: 'Mapas fechados de cobertura' }, { id: 'b', left: '¿Cambió la escorrentía?', right: 'Registros comparables de lluvia y flujo superficial' }, { id: 'c', left: '¿Dónde hay mayor pendiente?', right: 'Mapa topográfico' }] }),
      S.reading({ fase: 'aplicar', areas: ['cnt'], cnb: ['cnt:6.4.1'], prompt: 'Analiza el caso simulado.' }, { genre: 'Ficha de comparación', heading: 'Barrio Las Flores, escenario de estudio', passage: 'Entre 2015 y 2025, la superficie construida del sector simulado pasó de 30 a 46 hectáreas y el área verde de 24 a 15. No se aportan datos de lluvia, drenaje ni infiltración.', questions: [{ q: '¿Qué hallazgo está respaldado?', options: [{ id: 'a', text: 'El área verde disminuyó 9 hectáreas' }, { id: 'b', text: 'La reducción causó todas las inundaciones' }, { id: 'c', text: 'La lluvia dejó de infiltrarse por completo' }], correct: 'a' }] }),
      S.choice({ fase: 'aplicar', areas: ['cnt'], cnb: ['cnt:6.4.1'], prompt: '¿Cuál es la recomendación mejor justificada?', explain: 'Protege lo observado y propone medir antes de atribuir efectos.' }, { options: [{ id: 'a', text: 'Conservar áreas verdes y reunir datos de suelo, lluvia y drenaje para evaluar sus efectos locales' }, { id: 'b', text: 'Asegurar que plantar árboles impedirá cualquier inundación' }, { id: 'c', text: 'Afirmar que la reducción prueba por sí sola la causa de todos los problemas de agua' }], correct: ['a'] }),
      S.choice({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:6.4.1'], prompt: '¿Qué evidencia muestra directamente la desaparición de un área verde?' }, { options: [{ id: 'a', text: 'Dos mapas comparables y fechados de cobertura del suelo' }, { id: 'b', text: 'Un rumor sin fecha' }, { id: 'c', text: 'Una fotografía sin ubicación' }], correct: ['a'] }),
      S.tf({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:6.2.1', 'cnt:6.3.1', 'cnt:6.4.1'], prompt: 'Evalúa las afirmaciones.' }, { statements: [{ text: 'La vegetación puede influir en infiltración y erosión según condiciones locales.', answer: true }, { text: 'Un mapa de cobertura incluye automáticamente datos de lluvia y extracción.', answer: false }, { text: 'Observar tala basta para identificar una causa sin comparar otros datos.', answer: false }, { text: 'El crecimiento urbano puede reducir áreas verdes cuando cambia el uso del suelo.', answer: true }] }),
    ],
  }),

  lesson({
    id: 's07-cnt-3', title: 'Energía en un sistema de agua', icon: 'Zap', minutes: 14,
    gancho: '¿Qué formas de energía intervienen cuando una bomba sube agua a un tanque?',
    objetivos: ['Clasificar manifestaciones de energía y justificar un ahorro eléctrico en un sistema de agua'],
    resumen: ['La energía puede manifestarse como eléctrica, luminosa, térmica, química, radiante, solar o nuclear.', 'Una bomba transforma energía eléctrica en movimiento y también libera parte como calor y sonido.', 'El uso racional reduce consumo sin impedir el servicio necesario.'],
    media: {
      id: 's07-cnt-3-energia-agua', kind: 'animation', title: 'Transformaciones de energía en el bombeo', aspect: '16:9', duration: 45,
      alt: 'Sistema de agua simulado con panel solar, cables, bomba, tanque y lámpara; flechas nombran manifestaciones de energía sin marcar respuestas de evaluación.',
      brief: 'Animación 2D de 45 s, 1600×900, de un sistema de agua simplificado y rotulado MODELO. Mostrar radiación solar sobre panel, electricidad hacia una bomba, movimiento del agua, leve calor del motor y luz de un indicador. Incluir una comparación entre fuga reparada y bombeo innecesario, sin cifras de una comunidad real. Narración clara en español, subtítulos, flechas de alto contraste y rótulos grandes.',
    },
    steps: [
      S.explain({ fase: 'explorar', areas: ['cnt'], cnb: ['cnt:7.1.1'], title: 'Seguir la energía', prompt: 'La energía no desaparece en el sistema: se transfiere y transforma.' }, { icon: 'Zap', body: 'Identificaremos **manifestaciones** por la evidencia observable: corriente, luz, calor, radiación o sustancias.' }),
      S.choice({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:7.1.1'], prompt: '¿Qué energía recibe directamente una bomba conectada a la red?', explain: 'La bomba recibe energía eléctrica y la transforma principalmente en movimiento.' }, { options: [{ id: 'a', text: 'Eléctrica' }, { id: 'b', text: 'Nuclear' }, { id: 'c', text: 'Química' }], correct: ['a'] }),
      S.explain({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:7.1.1'], title: 'Manifestaciones', prompt: 'Usa la evidencia para distinguirlas.' }, { icon: 'Sun', body: 'Una misma situación puede incluir varias manifestaciones.', reveal: [{ icon: 'Zap', front: 'Eléctrica', back: 'Cargas en movimiento alimentan aparatos y motores.' }, { icon: 'Sun', front: 'Solar y radiante', back: 'El Sol es una fuente; su radiación transporta energía.' }, { icon: 'Thermometer', front: 'Térmica', back: 'Se reconoce por cambios de temperatura.' }, { icon: 'Battery', front: 'Química', back: 'Se almacena en combustibles, alimentos y baterías.' }, { icon: 'Lightbulb', front: 'Luminosa', back: 'La emiten lámparas y el Sol.' }, { icon: 'Atom', front: 'Nuclear', back: 'Se origina en cambios del núcleo atómico.' }] }),
      S.ejemplo({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:7.1.1', 'cnt:7.2.1'], title: 'Ejemplo: bomba y tanque', prompt: 'Sigue la transformación y encuentra una oportunidad de ahorro.' }, { icon: 'Waypoints', problem: 'Una bomba eléctrica llena un tanque; una fuga hace que se encienda más veces.', steps: [{ text: 'La bomba recibe energía **eléctrica**.' }, { text: 'La transforma en movimiento del agua; parte se manifiesta como calor y sonido.' }, { text: 'La fuga obliga a bombear más sin mejorar el servicio.' }, { text: 'Reparar la fuga y apagar la bomba al llenar el tanque reduce consumo verificable.' }], answer: 'Uso racional: mantener el sistema y evitar bombeo innecesario.' }),
      S.match({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:7.1.1'], prompt: 'Relaciona evidencia y manifestación.', hint: 'Pregunta qué se observa o de dónde procede.', explain: 'Las evidencias permiten clasificar sin adivinar.' }, { leftTitle: 'Evidencia', rightTitle: 'Manifestación', pairs: [{ id: 'a', left: 'Cable alimenta la bomba', right: 'Eléctrica' }, { id: 'b', left: 'Motor se calienta', right: 'Térmica' }, { id: 'c', left: 'Panel recibe radiación del Sol', right: 'Solar y radiante' }, { id: 'd', left: 'Indicador encendido', right: 'Luminosa' }] }),
      S.sort({ fase: 'construir', areas: ['cnt'], cnb: ['cnt:7.2.1'], prompt: 'Clasifica cada uso.', hint: 'Uso racional mantiene una función necesaria con menos desperdicio.', explain: 'Ahorrar no es dejar sin agua: es evitar pérdidas y operación innecesaria.' }, { buckets: [{ id: 'r', label: 'Uso racional', icon: 'Leaf', color: 'var(--c-ok)' }, { id: 'd', label: 'Desperdicio', icon: 'AlertTriangle', color: 'var(--c-bad)' }], items: [{ id: 'a', text: 'Reparar una fuga que activa la bomba repetidamente', bucket: 'r' }, { id: 'b', text: 'Dejar la bomba encendida con el tanque lleno', bucket: 'd' }, { id: 'c', text: 'Revisar el consumo antes y después del ajuste', bucket: 'r' }, { id: 'd', text: 'Encender una lámpara del cuarto de bombas de día sin necesitarla', bucket: 'd' }] }),
      S.choice({ fase: 'aplicar', areas: ['cnt'], cnb: ['cnt:7.1.1', 'cnt:7.2.1'], prompt: 'En el escenario, la bomba se enciende 8 veces y una llave gotea. ¿Qué acción y verificación son coherentes?', explain: 'La propuesta atiende una pérdida y compara evidencia.' }, { options: [{ id: 'a', text: 'Reparar la fuga y comparar cuántas veces se activa la bomba después' }, { id: 'b', text: 'Desconectar permanentemente el sistema y no verificar' }, { id: 'c', text: 'Pintar el tanque y afirmar que ahorra electricidad' }], correct: ['a'] }),
      S.write({ fase: 'aplicar', areas: ['cnt'], cnb: ['cnt:7.1.1', 'cnt:7.2.1'], prompt: 'Completa el análisis del caso: manifestación de energía, desperdicio, acción y dato para verificar.', explain: 'Cada parte conecta el concepto con evidencia medible.' }, { minWords: 24, placeholder: 'Energía: ...\nDesperdicio: ...\nAcción: ...\nVerificación: ...', model: 'Energía eléctrica en la bomba. Desperdicio: activaciones por fuga. Acción: reparar la llave. Verificación: comparar activaciones durante periodos iguales.', rubric: ['Nombré una manifestación correcta', 'Propuse una acción viable', 'Incluí una comparación verificable'] }),
      S.choice({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:7.1.1'], prompt: 'Una batería almacena principalmente energía…' }, { options: [{ id: 'a', text: 'química' }, { id: 'b', text: 'nuclear' }, { id: 'c', text: 'sonora' }], correct: ['a'] }),
      S.choice({ fase: 'comprobar', areas: ['cnt'], cnb: ['cnt:7.2.1'], prompt: '¿Qué decisión muestra ahorro eléctrico racional sin impedir el servicio de agua?' }, { options: [{ id: 'a', text: 'Reparar fugas y detener la bomba cuando el tanque alcanza su nivel previsto' }, { id: 'b', text: 'Dejarla encendida toda la noche aunque el tanque esté lleno' }, { id: 'c', text: 'Eliminar el acceso al agua para no usar electricidad' }], correct: ['a'] }),
    ],
  }),
];
