/** L2 (espanol como segundo idioma) · Unidad 1 · Semana 1. */
import { lesson, S } from '../../../../dsl';

const audio = (id: string, script: string, title: string) => ({
  id, kind: 'audio' as const, title, duration: 12,
  alt: 'Audio breve de un mensaje oral sobre un lugar de la comunidad; la transcripcion se ofrece despues de responder.',
  brief: `Audio MP3 de una voz adulta, acento guatemalteco y ritmo pausado. Texto exacto: "${script}" Dejar una pausa de 3 segundos despues de la primera oracion para anticipar y 2 segundos de silencio final. Duracion: 12 s. Transcripcion disponible despues de responder o por mediacion docente para accesibilidad. Reemplazo: public/media/${id}.mp3.`,
});

export default [
  lesson({
    id: 's01-l2-1', title: 'Tres mensajes para orientar', icon: 'MessagesSquare', minutes: 14,
    gancho: 'Un mismo mapa puede servir para informar, explicar o defender una propuesta.',
    objetivos: ['Producir mensajes informativos, expositivos y argumentativos breves sobre el lugar local y su mapa'],
    resumen: ['El informativo comunica datos verificables.', 'El expositivo explica como o por que.', 'El argumentativo presenta una postura con una razon.'],
    media: { id: 's01-l2-1-mensajes', kind: 'diagram', title: 'Tres propositos en un mapa local', aspect: '16:9', alt: 'Mapa local con tres globos rotulados informar, explicar y argumentar.', brief: 'Diagrama 1600x900 de un mapa local ficticio con escuela, parque, mercado y puente. Tres globos: dato verificable, explicacion de una ruta y postura con razon. Texto grande, alto contraste, iconos ademas de color y lectura lineal accesible.' },
    steps: [
      S.explain({ fase: 'explorar', areas: ['l2'], cnb: ['l2:1.2.2'], prompt: 'Produce mensajes informativos, expositivos y argumentativos sobre un lugar o mapa segun el proposito.' }, { icon: 'Goal', body: '**Informativo:** da un dato. **Expositivo:** explica como o por que. **Argumentativo:** propone una postura y la apoya con una razon.' }),
      S.explain({ fase: 'construir', areas: ['l2'], cnb: ['l2:1.2.2'], title: 'Proposito y forma', prompt: 'Para redactar cada mensaje sobre la comunidad, elige primero su proposito.' }, { icon: 'ListTree', body: 'Informar: "La biblioteca esta al norte del parque". Exponer: "La flecha norte permite orientar la ruta". Argumentar: "Conviene senalar el cruce porque ayuda a caminar con seguridad".' }),
      S.ejemplo({ fase: 'construir', areas: ['l2'], cnb: ['l2:1.2.2'], title: 'Modelo de produccion', prompt: 'Observa como se producen tres mensajes distintos sobre el mismo mapa local.' }, { icon: 'Map', problem: 'El mapa muestra una escuela, un puente y un sendero.', steps: [{ text: 'Informativo: La escuela esta al este del puente.' }, { text: 'Expositivo: El sendero llega a la escuela porque conecta con el puente.' }, { text: 'Argumentativo: Debemos marcar el puente, pues es una referencia util.' }], answer: 'Cada mensaje mantiene el tema y cambia su forma segun el proposito.' }),
      S.write({ fase: 'construir', areas: ['l2'], cnb: ['l2:1.2.2'], prompt: 'Con ayuda, produce mensajes informativos, expositivos y argumentativos sobre el mapa de una comunidad: escuela al norte, parque al centro y mercado al sur.', hint: 'Usa dato; como o por que; postura mas razon.', explain: 'Los tres mensajes tratan el mapa, pero cumplen propositos diferentes.' }, { minWords: 21, placeholder: 'Informativo: ... Expositivo: ... Argumentativo: ...', model: 'Informativo: la escuela esta al norte. Expositivo: el parque orienta porque queda al centro. Argumentativo: conviene marcar el mercado porque guia la ruta.', rubric: ['Produje los tres mensajes', 'Ajuste cada forma al proposito', 'Mantuve el tema local'] }),
      S.choice({ fase: 'construir', areas: ['l2'], cnb: ['l2:1.2.2'], prompt: 'Para producir un mensaje informativo, otro expositivo y otro argumentativo sobre una ruta local, ¿que plan sirve mejor?', hint: 'Busca dato, explicacion y postura con razon.', explain: 'El plan A distingue los tres propositos y conserva el tema del mapa.' }, { options: [{ id: 'a', text: 'Dato de ubicacion; explicacion del recorrido; propuesta con una razon' }, { id: 'b', text: 'Tres opiniones sin evidencia' }, { id: 'c', text: 'Tres listas de nombres sin proposito' }], correct: ['a'] }),
      S.write({ fase: 'aplicar', areas: ['l2'], cnb: ['l2:1.2.2'], prompt: 'Produce de forma independiente un mensaje informativo, uno expositivo y uno argumentativo sobre una plaza, una parada y una calle representadas en un mapa local.' }, { minWords: 24, placeholder: 'Informativo: ... Expositivo: ... Argumentativo: ...', model: 'Informativo: la parada esta junto a la plaza. Expositivo: la calle une ambos puntos. Argumentativo: conviene marcar el cruce porque aclara el recorrido.', rubric: ['Inclui un dato', 'Explique una relacion', 'Defendi una propuesta con razon'] }),
      S.choice({ fase: 'aplicar', areas: ['l2'], cnb: ['l2:1.2.2'], prompt: 'Al producir mensajes informativos, expositivos y argumentativos sobre el mapa del barrio, ¿cual inicio corresponde al proposito argumentativo?' }, { options: [{ id: 'a', text: 'Propongo marcar la fuente porque ayuda a reconocer la plaza.' }, { id: 'b', text: 'La fuente esta frente al edificio municipal.' }, { id: 'c', text: 'La fuente orienta la ruta al funcionar como referencia.' }], correct: ['a'] }),
      S.choice({ fase: 'comprobar', areas: ['l2'], cnb: ['l2:1.2.2'], prompt: 'Para producir mensajes informativos, expositivos y argumentativos sobre un mapa local, elige la opcion expositiva.' }, { options: [{ id: 'a', text: 'El sendero aparece con linea punteada.' }, { id: 'b', text: 'La linea punteada permite distinguir el sendero de la calle.' }, { id: 'c', text: 'Deberiamos usar esa linea porque se entiende mejor.' }], correct: ['b'] }),
      S.tf({ fase: 'comprobar', areas: ['l2'], cnb: ['l2:1.2.2'], prompt: 'Para producir mensajes informativos, expositivos y argumentativos sobre la comunidad, comprueba cada decision de proposito.' }, { statements: [{ text: 'El informativo puede comunicar una ubicacion verificable.', answer: true }, { text: 'El expositivo explica como o por que.', answer: true }, { text: 'El argumentativo prescinde de razones.', answer: false }] }),
    ],
  }),

  lesson({
    id: 's01-l2-2', title: 'Escucho, anticipo e identifico la intencion', icon: 'Ear', minutes: 15,
    gancho: 'Las primeras palabras y el tono pueden anunciar que viene y para que se dice.',
    objetivos: ['Anticipar el contenido de un mensaje oral e identificar su intencion como hecho u opinion'],
    resumen: ['Anticipar usa las primeras palabras, el tono y el tema.', 'Un hecho comunica algo comprobable; una opinion expresa una valoracion.', 'Despues de anticipar, se escucha el final para confirmar o corregir.'],
    media: { id: 's01-l2-2-ruta-escucha', kind: 'diagram', title: 'Ruta para escuchar con intencion', aspect: '16:9', alt: 'Tres pasos: anticipar con pistas, escuchar el cierre e identificar hecho u opinion.', brief: 'Diagrama educativo 1600x900 con tres pasos numerados: pistas iniciales para anticipar, escucha completa para confirmar o corregir, e intencion de hecho comprobable u opinion valorativa. Usar ondas de audio e iconos descriptivos, texto grande, alto contraste, patrones ademas de color y orden de lectura accesible.' },
    steps: [
      S.explain({ fase: 'explorar', areas: ['l2'], cnb: ['l2:1.2.4', 'l2:1.2.6'], prompt: 'Al escuchar un mensaje oral, anticipa que seguira e identifica si su intencion comunica un hecho o una opinion.' }, { icon: 'Ear', body: 'Usa inicio, tono y tema para **anticipar**. Luego pregunta: ¿la intencion es informar un **hecho comprobable** o expresar una **opinion**? Escucha el final para verificar.' }),
      S.explain({ fase: 'construir', areas: ['l2'], cnb: ['l2:1.2.4', 'l2:1.2.6'], title: 'Dos decisiones al escuchar', prompt: 'Anticipa el contenido del mensaje oral y reconoce su intencion como hecho u opinion.' }, { icon: 'GitCompare', body: '"El mapa registra..." suele continuar con un dato: hecho. "Me parece que este camino..." anuncia una valoracion: opinion. La anticipacion es provisional y puede corregirse.' }),
      S.ejemplo({ fase: 'construir', areas: ['l2'], cnb: ['l2:1.2.4', 'l2:1.2.6'], title: 'Modelo auditivo', prompt: 'Observa como anticipar un mensaje oral e identificar su intencion de comunicar hecho u opinion.' }, { icon: 'Radio', problem: 'Se oye: "Segun el mapa, la clinica queda..."', steps: [{ text: '"Segun el mapa" permite anticipar una ubicacion.' }, { text: 'El cierre "al oeste de la plaza" confirma el dato.' }, { text: 'Su intencion es informar un hecho comprobable, no una opinion.' }], answer: 'Anticipacion: ubicacion. Intencion: hecho.' }),
      S.choice({ fase: 'construir', areas: ['l2'], cnb: ['l2:1.2.4', 'l2:1.2.6'], prompt: 'Escucha, anticipa que completara el mensaje oral e identifica si su intencion es comunicar un hecho o una opinion.', hint: 'Atiende al inicio y decide si el cierre puede comprobarse.', explain: 'El inicio anuncia una ubicacion verificable en el mapa.', media: audio('s01-l2-2-guia', 'En el mapa de San Lucas, el puesto de salud aparece... al norte del mercado.', 'Ubicacion en San Lucas') }, { options: [{ id: 'a', text: 'Una ubicacion; intencion de comunicar un hecho' }, { id: 'b', text: 'Un gusto; intencion de expresar una opinion' }, { id: 'c', text: 'Una receta; intencion de ordenar pasos' }], correct: ['a'] }),
      S.tf({ fase: 'construir', areas: ['l2'], cnb: ['l2:1.2.4', 'l2:1.2.6'], prompt: 'Escucha otro mensaje oral, anticipa su cierre e identifica la intencion como hecho u opinion.', hint: 'Una expresion de preferencia anuncia una valoracion.', explain: '"Para mi" orienta hacia una opinion, aunque el lugar exista.', media: audio('s01-l2-2-guia-opinion', 'Para mi, la ruta junto al parque es... la mas agradable del pueblo.', 'Opinion sobre una ruta') }, { statements: [{ text: 'Se anticipa una valoracion.', answer: true }, { text: 'La intencion es expresar una opinion.', answer: true }, { text: 'El cierre comunica una medida comprobable.', answer: false }] }),
      S.choice({ fase: 'aplicar', areas: ['l2'], cnb: ['l2:1.2.4', 'l2:1.2.6'], prompt: 'Sin pista, escucha el mensaje oral, anticipa la informacion final e identifica su intencion como hecho u opinion.', media: audio('s01-l2-2-aplica', 'El registro de la alcaldia indica que el puente mide... doce metros de largo.', 'Dato sobre un puente') }, { options: [{ id: 'a', text: 'Una medida comprobable; hecho' }, { id: 'b', text: 'Un gusto personal; opinion' }, { id: 'c', text: 'Una invitacion; opinion' }], correct: ['a'] }),
      S.tf({ fase: 'aplicar', areas: ['l2'], cnb: ['l2:1.2.4', 'l2:1.2.6'], prompt: 'Escucha de forma independiente, anticipa el cierre del mensaje oral e identifica su intencion como hecho u opinion.', media: audio('s01-l2-2-aplica-opinion', 'Creo que la plaza central es... el sitio mas acogedor para reunirse.', 'Valoracion sobre la plaza') }, { statements: [{ text: 'El inicio permite anticipar una valoracion.', answer: true }, { text: 'La intencion es expresar una opinion.', answer: true }, { text: 'El cierre es una coordenada comprobable.', answer: false }] }),
      S.choice({ fase: 'comprobar', areas: ['l2'], cnb: ['l2:1.2.4', 'l2:1.2.6'], prompt: 'Salida: escucha, anticipa el final del mensaje oral e identifica su intencion como hecho u opinion.', media: audio('s01-l2-2-salida-a', 'La clave del mapa usa una cruz para representar... el centro de salud.', 'Simbolo de un mapa') }, { options: [{ id: 'a', text: 'El significado de un simbolo; hecho' }, { id: 'b', text: 'El lugar mas bonito; opinion' }, { id: 'c', text: 'Una preferencia de color; opinion' }], correct: ['a'] }),
      S.tf({ fase: 'comprobar', areas: ['l2'], cnb: ['l2:1.2.4', 'l2:1.2.6'], prompt: 'Salida nueva: escucha, anticipa el cierre del mensaje oral e identifica su intencion como hecho u opinion.', media: audio('s01-l2-2-salida-b', 'En mi opinion, el mirador del cerro es... la mejor parada del recorrido.', 'Valoracion sobre un mirador') }, { statements: [{ text: 'Se anticipa una valoracion del mirador.', answer: true }, { text: 'La intencion es expresar una opinion.', answer: true }, { text: 'El cierre aporta una cantidad medible.', answer: false }] }),
    ],
  }),
];
