import { makeUnit2Lesson as L } from './s11';

export default [
  L({ area:'l1', week:12, number:1, title:'Hablar con calma ante un grupo', icon:'Mic', cnb:['l1:2.2.2'],
    question:'¿Cómo se nota que quien expone quiere que todos comprendan?', idea:'La postura estable, una respiración tranquila y una voz clara ayudan a comunicar.', method:'Ensayo de pie, miro a distintos lugares del grupo y hago una pausa antes de cada idea importante.', example:'Ana explica el cuidado de los árboles sin leer todo el cartel.', model:'Ana respira, mira al grupo, señala solo la imagen útil y explica una idea por vez.',
    guided:'¿Qué ayuda más a una expositora nerviosa?', answer:'Respirar, pausar y mirar a varias personas', wrong:['Hablar cada vez más rápido','Dar la espalda al grupo'], transfer:'El grupo del fondo no oye. ¿Qué ajuste conviene?', transferAnswer:'Proyectar la voz sin gritar', transferWrong:['Susurrar para todos','Acelerar hasta terminar'], task:'Prepara tres indicaciones para ensayar una exposición breve y amable.', exit:'Un expositor hace una pausa antes de la conclusión. ¿Qué logra?', exitAnswer:'Da tiempo para comprender y resalta la idea', exitWrong:['Borra el tema','Impide escuchar'], trueStatement:'Ensayar una postura cómoda puede reducir la tensión.', falseStatement:'Leer el cartel de espaldas demuestra interés por la audiencia.' }),
  L({ area:'l1', week:12, number:2, title:'Iniciar una conversación según el contexto', icon:'MessagesSquare', cnb:['l1:2.3.1'],
    question:'¿Saludas del mismo modo a un amigo y a una persona que entrevistas?', idea:'La apertura de una conversación cambia con la relación, el propósito y el lugar.', method:'Saludo, digo por qué quiero hablar y formulo una pregunta clara; escucho la respuesta.', example:'Pides a la bibliotecaria información sobre un libro para una tarea.', model:'«Buenos días. Busco un libro sobre aves de Guatemala. ¿Podría indicarme en qué estante está?»', guided:'¿Cuál inicio es adecuado para pedir una entrevista?', answer:'«Buenas tardes. ¿Podría hacerle unas preguntas sobre su oficio?»', wrong:['«Respóndame ya.»','«No importa su respuesta.»'], transfer:'Quieres conversar con un amigo en el recreo. ¿Qué apertura suena natural?', transferAnswer:'«Hola, ¿te cuento una idea para el juego?»', transferWrong:['«Queda usted oficialmente citado.»','«No puedes opinar.»'], task:'Escribe dos aperturas para preguntar lo mismo a un amigo y a una autoridad escolar.', exit:'¿Qué debe seguir después de plantear una pregunta?', exitAnswer:'Escuchar la respuesta sin interrumpir', exitWrong:['Cambiar de tema de inmediato','Repetir la pregunta sin pausa'], trueStatement:'El propósito influye en la manera de empezar una conversación.', falseStatement:'Una conversación formal permite exigir respuestas sin saludar.' }),
  L({ area:'l1', week:12, number:3, title:'Roles para dialogar y llegar a acuerdos', icon:'UsersRound', cnb:['l1:2.3.2'],
    question:'¿Cómo evita un grupo que solo una persona hable?', idea:'Los roles ayudan a que una discusión tenga orden, escucha y conclusión compartida.', method:'El grupo acuerda tema y turnos: moderación da la palabra, relatoría registra ideas y portavocía presenta acuerdos.', example:'Cuatro estudiantes deciden cómo cuidar un rincón de lectura.', model:'Una modera turnos, otra anota propuestas; comparan razones y una portavoz comunica el acuerdo final.', guided:'¿Qué hace quien modera?', answer:'Distribuye turnos y mantiene el tema', wrong:['Decide sin escuchar','Copia las conclusiones sin hablar'], transfer:'Dos personas hablan al mismo tiempo. ¿Qué hace la moderación?', transferAnswer:'Pide un turno por persona y resume el punto en discusión', transferWrong:['Expulsa a ambas sin escucharlas','Cambia de tema para evitar el desacuerdo'], task:'Diseña roles y una regla de turnos para una conversación sobre el patio escolar.', exit:'¿Quién presenta la conclusión al resto de la clase?', exitAnswer:'La persona portavoz', exitWrong:['Quien llegue último','La persona que no participó'], trueStatement:'La relatoría puede registrar puntos de acuerdo y desacuerdo.', falseStatement:'Asignar roles significa que solo habla la moderación.' }),
  L({ area:'l1', week:12, number:4, title:'Reconocer cómo se organiza un medio', icon:'Newspaper', cnb:['l1:3.1.1'],
    question:'¿Dónde buscarías fecha, autor y noticia principal en un periódico?', idea:'Cada medio organiza mensajes para una audiencia y un propósito: informar, educar o entretener.', method:'Identifico nombre del medio, sección, titular, fecha, autor y contenido antes de interpretar el mensaje.', example:'Un periódico escolar tiene portada, sección de deportes y una entrevista.', model:'La portada presenta temas; la sección agrupa noticias similares; la firma indica quién escribió la entrevista.', guided:'¿Qué función cumple un titular?', answer:'Anticipa el tema principal del texto', wrong:['Reemplaza toda la evidencia','Indica siempre quién financió el medio'], transfer:'Buscas noticias de ciencia en un sitio web. ¿Qué miras primero?', transferAnswer:'La sección, el título, la fecha y la fuente', transferWrong:['Solo el color de la página','Solo el primer comentario'], task:'Diseña la estructura de una página de noticias escolares con sección, título, fecha y firma.', exit:'¿Cuál elemento permite saber cuándo se publicó una noticia?', exitAnswer:'La fecha de publicación', exitWrong:['El tamaño de la foto','El color del titular'], trueStatement:'Una sección agrupa contenidos relacionados.', falseStatement:'Todos los medios presentan sus mensajes de idéntica manera.' }),
  L({ area:'l1', week:12, number:5, title:'Comparar un anuncio y una noticia', icon:'PanelTop', cnb:['l1:3.1.1','l1:2.3.2'],
    question:'¿Por qué una noticia y un anuncio pueden hablar del mismo evento de forma distinta?', idea:'Una noticia informa sobre hechos; un anuncio invita a una acción y puede intentar persuadir.', method:'Comparo propósito, autor, datos verificables y palabras que buscan convencer.', example:'La noticia reporta una feria de libros; el anuncio invita a visitarla.', model:'La noticia responde qué ocurrió y cuándo; el anuncio dice «ven este sábado» y ofrece motivos para asistir.', guided:'¿Qué frase suena más a anuncio?', answer:'«¡Ven a la feria y descubre nuevos libros!»', wrong:['«La feria abrió el martes.»','«Asistieron tres escuelas.»'], transfer:'Lees «la biblioteca abrió una sala nueva» con fecha y firma. ¿Qué es?', transferAnswer:'Una noticia informativa', transferWrong:['Un mandato sin datos','Una receta de cocina'], task:'Escribe un titular de noticia y una frase de anuncio sobre un mismo evento escolar.', exit:'¿Qué dato permite evaluar una noticia?', exitAnswer:'La fuente y la fecha', exitWrong:['El número de signos de admiración','El color más vistoso'], trueStatement:'El propósito cambia la forma de presentar un evento.', falseStatement:'Una invitación publicitaria es siempre una noticia imparcial.' }),
];
